ValueSet: BRCategoriaExame
Id: BRCategoriaExame
Title: "BR Categoria Exame"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRSubGrupoTabelaSUS#0701 "Órteses, próteses e materiais especiais não relacionados ao ato cirúrgico"
* BRSubGrupoTabelaSUS#0702 "Órteses, próteses e materiais especiais relacionados ao ato cirúrgico"
* BRSubGrupoTabelaSUS#0803 "Autorização / Regulação"
* BRSubGrupoTabelaSUS#0801 "Ações relacionadas ao estabelecimento"
* BRSubGrupoTabelaSUS#0802 "Ações relacionadas ao atendimento"
* BRSubGrupoTabelaSUS#0604 "Componente Especializado da Assitencia Farmaceutica"
* BRSubGrupoTabelaSUS#0601 "Medicamentos de dispensação excepcional"
* BRSubGrupoTabelaSUS#0602 "Medicamentos estratégicos"
* BRSubGrupoTabelaSUS#0506 "Acompanhamento e intercorrências no pré e pós-transplante"
* BRSubGrupoTabelaSUS#0505 "Transplante de orgãos, tecidos e células"
* BRSubGrupoTabelaSUS#0603 "Medicamentos de âmbito hospitalar e urgência"
* BRSubGrupoTabelaSUS#0504 "Processamento de tecidos para transplante"
* BRSubGrupoTabelaSUS#0416 "Cirurgia em oncologia"
* BRSubGrupoTabelaSUS#0417 "Anestesiologia"
* BRSubGrupoTabelaSUS#0418 "Cirurgia em nefrologia"
* BRSubGrupoTabelaSUS#0502 "Avaliação de morte encefálica"
* BRSubGrupoTabelaSUS#0503 "Ações relacionadas à doação de orgãos e tecidos para transplante"
* BRSubGrupoTabelaSUS#0501 "Coleta e exames para fins de doação de orgãos, tecidos e células e de transplante"
* BRSubGrupoTabelaSUS#0412 "Cirurgia torácica"
* BRSubGrupoTabelaSUS#0414 "Bucomaxilofacial"
* BRSubGrupoTabelaSUS#0413 "Cirurgia reparadora"
* BRSubGrupoTabelaSUS#0415 "Outras cirurgias"
* BRSubGrupoTabelaSUS#0410 "Cirurgia de mama"
* BRSubGrupoTabelaSUS#0411 "Cirurgia obstétrica"
* BRSubGrupoTabelaSUS#0407 "Cirurgia do aparelho digestivo, orgãos anexos e parede abdominal"
* BRSubGrupoTabelaSUS#0409 "Cirurgia do aparelho geniturinário"
* BRSubGrupoTabelaSUS#0408 "Cirurgia do sistema osteomuscular"
* BRSubGrupoTabelaSUS#0406 "Cirurgia do aparelho circulatório"
* BRSubGrupoTabelaSUS#0404 "Cirurgia das vias aéreas superiores, da face, da cabeça e do pescoço"
* BRSubGrupoTabelaSUS#0405 "Cirurgia do aparelho da visão"
* BRSubGrupoTabelaSUS#0402 "Cirurgia de glândulas endócrinas"
* BRSubGrupoTabelaSUS#0403 "Cirurgia do sistema nervoso central e periférico"
* BRSubGrupoTabelaSUS#0401 "Pequenas cirurgias e cirurgias de pele, tecido subcutâneo e mucosa"
* BRSubGrupoTabelaSUS#0310 "Parto e nascimento"
* BRSubGrupoTabelaSUS#0309 "Terapias especializadas"
* BRSubGrupoTabelaSUS#0308 "Tratamento de lesões, envenenamentos e outros, decorrentes de causas externas"
* BRSubGrupoTabelaSUS#0307 "Tratamentos odontológicos"
* BRSubGrupoTabelaSUS#0303 "Tratamentos clínicos (outras especialidades)"
* BRSubGrupoTabelaSUS#0304 "Tratamento em oncologia"
* BRSubGrupoTabelaSUS#0306 "Hemoterapia"
* BRSubGrupoTabelaSUS#0305 "Tratamento em nefrologia"
* BRSubGrupoTabelaSUS#0212 "Diagnóstico e procedimentos especiais em hemoterapia"
* BRSubGrupoTabelaSUS#0214 "Diagnóstico por teste rápido"
* BRSubGrupoTabelaSUS#0302 "Fisioterapia"
* BRSubGrupoTabelaSUS#0301 "Consultas / Atendimentos / Acompanhamentos"
* BRSubGrupoTabelaSUS#0213 "Diagnóstico em vigilância epidemiológica e ambiental"
* BRSubGrupoTabelaSUS#0210 "Diagnóstico por radiologia intervencionista"
* BRSubGrupoTabelaSUS#0208 "Diagnóstico por medicina nuclear in vivo"
* BRSubGrupoTabelaSUS#0211 "Métodos diagnósticos em especialidades"
* BRSubGrupoTabelaSUS#0209 "Diagnóstico por endoscopia"
* BRSubGrupoTabelaSUS#0207 "Diagnóstico por ressonância magnética"
* BRSubGrupoTabelaSUS#0205 "Diagnóstico por ultrasonografia"
* BRSubGrupoTabelaSUS#0206 "Diagnóstico por tomografia"
* BRSubGrupoTabelaSUS#0204 "Diagnóstico por radiologia"
* BRSubGrupoTabelaSUS#0201 "Coleta de material"
* BRSubGrupoTabelaSUS#0203 "Diagnóstico por anatomia patológica e citopatologia"
* BRSubGrupoTabelaSUS#0202 "Diagnóstico em laboratório clínico"
* BRSubGrupoTabelaSUS#0102 "Vigilância em saúde"
* BRSubGrupoTabelaSUS#0101 "Ações coletivas/individuais em saúde"
