ValueSet: BRCIAP2
Id: BRCIAP2
Title: "BRCIAP 2"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRCIAP2#A93 "Recém nascido prematuro"
* BRCIAP2#A99 "Outras doenças gerais NE"
* BRCIAP2#P16 "Abuso agudo de álcool"
* BRCIAP2#P15 "Abuso crônico de álcool"
* BRCIAP2#P13 "Encoprese/outros problemas de incontinência fecal"
* BRCIAP2#P12 "Molhar a cama/enurese"
* BRCIAP2#P11 "Problemas de alimentação da criança"
* BRCIAP2#P10 "Gaguejar/balbuciar/tiques"
* BRCIAP2#P09 "Preocupação com a preferência sexual"
* BRCIAP2#P08 "Diminuição da satisfação sexual"
* BRCIAP2#P07 "Diminuição do desejo sexual"
* BRCIAP2#Z29 "Problema social NE"
* BRCIAP2#P06 "Perturbação do sono"
* BRCIAP2#Z28 "Limitação funcional/incapacidade"
* BRCIAP2#P05 "Sensação/comportamento senil"
* BRCIAP2#Z27 "Medo de problema social"
* BRCIAP2#P04 "Sentir/comportar-se de forma irritável/zangada"
* BRCIAP2#Z25 "Ato ou acontecimento violento"
* BRCIAP2#P03 "Tristeza/ Sensação de depressão"
* BRCIAP2#Z24 "Problema de relacionamento com amigos"
* BRCIAP2#P02 "Reação aguda ao estresse"
* BRCIAP2#Z23 "Perda/falecimento de familiar"
* BRCIAP2#P01 "Sensação de ansiedade/nervosismo/tensão"
* BRCIAP2#Z22 "Problema por doença familiar"
* BRCIAP2#N99 "Outras doenças do sistema neurológico"
* BRCIAP2#Z21 "Problema comportamental de familiar"
* BRCIAP2#N95 "Cefaléia tensional"
* BRCIAP2#Z20 "Problema de relacionamento com familiares"
* BRCIAP2#N94 "Neurite/ Nevrite/neuropatia periférica"
* BRCIAP2#Z19 "Perda ou falecimento de criança"
* BRCIAP2#N93 "Síndrome do túnel do carpo/ Síndrome do canal cárpico"
* BRCIAP2#Z18 "Problema com criança doente"
* BRCIAP2#N92 "Nevralgia do trigémio"
* BRCIAP2#Z16 "Problema de relacionamento com criança"
* BRCIAP2#N91 "Paralisia facial/paralisia de Bell"
* BRCIAP2#Z15 "Perda ou falecimento do parceiro/ companheiro"
* BRCIAP2#N90 "Cefaléia de cluster"
* BRCIAP2#Z14 "Problema por doença do parceiro/ companheiro"
* BRCIAP2#N89 "Enxaqueca"
* BRCIAP2#Z13 "Problema comportamental do parceiro/ companheiro"
* BRCIAP2#N88 "Epilepsia"
* BRCIAP2#Z12 "Problema de relacionamento com parceiro/ conjugal"
* BRCIAP2#N87 "Parkinsonismo"
* BRCIAP2#Z11 "Problema relacionado com estar doente"
* BRCIAP2#N86 "Esclerose múltipla"
* BRCIAP2#Z10 "Problema relacionado com sistema de saúde"
* BRCIAP2#N85 "Malformações congênitas"
* BRCIAP2#Z09 "Problema de ordem legal"
* BRCIAP2#N81 "Outra lesão do sistema neurológico"
* BRCIAP2#N80 "Outras lesões cranianas"
* BRCIAP2#Z08 "Problema relacionado com sistema de segurança social"
* BRCIAP2#N79 "Concussão"
* BRCIAP2#Z07 "Problemas relacionados com educação"
* BRCIAP2#N76 "Neoplasia do sistema neurológico de natureza incerta"
* BRCIAP2#Z06 "Problemas de desemprego"
* BRCIAP2#N75 "Neoplasia benigna do sistema neurológico"
* BRCIAP2#Z05 "Problemas com condições de trabalho"
* BRCIAP2#N74 "Neoplasia maligna do sistema neurológico"
* BRCIAP2#Z04 "Problema socio-cultural"
* BRCIAP2#N73 "Outra infecção neurológica"
* BRCIAP2#Z03 "Problemas de habitação/vizinhança"
* BRCIAP2#Z02 "Problemas relacionados a água/alimentação"
* BRCIAP2#N72 "Tétano"
* BRCIAP2#N71 "Meningite/encefalite"
* BRCIAP2#Z01 "Pobreza/problemas econômicos"
* BRCIAP2#N70 "Poliomielite"
* BRCIAP2#Y99 "Doença genital masculina, outra"
* BRCIAP2#N29 "Sinais/sintomas do sistema neurológico, outros"
* BRCIAP2#Y86 "Hidrocele"
* BRCIAP2#N28 "Limitação funcional/incapacidade"
* BRCIAP2#Y85 "Hipertrofia benigna da próstata/ hiperplasia prostática benigna"
* BRCIAP2#N27 "Medo de outras doenças neurológicas"
* BRCIAP2#Y84 "Malformação genital congénita masculina, outra"
* BRCIAP2#N26 "Medo de câncer do sistema neurológico"
* BRCIAP2#Y83 "Testículo não descido/ Criptorquidia/ Testículo ectópico"
* BRCIAP2#N19 "Perturbações da fala"
* BRCIAP2#Y82 "Hipospádias"
* BRCIAP2#N18 "Paralisia/fraqueza"
* BRCIAP2#Y81 "Fimose/prepúcio redundante"
* BRCIAP2#N17 "Vertigens/tonturas"
* BRCIAP2#Y80 "Traumatismo genital masculino, outro"
* BRCIAP2#N16 "Alterações do olfato/gosto"
* BRCIAP2#Y79 "Neoplasia benigna genital masculina NE"
* BRCIAP2#N08 "Movimentos involuntários anormais"
* BRCIAP2#Y78 "Neoplasia maligna genital masculina, outra"
* BRCIAP2#N07 "Convulsões/ataques"
* BRCIAP2#Y77 "Neoplasia maligna da próstata"
* BRCIAP2#N06 "Outras alterações da sensibilidade"
* BRCIAP2#Y76 "Condiloma acuminado"
* BRCIAP2#N05 "Formigamento/ parestesia nos dedos das mãos/pés"
* BRCIAP2#Y75 "Balanite/ Balanopostite"
* BRCIAP2#N04 "Síndrome das pernas inquietas"
* BRCIAP2#Y74 "Orquite/epididimite"
* BRCIAP2#N03 "Dores da face"
* BRCIAP2#Y73 "Prostatite/vesiculite seminal"
* BRCIAP2#N01 "Cefaléia"
* BRCIAP2#Y72 "Herpes genital"
* BRCIAP2#L99 "Outra doença do aparelho músculo-esquelético"
* BRCIAP2#Y71 "Gonorréia masculina"
* BRCIAP2#L98 "Malformação adquirida de um membro"
* BRCIAP2#Y70 "Sífilis masculina"
* BRCIAP2#L97 "Neoplasia benigna/incertas"
* BRCIAP2#Y29 "Sinais/sintomas, outros"
* BRCIAP2#L96 "Lesão interna aguda do joelho"
* BRCIAP2#Y28 "Limitação funcional/incapacidade"
* BRCIAP2#L95 "Osteoporose"
* BRCIAP2#Y27 "Medo de doença genital masculina, outra"
* BRCIAP2#L94 "Osteocondrose"
* BRCIAP2#Y26 "Medo de câncer genital masculino"
* BRCIAP2#L93 "Cotovelo de tenista"
* BRCIAP2#Y25 "Medo de doença sexualmente transmissível"
* BRCIAP2#L92 "Síndrome do ombro doloroso"
* BRCIAP2#Y24 "Medo de disfunção sexual masculina"
* BRCIAP2#L91 "Outras osteoartroses"
* BRCIAP2#Y16 "Sinais/sintomas da mama masculina"
* BRCIAP2#L90 "Osteoartrose do joelho"
* BRCIAP2#Y14 "Planejamento familiar, outros"
* BRCIAP2#L89 "Osteoartrose do quadril"
* BRCIAP2#Y13 "Esterilização masculina"
* BRCIAP2#L88 "Artrite reumatóide/seropositiva"
* BRCIAP2#Y10 "Infertilidade/subfertildade masculina"
* BRCIAP2#L87 "Bursite/tendinite/sinovite NE"
* BRCIAP2#Y08 "Sinais/sintomas da função sexual masculina, outros"
* BRCIAP2#L86 "Síndrome vertebral com irradiação dor"
* BRCIAP2#Y07 "Impotência NE"
* BRCIAP2#L85 "Deformação adquirida da coluna"
* BRCIAP2#Y06 "Sinais/sintomas da próstata"
* BRCIAP2#L84 "Doenças ou síndromes da coluna sem irradiação de dor"
* BRCIAP2#Y05 "Sinais/sintomas do escroto/testículos, outros"
* BRCIAP2#Y04 "Sinais/sintomas do pênis, outros"
* BRCIAP2#L83 "Doenças ou síndromes da coluna cervical"
* BRCIAP2#Y03 "Secreção uretral"
* BRCIAP2#L82 "Malformações congênitas do aparelho músculo-esquelético"
* BRCIAP2#Y02 "Dor no escroto/testículos"
* BRCIAP2#L81 "Traumatismos do aparelho musculoesquelético NE"
* BRCIAP2#Y01 "Dor no pênis"
* BRCIAP2#L80 "Luxação/subluxação"
* BRCIAP2#X99 "Doença genital feminina, outra"
* BRCIAP2#L79 "Entorses e distensões das articulações NE"
* BRCIAP2#X92 "Infecção por clamídia"
* BRCIAP2#L78 "Entorses e distensões do joelho"
* BRCIAP2#X91 "Condiloma acuminado feminino"
* BRCIAP2#L77 "Entorses e distensões do tornozelo"
* BRCIAP2#X90 "Herpes genital feminino"
* BRCIAP2#L76 "Outras fraturas"
* BRCIAP2#X89 "Síndrome da tensão pré-menstrual"
* BRCIAP2#L75 "Fratura: fémur"
* BRCIAP2#X88 "Doença fibrocística da mama"
* BRCIAP2#L74 "Fratura: osso da mão/pé"
* BRCIAP2#X87 "Prolapso utero-vaginal"
* BRCIAP2#L73 "Fratura: tíbia/perônio/ fíbula"
* BRCIAP2#X86 "Esfregaço de Papanicolau/colpocitologia oncótica anormal"
* BRCIAP2#L72 "Fratura: rádio/cúbito"
* BRCIAP2#X85 "Doença do colo NE"
* BRCIAP2#L71 "Neoplasia maligna do aparelho músculo-esquelético"
* BRCIAP2#X84 "Vaginite/vulvite NE"
* BRCIAP2#L70 "Infecções do aparelho músculo-esquelético"
* BRCIAP2#X83 "Malformações congênitas genitais"
* BRCIAP2#L29 "Outros sinais/sintomas do aparelho músculo-esquelético"
* BRCIAP2#X82 "Lesão traumática genital feminina"
* BRCIAP2#L28 "Limitação funcional/incapacidade"
* BRCIAP2#X81 "Neoplasia genital feminina, outra/NE"
* BRCIAP2#L27 "Medo de doença no aparelho músculo-esquelético, outro"
* BRCIAP2#X80 "Neoplasia benigna genital"
* BRCIAP2#L26 "Medo de câncer no aparelho músculo-esquelético"
* BRCIAP2#X79 "Neoplasia benigna da mama feminina/ fibroadenoma"
* BRCIAP2#L20 "Sinais/sintomas das articulações NE"
* BRCIAP2#X78 "Fibromioma uterino"
* BRCIAP2#L19 "Sinais/sintomas musculares NE"
* BRCIAP2#X77 "Neoplasia maligna genital feminina, outra"
* BRCIAP2#L18 "Dores musculares"
* BRCIAP2#X76 "Neoplasia maligna da mama feminina"
* BRCIAP2#L17 "Sinais/sintomas do pé/dedos pé"
* BRCIAP2#X75 "Neoplasia maligna do colo"
* BRCIAP2#L16 "Sinais/sintomas do tornozelo"
* BRCIAP2#X74 "Doença inflamatória pélvica"
* BRCIAP2#L15 "Sinais/sintomas do joelho"
* BRCIAP2#X73 "Tricomoníase genital feminina"
* BRCIAP2#L14 "Sinais/sintomas da coxa/perna"
* BRCIAP2#X72 "Candidíase genital feminina"
* BRCIAP2#L13 "Sinais/sintomas do quadril"
* BRCIAP2#X71 "Gonorréia feminina"
* BRCIAP2#L12 "Sinais/sintomas das mãos e dedos"
* BRCIAP2#X70 "Sífilis feminina"
* BRCIAP2#L11 "Sinais/sintomas dos punhos"
* BRCIAP2#X29 "Sinais/sintomas do aparelho genital feminino, outra"
* BRCIAP2#L10 "Sinais/sintomas dos cotovelos"
* BRCIAP2#X28 "Limitação funcional/incapacidade"
* BRCIAP2#L09 "Sinais/sintomas dos braços"
* BRCIAP2#X27 "Medo de outra doença genital/mama"
* BRCIAP2#L08 "Sinais/sintomas dos ombros"
* BRCIAP2#X26 "Medo de câncer na mama"
* BRCIAP2#L07 "Sinais/sintomas da mandíbula"
* BRCIAP2#X25 "Medo de câncer genital"
* BRCIAP2#L05 "Sinais/sintomas da axila"
* BRCIAP2#X24 "Medo de disfunção sexual"
* BRCIAP2#L04 "Sinais/sintomas do tórax"
* BRCIAP2#X23 "Medo de doença de transmissão sexual"
* BRCIAP2#L03 "Sinais/sintomas da região lombar"
* BRCIAP2#X22 "Preocupação com a aparência da mama feminina"
* BRCIAP2#L02 "Sinais/sintomas da região dorsal"
* BRCIAP2#X21 "Sinais/sintomas da mama feminina, outros"
* BRCIAP2#L01 "Sinais/sintomas do pescoço"
* BRCIAP2#X20 "Sinais/sintomas do mamilo da mulher"
* BRCIAP2#K99 "Outras doenças do aparelho circulatório"
* BRCIAP2#X19 "Tumor ou nódulo na mama feminina"
* BRCIAP2#K96 "Hemorróidas"
* BRCIAP2#X18 "Dor na mama feminina"
* BRCIAP2#K95 "Veias varicosas da perna"
* BRCIAP2#X17 "Sinais/sintomas da pélvis feminina"
* BRCIAP2#K94 "Flebite/tromboflebite"
* BRCIAP2#X16 "Sinais/sintomas da vulva"
* BRCIAP2#K93 "Embolia pulmonar"
* BRCIAP2#X15 "Sinais/sintomas da vagina"
* BRCIAP2#K92 "Aterosclerose/doença vascular periférica"
* BRCIAP2#X14 "Secreção vaginal"
* BRCIAP2#K91 "Doença vascular cerebral"
* BRCIAP2#X13 "Hemorragia pós-coital"
* BRCIAP2#K90 "Trombose/acidente vascular cerebral"
* BRCIAP2#X12 "Hemorragia pós-menopausa"
* BRCIAP2#K89 "Isquêmia/ acidente cerebral transitória(o)"
* BRCIAP2#X11 "Sinais/sintomas da menopausa/ climatério"
* BRCIAP2#K88 "Hipotensão postural"
* BRCIAP2#X10 "Desejo de alterar a data menstruação"
* BRCIAP2#K87 "Hipertensão com complicações"
* BRCIAP2#X09 "Sinais/sintomas pré-menstruais"
* BRCIAP2#X08 "Hemorragia intermenstrual"
* BRCIAP2#K86 "Hipertensão sem complicações"
* BRCIAP2#X07 "Menstruação irregular/frequente"
* BRCIAP2#K85 "Pressão arterial elevada"
* BRCIAP2#X06 "Menstruação excessiva"
* BRCIAP2#K84 "Outras doenças cardíacas"
* BRCIAP2#X05 "Menstruação escassa/ausente"
* BRCIAP2#K83 "Doença valvular cardíaca NE"
* BRCIAP2#X04 "Relação sexual dolorosa na mulher"
* BRCIAP2#K82 "Doença cardiopulmonar"
* BRCIAP2#X03 "Dores intermenstruais"
* BRCIAP2#K81 "Sopro cardíaco/arterial NE"
* BRCIAP2#X02 "Dores menstruais"
* BRCIAP2#K80 "Arritmia cardíaca NE"
* BRCIAP2#X01 "Dor genital"
* BRCIAP2#K79 "Taquicardia Paroxística"
* BRCIAP2#W99 "Outros problemas da gravidez/parto"
* BRCIAP2#K78 "Fibrilação/flutter auricular/ atrial"
* BRCIAP2#W96 "Outras complicações do puerpério"
* BRCIAP2#K77 "Insuficiência cardíaca"
* BRCIAP2#W95 "Outros problemas da mama durante gravidez/puerpério"
* BRCIAP2#K76 "Doença cardíaca isquémica sem angina"
* BRCIAP2#W94 "Mastite puerperal"
* BRCIAP2#K75 "Infarto ou Enfarte agudo miocárdio"
* BRCIAP2#W93 "Parto com complicações de natimorto"
* BRCIAP2#K74 "Doença cardíaca isquémica com angina"
* BRCIAP2#W92 "Parto com complicações de nascido vivo"
* BRCIAP2#K73 "Malformações congênitas do aparelho circulatório"
* BRCIAP2#W91 "Parto sem complicações de natimorto"
* BRCIAP2#K72 "Neoplasia do aparelho circulatório"
* BRCIAP2#W90 "Parto sem complicações de nascido vivo"
* BRCIAP2#K71 "Febre reumática/cardiopatia"
* BRCIAP2#W85 "Diabetes gestacional"
* BRCIAP2#K70 "Doença infecciosa do aparelho circulatório"
* BRCIAP2#W84 "Gravidez de alto risco"
* BRCIAP2#K29 "Outros sinais/sintomas cardiovasculares"
* BRCIAP2#W83 "Aborto provocado"
* BRCIAP2#K28 "Limitação funcional/incapacidade"
* BRCIAP2#W82 "Aborto espontâneo"
* BRCIAP2#K27 "Medo de outra doença cardiovascular"
* BRCIAP2#W81 "Toxemia gravídica/ DHEG"
* BRCIAP2#K25 "Medo de hipertensão"
* BRCIAP2#W80 "Gravidez ectópica"
* BRCIAP2#K24 "Medo de doença cardíaca"
* BRCIAP2#W79 "Gravidez não desejada"
* BRCIAP2#W78 "Gravidez"
* BRCIAP2#K22 "Fator de risco para doença cardiovascular"
* BRCIAP2#W76 "Malformação congénita que complica a gravidez"
* BRCIAP2#K07 "Tornozelos inchados/edema"
* BRCIAP2#W75 "Lesões traumáticas que complicam a gravidez"
* BRCIAP2#K06 "Veias proeminentes"
* BRCIAP2#K05 "Outras irregularidades dos batimentos cardíacos"
* BRCIAP2#W73 "Neoplasia benigna/incerta relacionada com a gravidez"
* BRCIAP2#K04 "Palpitações/percepção dos batimentos cardíacos"
* BRCIAP2#W72 "Neoplasia maligna relacionada com gravidez"
* BRCIAP2#K03 "Dores atribuídas ao aparelho circulatório NE"
* BRCIAP2#W71 "Infecções que complicam a gravidez"
* BRCIAP2#K02 "Sensação de pressão/aperto atribuída ao coração"
* BRCIAP2#W70 "Sepsis/infecção puerperal"
* BRCIAP2#K01 "Dor atribuída ao coração"
* BRCIAP2#W29 "Sinais/sintomas da gravidez, outros"
* BRCIAP2#H99 "Outra doença do ouvido/mastóide"
* BRCIAP2#W28 "Limitação funcional/incapacidade"
* BRCIAP2#H86 "Surdez"
* BRCIAP2#W27 "Medo de complicações na gravidez"
* BRCIAP2#H85 "Lesão acústica"
* BRCIAP2#W21 "Preocupação com a imagem corporal na gravidez"
* BRCIAP2#H84 "Presbiacusia"
* BRCIAP2#W19 "Sinais/sintomas da mama/lactação"
* BRCIAP2#W18 "Sinais/sintomas pós-parto"
* BRCIAP2#H83 "Otoesclerose"
* BRCIAP2#W17 "Hemorragia pós-parto"
* BRCIAP2#H82 "Síndrome vertiginosa"
* BRCIAP2#H81 "Cerúmen no ouvido em excesso"
* BRCIAP2#W15 "Infertilidade/subfertildade"
* BRCIAP2#H80 "Malformações congênitas do ouvido"
* BRCIAP2#W14 "Contracepção/outros"
* BRCIAP2#H79 "Outros traumatismos do ouvido"
* BRCIAP2#W13 "Esterilização"
* BRCIAP2#W12 "Contracepção intra-uterina/ Dispositivo Intrauterino/ DIU"
* BRCIAP2#H78 "Traumatismo superficial do ouvido"
* BRCIAP2#W11 "Contracepção oral"
* BRCIAP2#H77 "Perfuração do tímpano"
* BRCIAP2#H76 "Corpo estranho do ouvido"
* BRCIAP2#W10 "Contracepção pós-coital"
* BRCIAP2#W05 "Vómitos/náuseas durante a gravidez"
* BRCIAP2#H75 "Neoplasia do ouvido"
* BRCIAP2#W03 "Hemorragia antes do parto"
* BRCIAP2#H74 "Otite media crónica"
* BRCIAP2#W02 "Medo de estar grávida"
* BRCIAP2#H73 "Infecção da Trompa de Eustáquio"
* BRCIAP2#H72 "Otite média serosa"
* BRCIAP2#W01 "Questão sobre gravidez"
* BRCIAP2#U99 "Outras doenças urinárias"
* BRCIAP2#H71 "Otite media aguda/miringite"
* BRCIAP2#U98 "Análise de urina anormal NE"
* BRCIAP2#H70 "Otite externa"
* BRCIAP2#U95 "Cálculo urinário"
* BRCIAP2#H29 "Outros sinais/sintomas ouvido"
* BRCIAP2#U90 "Albuminúria/proteinúria ortostática"
* BRCIAP2#H28 "Limitação funcional/incapacidade"
* BRCIAP2#U88 "Glomerulonefrite/ sindrome nefrótica"
* BRCIAP2#H27 "Medo de doença do ouvido"
* BRCIAP2#U85 "Malformação congénita do aparelho urinário"
* BRCIAP2#H15 "Preocupação com a aparência das orelhas"
* BRCIAP2#U80 "Lesões traumáticas do aparelho urinário"
* BRCIAP2#H13 "Sensação de ouvido tapado"
* BRCIAP2#U79 "Neoplasia do aparelho urinário NE"
* BRCIAP2#H05 "Hemorragia no ouvido"
* BRCIAP2#U78 "Neoplasia benigna do aparelho urinário"
* BRCIAP2#H04 "Secreção no ouvido"
* BRCIAP2#U77 "Neoplasia maligna do aparelho urinário, outra"
* BRCIAP2#H03 "Acufeno, zumbidos, ruído, assobios"
* BRCIAP2#U76 "Neoplasia benigna do rim"
* BRCIAP2#H02 "Problemas de audição"
* BRCIAP2#U75 "Neoplasia maligna do rim"
* BRCIAP2#H01 "Dor de ouvidos"
* BRCIAP2#U72 "Uretrite"
* BRCIAP2#F99 "Outra doenças oculares/anexos"
* BRCIAP2#U71 "Cistite/outra infecção urinária"
* BRCIAP2#F95 "Estrabismo"
* BRCIAP2#U70 "Pielonefrite"
* BRCIAP2#F94 "Cegueira"
* BRCIAP2#U29 "Sinais/sintomas aparelho urinário, outros"
* BRCIAP2#F93 "Glaucoma"
* BRCIAP2#U28 "Limitação funcional/incapacidade"
* BRCIAP2#F92 "Catarata"
* BRCIAP2#U27 "Medo de outra doença urinária"
* BRCIAP2#F91 "Erro de refração"
* BRCIAP2#U26 "Medo de câncer no aparelho urinário"
* BRCIAP2#F86 "Tracoma"
* BRCIAP2#U14 "Sinais/sintomas dos rins"
* BRCIAP2#U13 "Sinais/sintomas da bexiga, outros"
* BRCIAP2#F85 "Ulcera da córnea"
* BRCIAP2#F84 "Degeneração macular"
* BRCIAP2#U08 "Retenção urinária"
* BRCIAP2#U07 "Outros sinais/sintomas urinários"
* BRCIAP2#F83 "Retinopatia"
* BRCIAP2#U06 "Hematúria"
* BRCIAP2#F82 "Descolamento da retina"
* BRCIAP2#U05 "Outros problemas com a micção"
* BRCIAP2#F81 "Outras malformações congênitas do olho"
* BRCIAP2#U04 "Incontinência urinária"
* BRCIAP2#F80 "Obstrução canal lacrimal da criança"
* BRCIAP2#U02 "Micção frequente/urgência urinária/ polaciúria"
* BRCIAP2#U01 "Disúria/micção dolorosa"
* BRCIAP2#F79 "Outras lesões traumáticas oculares"
* BRCIAP2#T99 "Outras doenças endocrinológica/metabólica/nutricionais"
* BRCIAP2#F76 "Corpo estranho ocular"
* BRCIAP2#T93 "Alteração no metabolismo dos lípidos"
* BRCIAP2#F75 "Contusão/hemorragia ocular"
* BRCIAP2#T92 "Gota"
* BRCIAP2#F74 "Neoplasia do olho/anexos"
* BRCIAP2#F73 "Outras infecções/inflamações oculares"
* BRCIAP2#T91 "Deficiência vitamínica/nutricional"
* BRCIAP2#F72 "Blefarite/hordéolo/calázio"
* BRCIAP2#T90 "Diabetes não insulino-dependente"
* BRCIAP2#F71 "Conjuntivite alérgica"
* BRCIAP2#T89 "Diabetes insulino-dependente"
* BRCIAP2#F70 "Conjuntivite infecciosa"
* BRCIAP2#T87 "Hipoglicemia"
* BRCIAP2#F29 "Outros sinais/sintomas oculares"
* BRCIAP2#T86 "Hipotiroidismo/mixedema"
* BRCIAP2#F28 "Limitação funcional/incapacidade"
* BRCIAP2#T85 "Hipertiroidismo/tireotoxicose"
* BRCIAP2#F27 "Medo de doença ocular"
* BRCIAP2#T83 "Excesso de peso"
* BRCIAP2#F18 "Sinais/sintomas relacionados a lentes de contato"
* BRCIAP2#T82 "Obesidade"
* BRCIAP2#F17 "Sinais/sintomas relacionados a óculos"
* BRCIAP2#T81 "Bócio"
* BRCIAP2#F16 "Sinais/sintomas das pálpebras"
* BRCIAP2#T80 "Malformação congénita endócrina/metabólica"
* BRCIAP2#F15 "Aparência anormal nos olhos"
* BRCIAP2#T78 "Cisto do canal tiroglosso"
* BRCIAP2#F14 "Movimentos oculares anormais"
* BRCIAP2#T73 "Outra neoplasia endócrina NE"
* BRCIAP2#F13 "Sensações oculares anormais"
* BRCIAP2#T72 "Neoplasia benigna da tiróide"
* BRCIAP2#F05 "Outras perturbações visuais"
* BRCIAP2#T71 "Neoplasia maligna da tiróide"
* BRCIAP2#F04 "Moscas volantes/pontos luminosos/escotomas/ manchas"
* BRCIAP2#T70 "Infecção endócrina"
* BRCIAP2#F03 "Secreção ocular"
* BRCIAP2#T29 "Sinais/sintomas endocrinológicos/metabolicos/nutricionais, outros"
* BRCIAP2#F02 "Olho vermelho"
* BRCIAP2#T28 "Limitação funcional/incapacidade"
* BRCIAP2#F01 "Dor no olho"
* BRCIAP2#T27 "Medo de outra doença endócrina/metabólica"
* BRCIAP2#D99 "Outra doença do aparelho digestivo"
* BRCIAP2#T26 "Medo de câncer do sistema endócrino"
* BRCIAP2#D98 "Colecistite, colelitiase"
* BRCIAP2#T11 "Desidratação"
* BRCIAP2#D97 "Doenças do fígado /NE"
* BRCIAP2#T10 "Atraso do crescimento"
* BRCIAP2#D96 "Lombrigas /outros parasitas"
* BRCIAP2#T08 "Perda de peso"
* BRCIAP2#D95 "Fissura anal / abcesso perianal"
* BRCIAP2#T07 "Aumento de peso"
* BRCIAP2#D94 "Enterite crónica/colite ulcerosa"
* BRCIAP2#T05 "Problemas alimentares do adulto"
* BRCIAP2#D93 "Síndrome do cólon irritável"
* BRCIAP2#T04 "Problemas alimentares de lactente/criança"
* BRCIAP2#D92 "Doença diverticular intestinal"
* BRCIAP2#T03 "Perda de apetite"
* BRCIAP2#D91 "Hérnia abdominal, outras"
* BRCIAP2#T02 "Apetite excessivo"
* BRCIAP2#D90 "Hérnia de hiato /diafragmática"
* BRCIAP2#T01 "Sede excessiva"
* BRCIAP2#D89 "Hérnia inguinal"
* BRCIAP2#S99 "Outras doenças da pele"
* BRCIAP2#D88 "Apendicite"
* BRCIAP2#S98 "Urticária"
* BRCIAP2#S97 "Úlcera crónica da pele"
* BRCIAP2#D87 "Alterações funcionais estômago"
* BRCIAP2#D86 "Úlcera péptica, outra"
* BRCIAP2#S96 "Acne"
* BRCIAP2#D85 "Úlcera do duodeno"
* BRCIAP2#S95 "Molusco contagioso"
* BRCIAP2#D84 "Doença do esôfago"
* BRCIAP2#S94 "Unha encravada"
* BRCIAP2#D83 "Doença da boca/língua/lábios"
* BRCIAP2#S93 "Cisto sebáceo"
* BRCIAP2#D82 "Doença dos dentes/gengivas"
* BRCIAP2#S92 "Doença das glândulas sudoríparas"
* BRCIAP2#D81 "Malformações congênitas do aparelho digestivo"
* BRCIAP2#S91 "Psoríase"
* BRCIAP2#S90 "Pitiríase rosada"
* BRCIAP2#D80 "Outras lesões traumáticas"
* BRCIAP2#S89 "Dermatite das fraldas"
* BRCIAP2#D79 "Corpo estranho no aparelho digestivo"
* BRCIAP2#S88 "Dermatite de contato/alérgica"
* BRCIAP2#D78 "Neoplasia benigna do aparelho digestivo/incerta"
* BRCIAP2#S87 "Dermatite/eczema atópico"
* BRCIAP2#D77 "Neoplasia maligna do aparelho digestivo NE"
* BRCIAP2#S86 "Dermatite seborreica"
* BRCIAP2#D76 "Neoplasia maligna do pâncreas"
* BRCIAP2#S85 "Cisto pilonidal/fistula"
* BRCIAP2#D75 "Neoplasia maligna do cólon/reto"
* BRCIAP2#S84 "Impetigo"
* BRCIAP2#D74 "Neoplasia maligna do estômago"
* BRCIAP2#S83 "Lesões da pele congênitas, outras"
* BRCIAP2#D73 "Gastroenterite, presumível infecção"
* BRCIAP2#S82 "Nevos/sinais da pele"
* BRCIAP2#D72 "Hepatite viral"
* BRCIAP2#S81 "Hemangioma/linfangioma"
* BRCIAP2#D71 "Caxumba/parotidite epidêmica"
* BRCIAP2#S80 "Ceratose/ Queratose solar/queimadura solar"
* BRCIAP2#D70 "Infecção gastrointestinal"
* BRCIAP2#S79 "Neoplasia cutânea benigna/incerta"
* BRCIAP2#D29 "Outros sinais/sintomas digestivos"
* BRCIAP2#S78 "Lipoma"
* BRCIAP2#D28 "Limitação funcional/incapacidade"
* BRCIAP2#S77 "Neoplasias malignas da pele"
* BRCIAP2#D27 "Medo de outras doenças aparelho digestivo"
* BRCIAP2#S76 "Outras infecções da pele"
* BRCIAP2#D26 "Medo de câncer no aparelho digestivo"
* BRCIAP2#S75 "Monilíase oral/candidíase na pele"
* BRCIAP2#D25 "Distensão abdominal"
* BRCIAP2#S74 "Dermatofitose"
* BRCIAP2#D24 "Massa abdominal NE"
* BRCIAP2#S73 "Pediculose/outras infecções da pele"
* BRCIAP2#D23 "Hepatomegalia"
* BRCIAP2#S72 "Escabiose/outras acaríases"
* BRCIAP2#D21 "Problemas de deglutição"
* BRCIAP2#S71 "Herpes simples"
* BRCIAP2#D20 "Sinais/sintomas da boca/língua/lábios"
* BRCIAP2#S70 "Herpes zoster"
* BRCIAP2#D19 "Sinais/sintomas dos dentes/gengivas"
* BRCIAP2#S29 "Sinais/sintomas da pele, outros"
* BRCIAP2#D18 "Alterações nas fezes/mov. intestinais"
* BRCIAP2#S28 "Limitação funcional/incapacidade"
* BRCIAP2#D17 "Incontinência fecal"
* BRCIAP2#S27 "Medo de outra doença da pele"
* BRCIAP2#D16 "Hemorragia retal"
* BRCIAP2#S26 "Medo de câncer de pele"
* BRCIAP2#D15 "Melena"
* BRCIAP2#D14 "Hematêmese/vómito sangue"
* BRCIAP2#S24 "Sinais/sintomas do cabelo/couro cabeludo"
* BRCIAP2#D13 "Icterícia"
* BRCIAP2#S23 "Queda de cabelo/calvície"
* BRCIAP2#D12 "Obstipação"
* BRCIAP2#S22 "Sinais/sintomas das unhas"
* BRCIAP2#S21 "Sinais/sintomas da textura da pele"
* BRCIAP2#D11 "Diarreia"
* BRCIAP2#S20 "Calos/calosidades"
* BRCIAP2#D10 "Vomito"
* BRCIAP2#S19 "Outra lesão cutânea"
* BRCIAP2#D09 "Náusea"
* BRCIAP2#S18 "Laceração/corte"
* BRCIAP2#D08 "Flatulência /gases/eructações"
* BRCIAP2#S17 "Abrasão/arranhão/bolhas"
* BRCIAP2#D07 "Dispepsia/indigestão"
* BRCIAP2#S16 "Traumatismo/contusão"
* BRCIAP2#D06 "Outras dores abdominais localizadas"
* BRCIAP2#S15 "Corpo estranho na pele"
* BRCIAP2#D05 "Irritação perianal"
* BRCIAP2#S14 "Queimadura/escaldão"
* BRCIAP2#D04 "Dor anal/retal"
* BRCIAP2#S13 "Mordedura animal/humana"
* BRCIAP2#D03 "Azia/ Queimação"
* BRCIAP2#S12 "Picada ou mordedura de inseto"
* BRCIAP2#D02 "Dores abdominais, epigástricas"
* BRCIAP2#S11 "Infecção pós-traumática da pele"
* BRCIAP2#D01 "Dor abdominal generalizada/cólicas"
* BRCIAP2#S10 "Furúnculo/carbúnculo"
* BRCIAP2#B99 "Outra doença do sangue/linfáticos/baço"
* BRCIAP2#S09 "Infecção dos dedos das mãos/pés"
* BRCIAP2#B90 "Infecção por VIH/ HIV/SIDA/ AIDS"
* BRCIAP2#S08 "Alterações da cor da pele"
* BRCIAP2#B87 "Esplenomegalia"
* BRCIAP2#S07 "Erupção cutânea generalizada"
* BRCIAP2#B84 "Glóbulos brancos anormais"
* BRCIAP2#S06 "Erupção cutânea localizada"
* BRCIAP2#B83 "Púrpura/defeitos de coagulação"
* BRCIAP2#S05 "Tumores/inchaços generalizados"
* BRCIAP2#B82 "Outras anemias NE"
* BRCIAP2#S04 "Tumor/inchaço localizado"
* BRCIAP2#B81 "Anemia perniciosa/deficiência de folatos"
* BRCIAP2#S03 "Verrugas"
* BRCIAP2#B80 "Anemia por deficiência de ferro"
* BRCIAP2#S02 "Prurido"
* BRCIAP2#B79 "Outra malformação congênita do sangue/linfática"
* BRCIAP2#S01 "Dor/sensibilidade dolorosa da pele"
* BRCIAP2#B78 "Anemia hemolítica hereditária"
* BRCIAP2#R99 "Outras doenças respiratórias"
* BRCIAP2#R98 "Síndrome de hiperventilação"
* BRCIAP2#B77 "Outras lesões traumáticas do sangue/linfa/baço"
* BRCIAP2#R97 "Rinite alérgica"
* BRCIAP2#B76 "Rotura traumática do baço"
* BRCIAP2#R96 "Asma"
* BRCIAP2#B75 "Neoplasia benigna NE"
* BRCIAP2#R95 "Doença pulmonar obstrutiva crónica"
* BRCIAP2#B74 "Outra neoplasia maligna no sangue"
* BRCIAP2#R92 "Neoplasia respiratória NE"
* BRCIAP2#B73 "Leucemia"
* BRCIAP2#R90 "Hipertrofia das amígdalas/adenóides"
* BRCIAP2#B72 "Doença de Hodgkin/linfomas"
* BRCIAP2#R89 "Malformação congénita do aparelho respiratório"
* BRCIAP2#B71 "Linfadenite crónica NE"
* BRCIAP2#R88 "Outra lesão respiratória"
* BRCIAP2#B70 "Linfadenite aguda"
* BRCIAP2#R87 "Corpo estranho nariz/laringe/brônquios"
* BRCIAP2#B29 "Outros sinais/ sintomas do sangue/ sistema linfático/ baço NE"
* BRCIAP2#R86 "Neoplasia benigna respiratória"
* BRCIAP2#B28 "Limitação funcional/incapacidade"
* BRCIAP2#R85 "Outra neoplasia respiratória maligna"
* BRCIAP2#B27 "Medo de outras doenças do sangue /vasos linfáticos"
* BRCIAP2#R84 "Neoplasia maligna dos brônquios/pulmão"
* BRCIAP2#B26 "Medo de câncer no sangue/linfático"
* BRCIAP2#R83 "Outra infecção respiratória"
* BRCIAP2#R82 "Pleurite/derrame pleural"
* BRCIAP2#B25 "Medo de VIH/ HIV/SIDA/ AIDS"
* BRCIAP2#R81 "Pneumonia"
* BRCIAP2#B04 "Sinais/sintomas sangue"
* BRCIAP2#R80 "Gripe"
* BRCIAP2#R79 "Bronquite crônica"
* BRCIAP2#B02 "Gânglio linfático aumentado/doloroso"
* BRCIAP2#R78 "Bronquite/bronquiolite aguda"
* BRCIAP2#R77 "Laringite/traqueíte aguda"
* BRCIAP2#R76 "Amigdalite aguda"
* BRCIAP2#A98 "Medicina preventiva/manutenção da saúde"
* BRCIAP2#R75 "Sinusite crónica/aguda"
* BRCIAP2#A97 "Sem doença"
* BRCIAP2#R74 "Infecção aguda do aparelho respiratório superior (IVAS)"
* BRCIAP2#A96 "Morte"
* BRCIAP2#R73 "Abcesso/furúnculo no nariz"
* BRCIAP2#A95 "Mortalidade perinatal"
* BRCIAP2#R72 "Infecção estreptocócica da orofaringe"
* BRCIAP2#A94 "Morbidade perinatal, outra"
* BRCIAP2#R71 "Tosse convulsa/ pertussis"
* BRCIAP2#R29 "Sinais/sintomas do aparelho respiratório, outros"
* BRCIAP2#A92 "Alergia/reação alérgica NE"
* BRCIAP2#R28 "Limitação funcional/incapacidade"
* BRCIAP2#A91 "Investigação com resultado anormal NE"
* BRCIAP2#R27 "Medo de outras doenças respiratórias"
* BRCIAP2#A90 "Malformação congênita NE/múltiplas"
* BRCIAP2#R26 "Medo de câncer do aparelho respiratório"
* BRCIAP2#A89 "Efeito da prótese"
* BRCIAP2#R25 "Expectoração/mucosidade anormal"
* BRCIAP2#A88 "Efeito adverso de fator físico"
* BRCIAP2#R24 "Hemoptise"
* BRCIAP2#A87 "Complicações de tratamento médico"
* BRCIAP2#R23 "Sinais/sintomas da voz"
* BRCIAP2#A86 "Efeito tóxico de substância não medicinal"
* BRCIAP2#R21 "Sinais/sintomas da garganta"
* BRCIAP2#A85 "Efeito adverso de fármaco dose correta"
* BRCIAP2#R09 "Sinais/sintomas dos seios paranasais"
* BRCIAP2#A84 "Intoxicação por medicamento"
* BRCIAP2#R08 "Outros sinais/sintomas nasais"
* BRCIAP2#A82 "Efeito secundário de lesão traumática"
* BRCIAP2#R07 "Espirro/congestão nasal"
* BRCIAP2#A81 "Politraumatismos/ferimentos múltiplos"
* BRCIAP2#R06 "Hemorragia nasal/epistaxe"
* BRCIAP2#A80 "Lesão traumática/acidente NE"
* BRCIAP2#R05 "Tosse"
* BRCIAP2#A79 "Carcinomatose (localização primária desconhecida)"
* BRCIAP2#R04 "Outros problemas respiratórios"
* BRCIAP2#A78 "Hanseníase e outras doenças infecciosas NE"
* BRCIAP2#R03 "Respiração ruidosa"
* BRCIAP2#A77 "Dengue e outras doenças virais NE"
* BRCIAP2#R02 "Dificuldade respiratória, dispneia"
* BRCIAP2#A76 "Outro exantema viral"
* BRCIAP2#R01 "Dor atribuída ao aparelho respiratório"
* BRCIAP2#A75 "Mononucleose infecciosa"
* BRCIAP2#P99 "Outras perturbações psicológicas"
* BRCIAP2#A74 "Rubéola"
* BRCIAP2#P98 "Outras psicoses NE"
* BRCIAP2#A73 "Malária"
* BRCIAP2#P86 "Anorexia nervosa, bulimia"
* BRCIAP2#A72 "Varicela"
* BRCIAP2#P85 "Retardo/ Atraso mental"
* BRCIAP2#A71 "Sarampo"
* BRCIAP2#P82 "Estresse pós traumático"
* BRCIAP2#A70 "Tuberculose"
* BRCIAP2#P81 "Perturbação hipercinética"
* BRCIAP2#A29 "Outros sinais/sintomas gerais"
* BRCIAP2#P80 "Perturbações de personalidade"
* BRCIAP2#A28 "Limitação funcional/incapacidade NE"
* BRCIAP2#P79 "Fobia/perturbação compulsiva"
* BRCIAP2#A27 "Medo de outra doença NE"
* BRCIAP2#P78 "Neurastenia"
* BRCIAP2#A26 "Medo de câncer NE"
* BRCIAP2#P77 "Suicídio/tentativa de suicídio"
* BRCIAP2#A25 "Medo de morrer/medo da morte"
* BRCIAP2#P76 "Perturbações depressivas"
* BRCIAP2#A23 "Fator de risco NE"
* BRCIAP2#P75 "Somatização"
* BRCIAP2#A21 "Fator de risco de malignidade"
* BRCIAP2#P74 "Distúrbio ansioso/estado de ansiedade"
* BRCIAP2#A20 "Pedido/discussão eutanásia"
* BRCIAP2#P73 "Psicose afetiva"
* BRCIAP2#A18 "Preocupação com aparência"
* BRCIAP2#P72 "Esquizofrenia"
* BRCIAP2#A16 "Criança irritável"
* BRCIAP2#P71 "Outras psicoses orgânicas NE"
* BRCIAP2#A13 "Receio/Medo do tratamento"
* BRCIAP2#P70 "Demência"
* BRCIAP2#P29 "Sinais/sintomas psicológicos, outros"
* BRCIAP2#A11 "Dores torácicas NE"
* BRCIAP2#A10 "Sangramento/Hemorragia NE"
* BRCIAP2#P28 "Limitação funcional/incapacidade"
* BRCIAP2#P27 "Medo de perturbações mentais"
* BRCIAP2#A09 "Problemas de sudorese"
* BRCIAP2#P25 "Problemas da fase de vida de adulto"
* BRCIAP2#A08 "Inchaço"
* BRCIAP2#P24 "Dificuldades especificas de aprendizagem"
* BRCIAP2#A07 "Coma"
* BRCIAP2#P23 "Sinais/sintomas relacionados ao comportamento do adolescente"
* BRCIAP2#A06 "Desmaio/síncope"
* BRCIAP2#P22 "Sinais/sintomas relacionados ao comportamento da criança"
* BRCIAP2#A05 "Sentir-se doente"
* BRCIAP2#P20 "Alterações da memória"
* BRCIAP2#A04 "Debilidade/cansaço geral/fadiga"
* BRCIAP2#A03 "Febre"
* BRCIAP2#P19 "Abuso de drogas"
* BRCIAP2#A02 "Arrepios/ calafrios"
* BRCIAP2#P18 "Abuso de medicação"
* BRCIAP2#A01 "Dor generalizada /múltipla"
* BRCIAP2#P17 "Abuso do tabaco"