ValueSet: BRCID10
Id: BRCID10
Title: "BRCID 10"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRCID10#P52.1 "Hemorragia intraventricular (não-traumática) grau 2, do feto e do recém-nascido"
* BRCID10#P52.0 "Hemorragia intraventricular (não-traumática) grau 1, do feto e do recém-nascido"
* BRCID10#P52 "Hemorragia intracraniana não-traumática do feto e do recém-nascido"
* BRCID10#P51.9 "Hemorragia umbilical do recém-nascido, não especificada"
* BRCID10#P51.8 "Outras hemorragias umbilicais do recém-nascido"
* BRCID10#P51.0 "Hemorragia umbilical maciça do recém-nascido"
* BRCID10#P51 "Hemorragia umbilical do recém-nascido"
* BRCID10#P50.9 "Perda sangüínea fetal não especificada"
* BRCID10#P50.8 "Outras perdas sangüíneas fetais"
* BRCID10#P50.5 "Perda sangüínea devido a secção do cordão umbilical do outro gemelar"
* BRCID10#P50.4 "Hemorragia para a circulação materna"
* BRCID10#P50.3 "Hemorragia para a circulação do outro gêmeo"
* BRCID10#P50.2 "Perda sangüínea fetal originada da placenta"
* BRCID10#P50.1 "Perda sangüínea fetal por ruptura do cordão"
* BRCID10#P50.0 "Perda sangüínea fetal devida a vasa prévia"
* BRCID10#P50 "Perda sangüínea fetal"
* BRCID10#P39.9 "Infecção própria do período perinatal não especificada"
* BRCID10#P39.8 "Outras infecções especificadas próprias do período perinatal"
* BRCID10#P39.4 "Infecção neonatal da pele"
* BRCID10#P39.3 "Infecção neonatal do trato urinário"
* BRCID10#P39.2 "Infecção intra-amniótica do feto não classificada em outra parte"
* BRCID10#P39.1 "Conjuntivite e dacriocistite neonatais"
* BRCID10#P39.0 "Mastite infecciosa neonatal"
* BRCID10#P39 "Outras infecções específicas do período perinatal"
* BRCID10#P38 "Onfalite do recém-nascido com ou sem hemorragia leve"
* BRCID10#P37.9 "Doença infecciosa ou parasitária congênita não especificada"
* BRCID10#P37.8 "Outras doenças infecciosas e parasitárias congênitas especificadas"
* BRCID10#P37.5 "Candidíase neonatal"
* BRCID10#P37.4 "Outras malárias congênitas"
* BRCID10#P37.3 "Malária falciparum congênita"
* BRCID10#P37.2 "Listeriose neonatal (disseminada)"
* BRCID10#P37.1 "Toxoplasmose congênita"
* BRCID10#P37.0 "Tuberculose congênita"
* BRCID10#P37 "Outras doenças infecciosas e parasitárias congênitas"
* BRCID10#P36.9 "Septicemia bacteriana não especificada do recém-nascido"
* BRCID10#P36.8 "Outras septicemias bacterianas do recém-nascido"
* BRCID10#P36.5 "Septicemia do recém-nascido devida a anaeróbios"
* BRCID10#P36.4 "Septicemia do recém-nascido devida a Escherichia coli"
* BRCID10#P36.3 "Septicemia do recém-nascido devida a outros estafilococos e aos não especificados"
* BRCID10#P36.2 "Septicemia do recém-nascido devida ao Stafilococcus aureus"
* BRCID10#P36.1 "Septicemia do recém-nascido devida a outros estreptococos e aos não especificados"
* BRCID10#P36.0 "Septicemia do recém-nascido devida a estreptococo do grupo B"
* BRCID10#P36 "Septicemia bacteriana do recém-nascido"
* BRCID10#P35.9 "Doença viral congênita não especificada"
* BRCID10#P35.8 "Outras doenças virais congênitas"
* BRCID10#P35.3 "Hepatite viral congênita"
* BRCID10#P35.2 "Infecção congênita por vírus do herpes [simples]"
* BRCID10#P35.1 "Infecção congênita por citomegalovirus"
* BRCID10#P35.0 "Síndrome da rubéola congênita"
* BRCID10#P35 "Doenças virais congênitas"
* BRCID10#P29.9 "Transtornos cardiovasculares não especificados originados no período perinatal"
* BRCID10#P29.8 "Outros transtornos cardiovasculares originados no período perinatal"
* BRCID10#P29.4 "Isquemia miocárdica transitória do recém-nascido"
* BRCID10#P29.3 "Persistência da circulação fetal"
* BRCID10#P29.2 "Hipertensão neonatal"
* BRCID10#P29.1 "Disritmia cardíaca neonatal"
* BRCID10#P29.0 "Insuficiência cardíaca neonatal"
* BRCID10#P29 "Transtornos cardiovasculares originados no período perinatal"
* BRCID10#P28.9 "Afecção respiratória do recém-nascido, não especificada"
* BRCID10#P28.8 "Outras afecções respiratórias especificadas do recém-nascido"
* BRCID10#P28.5 "Insuficiência respiratória do recém-nascido"
* BRCID10#P28.4 "Outras apnéias do recém-nascido"
* BRCID10#P28.3 "Apnéia primária do sono do recém-nascido"
* BRCID10#P28.2 "Crises cianóticas do recém-nascido"
* BRCID10#P28.1 "Outras atelectasias do recém-nascido e as não especificadas"
* BRCID10#P28.0 "Atelectasia primária do recém-nascido"
* BRCID10#P28 "Outras afecções respiratórias originadas no período perinatal"
* BRCID10#P27.9 "Doença respiratória crônica não especificada originada no período perinatal"
* BRCID10#P27.8 "Outras doenças respiratórias crônicas originadas no período perinatal"
* BRCID10#P27.1 "Displasia broncopulmonar originada no período perinatal"
* BRCID10#P27.0 "Síndrome de Wilson-Mikity"
* BRCID10#P27 "Doença respiratória crônica originada no período perinatal"
* BRCID10#P26.9 "Hemorragia pulmonar não especificada originada no período perinatal"
* BRCID10#P26.8 "Outras hemorragias pulmonares originadas no período perinatal"
* BRCID10#P26.1 "Hemorragia pulmonar maciça originada no período perinatal"
* BRCID10#P26.0 "Hemorragia traqueobrônquica originada no período perinatal"
* BRCID10#P26 "Hemorragia pulmonar originada no período perinatal"
* BRCID10#P25.8 "Outras afecções relacionadas com o enfisema intersticial originadas no período perinatal"
* BRCID10#P25.3 "Pneumopericárdio originado no período perinatal"
* BRCID10#P25.2 "Pneumomediastino originado no período perinatal"
* BRCID10#P25.1 "Pneumotórax originado no período perinatal"
* BRCID10#P25.0 "Enfisema intersticial originado no período perinatal"
* BRCID10#P25 "Enfisema intersticial e afecções correlatas originadas no período perinatal"
* BRCID10#P24.9 "Síndrome de aspiração neonatal não especificada"
* BRCID10#P24.8 "Outras síndromes de aspiração neonatais"
* BRCID10#P24.3 "Aspiração neonatal de leite e alimento regurgitados"
* BRCID10#P24.2 "Aspiração neonatal de sangue"
* BRCID10#P24.1 "Aspiração neonatal de líquido amniótico e muco"
* BRCID10#P24.0 "Aspiração neonatal de mecônio"
* BRCID10#P24 "Síndrome de aspiração neonatal"
* BRCID10#P23.9 "Pneumonia congênita não especificada"
* BRCID10#P23.8 "Pneumonia congênita devida a outros organismos"
* BRCID10#P23.6 "Pneumonia congênita devida a outros agentes bacterianos"
* BRCID10#P23.5 "Pneumonia congênita devida a Pseudomonas"
* BRCID10#P23.4 "Pneumonia congênita devida a Escherichia coli"
* BRCID10#P23.3 "Pneumonia congênita devida a estreptococo do grupo B"
* BRCID10#P23.2 "Pneumonia congênita devida a estafilococo"
* BRCID10#P23.1 "Pneumonia congênita devida a Clamídia"
* BRCID10#P23.0 "Pneumonia congênita devida a agente viral"
* BRCID10#P23 "Pneumonia congênita"
* BRCID10#P22.9 "Desconforto respiratório não especificado do recém-nascido"
* BRCID10#P22.8 "Outros desconfortos respiratórios do recém-nascido"
* BRCID10#P22.1 "Taquipnéia transitória do recém-nascido"
* BRCID10#P22.0 "Síndrome da angústia respiratória do recém-nascido"
* BRCID10#P22 "Desconforto (angústia) respiratório(a) do recém-nascido"
* BRCID10#P21.9 "Asfixia ao nascer, não especificada"
* BRCID10#P21.1 "Asfixia leve ou moderada ao nascer"
* BRCID10#P21.0 "Asfixia grave ao nascer"
* BRCID10#P21 "Asfixia ao nascer"
* BRCID10#P20.9 "Hipóxia intra-uterina não especificada"
* BRCID10#P20.1 "Hipóxia intra-uterina diagnosticada durante o trabalho de parto e o parto"
* BRCID10#P20.0 "Hipóxia intra-uterina diagnosticada antes do início do trabalho de parto"
* BRCID10#P20 "Hipóxia intra-uterina"
* BRCID10#P15.9 "Traumatismo de parto não especificado"
* BRCID10#P15.8 "Outros traumatismos de parto especificados"
* BRCID10#P15.6 "Necrose de gordura subcutânea devida a traumatismo de parto"
* BRCID10#P15.5 "Lesão dos órgãos genitais externos, devida a traumatismo de parto"
* BRCID10#P15.4 "Lesão da face ao nascer"
* BRCID10#P15.3 "Lesão dos olhos devida a traumatismo de parto"
* BRCID10#P15.2 "Lesão do esternomastóide devida a traumatismo de parto"
* BRCID10#P15.1 "Lesão do baço devida a traumatismo de parto"
* BRCID10#P15.0 "Lesão do fígado devida a traumatismo de parto"
* BRCID10#P15 "Outros traumatismos de parto"
* BRCID10#P14.9 "Lesão não especificada do sistema nervoso periférico devida a traumatismo de parto"
* BRCID10#P14.8 "Outras lesões de outras partes do sistema nervoso periférico devidas a traumatismo de parto"
* BRCID10#P14.3 "Outras lesões do plexo braquial devidas a traumatismo de parto"
* BRCID10#P14.2 "Paralisia do nervo frênico devida a traumatismo de parto"
* BRCID10#P14.1 "Paralisia de Klumpke devida a traumatismo de parto"
* BRCID10#P14.0 "Paralisia de Erb devida a traumatismo de parto"
* BRCID10#P14 "Lesões ao nascer do sistema nervoso periférico"
* BRCID10#P13.9 "Lesões não especificadas do esqueleto devidas a traumatismo de parto"
* BRCID10#P13.8 "Lesões de outras partes do esqueleto devidas a traumatismo de parto"
* BRCID10#P13.4 "Fratura da clavícula devida a traumatismo de parto"
* BRCID10#P13.3 "Lesão de outros ossos longos devida a traumatismo de parto"
* BRCID10#P13.2 "Lesão do fêmur devida a traumatismo de parto"
* BRCID10#P13.1 "Outras lesões cranianas devidas a traumatismo de parto"
* BRCID10#P13.0 "Fratura de crânio devida a traumatismo de parto"
* BRCID10#P13 "Lesões do esqueleto devidas a traumatismo de parto"
* BRCID10#P12.9 "Lesão não especificada do couro cabeludo devida a traumatismo de parto"
* BRCID10#P12.8 "Outras lesões do couro cabeludo devidas a traumatismo de parto"
* BRCID10#P12.4 "Lesão por monitorização do couro cabeludo do recém-nascido"
* BRCID10#P12.3 "Esmagamento do couro cabeludo devido a traumatismo de parto"
* BRCID10#P12.2 "Hemorragia subaponeurótica epicraniana devida a traumatismo de parto"
* BRCID10#P12.1 "Chignon devido a traumatismo de parto"
* BRCID10#P12.0 "Céfalo-hematoma devido a traumatismo de parto"
* BRCID10#P12 "Lesão do couro cabeludo devida a traumatismo de parto"
* BRCID10#P11.9 "Traumatismo de parto não especificado do sistema nervoso central"
* BRCID10#P11.5 "Traumatismo de parto da coluna e da medula espinhal"
* BRCID10#P11.4 "Traumatismo de parto de outros nervos cranianos"
* BRCID10#P11.3 "Traumatismo de parto do nervo facial"
* BRCID10#P11.2 "Lesão cerebral não especificada devida a traumatismo de parto"
* BRCID10#P11.1 "Outras lesões cerebrais especificadas devidas a traumatismo de parto"
* BRCID10#P11.0 "Edema cerebral devido a traumatismo de parto"
* BRCID10#P11 "Outros traumatismos de parto do sistema nervoso central"
* BRCID10#P10.9 "Laceração e hemorragia intracranianas não especificadas devidas a traumatismo de parto"
* BRCID10#P10.8 "Outras lacerações e hemorragias intracranianas devidas a traumatismo de parto"
* BRCID10#P10.4 "Ruptura tentorial devida a traumatismo de parto"
* BRCID10#P10.3 "Hemorragia subaracnoídea devida a traumatismo de parto"
* BRCID10#P10.2 "Hemorragia intraventricular devida a traumatismo de parto"
* BRCID10#P10.1 "Hemorragia cerebral devida a traumatismo de parto"
* BRCID10#P10.0 "Hemorragia subdural devida a traumatismo de parto"
* BRCID10#P10 "Laceração intracraniana e hemorragia devidas a traumatismo de parto"
* BRCID10#P08.2 "Recém-nascido pós-termo, não-grande para a idade gestacional"
* BRCID10#P08.1 "Outros recém-nascidos grandes para a idade gestacional"
* BRCID10#P08.0 "Recém-nascido de tamanho excessivamente grande"
* BRCID10#P08 "Transtornos relacionados com a gestação prolongada e peso elevado ao nascer"
* BRCID10#P07.3 "Outros recém-nascidos de pré-termo"
* BRCID10#P07.2 "Imaturidade extrema"
* BRCID10#P07.1 "Outros recém-nascidos de peso baixo"
* BRCID10#P07.0 "Recém-nascido com peso muito baixo"
* BRCID10#P07 "Transtornos relacionados com a gestação de curta duração e peso baixo ao nascer não classificados em outra parte"
* BRCID10#P05.9 "Retardo não especificado do crescimento fetal"
* BRCID10#P05.2 "Desnutrição fetal sem menção de peso e comprimento baixos para a idade gestacional"
* BRCID10#P05.1 "Pequeno para a idade gestacional"
* BRCID10#P05.0 "Recém-nascido de baixo peso para a idade gestacional"
* BRCID10#P05 "Crescimento fetal retardado e desnutrição fetal"
* BRCID10#P04.9 "Feto e recém-nascido afetados por influências nocivas maternas não especificadas"
* BRCID10#P04.8 "Feto e recém-nascido afetados por outras influências nocivas maternas"
* BRCID10#P04.6 "Feto e recém-nascido afetados pela exposição da mãe a substâncias químicas do meio ambiente"
* BRCID10#P04.5 "Feto e recém-nascido afetados por uso materno de substâncias químicas dos alimentos"
* BRCID10#P04.4 "Feto e recém-nascido afetados pelo uso de drogas que causam dependência pela mãe"
* BRCID10#P04.3 "Feto e recém-nascido afetados pelo uso de álcool pela mãe"
* BRCID10#P04.2 "Feto e recém-nascido afetados pelo uso de fumo pela mãe"
* BRCID10#P04.1 "Feto e recém-nascido afetados por outros medicamentos utilizados pela mãe"
* BRCID10#P04.0 "Feto e recém-nascido afetados por anestesia e analgesia materna durante a gravidez, trabalho de parto e parto"
* BRCID10#P04 "Feto e recém-nascido afetados por influências nocivas transmitidas ao feto via placenta ou leite materno"
* BRCID10#P03.9 "Feto e recém-nascido afetados por complicações não especificadas do trabalho de parto e do parto"
* BRCID10#P03.8 "Feto e recém-nascido afetados por outras complicações especificadas do trabalho de parto e do parto"
* BRCID10#P03.6 "Feto e recém-nascido afetados por contrações uterinas anormais"
* BRCID10#P03.5 "Feto e recém-nascido afetados por parto precipitado"
* BRCID10#P03.4 "Feto e recém-nascido afetados por parto por cesariana"
* BRCID10#P03.3 "Feto e recém-nascido afetados por parto por vácuo-extrator [ventosa]"
* BRCID10#P03.2 "Feto e recém-nascido afetados por parto por fórceps"
* BRCID10#P03.1 "Feto e recém-nascido afetados por outras apresentações anormais, má-posições e desproporções durante o trabalho de parto e o par"
* BRCID10#P03.0 "Feto e recém-nascido afetados por parto e extração pélvicas"
* BRCID10#P03 "Feto e recém-nascido afetados por outras complicações do trabalho de parto e do parto"
* BRCID10#P02.9 "Feto e recém-nascido afetados por anormalidade não especificada das membranas"
* BRCID10#P02.8 "Feto e recém-nascido afetados por outras anormalidades das membranas"
* BRCID10#P02.7 "Feto e recém-nascido afetados por corioamnionite"
* BRCID10#P02.6 "Feto e recém-nascido afetados por outras afecções do cordão umbilical e as não especificadas"
* BRCID10#P02.5 "Feto e recém-nascido afetados por outras compressões do cordão umbilical"
* BRCID10#P02.4 "Feto e recém-nascido afetados por prolapso de cordão umbilical"
* BRCID10#P02.3 "Feto e recém-nascido afetados por síndromes de transfusão placentária"
* BRCID10#P02.2 "Feto e recém-nascido afetados por outras anormalidades morfológicas e funcionais da placenta e as não especificadas"
* BRCID10#P02.1 "Feto e recém-nascido afetados por outras formas de descolamento da placenta e hemorragia"
* BRCID10#P02.0 "Feto e recém-nascido afetados por placenta prévia"
* BRCID10#P02 "Feto e recém-nascido afetados por complicações da placenta, do cordão umbilical e das membranas"
* BRCID10#P01.9 "Feto e recém-nascido afetados por afecções maternas da gravidez, não especificadas"
* BRCID10#P01.8 "Feto e recém-nascido afetados por outras complicações maternas da gravidez"
* BRCID10#P01.7 "Feto e recém-nascido afetados por apresentação anormal antes do trabalho de parto"
* BRCID10#P01.6 "Feto e recém-nascido afetados por morte materna"
* BRCID10#P01.5 "Feto e recém-nascido afetados por gravidez múltipla"
* BRCID10#P01.4 "Feto e recém-nascido afetados por gravidez ectópica"
* BRCID10#P01.3 "Feto e recém-nascido afetados por polihidrâmnio"
* BRCID10#P01.2 "Feto e recém-nascido afetados por oligohidrâmnio"
* BRCID10#P01.1 "Feto e recém-nascido afetados por ruptura prematura das membranas"
* BRCID10#P01.0 "Feto e recém-nascido afetados por incompetência do colo uterino"
* BRCID10#P01 "Feto e recém-nascido afetados por complicações maternas da gravidez"
* BRCID10#P00.9 "Feto e recém-nascido afetados por afecção materna não especificada"
* BRCID10#P00.8 "Feto e recém-nascido afetados por outras afecções maternas"
* BRCID10#P00.7 "Feto e recém-nascido afetados por outros procedimentos médicos na mãe, não classificados em outra parte"
* BRCID10#P00.6 "Feto e recém-nascido afetados por intervenção cirúrgica na mãe"
* BRCID10#P00.5 "Feto e recém-nascido afetados por traumatismo materno"
* BRCID10#P00.4 "Feto e recém-nascido afetados por transtornos nutricionais maternos"
* BRCID10#P00.3 "Feto e recém-nascido afetados por outras doenças circulatórias e respiratórias maternas"
* BRCID10#P00.2 "Feto e recém-nascido afetados por doenças infecciosas e parasitárias da mãe"
* BRCID10#P00.1 "Feto e recém-nascido afetados por doenças maternas renais e das vias urinárias"
* BRCID10#P00.0 "Feto e recém-nascido afetados por transtornos maternos hipertensivos"
* BRCID10#P00 "Feto e recém-nascido afetados por afecções maternas, não obrigatoriamente relacionadas com a gravidez atual"
* BRCID10#O99.8 "Outras doenças e afecções especificadas complicando a gravidez, o parto e o puerpério"
* BRCID10#O99.7 "Doenças da pele e do tecido subcutâneo complicando a gravidez, o parto e o puerpério"
* BRCID10#O99.6 "Doenças do aparelho digestivo complicando a gravidez, o parto e o puerpério"
* BRCID10#O99.5 "Doenças do aparelho respiratório complicando a gravidez, o parto e o puerpério"
* BRCID10#O99.4 "Doenças do aparelho circulatório complicando a gravidez, o parto e o puerpério"
* BRCID10#O99.3 "Transtornos mentais e doenças do sistema nervoso complicando a gravidez, o parto e o puerpério"
* BRCID10#O99.2 "Doenças endócrinas, nutricionais e metabólicas complicando a gravidez, o parto e o puerpério"
* BRCID10#O99.1 "Outras doenças do sangue e dos órgãos hematopoéticos e alguns transtornos que comprometem o sistema imunológico, complicando a g"
* BRCID10#O99.0 "Anemia complicando a gravidez, o parto e o puerpério"
* BRCID10#O99 "Outras doenças da mãe, classificadas em outra parte, mas que complicam a gravidez o parto e o puerpério"
* BRCID10#O98.9 "Doenças infecciosas e parasitárias maternas, não especificadas, complicando a gravidez, o parto e o puerpério"
* BRCID10#O98.8 "Outras doenças infecciosas e parasitárias maternas complicando a gravidez, o parto e o puerpério"
* BRCID10#O98.6 "Doenças causadas por protozoários complicando a gravidez, o parto e o puerpério"
* BRCID10#O98.5 "Outras doenças virais complicando a gravidez, o parto e o puerpério"
* BRCID10#O98.4 "Hepatite viral complicando a gravidez, o parto e o puerpério"
* BRCID10#O98.3 "Outras infecções em que a via de transmissão é predominantemente sexual, complicando a gravidez, o parto e o puerpério"
* BRCID10#O98.2 "Gonorréia complicando a gravidez, o parto e o puerpério"
* BRCID10#O98.1 "Sífilis complicando a gravidez, o parto e o puerpério"
* BRCID10#O98.0 "Tuberculose complicando a gravidez, o parto e o puerpério"
* BRCID10#O98 "Doenças infecciosas e parasitárias maternas classificáveis em outra parte mas que compliquem a gravidez, o parto e o puerpério"
* BRCID10#O97 "Morte por seqüelas de causas obstétricas diretas"
* BRCID10#O96 "Morte, por qualquer causa obstétrica, que ocorre mais de 42 dias, mas menos de 1 ano, após o parto"
* BRCID10#O95 "Morte obstétrica de causa não especificada"
* BRCID10#O94 "Seqüelas de complicações da gravidez, parto e puerpério"
* BRCID10#O92.7 "Outros distúrbios da lactação e os não especificados"
* BRCID10#O92.6 "Galactorréia"
* BRCID10#O92.5 "Suspensão da lactação"
* BRCID10#O92.4 "Hipogalactia"
* BRCID10#O92.3 "Agalactia"
* BRCID10#O92.2 "Outras afecções da mama, e as não especificadas, associadas ao parto"
* BRCID10#O92.1 "Fissuras do mamilo associadas ao parto"
* BRCID10#O92.0 "Mamilo retraído associado ao parto"
* BRCID10#O92 "Outras afecções da mama e da lactação associadas ao parto"
* BRCID10#O91.2 "Mastite não purulenta associada ao parto"
* BRCID10#O91.1 "Abscesso da mama associada ao parto"
* BRCID10#O91.0 "Infecção do mamilo associada ao parto"
* BRCID10#O91 "Infecções mamárias associadas ao parto"
* BRCID10#O90.9 "Complicação do puerpério não especificada"
* BRCID10#O90.8 "Outras complicações do puerpério, não classificadas em outra parte"
* BRCID10#O90.5 "Tireoidite do pós-parto"
* BRCID10#O90.4 "Insuficiência renal aguda do pós-parto"
* BRCID10#O90.3 "Cardiomiopatia no puerpério"
* BRCID10#O90.2 "Hematoma da incisão obstétrica"
* BRCID10#O90.1 "Ruptura da incisão obstétrica, no períneo"
* BRCID10#O90.0 "Ruptura da incisão de cesariana"
* BRCID10#O90 "Complicações do puerpério não classificadas em outra parte"
* BRCID10#O89.9 "Complicação devida a anestesia, durante o puerpério, não especificada"
* BRCID10#O89.8 "Outras complicações da anestesia durante o puerpério"
* BRCID10#O89.6 "Falha na ou dificuldade de entubação, durante o puerpério"
* BRCID10#O89.5 "Outras complicações de anestesia raquidiana ou peridural, durante o puerpério"
* BRCID10#O89.4 "Cefaléia provocada por uma anestesia raquidiana ou peridural, durante o puerpério"
* BRCID10#O89.3 "Reação tóxica a uma anestesia local durante o puerpério"
* BRCID10#O89.2 "Complicações relativas ao sistema nervoso central devidas a anestesia durante o puerpério"
* BRCID10#O89.1 "Complicações cardíacas devidas a anestesia durante o puerpério"
* BRCID10#O89.0 "Complicações pulmonares da anestesia durante o puerpério"
* BRCID10#O89 "Complicações da anestesia administrada durante o puerpério"
* BRCID10#O88.8 "Outras embolias de origem obstétrica"
* BRCID10#O88.3 "Embolia séptica ou piêmica de origem obstétrica"
* BRCID10#O88.2 "Embolia obstétrica por coágulo de sangue"
* BRCID10#O88.1 "Embolia amniótica"
* BRCID10#O88.0 "Embolia gasosa de origem obstétrica"
* BRCID10#O88 "Embolia de origem obstétrica"
* BRCID10#O87.9 "Complicações venosas no puerpério, não especificadas"
* BRCID10#O87.8 "Outras complicações venosas no puerpério"
* BRCID10#O87.3 "Trombose venosa cerebral no puerpério"
* BRCID10#O87.2 "Hemorróidas no puerpério"
* BRCID10#O87.1 "Tromboflebite profunda no puerpério"
* BRCID10#O87.0 "Tromboflebite superficial no puerpério"
* BRCID10#O87 "Complicações venosas no puerpério"
* BRCID10#O86.8 "Outras infecções puerperais especificadas"
* BRCID10#O86.4 "Febre de origem desconhecida subseqüente ao parto"
* BRCID10#O86.3 "Outras infecções das vias genitourinárias subseqüentes ao parto"
* BRCID10#O86.2 "Infecção das vias urinárias subseqüentes ao parto"
* BRCID10#O86.1 "Outras infecções dos órgãos genitais subseqüentes ao parto"
* BRCID10#O86.0 "Infecção da incisão cirúrgica de origem obstétrica"
* BRCID10#O86 "Outras infecções puerperais"
* BRCID10#O85 "Infecção puerperal"
* BRCID10#O84.9 "Parto múltiplo, não especificado"
* BRCID10#O84.8 "Outro tipo de parto múltiplo"
* BRCID10#O84.2 "Parto múltiplo, todos por cesariana"
* BRCID10#O84.1 "Parto múltiplo, todos por fórceps ou vácuo-extrator"
* BRCID10#O84.0 "Parto múltiplo, todos espontâneos"
* BRCID10#O84 "Parto múltiplo"
* BRCID10#O83.9 "Parto único assistido, não especificado"
* BRCID10#O83.8 "Outros tipos especificados de parto único assistido"
* BRCID10#O83.4 "Cirurgia destrutiva para facilitar o parto"
* BRCID10#O83.3 "Parto de gravidez intra-abdominal com feto viável"
* BRCID10#O83.2 "Outras formas de parto com o auxílio de manipulação"
* BRCID10#O83.1 "Outros tipos de parto pélvico assistido"
* BRCID10#O83.0 "Extração pélvica"
* BRCID10#O83 "Outros tipos de parto único assistido"
* BRCID10#O82.9 "Parto por cesariana, não especificada"
* BRCID10#O82.8 "Outros tipos de parto único por cesariana"
* BRCID10#O82.2 "Parto por cesariana para histerectomia"
* BRCID10#O82.1 "Parto por cesariana de emergência"
* BRCID10#O82.0 "Parto por cesariana eletiva"
* BRCID10#O82 "Parto único por cesariana"
* BRCID10#O81.5 "Parto por combinação de fórceps e vácuo-extrator"
* BRCID10#O81.4 "Parto por vácuo-extrator"
* BRCID10#O81.3 "Outros tipos de parto por fórceps e os não especificados"
* BRCID10#O81.2 "Fórceps da cavidade mediana com rotação"
* BRCID10#O81.1 "Parto por fórceps da cavidade mediana"
* BRCID10#O81.0 "Parto por fórceps baixo"
* BRCID10#O81 "Parto único por fórceps ou vácuo-extrator"
* BRCID10#O80.9 "Parto único espontâneo, não especificado"
* BRCID10#O80.8 "Outros tipos de parto único espontâneo"
* BRCID10#O80.1 "Parto espontâneo pélvico"
* BRCID10#O80.0 "Parto espontâneo cefálico"
* BRCID10#O80 "Parto único espontâneo"
* BRCID10#O75.9 "Complicações do trabalho de parto e do parto, não especificadas"
* BRCID10#O75.8 "Outras complicações especificadas do trabalho de parto e do parto"
* BRCID10#O75.7 "Parto vaginal subseqüente a cesariana anterior"
* BRCID10#O75.6 "Demora do parto após ruptura espontânea ou não especificada das membranas"
* BRCID10#O75.5 "Demora do parto após ruptura artificial das membranas"
* BRCID10#O75.4 "Outras complicações de procedimentos ou de cirurgia obstétrica"
* BRCID10#O75.3 "Outras infecções durante o trabalho de parto"
* BRCID10#O75.2 "Febre durante o trabalho de parto não classificada em outra parte"
* BRCID10#O75.1 "Choque durante ou subseqüente ao trabalho de parto e o parto"
* BRCID10#O75.0 "Sofrimento materno durante o trabalho de parto e o parto"
* BRCID10#O75 "Outras complicações do trabalho de parto e do parto não classificadas em outra parte"
* BRCID10#O74.9 "Complicações de anestesia durante o trabalho de parto e parto, não especificadas"
* BRCID10#O74.8 "Outras complicações de anestesia durante o trabalho de parto e parto"
* BRCID10#O74.7 "Falha ou dificuldade de entubação durante o trabalho de parto e parto"
* BRCID10#O74.6 "Outras complicações de anestesia raquidiana ou peridural, durante o trabalho de parto e parto"
* BRCID10#O74.5 "Cefaléia pós-anestesia raquidiana e peridural, durante o trabalho de parto e parto"
* BRCID10#O74.4 "Reação tóxica a anestesia local durante trabalho de parto e o parto"
* BRCID10#O74.3 "Complicações do sistema nervoso central devidas a anestesia durante o trabalho de parto e no parto"
* BRCID10#O74.2 "Complicações cardíacas devidas a anestesia durante o trabalho de parto e no parto"
* BRCID10#O74.1 "Outras complicações pulmonares devidas a anestesia durante o trabalho de parto e no parto"
* BRCID10#O74.0 "Pneumonite aspirativa devida a anestesia durante o trabalho de parto e o parto"
* BRCID10#O74 "Complicações de anestesia durante o trabalho de parto e o parto"
* BRCID10#O73.1 "Retenção de partes da placenta ou das membranas, sem hemorragia"
* BRCID10#O73.0 "Retenção da placenta sem hemorragia"
* BRCID10#O73 "Retenção da placenta e das membranas, sem hemorragias"
* BRCID10#O72.3 "Deficiências de coagulação pós-parto"
* BRCID10#O72.2 "Hemorragias pós-parto, tardias e secundárias"
* BRCID10#O72.1 "Outras hemorragias do pós-parto imediato"
* BRCID10#O72.0 "Hemorragia do terceiro estágio"
* BRCID10#O72 "Hemorragia pós-parto"
* BRCID10#O71.9 "Traumatismo obstétrico, não especificado"
* BRCID10#O71.8 "Outros traumatismos obstétricos especificados"
* BRCID10#O71.7 "Hematoma obstétrico da pelve"
* BRCID10#O71.6 "Lesão obstétrica das articulações e dos ligamentos pélvicos"
* BRCID10#O71.5 "Outras lesões obstétricas aos órgãos pélvicos"
* BRCID10#O71.4 "Laceração vaginal alta isolada, de origem obstétrica"
* BRCID10#O71.3 "Laceração obstétrica do colo do útero"
* BRCID10#O71.2 "Inversão do útero pós-parto"
* BRCID10#O71.1 "Ruptura do útero durante o trabalho de parto"
* BRCID10#O71.0 "Ruptura do útero antes do início do trabalho de parto"
* BRCID10#O71 "Outros traumatismos obstétricos"
* BRCID10#O70.9 "Laceração de períneo durante o parto, não especificada"
* BRCID10#O70.3 "Laceração de períneo de quarto grau durante o parto"
* BRCID10#O70.2 "Laceração de períneo de terceiro grau durante o parto"
* BRCID10#O70.1 "Laceração de períneo de segundo grau durante o parto"
* BRCID10#O70.0 "Laceração de períneo de primeiro grau durante o parto"
* BRCID10#O70 "Laceração do períneo durante o parto"
* BRCID10#O69.9 "Trabalho de parto e parto complicados por complicações do cordão, não especificadas"
* BRCID10#O69.8 "Trabalho de parto e parto complicados por outras complicações do cordão"
* BRCID10#O69.5 "Trabalho de parto e parto complicados por lesão vascular do cordão"
* BRCID10#O69.4 "Trabalho de parto e parto complicados por vasa praevia"
* BRCID10#O69.3 "Trabalho de parto e parto complicados por cordão curto"
* BRCID10#O69.2 "Trabalho de parto e parto complicados por outros enovelamentos do cordão"
* BRCID10#O69.1 "Trabalho de parto e parto complicados por circular de cordão, com compressão"
* BRCID10#O69.0 "Trabalho de parto e parto complicados por prolapso do cordão"
* BRCID10#O69 "Trabalho de parto e parto complicados por anormalidade do cordão umbilical"
* BRCID10#O68.9 "Trabalho de parto e parto complicados por sofrimento fetal, não especificado"
* BRCID10#O68.8 "Trabalho de parto e parto complicados por outras evidências de sofrimento fetal"
* BRCID10#O68.3 "Trabalho de parto e parto complicados por evidências bioquímicas de sofrimento fetal"
* BRCID10#O68.2 "Trabalho de parto e parto complicados por anormalidade na freqüência cardíaca fetal com mecônio no líquido amniótico"
* BRCID10#O68.1 "Trabalho de parto e parto complicados por mecônio no líquido amniótico"
* BRCID10#O68.0 "Trabalho de parto e parto complicados por anormalidade da freqüência cardíaca fetal"
* BRCID10#O68 "Trabalho de parto e parto complicados por sofrimento fetal"
* BRCID10#O67.9 "Hemorragia intraparto não especificada"
* BRCID10#O67.8 "Outras hemorragias intraparto"
* BRCID10#O67.0 "Hemorragia intraparto com deficiência de coagulação"
* BRCID10#O67 "Trabalho de parto e parto complicados por hemorragia intraparto não classificados em outra parte"
* BRCID10#O66.9 "Obstrução do trabalho de parto, não especificado"
* BRCID10#O66.8 "Outras formas de obstrução do trabalho de parto, especificadas"
* BRCID10#O66.5 "Falha de aplicação de fórceps e vácuo-extrator, não especificada"
* BRCID10#O66.4 "Falha de tentativa de trabalho de parto, não especificada"
* BRCID10#O66.3 "Obstrução do trabalho de parto devido a outras anormalidades do feto"
* BRCID10#O66.2 "Obstrução do trabalho de parto por feto excepcionalmente grande"
* BRCID10#O66.1 "Obstrução do trabalho de parto por colisão de gêmeos"
* BRCID10#O66.0 "Obstrução do trabalho de parto devido a distócia de ombro"
* BRCID10#O66 "Outras formas de obstrução do trabalho de parto"
* BRCID10#O65.9 "Obstrução do trabalho de parto devida a anormalidades pélvicas maternas não especificadas"
* BRCID10#O65.8 "Obstrução do trabalho de parto devida a outras anormalidades pélvicas maternas"
* BRCID10#O65.5 "Obstrução do trabalho de parto devida a anormalidade dos órgãos pélvicos maternos"
* BRCID10#O65.4 "Obstrução do trabalho de parto devida a desproporção feto-pélvica, não especificada"
* BRCID10#O65.3 "Obstrução do trabalho de parto devida à contração do estreito inferior ou da cavidade mediana"
* BRCID10#O65.2 "Obstrução do trabalho de parto devida à contração do estreito superior"
* BRCID10#O65.1 "Obstrução do trabalho de parto devida à contração geral da pelve"
* BRCID10#O65.0 "Obstrução do trabalho de parto devida a deformidade pélvica"
* BRCID10#O65 "Obstrução do trabalho de parto devida a anormalidade pélvica da mãe"
* BRCID10#O64.9 "Obstrução do trabalho de parto devida a má-posição ou má-apresentação, não especificadas"
* BRCID10#O64.8 "Obstrução do trabalho de parto devida a outras formas de má-apresentação e má-posição"
* BRCID10#O64.5 "Obstrução do trabalho de parto devida à apresentação complexa"
* BRCID10#O64.4 "Obstrução do trabalho de parto devida à apresentação de ombro"
* BRCID10#O64.3 "Obstrução do trabalho de parto devida à apresentação de fronte"
* BRCID10#O64.2 "Obstrução do trabalho de parto devida à apresentação de face"
* BRCID10#O64.1 "Obstrução do trabalho de parto devida à apresentação pélvica"
* BRCID10#O64.0 "Obstrução do trabalho de parto devida à rotação incompleta do polo cefálico fetal"
* BRCID10#O64 "Obstrução do trabalho de parto devida à má-posição ou má-apresentação do feto"
* BRCID10#O63.9 "Trabalho de parto prolongado, não especificado"
* BRCID10#O63.2 "Parto retardado do segundo gêmeo, do terceiro gêmeo etc"
* BRCID10#O63.1 "Prolongamento do segundo período (expulsão)"
* BRCID10#O63.0 "Prolongamento do primeiro período (dilatação)"
* BRCID10#O63 "Trabalho de parto prolongado"
* BRCID10#O62.9 "Anormalidades da contração uterina, não especificadas"
* BRCID10#O62.8 "Outras anormalidades da contração uterina"
* BRCID10#O62.4 "Contrações uterinas hipertônicas, incoordenadas ou prolongadas"
* BRCID10#O62.3 "Trabalho de parto precipitado"
* BRCID10#O62.2 "Outras formas de inércia uterina"
* BRCID10#O62.1 "Inércia uterina secundária"
* BRCID10#O62.0 "Contrações iniciais inadequadas"
* BRCID10#O62 "Anormalidades da contração uterina"
* BRCID10#O61.9 "Falha na indução do trabalho de parto, não especificada"
* BRCID10#O61.8 "Outras formas de falha na indução do trabalho de parto"
* BRCID10#O61.1 "Falha na indução instrumental do trabalho de parto"
* BRCID10#O61.0 "Falha na indução médica do trabalho de parto"
* BRCID10#O61 "Falha na indução do trabalho de parto"
* BRCID10#O60.2 "Trabalho de parto pré-termo com parto a termo"
* BRCID10#O60.1 "Trabalho de parto pré-termo com parto pré-termo"
* BRCID10#O60.0 "Trabalho de parto pré-termo sem parto"
* BRCID10#O60 "Trabalho de parto pré-termo"
* BRCID10#O48 "Gravidez prolongada"
* BRCID10#O47.9 "Falso trabalho de parto, não especificado"
* BRCID10#O47.1 "Falso trabalho de parto na 37ª semana completa ou depois dela"
* BRCID10#O47.0 "Falso trabalho de parto antes de se completarem 37 semanas de gestação"
* BRCID10#O47 "Falso trabalho de parto"
* BRCID10#O46.9 "Hemorragia anteparto, não especificada"
* BRCID10#O46.8 "Outra forma de hemorragia anteparto"
* BRCID10#O46.0 "Hemorragia anteparto com deficiência de coagulação"
* BRCID10#O46 "Hemorragia anteparto não classificada em outra parte"
* BRCID10#O45.9 "Descolamento prematuro da placenta, não especificado"
* BRCID10#O45.8 "Outro descolamento prematuro da placenta"
* BRCID10#O45.0 "Descolamento prematuro da placenta com deficiência de coagulação"
* BRCID10#O45 "Descolamento prematuro da placenta [abruptio placentae]"
* BRCID10#O44.1 "Placenta prévia com hemorragia"
* BRCID10#O44.0 "Placenta prévia especificada como sem hemorragia"
* BRCID10#O44 "Placenta prévia"
* BRCID10#O43.9 "Transtorno da placenta, não especificado"
* BRCID10#O43.8 "Outros transtornos da placenta"
* BRCID10#O43.1 "Malformação da placenta"
* BRCID10#O43.0 "Síndromes de transfusão placentária"
* BRCID10#O43 "Transtornos da placenta"
* BRCID10#O42.9 "Ruptura prematura de membranas, não especificada"
* BRCID10#O42.2 "Ruptura prematura de membranas, com trabalho de parto retardado por terapêutica"
* BRCID10#O42.1 "Ruptura prematura de membranas, com início do trabalho de parto depois das primeiras 24 horas"
* BRCID10#O42.0 "Ruptura prematura de membranas, com início do trabalho de parto dentro de 24 horas"
* BRCID10#O42 "Ruptura prematura de membranas"
* BRCID10#O41.9 "Transtornos do líquido amniótico e das membranas não especificados"
* BRCID10#O41.8 "Outros transtornos especificados do líquido amniótico e das membranas"
* BRCID10#O41.1 "Infecção do saco amniótico e das membranas"
* BRCID10#O41.0 "Oligohidrâmnio"
* BRCID10#O41 "Outros transtornos das membranas e do líquido amniótico"
* BRCID10#O40 "Polihidrâmnio"
* BRCID10#O36.9 "Assistência prestada à mãe por problema fetal não especificado"
* BRCID10#O36.8 "Assistência prestada à mãe por outros problemas fetais especificados"
* BRCID10#O36.7 "Assistência prestada à mãe por feto viável em gravidez abdominal"
* BRCID10#Z99.9 "Dependência de máquina e aparelho capacitante não especificado"
* BRCID10#O36.6 "Assistência prestada à mãe por crescimento fetal excessivo"
* BRCID10#Z99.8 "Dependência de outras máquinas e aparelhos capacitantes"
* BRCID10#O36.5 "Assistência prestada à mãe por insuficiência de crescimento fetal"
* BRCID10#Z99.3 "Dependência de cadeira de rodas"
* BRCID10#O36.4 "Assistência prestada à mãe por morte intra-uterina"
* BRCID10#Z99.2 "Dependência de diálise renal"
* BRCID10#O36.3 "Assistência prestada à mãe por sinais de hipóxia fetal"
* BRCID10#O36.2 "Assistência prestada à mãe por hidropsia fetal"
* BRCID10#Z99.1 "Dependência de respirador"
* BRCID10#O36.1 "Assistência prestada à mãe por outros tipos de isoimunização"
* BRCID10#Z99.0 "Dependência de aspirador"
* BRCID10#O36.0 "Assistência prestada à mãe por isoimunização Rh"
* BRCID10#Z99 "Dependência de máquinas e dispositivos capacitantes, não classificados em outra parte"
* BRCID10#O36 "Assistência prestada à mãe por outros problemas fetais conhecidos ou suspeitados"
* BRCID10#Z98.8 "Outros estados pós-cirúrgicos especificados"
* BRCID10#O35.9 "Assistência prestada à mãe por lesão ou anormalidade fetais (suspeitadas), não especificadas"
* BRCID10#Z98.2 "Presença de dispositivo de drenagem do líquor"
* BRCID10#O35.8 "Assistência prestada à mãe por outras anormalidades ou lesões fetais (suspeitadas)"
* BRCID10#Z98.1 "Artrodese"
* BRCID10#O35.7 "Assistência prestada à mãe por lesão fetal (suspeitada) causada por outros procedimentos médicos"
* BRCID10#Z98.0 "Derivação intestinal ou anastomose intestinal"
* BRCID10#O35.6 "Assistência prestada à mãe por lesão fetal (suspeitada) causada por radiação"
* BRCID10#Z98 "Outros estados pós-cirúrgicos"
* BRCID10#O35.5 "Assistência prestada à mãe por lesão fetal (suspeitada) causada por drogas"
* BRCID10#Z97.8 "Presença de outros dispositivos especificados"
* BRCID10#O35.4 "Assistência prestada à mãe por lesão (suspeitada) causada ao feto por alcoolismo materno"
* BRCID10#Z97.5 "Presença de dispositivo anticoncepcional intra-uterino [DIU]"
* BRCID10#O35.3 "Assistência prestada à mãe por lesão fetal (suspeitada) causada por doença viral materna"
* BRCID10#Z97.4 "Presença de aparelho externo de surdez"
* BRCID10#O35.2 "Assistência prestada à mãe por doença hereditária (suspeitada) do feto"
* BRCID10#Z97.3 "Presença de óculos e de lentes de contato"
* BRCID10#O35.1 "Assistência prestada à mãe por anormalidade cromossômica (suspeitada) do feto"
* BRCID10#Z97.2 "Presença de dispositivo protético dentário (completo) (parcial)"
* BRCID10#O35.0 "Assistência prestada à mãe por malformação do sistema nervoso central do feto (suspeitada)"
* BRCID10#Z97.1 "Presença de membro artificial (completo) (parcial)"
* BRCID10#O35 "Assistência prestada à mãe por anormalidade e lesão fetais, conhecidas ou suspeitadas"
* BRCID10#Z97.0 "Presença de olho artificial"
* BRCID10#O34.9 "Assistência prestada à mãe por anormalidade de órgãos pélvicos, não especificada"
* BRCID10#Z97 "Presença de outros dispositivos protéticos"
* BRCID10#O34.8 "Assistência prestada à mãe por outras anormalidades dos órgãos pélvicos"
* BRCID10#Z96.9 "Presença de implante funcional não especificado"
* BRCID10#O34.7 "Assistência prestada à mãe por anormalidade da vulva e do períneo"
* BRCID10#Z96.8 "Presença de outros implantes funcionais especificados"
* BRCID10#O34.6 "Assistência prestada à mãe por anormalidade da vagina"
* BRCID10#Z96.7 "Presença de outros implantes de osso e tendão"
* BRCID10#O34.5 "Assistência prestada à mãe por outras anormalidades do útero gravídico"
* BRCID10#Z96.6 "Presença de implantes articulares ortopédicos"
* BRCID10#Z96.5 "Presença de raiz dentária e implantes mandibulares"
* BRCID10#O34.4 "Assistência prestada à mãe por outras anormalidades do colo do útero"
* BRCID10#Z96.4 "Presença de implantes endócrinos"
* BRCID10#O34.3 "Assistência prestada à mãe por incompetência cervical"
* BRCID10#Z96.3 "Presença de laringe artificial"
* BRCID10#O34.2 "Assistência prestada à mãe por cicatriz uterina devida a uma cirurgia anterior"
* BRCID10#Z96.2 "Presença de implante otológicos e audiológicos"
* BRCID10#O34.1 "Assistência prestada à mãe por tumor do corpo do útero"
* BRCID10#Z96.1 "Presença de lente intra-ocular"
* BRCID10#O34.0 "Assistência à mãe por malformação congênita do útero"
* BRCID10#O34 "Assistência prestada à mãe por anormalidade, conhecida ou suspeita, dos órgãos pélvicos maternos"
* BRCID10#Z96.0 "Presença de implantes urogenitais"
* BRCID10#O33.9 "Assistência prestada à mãe por uma desproporção, não especificada"
* BRCID10#Z96 "Presença de outros implantes funcionais"
* BRCID10#O33.8 "Assistência prestada à mãe por uma desproporção de outra origem"
* BRCID10#Z95.9 "Presença de implante e enxerto cardíaco e vascular não especificado"
* BRCID10#O33.7 "Assistência prestada à mãe por uma desproporção devida a outras deformidades fetais"
* BRCID10#Z95.8 "Presença de outros implantes e enxertos cardíacos e vasculares"
* BRCID10#O33.6 "Assistência prestada à mãe por uma desproporção devida a feto hidrocefálico"
* BRCID10#Z95.5 "Presença de implante e enxerto de angioplastia coronária"
* BRCID10#O33.5 "Assistência prestada à mãe por uma desproporção devida a feto excepcionalmente grande"
* BRCID10#Z95.4 "Presença de outras substituições valvares cardíacas"
* BRCID10#O33.4 "Assistência prestada à mãe por uma desproporção de origem mista, materna e fetal"
* BRCID10#Z95.3 "Presença de valva cardíaca xenógena"
* BRCID10#O33.3 "Assistência prestada à mãe por uma desproporção devida à contração do estreito inferior da pelve"
* BRCID10#Z95.2 "Presença de prótese de válvula cardíaca"
* BRCID10#O33.2 "Assistência prestada à mãe por uma desproporção devida à contração do estreito superior da pelve"
* BRCID10#Z95.1 "Presença de enxerto de ponte [\"bypass\"] aortocoronária"
* BRCID10#O33.1 "Assistência prestada à mãe por uma desproporção devida à contração geral da pelve"
* BRCID10#Z95.0 "Presença de marca-passo cardíaco"
* BRCID10#O33.0 "Assistência prestada à mãe por uma desproporção devida à deformidade da pelve óssea materna"
* BRCID10#Z95 "Presença de implantes e enxertos cardíacos e vasculares"
* BRCID10#O33 "Assistência prestada à mãe por uma desproporção conhecida ou suspeita"
* BRCID10#Z94.9 "Órgão e tecido não especificado transplantado"
* BRCID10#O32.9 "Assistência prestada à mãe por apresentação anormal do feto, não especificada"
* BRCID10#Z94.8 "Outros órgãos e tecidos transplantados"
* BRCID10#O32.8 "Assistência prestada à mãe por outras formas de apresentação anormal do feto"
* BRCID10#Z94.7 "Córnea transplantada"
* BRCID10#O32.6 "Assistência prestada à mãe por apresentação composta"
* BRCID10#Z94.6 "Osso transplantado"
* BRCID10#O32.5 "Assistência prestada à mãe por gestação múltipla com apresentação anormal de um ou mais fetos"
* BRCID10#Z94.5 "Pele transplantada"
* BRCID10#O32.4 "Assistência prestada à mãe por polo cefálico alto em gestação a termo"
* BRCID10#Z94.4 "Fígado transplantado"
* BRCID10#O32.3 "Assistência prestada à mãe por apresentação de face, mento e fronte"
* BRCID10#Z94.3 "Coração e pulmões transplantados"
* BRCID10#O32.2 "Assistência prestada à mãe por posição fetal transversa e oblíqua"
* BRCID10#Z94.2 "Pulmão transplantado"
* BRCID10#O32.1 "Assistência prestada à mãe por apresentação pélvica"
* BRCID10#Z94.1 "Coração transplantado"
* BRCID10#O32.0 "Assistência prestada à mãe por posição fetal instável"
* BRCID10#Z94.0 "Rim transplantado"
* BRCID10#O32 "Assistência prestada à mãe por motivo de apresentação anormal, conhecida ou suspeitada, do feto"
* BRCID10#Z94 "Órgãos e tecidos transplantados"
* BRCID10#O31.8 "Outras complicações específicas de gestação múltipla"
* BRCID10#Z93.9 "Orifício artificial não especificado"
* BRCID10#O31.2 "Continuação da gravidez após a morte intra-uterina de um ou mais fetos"
* BRCID10#Z93.8 "Outros orifícios artificiais"
* BRCID10#O31.1 "Continuação da gravidez após aborto de um ou mais fetos"
* BRCID10#Z93.6 "Outros orifícios artificiais do aparelho urinário"
* BRCID10#O31.0 "Feto papiráceo"
* BRCID10#Z93.5 "Cistostomia"
* BRCID10#O31 "Complicações específicas de gestação múltipla"
* BRCID10#Z93.4 "Outros orifícios artificiais do trato gastrointestinal"
* BRCID10#O30.9 "Gestação múltipla, não especificada"
* BRCID10#Z93.3 "Colostomia"
* BRCID10#O30.8 "Outras gestações múltiplas"
* BRCID10#Z93.2 "Ileostomia"
* BRCID10#O30.2 "Gravidez quadrigemelar"
* BRCID10#Z93.1 "Gastrostomia"
* BRCID10#O30.1 "Gravidez trigemelar"
* BRCID10#Z93.0 "Traqueostomia"
* BRCID10#O30.0 "Gravidez dupla"
* BRCID10#Z93 "Orifícios artificiais"
* BRCID10#O30 "Gestação múltipla"
* BRCID10#Z92.9 "História pessoal de tratamento médico não especificado"
* BRCID10#O29.9 "Complicações de anestesia durante a gravidez, não especificadas"
* BRCID10#Z92.8 "História pessoal de outros tratamentos médicos"
* BRCID10#O29.8 "Outras complicações de anestesia durante a gravidez"
* BRCID10#Z92.6 "História pessoal de quimioterapia para doença neoplásica"
* BRCID10#O29.6 "Falha ou dificuldade na entubação durante a gravidez"
* BRCID10#Z92.5 "História pessoal de medidas de reabilitação"
* BRCID10#O29.5 "Outras complicações de anestesia raquidiana ou peridural administradas durante a gravidez"
* BRCID10#Z92.4 "História pessoal de cirurgia de grande porte não classificada em outra parte"
* BRCID10#O29.4 "Cefaléia causada por anestesia raquidiana ou peridural administradas durante a gravidez"
* BRCID10#Z92.3 "História pessoal de irradiação"
* BRCID10#O29.3 "Reação tóxica causada por anestesia local administrada durante a gravidez"
* BRCID10#Z92.2 "História pessoal de uso de longo prazo (atual) de outros medicamentos"
* BRCID10#O29.2 "Complicações relativas ao sistema nervoso central devidas a anestesia administrada durante a gravidez"
* BRCID10#Z92.1 "História pessoal de uso de longo prazo (atual) de anticoagulantes"
* BRCID10#O29.1 "Complicações cardíacas de anestesia administrada durante a gravidez"
* BRCID10#Z92.0 "História pessoal de anticoncepção"
* BRCID10#O29.0 "Complicações pulmonares de anestesia administrada durante a gravidez"
* BRCID10#Z92 "História pessoal de tratamento médico"
* BRCID10#O29 "Complicações de anestesia administrada durante a gravidez"
* BRCID10#Z91.8 "História pessoal de outros fatores de risco especificados não classificados em outra parte"
* BRCID10#O28.9 "Achados anormais do rastreamento [\"screening\"] antenatal da mãe, não especificados"
* BRCID10#Z91.6 "História pessoal de outros traumas físicos"
* BRCID10#O28.8 "Outros achados anormais do rastreamento [\"screening\"] antenatal da mãe"
* BRCID10#Z91.5 "História pessoal de auto agressão"
* BRCID10#O28.5 "Achados cromossômicos e genéticos anormais do rastreamento [\"screening\"] antenatal da mãe"
* BRCID10#Z91.4 "História pessoal de trauma psicológico não classificado em outra parte"
* BRCID10#O28.4 "Achados radiológicos anormais do rastreamento [\"screening\"] antenatal da mãe"
* BRCID10#Z91.3 "História pessoal de ciclo vigília-sono anormal"
* BRCID10#O28.3 "Achados ultrassonográficos anormais do rastreamento [\"screening\"] antenatal da mãe"
* BRCID10#Z91.2 "História pessoal de má higiene pessoal"
* BRCID10#O28.2 "Achados citológicos anormais do rastreamento [\"screening\"] antenatal da mãe"
* BRCID10#Z91.1 "História pessoal de não aderência a tratamento ou regime médico"
* BRCID10#O28.1 "Achados bioquímicos anormais do rastreamento [\"screening\"] antenatal da mãe"
* BRCID10#Z91.0 "História pessoal de alergia exceto a drogas e a substâncias biológicas"
* BRCID10#Z91 "História pessoal de fatores de risco, não classificados em outra parte"
* BRCID10#O28.0 "Achados hematológicos anormais do rastreamento [\"screening\"] antenatal da mãe"
* BRCID10#Z90.8 "Ausência adquirida de outros órgãos"
* BRCID10#O28 "Achados anormais do rastreamento [\"screening\"] antenatal da mãe"
* BRCID10#Z90.7 "Ausência adquirida de órgão(s) genital(is)"
* BRCID10#O26.9 "Afecções ligadas a gravidez, não especificadas"
* BRCID10#Z90.6 "Ausência adquirida de outras partes do trato urinário"
* BRCID10#O26.8 "Outras afecções especificadas, ligadas a gravidez"
* BRCID10#Z90.5 "Ausência adquirida do rim"
* BRCID10#O26.7 "Subluxação da sínfise (púbica) na gravidez, parto e puerpério"
* BRCID10#Z90.4 "Ausência adquirida de outras partes do trato digestivo"
* BRCID10#O26.6 "Transtornos do fígado na gravidez, no parto e no puerpério"
* BRCID10#Z90.3 "Ausência adquirida de parte do estômago"
* BRCID10#O26.5 "Síndrome da hipotensão materna"
* BRCID10#Z90.2 "Ausência adquirida [de parte] do pulmão"
* BRCID10#O26.4 "Herpes gestacional"
* BRCID10#Z90.1 "Ausência adquirida da(s) mama(s)"
* BRCID10#O26.3 "Retenção de dispositivo intra-uterino contraceptivo (DIU) na gravidez"
* BRCID10#Z90.0 "Ausência adquirida de parte da cabeça e do pescoço"
* BRCID10#O26.2 "Assistência à gravidez por motivo de abortamento habitual"
* BRCID10#Z90 "Ausência adquirida de órgãos não classificados em outra parte"
* BRCID10#O26.1 "Ganho de peso insuficiente na gravidez"
* BRCID10#Z89.9 "Ausência adquirida de membro não especificado"
* BRCID10#O26.0 "Ganho excessivo de peso na gravidez"
* BRCID10#Z89.8 "Ausência adquirida dos membros superiores e inferiores [qualquer nível]"
* BRCID10#O26 "Assistência materna por outras complicações ligadas predominantemente à gravidez"
* BRCID10#Z89.7 "Ausência adquirida de ambos membros inferiores [qualquer nível, exceto somente artelhos]"
* BRCID10#O25 "Desnutrição na gravidez"
* BRCID10#Z89.6 "Ausência adquirida da perna acima do joelho"
* BRCID10#O24.9 "Diabetes mellitus na gravidez, não especificado"
* BRCID10#Z89.5 "Ausência adquirida da perna ao nível ou abaixo do joelho"
* BRCID10#O24.4 "Diabetes mellitus que surge durante a gravidez"
* BRCID10#Z89.4 "Ausência adquirida de pé e tornozelo"
* BRCID10#O24.3 "Diabetes mellitus pré-existente, não especificado"
* BRCID10#Z89.3 "Ausência adquirida de ambos membros superiores [qualquer nível]"
* BRCID10#O24.2 "Diabetes mellitus pré-existente, relacionado com a desnutrição"
* BRCID10#Z89.2 "Ausência adquirida de braço acima do punho"
* BRCID10#O24.1 "Diabetes mellitus pré-existente, não-insulino-dependente"
* BRCID10#Z89.1 "Ausência adquirida de mão e punho"
* BRCID10#O24.0 "Diabetes mellitus pré-existente, insulino-dependente"
* BRCID10#Z89.0 "Ausência adquirida de dedo(s) da mão [inclusive polegar] unilateral"
* BRCID10#O24 "Diabetes mellitus na gravidez"
* BRCID10#Z89 "Ausência adquirida de membros"
* BRCID10#O23.9 "Outras infecções e as não especificadas do trato urinário na gravidez"
* BRCID10#Z88.9 "História pessoal de alergia a drogas, medicamentos e substâncias biológicas não especificadas"
* BRCID10#O23.5 "Infecções do trato genital na gravidez"
* BRCID10#Z88.8 "História pessoal de alergia a outros drogas, medicamentos e substâncias biológicas"
* BRCID10#O23.4 "Infecção não especificada do trato urinário na gravidez"
* BRCID10#Z88.7 "História pessoal de alergia a soro e à vacina"
* BRCID10#O23.3 "Infecções de outras partes do trato urinário na gravidez"
* BRCID10#Z88.6 "História pessoal de alergia a agente analgésico"
* BRCID10#O23.2 "Infecções da uretra na gravidez"
* BRCID10#Z88.5 "História pessoal de alergia a agente narcótico"
* BRCID10#O23.1 "Infecções da bexiga na gravidez"
* BRCID10#Z88.4 "História pessoal de alergia a agente anestésico"
* BRCID10#O23.0 "Infecções do rim na gravidez"
* BRCID10#Z88.3 "História pessoal de alergia a outros agentes antiinfecciosos"
* BRCID10#O23 "Infecções do trato geniturinário na gravidez"
* BRCID10#Z88.2 "História pessoal de alergia às sulfonamidas"
* BRCID10#O22.9 "Complicações venosas na gravidez, não especificadas"
* BRCID10#Z88.1 "História pessoal de alergia a outro agente antibiótico"
* BRCID10#Z88.0 "História pessoal de alergia à penicilina"
* BRCID10#O22.8 "Outras complicações venosas na gravidez"
* BRCID10#Z88 "História pessoal de alergia a drogas, medicamentos e a substâncias biológicas"
* BRCID10#O22.5 "Trombose venosa cerebral na gravidez"
* BRCID10#Z87.8 "História pessoal de outras afecções especificadas"
* BRCID10#O22.4 "Hemorróidas na gravidez"
* BRCID10#Z87.7 "História pessoal de malformações e deformidades congênitas e anomalias cromossômicas"
* BRCID10#O22.3 "Flebotrombose profunda na gravidez"
* BRCID10#Z87.6 "História pessoal de algumas afecções originadas no período perinatal"
* BRCID10#O22.2 "Tromboflebite superficial na gravidez"
* BRCID10#Z87.5 "História pessoal de complicações da gravidez, parto e puerpério"
* BRCID10#O22.1 "Varizes genitais na gravidez"
* BRCID10#Z87.4 "História pessoal de doenças do aparelho geniturinário"
* BRCID10#O22.0 "Varizes dos membros inferiores na gravidez"
* BRCID10#Z87.3 "História pessoal de doenças do sistema osteomuscular e tecido conjuntivo"
* BRCID10#O22 "Complicações venosas na gravidez"
* BRCID10#Z87.2 "História pessoal de doenças da pele e tecido subcutâneo"
* BRCID10#O21.9 "Vômitos da gravidez, não especificados"
* BRCID10#O21.8 "Outras formas de vômitos complicando a gravidez"
* BRCID10#Z87.1 "História pessoal de doenças do aparelho digestivo"
* BRCID10#Z87.0 "História pessoal de doenças do aparelho respiratório"
* BRCID10#O21.2 "Vômitos tardios da gravidez"
* BRCID10#Z87 "História pessoal de outras doenças e afecções"
* BRCID10#O21.1 "Hiperêmese gravídica com distúrbio metabólico"
* BRCID10#Z86.7 "História pessoal de doenças do aparelho circulatório"
* BRCID10#O21.0 "Hiperêmese gravídica leve"
* BRCID10#Z86.6 "História pessoal de doenças do sistema nervoso e dos órgãos dos sentidos"
* BRCID10#O21 "Vômitos excessivos na gravidez"
* BRCID10#Z86.5 "História pessoal de outros transtornos mentais e comportamentais"
* BRCID10#O20.9 "Hemorragia do início da gravidez, não especificada"
* BRCID10#Z86.4 "História pessoal de abuso de substâncias psicoativas"
* BRCID10#O20.8 "Outras hemorragias do início da gravidez"
* BRCID10#Z86.3 "História pessoal de doenças endócrinas, nutricionais e metabólicas"
* BRCID10#O20.0 "Ameaça de aborto"
* BRCID10#Z86.2 "História pessoal de doenças do sangue e dos órgãos hematopoéticos e alguns transtornos imunitários"
* BRCID10#O20 "Hemorragia do início da gravidez"
* BRCID10#Z86.1 "História pessoal de doenças infecciosas e parasitárias"
* BRCID10#O16 "Hipertensão materna não especificada"
* BRCID10#Z86.0 "História pessoal de outras neoplasias"
* BRCID10#O15.9 "Eclâmpsia não especificada quanto ao período"
* BRCID10#Z86 "História pessoal de algumas outras doenças"
* BRCID10#O15.2 "Eclâmpsia no puerpério"
* BRCID10#Z85.9 "História pessoal de neoplasia maligna não especificada"
* BRCID10#O15.1 "Eclâmpsia no trabalho de parto"
* BRCID10#Z85.8 "História pessoal de neoplasias malignas de outros órgãos ou aparelhos"
* BRCID10#O15.0 "Eclâmpsia na gravidez"
* BRCID10#Z85.7 "História pessoal de outras neoplasias malignas do tecido linfático, hematopoético e tecidos correlatos"
* BRCID10#O15 "Eclâmpsia"
* BRCID10#Z85.6 "História pessoal de leucemia"
* BRCID10#O14.9 "Pré-eclâmpsia não especificada"
* BRCID10#Z85.5 "História pessoal de neoplasia maligna de trato urinário"
* BRCID10#O14.1 "Pré-eclâmpsia grave"
* BRCID10#Z85.4 "História pessoal de neoplasia maligna de órgãos genitais"
* BRCID10#O14.0 "Pré-eclâmpsia moderada"
* BRCID10#Z85.3 "História pessoal de neoplasia maligna de mama"
* BRCID10#O14 "Hipertensão gestacional [induzida pela gravidez] com proteinúria significativa"
* BRCID10#Z85.2 "História pessoal de neoplasia maligna de outros órgãos respiratórios e intratorácicos"
* BRCID10#O13 "Hipertensão gestacional [induzida pela gravidez] sem proteinúria significativa"
* BRCID10#Z85.1 "História pessoal de neoplasia maligna de traquéia, brônquio e pulmão"
* BRCID10#O12.2 "Edema gestacional com proteinúria"
* BRCID10#Z85.0 "História pessoal de neoplasia maligna de órgãos digestivos"
* BRCID10#Z85 "História pessoal de neoplasia maligna"
* BRCID10#O12.1 "Proteinúria gestacional"
* BRCID10#O12.0 "Edema gestacional"
* BRCID10#Z84.8 "História familiar de outras afecções especificadas"
* BRCID10#Z84.3 "História familiar de consangüinidade"
* BRCID10#O12 "Edema e proteinúria gestacionais [induzidos pela gravidez], sem hipertensão"
* BRCID10#Z84.2 "História familiar de outras doenças do aparelho geniturinário"
* BRCID10#O11 "Distúrbio hipertensivo pré-existente com proteinúria superposta"
* BRCID10#Z84.1 "História familiar de transtornos do rim e ureter"
* BRCID10#O10.9 "Hipertensão pré-existente não especificada, complicando a gravidez, o parto e o puerpério"
* BRCID10#Z84.0 "História familiar de doenças da pele e do tecido subcutâneo"
* BRCID10#O10.4 "Hipertensão secundária pré-existente complicando a gravidez, o parto e o puerpério"
* BRCID10#Z84 "História familiar de outras afecções"
* BRCID10#O10.3 "Doença cardíaca e renal hipertensiva pré-existente complicando a gravidez, o parto e o puerpério"
* BRCID10#Z83.7 "História familiar das doenças do aparelho digestivo"
* BRCID10#O10.2 "Doença renal hipertensiva pré-existente complicando a gravidez, o parto e o puerpério"
* BRCID10#Z83.6 "História familiar de doenças do aparelho respiratório"
* BRCID10#O10.1 "Doença cardíaca hipertensiva pré-existente complicando a gravidez, o parto e o puerpério"
* BRCID10#Z83.5 "História familiar de outros transtornos dos olhos e dos ouvidos"
* BRCID10#O10.0 "Hipertensão essencial pré-existente complicando a gravidez, o parto e o puerpério"
* BRCID10#Z83.4 "História familiar de outras doenças endócrinas, nutricionais e metabólicas"
* BRCID10#O10 "Hipertensão pré-existente complicando a gravidez, o parto e o puerpério"
* BRCID10#Z83.3 "História familiar de diabetes mellitus"
* BRCID10#O08.9 "Complicações conseqüentes a aborto e gravidez ectópica e molar, não especificadas"
* BRCID10#Z83.2 "História familiar de doenças do sangue e dos órgãos hematopoéticos e alguns transtornos imunitários"
* BRCID10#O08.8 "Outras complicações conseqüentes a aborto e a gravidez ectópica e molar"
* BRCID10#Z83.1 "História familiar de outras doenças infecciosas e parasitárias"
* BRCID10#O08.7 "Outras complicações venosas conseqüentes a aborto e a gravidez ectópica e molar"
* BRCID10#Z83.0 "História familiar de doença pelo vírus da imunodeficiência humana [HIV]"
* BRCID10#O08.6 "Lesão a órgãos e a tecidos pélvicos conseqüentes a aborto e a gravidez ectópica e molar"
* BRCID10#Z83 "História familiar de outros transtornos específicos"
* BRCID10#O08.5 "Distúrbios metabólicos conseqüentes a aborto e a gravidez ectópica e molar"
* BRCID10#Z82.8 "História familiar de outras incapacidades e doenças crônicas que conduzem a incapacitação, não classificadas em outra parte"
* BRCID10#O08.4 "Insuficiência renal conseqüente a aborto e a gravidez ectópica e molar"
* BRCID10#Z82.7 "História familiar de malformações e deformações congênitas e anomalias cromossômicas"
* BRCID10#O08.3 "Choque conseqüente a aborto e a gravidez ectópica e molar"
* BRCID10#Z82.6 "História familiar de artrite e outras doenças do sistema osteomuscular e tecido conjuntivo"
* BRCID10#O08.2 "Embolia conseqüente a aborto e a gravidez ectópica e molar"
* BRCID10#Z82.5 "História familiar de asma e outras doenças respiratórias inferiores crônicas"
* BRCID10#O08.1 "Hemorragia tardia ou excessiva conseqüente a aborto e a gravidez ectópica e molar"
* BRCID10#Z82.4 "História familiar de doença isquêmica do coração e outras doenças do aparelho circulatório"
* BRCID10#O08.0 "Infecção do trato genital e dos órgãos pélvicos conseqüente a aborto e gravidez ectópica e molar"
* BRCID10#Z82.3 "História familiar de acidente vascular cerebral"
* BRCID10#O08 "Complicações conseqüentes a aborto e gravidez ectópica ou molar"
* BRCID10#Z82.2 "História familiar de surdez e perda de audição"
* BRCID10#O07.9 "Outras formas, e as não especificadas, de falha na provocação de aborto, sem complicação"
* BRCID10#Z82.1 "História familiar de cegueira e perda de visão"
* BRCID10#O07.8 "Outras formas, e as não especificadas, de falha na provocação de aborto, com outras complicações ou com complicações não especif"
* BRCID10#Z82.0 "História familiar de epilepsia e de outras doenças do sistema nervoso"
* BRCID10#O07.7 "Outras formas, e as não especificadas, de falha na provocação de aborto, complicadas por embolia"
* BRCID10#Z82 "História familiar de algumas incapacidades e doenças crônicas que conduzem a incapacitação"
* BRCID10#O07.6 "Outras formas, e as não especificadas, de falha na provocação de aborto, complicadas por hemorragia tardia ou excessiva"
* BRCID10#Z81.8 "História familiar de outros transtornos mentais e comportamentais"
* BRCID10#O07.5 "Outras formas, e as não especificadas, de falha na provocação de aborto, complicadas por infecção do trato genital e por infecçã"
* BRCID10#Z81.4 "História familiar de abuso de outra substância"
* BRCID10#O07.4 "Falha de aborto provocado por razões médicas, sem complicações"
* BRCID10#Z81.3 "História familiar de abuso de outra substância psicoativa"
* BRCID10#O07.3 "Falha de aborto provocado por razões médicas, com outras complicações ou com complicações não especificadas"
* BRCID10#Z81.2 "História familiar de abuso de fumo"
* BRCID10#O07.2 "Falha de aborto provocado por razões médicas, complicado por embolia"
* BRCID10#Z81.1 "História familiar de abuso de álcool"
* BRCID10#O07.1 "Falha de aborto provocado por razões médicas, complicado por hemorragia tardia ou excessiva"
* BRCID10#Z81.0 "História familiar de retardo mental"
* BRCID10#O07.0 "Falha de aborto provocado por razões médicas, complicado por infecção do trato genital ou dos órgãos pélvicos"
* BRCID10#Z81 "História familiar de transtornos mentais e comportamentais"
* BRCID10#O07 "Falha de tentativa de aborto"
* BRCID10#Z80.9 "História familiar de neoplasia maligna não especificada"
* BRCID10#O06.9 "Aborto não especificado - completo ou não especificado, sem complicações"
* BRCID10#Z80.8 "História familiar de neoplasia maligna de outros órgãos ou aparelhos"
* BRCID10#O06.8 "Aborto não especificado - completo ou não especificado, com outras complicações ou com complicações não especificadas"
* BRCID10#Z80.7 "História familiar de outras neoplasias malignas dos tecidos linfático, hematopoético e correlacionados"
* BRCID10#O06.7 "Aborto não especificado - completo ou não especificado, complicado por embolia"
* BRCID10#Z80.6 "História familiar de leucemia"
* BRCID10#O06.6 "Aborto não especificado - completo ou não especificado, complicado por hemorragia excessiva ou tardia"
* BRCID10#Z80.5 "História familiar de neoplasia maligna do trato urinário"
* BRCID10#O06.5 "Aborto não especificado - completo ou não especificado, complicado por infecções do trato genital ou dos órgãos pélvicos"
* BRCID10#Z80.4 "História familiar de neoplasia maligna de órgãos genitais"
* BRCID10#O06.4 "Aborto não especificado - incompleto, sem complicações"
* BRCID10#Z80.3 "História familiar de neoplasia de mama"
* BRCID10#O06.3 "Aborto não especificado - incompleto, com outras complicações ou com complicações não especificadas"
* BRCID10#Z80.2 "História familiar de neoplasia maligna de outros órgãos respiratórios e intratorácicos"
* BRCID10#O06.2 "Aborto não especificado - incompleto, complicado por embolia"
* BRCID10#Z80.1 "História familiar de neoplasia maligna de traquéia, brônquio e pulmão"
* BRCID10#O06.1 "Aborto não especificado - incompleto, complicado por hemorragia excessiva ou tardia"
* BRCID10#Z80.0 "História familiar de neoplasia maligna de órgãos digestivos"
* BRCID10#O06.0 "Aborto não especificado - incompleto, complicado por infecção do trato genital ou dos órgãos pélvicos"
* BRCID10#Z80 "História familiar de neoplasia maligna"
* BRCID10#O06 "Aborto não especificado"
* BRCID10#Z76.9 "Pessoa em contato com serviços de saúde em circunstâncias não especificadas"
* BRCID10#O05.9 "Outros tipos de aborto - completo ou não especificado, sem complicações"
* BRCID10#Z76.8 "Contatos com serviços de saúde por outras circunstâncias especificadas"
* BRCID10#O05.8 "Outros tipos de aborto - completo ou não especificado, com outras complicações ou com complicações não especificadas"
* BRCID10#Z76.5 "Pessoa fingindo ser doente [simulação consciente]"
* BRCID10#O05.7 "Outros tipos de aborto - completo ou não especificado, complicado por embolia"
* BRCID10#Z76.4 "Outros pensionistas em estabelecimentos de cuidados de saúde"
* BRCID10#O05.6 "Outros tipos de aborto - completo ou não especificado, complicado por hemorragia excessiva ou tardia"
* BRCID10#Z76.3 "Pessoa em boa saúde acompanhando pessoa doente"
* BRCID10#O05.5 "Outros tipos de aborto - completo ou não especificado, complicado por infecções do trato genital ou dos órgãos pélvicos"
* BRCID10#Z76.2 "Supervisão de cuidado de saúde de outras crianças ou recém-nascidos sadios"
* BRCID10#O05.4 "Outros tipos de aborto - incompleto, sem complicações"
* BRCID10#Z76.1 "Supervisão e cuidado de saúde de crianças assistidas"
* BRCID10#O05.3 "Outros tipos de aborto - incompleto, com outras complicações ou com complicações não especificadas"
* BRCID10#Z76.0 "Emissão de prescrição de repetição"
* BRCID10#O05.2 "Outros tipos de aborto - incompleto, complicado por embolia"
* BRCID10#Z76 "Pessoas em contato com os serviços de saúde em outras circunstâncias"
* BRCID10#O05.1 "Outros tipos de aborto - incompleto, complicado por hemorragia excessiva ou tardia"
* BRCID10#Z75.9 "Problema não especificado relacionado com facilidades médicas e com outros cuidados de saúde"
* BRCID10#O05.0 "Outros tipos de aborto - incompleto, complicado por infecção do trato genital ou dos órgãos pélvicos"
* BRCID10#Z75.8 "Outras dificuldades especificadas relacionadas com facilidades médicas e com outros cuidados de saúde"
* BRCID10#O05 "Outros tipos de aborto"
* BRCID10#Z75.5 "Cuidados dispensados para ajudar às famílias durante as férias"
* BRCID10#O04.9 "Aborto por razões médicas e legais - completo ou não especificado, sem complicações"
* BRCID10#Z75.4 "Outras organizações de cuidados não disponíveis ou não acessíveis"
* BRCID10#O04.8 "Aborto por razões médicas e legais - completo ou não especificado, com outras complicações ou com complicações não especificadas"
* BRCID10#Z75.3 "Facilidades de saúde não disponíveis ou não acessíveis"
* BRCID10#O04.7 "Aborto por razões médicas e legais - completo ou não especificado, complicado por embolia"
* BRCID10#Z75.2 "Outro período de espera para investigação e tratamento"
* BRCID10#O04.6 "Aborto por razões médicas e legais - completo ou não especificado, complicado por hemorragia excessiva ou tardia"
* BRCID10#Z75.1 "Pessoa esperando ser admitida em estabelecimento médico adequado em outra parte"
* BRCID10#O04.5 "Aborto por razões médicas e legais - completo ou não especificado, complicado por infecções do trato genital ou dos órgãos pélvi"
* BRCID10#Z75.0 "Falta de disponibilidade de serviços médicos no domicílio"
* BRCID10#O04.4 "Aborto por razões médicas e legais - incompleto, sem complicações"
* BRCID10#Z75 "Problemas relacionados com as facilidades médicas e outros cuidados de saúde"
* BRCID10#O04.3 "Aborto por razões médicas e legais - incompleto, com outras complicações ou com complicações não especificadas"
* BRCID10#Z74.9 "Problema não especificado relacionado com a dependência de pessoa que oferece cuidados de saúde"
* BRCID10#O04.2 "Aborto por razões médicas e legais - incompleto, complicado por embolia"
* BRCID10#Z74.8 "Outros problemas relacionados com a dependência de pessoa que oferece cuidados de saúde"
* BRCID10#O04.1 "Aborto por razões médicas e legais - incompleto, complicado por hemorragia excessiva ou tardia"
* BRCID10#Z74.3 "Necessidade de supervisão contínua"
* BRCID10#Z74.2 "Necessidade de assistência a domicílio, sendo que nenhuma pessoa do lar é capaz de assegurar os cuidados"
* BRCID10#O04.0 "Aborto por razões médicas e legais - incompleto, complicado por infecção do trato genital ou dos órgãos pélvicos"
* BRCID10#Z74.1 "Necessidade de assistência com cuidados pessoais"
* BRCID10#O04 "Aborto por razões médicas e legais"
* BRCID10#Z74.0 "Mobilidade reduzida"
* BRCID10#O03.9 "Aborto espontâneo - completo ou não especificado, sem complicações"
* BRCID10#Z74 "Problemas relacionados com a dependência de uma pessoa que oferece cuidados de saúde"
* BRCID10#O03.8 "Aborto espontâneo - completo ou não especificado, com outras complicações ou com complicações não especificadas"
* BRCID10#Z73.9 "Problema relacionado com a organização de seu modo de vida não especificado"
* BRCID10#O03.7 "Aborto espontâneo - completo ou não especificado, complicado por embolia"
* BRCID10#Z73.8 "Outros problemas relacionados com a organização do seu modo de vida"
* BRCID10#O03.6 "Aborto espontâneo - completo ou não especificado, complicado por hemorragia excessiva ou tardia"
* BRCID10#Z73.6 "Limites impostos às atividades por invalidez"
* BRCID10#O03.5 "Aborto espontâneo - completo ou não especificado, complicado por infecções do trato genital ou dos órgãos pélvicos"
* BRCID10#O03.4 "Aborto espontâneo - incompleto, sem complicações"
* BRCID10#Z73.5 "Conflito sobre o papel social, não classificado em outra parte"
* BRCID10#O03.3 "Aborto espontâneo - incompleto, com outras complicações ou com complicações não especificadas"
* BRCID10#Z73.4 "Habilidades sociais inadequadas não classificadas em outra parte"
* BRCID10#O03.2 "Aborto espontâneo - incompleto, complicado por embolia"
* BRCID10#Z73.3 "Stress não classificado em outra parte"
* BRCID10#Z73.2 "Falta de repouso e de lazer"
* BRCID10#O03.1 "Aborto espontâneo - incompleto, complicado por hemorragia excessiva ou tardia"
* BRCID10#Z73.1 "Acentuação de traços de personalidade"
* BRCID10#O03.0 "Aborto espontâneo - incompleto, complicado por infecção do trato genital ou dos órgãos pélvicos"
* BRCID10#Z73.0 "Esgotamento"
* BRCID10#O03 "Aborto espontâneo"
* BRCID10#Z73 "Problemas relacionados com a organização de seu modo de vida"
* BRCID10#O02.9 "Produto anormal da concepção, não especificado"
* BRCID10#Z72.9 "Problema não especificado relacionado com o estilo de vida"
* BRCID10#O02.8 "Outros produtos anormais da concepção especificados"
* BRCID10#Z72.8 "Outros problemas relacionados com o estilo de vida"
* BRCID10#O02.1 "Aborto retido"
* BRCID10#Z72.6 "Mania de jogo e apostas"
* BRCID10#O02.0 "Ovo claro e mola não-hidatiforme"
* BRCID10#Z72.5 "Comportamento sexual de alto risco"
* BRCID10#O02 "Outros produtos anormais da concepção"
* BRCID10#Z72.4 "Regime e hábitos alimentares inadequados"
* BRCID10#O01.9 "Mola hidatiforme não especificada"
* BRCID10#Z72.3 "Falta de exercício físico"
* BRCID10#O01.1 "Mola hidatiforme incompleta ou parcial"
* BRCID10#Z72.2 "Uso de droga"
* BRCID10#O01.0 "Mola hidatiforme clássica"
* BRCID10#Z72.1 "Uso de álcool"
* BRCID10#O01 "Mola hidatiforme"
* BRCID10#Z72.0 "Uso do tabaco"
* BRCID10#O00.9 "Gravidez ectópica, não especificada"
* BRCID10#Z72 "Problemas relacionados com o estilo de vida"
* BRCID10#O00.8 "Outras formas de gravidez ectópica"
* BRCID10#Z71.9 "Aconselhamento não especificado"
* BRCID10#O00.2 "Gravidez ovariana"
* BRCID10#Z71.8 "Outros aconselhamentos especificados"
* BRCID10#O00.1 "Gravidez tubária"
* BRCID10#Z71.7 "Aconselhamento a propósito do vírus da imunodeficiência humana [HIV]"
* BRCID10#O00.0 "Gravidez abdominal"
* BRCID10#Z71.6 "Aconselhamento para o abuso de fumo"
* BRCID10#O00 "Gravidez ectópica"
* BRCID10#Z71.5 "Aconselhamento e supervisão para abuso de drogas"
* BRCID10#N99.9 "Transtorno pós-procedimento não especificado do aparelho geniturinário"
* BRCID10#Z71.4 "Aconselhamento e supervisão para abuso de álcool"
* BRCID10#N99.8 "Outros transtornos pós-procedimentos do aparelho geniturinário"
* BRCID10#Z71.3 "Aconselhamento e supervisão dietéticos"
* BRCID10#N99.5 "Mau funcionamento de abertura externa (estoma) do trato urinário"
* BRCID10#Z71.2 "Pessoa que consulta para explicação de achados de exame"
* BRCID10#N99.4 "Aderências do peritônio pélvico pós-procedimentos"
* BRCID10#Z71.1 "Pessoa com medo de uma queixa para a qual não foi feito diagnóstico"
* BRCID10#N99.3 "Prolapso de cúpula de vagina pós-histerectomia"
* BRCID10#Z71.0 "Pessoa que consulta no interesse de um terceiro"
* BRCID10#N99.2 "Aderências pós-operatórias da vagina"
* BRCID10#Z71 "Pessoas em contato com os serviços de saúde para outros aconselhamentos e conselho médico, não classificados em outra parte"
* BRCID10#N99.1 "Estreitamento de uretra pós-procedimentos"
* BRCID10#Z70.9 "Aconselhamento não especificado em matéria de sexualidade"
* BRCID10#N99.0 "Insuficiência renal pós-procedimentos"
* BRCID10#N99 "Transtornos do trato geniturinário pós-procedimentos não classificados em outra parte"
* BRCID10#Z70.8 "Outros aconselhamentos em matéria de sexualidade"
* BRCID10#Z70.3 "Aconselhamento relativo a preocupações associadas relacionadas com as atitudes, o comportamento e orientação em matéria de sexua"
* BRCID10#N98.9 "Complicações não especificadas associadas à fecundação artificial"
* BRCID10#Z70.2 "Aconselhamento relativo ao comportamento e à orientação sexual de um terceiro"
* BRCID10#N98.8 "Outras complicações associadas à fecundação artificial"
* BRCID10#Z70.1 "Aconselhamento relativo ao comportamento e à orientação sexual do sujeito"
* BRCID10#N98.3 "Complicações relacionadas com a tentativa de transferência do embrião"
* BRCID10#Z70.0 "Acompanhamento relativo às atitudes em matéria de sexualidade"
* BRCID10#N98.2 "Complicações relacionadas com a tentativa de introdução do óvulo fecundado artificialmente (in vitro)"
* BRCID10#Z70 "Aconselhamento relativo às atitudes, comportamento e orientação em matéria de sexualidade"
* BRCID10#N98.1 "Hiperestimulação dos ovários"
* BRCID10#Z65.9 "Problemas relacionados com circunstâncias psicossociais não especificadas"
* BRCID10#N98.0 "Infecção associada à inseminação artificial"
* BRCID10#Z65.8 "Outros problemas especificados relacionados com circunstâncias psicossociais"
* BRCID10#N98 "Complicações associadas à fecundação artificial"
* BRCID10#Z65.5 "Exposição a catástrofe, guerra e outras hostilidades"
* BRCID10#N97.9 "Infertilidade feminina não especificada"
* BRCID10#Z65.4 "Vítima de crime ou de atos terroristas"
* BRCID10#N97.8 "Infertilidade feminina de outra origem"
* BRCID10#Z65.3 "Problemas ligados à outras circunstâncias legais"
* BRCID10#N97.4 "Infertilidade feminina associada à fatores do parceiro"
* BRCID10#Z65.2 "Problemas ligados à libertação de prisão"
* BRCID10#N97.3 "Infertilidade feminina de origem cervical"
* BRCID10#Z65.1 "Prisão ou encarceramento"
* BRCID10#N97.2 "Infertilidade feminina de origem uterina"
* BRCID10#Z65.0 "Condenação, sem prisão, por tribunal civil ou criminal"
* BRCID10#N97.1 "Infertilidade feminina de origem tubária"
* BRCID10#Z65 "Problemas relacionados com outras circunstâncias psicossociais"
* BRCID10#N97.0 "Infertilidade feminina associada à anovulação"