ValueSet: BRCondicaoAmostra
Id: BRCondicaoAmostra
Title: "BRCondicaoAmostra"
* ^version = "HEAD"
* ^status = #active
* ^publisher = "MS"
* $BRCondicaoAmostra#QUE "Recipiente quebrado"
* $BRCondicaoAmostra#TEC "Incidente técnico"
* $BRCondicaoAmostra#CIN "Coleta inadequada da amostra"
* $BRCondicaoAmostra#INS "Amostra insuficiente"
* $BRCondicaoAmostra#INC "Cadastro incorreto da amostra"
* $BRCondicaoAmostra#IMP "Amostra imprópria para análise solicitada."
* $BRCondicaoAmostra#NCI "Amostra não correpondente à identificada"
* $BRCondicaoAmostra#FPC "Amostra fora do prazo de coleta"
* $BRCondicaoAmostra#SID "Amostra sem identificação"
* $BRCondicaoAmostra#ILE "Amostra com identificação ilegível"
* $BRCondicaoAmostra#INA "Amostra com identificação inadequada"
* $BRCondicaoAmostra#VAZ "Amostra vazada"
* $v2-0493#CON "Contaminated"
* $v2-0493#LIVE "Live"
* $v2-0493#HEM "Hemolyzed"
* $v2-0493#FROZ "Frozen"
* $v2-0493#CFU "Centrifuged"
* $v2-0493#AUT "Autolyzed"
* $v2-0493#CLOT "Clotted"
* $v2-0493#ROOM "Room temperature"
* $v2-0493#SNR "Sample not received"
* $v2-0493#COOL "Cool"
