ValueSet: BRCOREN
Id: BRCOREN
Title: "Conselhos regionais de Enfermagem do Brasil"
Description: "Conjunto de todos os conselhos regionais de enfermagem do Brasil"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^identifier.system = "https://saude.gov.br/fhir/sid/valueset"
* ^identifier.value = "BRCOREN"
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = true
* ^date = "2023-07-18T10:52:24-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* ^purpose = "O propósito deste conjunto é agrupar todos os conselhos regionais de enfermagem para fins de validação do identificador profissional do enfermeiro"
* ^copyright = "CC-1.0"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-ac "COREN-AC"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-al "COREN-AL"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-am "COREN-AM"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-ap "COREN-AP"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-ba "COREN-BA"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-ce "COREN-CE"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-df "COREN-DF"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-es "COREN-ES"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-go "COREN-GO"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-ma "COREN-MA"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-mg "COREN-MG"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-ms "COREN-MS"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-mt "COREN-MT"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-pa "COREN-PA"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-pb "COREN-PB"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-pe "COREN-PE"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-pi "COREN-PI"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-pr "COREN-PR"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-rj "COREN-RJ"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-rn "COREN-RN"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-ro "COREN-RO"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-rr "COREN-RR"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-rs "COREN-RS"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-sc "COREN-SC"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-se "COREN-SE"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-sp "COREN-SP"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/coren-to "COREN-TO"