ValueSet: BRCRM
Id: BRCRM
Title: "Conselhos regionais de Medicina do Brasil"
Description: "Conjunto de todos os conselhos regionais de medicina do Brasil"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^identifier.system = "https://saude.gov.br/fhir/sid/valueset"
* ^identifier.value = "BRCRM"
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = true
* ^date = "2023-07-18T10:52:24-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* ^purpose = "O propósito deste conjunto é agrupar todos os conselhos regionais de medicina para fins de validação do identificador profissional do médico"
* ^copyright = "CC-1.0"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-ac "CRM-AC"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-al "CRM-AL"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-am "CRM-AM"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-ap "CRM-AP"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-ba "CRM-BA"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-ce "CRM-CE"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-df "CRM-DF"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-es "CRM-ES"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-go "CRM-GO"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-ma "CRM-MA"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-mg "CRM-MG"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-ms "CRM-MS"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-mt "CRM-MT"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-pa "CRM-PA"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-pb "CRM-PB"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-pe "CRM-PE"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-pi "CRM-PI"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-pr "CRM-PR"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-rj "CRM-RJ"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-rn "CRM-RN"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-ro "CRM-RO"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-rr "CRM-RR"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-rs "CRM-RS"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-sc "CRM-SC"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-se "CRM-SE"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-sp "CRM-SP"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crm-to "CRM-TO"