ValueSet: BRCRO
Id: BRCRO
Title: "Conselhos regionais de Odontologia do Brasil"
Description: "Conjunto de todos os conselhos regionais de farmácia do Brasil"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^identifier.system = "https://saude.gov.br/fhir/sid/valueset"
* ^identifier.value = "BRCRO"
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = true
* ^date = "2023-07-18T10:52:24-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* ^purpose = "O propósito deste conjunto é agrupar todos os conselhos regionais de farmácia para fins de validação do identificador profissional do odontólogo"
* ^copyright = "CC-1.0"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-ac "CRO-AC"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-al "CRO-AL"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-am "CRO-AM"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-ap "CRO-AP"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-ba "CRO-BA"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-ce "CRO-CE"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-df "CRO-DF"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-es "CRO-ES"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-go "CRO-GO"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-ma "CRO-MA"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-mg "CRO-MG"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-ms "CRO-MS"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-mt "CRO-MT"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-pa "CRO-PA"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-pb "CRO-PB"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-pe "CRO-PE"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-pi "CRO-PI"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-pr "CRO-PR"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-rj "CRO-RJ"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-rn "CRO-RN"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-ro "CRO-RO"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-rr "CRO-RR"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-rs "CRO-RS"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-sc "CRO-SC"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-se "CRO-SE"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-sp "CRO-SP"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/cro-to "CRO-TO"