ValueSet: BRCRF
Id: BRCRF
Title: "Conselhos regionais de Farmácia do Brasil"
Description: "Conjunto de todos os conselhos regionais de farmácia do Brasil"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^identifier.system = "https://saude.gov.br/fhir/sid/valueset"
* ^identifier.value = "BRCRF"
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = true
* ^date = "2023-07-18T10:52:24-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* ^purpose = "O propósito deste conjunto é agrupar todos os conselhos regionais de farmácia para fins de validação do identificador profissional do farmacêutico"
* ^copyright = "CC-1.0"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-ac "CRF-AC"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-al "CRF-AL"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-am "CRF-AM"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-ap "CRF-AP"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-ba "CRF-BA"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-ce "CRF-CE"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-df "CRF-DF"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-es "CRF-ES"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-go "CRF-GO"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-ma "CRF-MA"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-mg "CRF-MG"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-ms "CRF-MS"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-mt "CRF-MT"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-pa "CRF-PA"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-pb "CRF-PB"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-pe "CRF-PE"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-pi "CRF-PI"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-pr "CRF-PR"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-rj "CRF-RJ"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-rn "CRF-RN"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-ro "CRF-RO"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-rr "CRF-RR"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-rs "CRF-RS"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-sc "CRF-SC"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-se "CRF-SE"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-sp "CRF-SP"
* BRConselhoProfissional#https://saude.gov.br/fhir/sid/crf-to "CRF-TO"