ValueSet: BRDeficiencias
Id: BRDeficiencias
Title: "BRDeficiencias"
* ^version = "HEAD"
* ^status = #active
* ^publisher = "MS"
* $BRCID10#R47 "Distúrbios da fala não classificados em outra parte"
* $BRCID10#R47.8 "Outros distúrbios da fala e os não especificados"
* $BRCID10#R47.1 "Disartria e anartria"
* $BRCID10#R47.0 "Disfasia e afasia"
* $BRCID10#R49 "Distúrbios da voz"
* $BRCID10#R49.8 "Outros distúrbios da voz e os não especificados"
* $BRCID10#R49.1 "Afonia"
* $BRCID10#R49.0 "Disfonia"
* $BRCID10#H53.6 "Cegueira noturna"
* $BRCID10#H54.4 "Cegueira em um olho"
* $BRCID10#H54.0 "Cegueira, ambos os olhos"
* $BRCID10#H54 "Cegueira e visão subnormal"
* $BRCID10#H54.1 "Cegueira em um olho e visão subnormal em outro"
* $BRCID10#E50.5 "Deficiência de vitamina A com cegueira noturna"
* $BRCID10#J38.0 "Paralisia das cordas vocais e da laringe"
* $BRCID10#Z97.4 "Presença de aparelho externo de surdez"
* $BRCID10#S19 "Outros traumatismos do pescoço e os não especificados"
* $BRCID10#H91.1 "Presbiacusia"
* $BRCID10#H91.3 "Surdo-mudez não classificada em outra parte"
* $BRCID10#M05 "Artrite reumatóide soro-positiva"
* $BRCID10#M05.1 "Doença reumatóide do pulmão"
* $BRCID10#M05.2 "Vasculite reumatóide"
* $BRCID10#M05.9 "Artrite reumatóide soro-positiva não especificada"
* $BRCID10#M05.3 "Artrite reumatóide com comprometimento de outros órgãos e sistemas"
* $BRCID10#M05.8 "Outras artrites reumatóides soro-positivas"
* $BRCID10#H91.0 "Perda de audição ototóxica"
* $BRCID10#H91 "Outras perdas de audição"
* $BRCID10#H90.4 "Perda de audição unilateral neuro-sensorial, sem restrição de audição contralateral"
* $BRCID10#H91.9 "Perda não especificada de audição"
* $BRCID10#H91.8 "Outras perdas de audição especificadas"
* $BRCID10#H91.2 "Perda de audição súbita idiopática"
* $BRCID10#H90.3 "Perda de audição bilateral neuro-sensorial"
* $BRCID10#H90.1 "Perda de audição unilateral por transtorno de condução, sem restrição de audição contralateral"
* $BRCID10#H90.5 "Perda de audição neuro-sensorial não especificada"
* $BRCID10#H90.7 "Perda de audição unilateral mista, de condução e neuro-sensorial, sem restrição de audição contralateral"
* $BRCID10#Q16 "Malformações congênitas do ouvido causando comprometimento da audição"
* $BRCID10#H90.6 "Perda de audição bilateral mista, de condução e neuro-sensorial"
* $BRCID10#H90.0 "Perda de audição bilateral devida a transtorno de condução"
* $BRCID10#H90.8 "Perda de audição mista, de condução e neuro-sensorial, não especificada"
* $BRCID10#H90.2 "Perda não especificada de audição devida a transtorno de condução"
* $BRCID10#H90 "Perda de audição por transtorno de condução e/ou neuro-sensorial"
* $BRCID10#Q16.9 "Malformação congênita do ouvido não especificada causando comprometimento da audição"
* $BRCID10#S02 "Fratura do crânio e dos ossos da face"
* $BRCID10#S02.0 "Fratura da abóbada do crânio"
* $BRCID10#S02.3 "Fratura do assoalho orbital"
* $BRCID10#S02.2 "Fratura dos ossos nasais"
* $BRCID10#S02.6 "Fratura de mandíbula"
* $BRCID10#S02.7 "Fraturas múltiplas envolvendo os ossos do crânio e da face"
* $BRCID10#S02.8 "Outras fraturas do crânio e dos ossos da face"
* $BRCID10#S02.1 "Fratura da base do crânio"
* $BRCID10#S02.9 "Fratura do crânio ou dos ossos da face, parte não especificada"
* $BRCID10#S02.4 "Fratura dos ossos malares e maxilares"
* $BRCID10#H54.7 "Perda não especificada da visão"
* $BRCID10#H54.6 "Perda não qualificada da visão em um olho"
* $BRCID10#H54.5 "Visão subnormal em um olho"
* $BRCID10#H54.3 "Perda não qualificada da visão em ambos os olhos"
* $BRCID10#H54.2 "Visão subnormal de ambos os olhos"
* $BRCID10#Q05 "Espinha bífida"
* $BRCID10#Q05.8 "Espinha bífida sacra, sem hidrocefalia"
* $BRCID10#Q05.6 "Espinha bífida torácica, sem hidrocefalia"
* $BRCID10#Q05.2 "Espinha bífida lombar com hidrocefalia"
* $BRCID10#Q05.4 "Espinha bífida não especificada, com hidrocefalia"
* $BRCID10#Q05.9 "Espinha bífida não especificada"
* $BRCID10#Q05.5 "Espinha bífida cervical, sem hidrocefalia"
* $BRCID10#Q05.3 "Espinha bífida sacra com hidrocefalia"
* $BRCID10#Q05.1 "Espinha bífida torácica com hidrocefalia"
* $BRCID10#Q05.0 "Espinha bífida cervical com hidrocefalia"
* $BRCID10#Q05.7 "Espinha bífida lombar, sem hidrocefalia"
* $BRCID10#F71 "Retardo mental moderado"
* $BRCID10#F71.9 "Retardo mental moderado - sem menção de comprometimento do comportamento"
* $BRCID10#F71.8 "Retardo mental moderado - outros comprometimentos do comportamento"
* $BRCID10#F71.1 "Retardo mental moderado - comprometimento significativo do comportamento, requerendo vigilância ou tratamento"
* $BRCID10#F71.0 "Retardo mental moderado - menção de ausência de ou de comprometimento mínimo do comportamento"
* $BRCID10#T04 "Traumatismos por esmagamento envolvendo múltiplas regiões do corpo"
* $BRCID10#T04.3 "Traumatismos por esmagamento envolvendo regiões múltiplas do(s) membro(s) inferior(es)"
* $BRCID10#T04.2 "Traumatismos por esmagamento envolvendo regiões múltiplas do(s) membro(s) superior(es)"
* $BRCID10#T04.9 "Traumatismo múltiplos por esmagamento não especificados"
* $BRCID10#T04.8 "Traumatismos por esmagamento envolvendo outras combinações de regiões do corpo"
* $BRCID10#T05 "Amputações traumáticas envolvendo múltiplas regiões do corpo"
* $BRCID10#T05.0 "Amputação traumática de ambas as mãos"
* $BRCID10#T05.3 "Amputação traumática de ambos os pés"
* $BRCID10#T05.2 "Amputação traumática de ambos os braços [qualquer nível]"
* $BRCID10#T05.5 "Amputação traumática de ambas as pernas [qualquer nível]"
* $BRCID10#T05.8 "Amputações traumáticas envolvendo outras combinações de regiões do corpo"
* $BRCID10#T05.6 "Amputação traumática de membros superiores e inferiores, qualquer combinação [qualquer nível]"
* $BRCID10#F84 "Transtornos globais do desenvolvimento"
* $BRCID10#F84.9 "Transtornos globais não especificados do desenvolvimento"
* $BRCID10#F84.8 "Outros transtornos globais do desenvolvimento"
* $BRCID10#F84.5 "Síndrome de Asperger"
* $BRCID10#F84.4 "Transtorno com hipercinesia associada a retardo mental e a movimentos estereotipados"
* $BRCID10#F84.3 "Outro transtorno desintegrativo da infância"
* $BRCID10#F84.2 "Síndrome de Rett"
* $BRCID10#F84.1 "Autismo atípico"
* $BRCID10#F84.0 "Autismo infantil"
* $BRCID10#T04.1 "Traumatismos por esmagamento envolvendo tórax com o abdome, parte inferior do dorso e da pelve"
* $BRCID10#T04.7 "Traumatismo por esmagamento do tórax com abdome, parte inferior do dorso, pelve e membro(s)"
* $BRCID10#T04.0 "Traumatismos por esmagamento envolvendo a cabeça com o pescoço"
* $BRCID10#T09.4 "Traumatismo de nervos, de raízes de nervos espinhais e de plexos não especificados do tronco"
* $BRCID10#T32.9 "Corrosões envolvendo 90% ou mais da superfície corporal"
* $BRCID10#T31.9 "Queimaduras envolvendo 90% ou mais da superfície corporal"
* $BRCID10#G11.4 "Paraplegia espástica hereditária"
* $BRCID10#G04.1 "Paraplegia espástica tropical"
* $BRCID10#M62.3 "Síndrome de imobilidade (paraplégica)"
* $BRCID10#G80 "Paralisia cerebral"
* $BRCID10#G80.9 "Paralisia cerebral não especificada"
* $BRCID10#G80.8 "Outras formas de paralisia cerebral"
* $BRCID10#G80.4 "Paralisia cerebral atáxica"
* $BRCID10#G80.3 "Paralisia cerebral discinética"
* $BRCID10#G80.2 "Paralisia cerebral hemiplégica espástica"
* $BRCID10#G80.1 "Paralisia cerebral diplégica espástica"
* $BRCID10#G80.0 "Paralisia cerebral quadriplágica espástica"
* $BRCID10#M73.1 "Bursite sifilítica"
* $BRCID10#M73.0 "Bursite gonocócica"
* $BRCID10#M75.5 "Bursite do ombro"
* $BRCID10#M76.4 "Bursite tibial colateral [Pellegrini-Stieda]"
* $BRCID10#M71.1 "Outras bursites infecciosas"
* $BRCID10#G71 "Transtornos primários dos músculos"
* $BRCID10#G71.9 "Transtorno muscular primário não especificado"
* $BRCID10#G71.8 "Outros transtornos primários dos músculos"
* $BRCID10#G71.3 "Miopatia mitocondrial não classificada em outra parte"
* $BRCID10#G71.2 "Miopatias congênitas"
* $BRCID10#G71.1 "Transtornos miotônicos"
* $BRCID10#G71.0 "Distrofia muscular"
* $BRCID10#M65.2 "Tendinite calcificada"
* $BRCID10#M75.2 "Tendinite bicepital"
* $BRCID10#M76.0 "Tendinite glútea"
* $BRCID10#M76.6 "Tendinite aquileana"
* $BRCID10#M76.5 "Tendinite patelar"
* $BRCID10#M76.1 "Tendinite do psoas"
* $BRCID10#M76.7 "Tendinite do perôneo"
* $BRCID10#M75.3 "Tendinite calcificante do ombro"
* $BRCID10#S14 "Traumatismo de nervos e da medula espinhal ao nível cervical"
* $BRCID10#S14.6 "Traumatismo de outros nervos e dos não especificados do pescoço"
* $BRCID10#S14.5 "Traumatismo dos nervos simpáticos do pescoço"
* $BRCID10#S14.4 "Traumatismo dos nervos periféricos do pescoço"
* $BRCID10#S14.3 "Traumatismo do plexo braquial"
* $BRCID10#S14.2 "Traumatismo da raiz nervosa da coluna cervical"
* $BRCID10#S14.1 "Outros traumatismos e os não especificados da medula cervical"
* $BRCID10#S14.0 "Concussão e edema da medula cervical"
* $BRCID10#C48.2 "Neoplasia maligna do peritônio"
* $BRCID10#C51 "Neoplasia maligna da vulva"
* $BRCID10#C51.2 "Neoplasia maligna do clitóris"
* $BRCID10#C52 "Neoplasia maligna da vagina"
* $BRCID10#C56 "Neoplasia maligna do ovário"
* $BRCID10#C57.3 "Neoplasia maligna do paramétrio"
* $BRCID10#C60 "Neoplasia maligna do pênis"
* $BRCID10#C58 "Neoplasia maligna da placenta"
* $BRCID10#C60.0 "Neoplasia maligna do prepúcio"
* $BRCID10#C61 "Neoplasia maligna da próstata"
* $BRCID10#C60.1 "Neoplasia maligna da glande"
* $BRCID10#C63.2 "Neoplasia maligna do escroto"
* $BRCID10#C63.0 "Neoplasia maligna do epidídimo"
* $BRCID10#C66 "Neoplasia maligna dos ureteres"
* $BRCID10#C67 "Neoplasia maligna da bexiga"
* $BRCID10#C69.0 "Neoplasia maligna da conjuntiva"
* $BRCID10#C69.3 "Neoplasia maligna da coróide"
* $BRCID10#C69.2 "Neoplasia maligna da retina"
* $BRCID10#C69.6 "Neoplasia maligna da órbita"
* $BRCID10#C70 "Neoplasia maligna das meninges"
* $BRCID10#C71.6 "Neoplasia maligna do cerebelo"
* $BRCID10#C76.1 "Neoplasia maligna do tórax"
* $BRCID10#C76.2 "Neoplasia maligna do abdome"
* $BRCID10#C76.3 "Neoplasia maligna da pelve"
* $BRCID10#S24 "Traumatismos de nervos e da medula espinhal ao nível do tórax"
* $BRCID10#S24.6 "Traumatismo de nervo do tórax não especificado"
* $BRCID10#S24.5 "Traumatismo de outros nervos do tórax"
* $BRCID10#S24.4 "Traumatismo de nervos simpáticos do tórax"
* $BRCID10#S24.3 "Traumatismo de nervos periféricos do tórax"
* $BRCID10#S24.2 "Traumatismo da raiz de nervo da coluna torácica"
* $BRCID10#S24.1 "Outros traumatismos da medula espinhal torácica e os não especificados"
* $BRCID10#S24.0 "Concussão e edema da medula espinhal torácica"
* $BRCID10#C25 "Neoplasia maligna do pâncreas"
* $BRCID10#C26.1 "Neoplasia maligna do baço"
* $BRCID10#C32 "Neoplasia maligna da laringe"
* $BRCID10#C17.1 "Neoplasia maligna do jejuno"
* $BRCID10#C17.2 "Neoplasia maligna do íleo"
* $BRCID10#C18 "Neoplasia maligna do cólon"
* $BRCID10#C37 "Neoplasia maligna do timo"
* $BRCID10#C38.0 "Neoplasia maligna do coração"
* $BRCID10#C38.4 "Neoplasia maligna da pleura"
* $BRCID10#C00 "Neoplasia maligna do lábio"
* $BRCID10#C41.1 "Neoplasia maligna da mandíbula"
* $BRCID10#C03 "Neoplasia maligna da gengiva"
* $BRCID10#C05 "Neoplasia maligna do palato"
* $BRCID10#C09 "Neoplasia maligna da amígdala"
* $BRCID10#C10.0 "Neoplasia maligna da valécula"
* $BRCID10#C10 "Neoplasia maligna da orofaringe"
* $BRCID10#C13 "Neoplasia maligna da hipofaringe"
* $BRCID10#C11 "Neoplasia maligna da nasofaringe"
* $BRCID10#C16.4 "Neoplasia maligna do piloro"
* $BRCID10#C16.0 "Neoplasia maligna da cárdia"
* $BRCID10#C16 "Neoplasia maligna do estômago"
* $BRCID10#S34 "Traumatismo dos nervos e da medula lombar ao nível do abdome, do dorso e da pelve"
* $BRCID10#S34.8 "Traumatismo de outros nervos e dos não especificados ao nível do abdome, do dorso e da pelve"
* $BRCID10#S34.6 "Traumatismo do(s) nervo(s) periférico(s) do abdome, do dorso e da pelve"
* $BRCID10#S34.5 "Traumatismo de nervos simpáticos lombares, sacros e pélvicos"
* $BRCID10#S34.4 "Traumatismo do plexo lombossacro"
* $BRCID10#S34.3 "Traumatismo de cauda eqüina"
* $BRCID10#S34.2 "Traumatismo de raiz nervosa da medula lombar e sacra"
* $BRCID10#S34.1 "Outro traumatismo da medula lombar"
* $BRCID10#S34.0 "Concussão e edema da medula lombar"
* $BRCID10#C50 "Neoplasia maligna da mama"
* $BRCID10#C69.1 "Neoplasia maligna da córnea"
* $BRCID10#C68.0 "Neoplasia maligna da uretra"
* $BRCID10#C62 "Neoplasia maligna dos testículos"
* $BRCID10#C54.2 "Neoplasia maligna do miométrio"
* $BRCID10#C54.1 "Neoplasia maligna do endométrio"
* $BRCID10#C53.1 "Neoplasia maligna do exocérvix"
* $BRCID10#C17.0 "Neoplasia maligna do duodeno"
* $BRCID10#C15 "Neoplasia maligna do esôfago"
* $BRCID10#C05.2 "Neoplasia maligna da úvula"
* $BRCID10#C20 "Neoplasia maligna do reto"
* $BRCID10#C18.0 "Neoplasia maligna do ceco"
* $BRCID10#C33 "Neoplasia maligna da traquéia"
* $BRCID10#C32.0 "Neoplasia maligna da glote"
* $BRCID10#C48.0 "Neoplasia maligna do retroperitônio"
* $BRCID10#C53.0 "Neoplasia maligna do endocérvix"
* $BRCID10#C71 "Neoplasia maligna do encéfalo"
* $BRCID10#T90 "Seqüelas de traumatismo da cabeça"
* $BRCID10#T90.9 "Seqüelas de traumatismo não especificado da cabeça"
* $BRCID10#T90.8 "Seqüelas de outros traumatismos especificados da cabeça"
* $BRCID10#T90.5 "Seqüelas de traumatismo intracraniano"
* $BRCID10#T90.4 "Seqüelas de traumatismo do olho e da órbita"
* $BRCID10#T90.3 "Seqüelas de traumatismo de nervos cranianos"
* $BRCID10#T90.2 "Seqüelas de fratura de crânio e de ossos da face"
* $BRCID10#T90.1 "Seqüelas de ferimento da cabeça"
* $BRCID10#T90.0 "Seqüelas de traumatismo superficial da cabeça"
* $BRCID10#C67.7 "Neoplasia maligna do úraco"
* $BRCID10#T91 "Seqüelas de traumatismos do pescoço e do tronco"
* $BRCID10#T91.9 "Seqüelas de traumatismo não especificado do pescoço e do tronco"
* $BRCID10#T91.8 "Seqüelas de outros traumatismos especificados do pescoço e do tronco"
* $BRCID10#T91.5 "Seqüelas de traumatismo de órgãos intra-abdominais e órgãos pélvicos"
* $BRCID10#T91.4 "Seqüelas de traumatismo de órgãos intratorácicos"
* $BRCID10#T91.3 "Seqüelas de traumatismo de medula espinhal"
* $BRCID10#T91.2 "Seqüelas de outra fratura do tórax e da pelve"
* $BRCID10#T91.1 "Seqüelas de fratura de coluna vertebral"
* $BRCID10#T91.0 "Seqüelas de traumatismo superficial e ferimento do pescoço e do tronco"
* $BRCID10#C51.0 "Neoplasia maligna dos grandes lábios"
* $BRCID10#C57.1 "Neoplasia maligna do ligamento largo"
* $BRCID10#C57.2 "Neoplasia maligna do ligamento redondo"
* $BRCID10#C62.0 "Neoplasia maligna do testículo criptorquídico"
* $BRCID10#C63.1 "Neoplasia maligna do cordão espermático"
* $BRCID10#C65 "Neoplasia maligna da pelve renal"
* $BRCID10#C67.6 "Neoplasia maligna do orifício uretérico"
* $BRCID10#C69.4 "Neoplasia maligna do corpo ciliar"
* $BRCID10#C70.1 "Neoplasia maligna das meninges espinhais"
* $BRCID10#C71.1 "Neoplasia maligna do lobo frontal"
* $BRCID10#C71.2 "Neoplasia maligna do lobo temporal"
* $BRCID10#C71.5 "Neoplasia maligna do ventrículo cerebral"
* $BRCID10#C71.7 "Neoplasia maligna do tronco cerebral"
* $BRCID10#C72.0 "Neoplasia maligna da medula espinhal"
* $BRCID10#C78.1 "Neoplasia maligna secundária do mediastino"
* $BRCID10#C78.0 "Neoplasia maligna secundária dos pulmões"
* $BRCID10#C78.2 "Neoplasia maligna secundária da pleura"
* $BRCID10#C79.2 "Neoplasia maligna secundária da pele"
* $BRCID10#C79.6 "Neoplasia maligna secundária do ovário"
* $BRCID10#C72.1 "Neoplasia maligna da cauda eqüina"
* $BRCID10#C72.2 "Neoplasia maligna do nervo olfativo"
* $BRCID10#C72.3 "Neoplasia maligna do nervo óptico"
* $BRCID10#C73 "Neoplasia maligna da glândula tireóide"
* $BRCID10#C75.0 "Neoplasia maligna da glândula paratireóide"
* $BRCID10#C75.4 "Neoplasia maligna do corpo carotídeo"
* $BRCID10#C76.4 "Neoplasia maligna do membro superior"
* $BRCID10#C23 "Neoplasia maligna da vesícula biliar"
* $BRCID10#C25.3 "Neoplasia maligna do canal pancreático"
* $BRCID10#C30.0 "Neoplasia maligna da cavidade nasal"
* $BRCID10#C30.1 "Neoplasia maligna do ouvido médio"
* $BRCID10#C18.1 "Neoplasia maligna do apêndice (vermiforme)"
* $BRCID10#C19 "Neoplasia maligna da junção retossigmóide"
* $BRCID10#C21.2 "Neoplasia maligna da zona cloacogênica"
* $BRCID10#C21.1 "Neoplasia maligna do canal anal"
* $BRCID10#T92 "Seqüelas de traumatismos do membro superior"
* $BRCID10#T92.9 "Seqüelas de traumatismo não especificado do membro superior"
* $BRCID10#T92.8 "Seqüelas de outros traumatismos especificados do membro superior"
* $BRCID10#T92.6 "Seqüelas de esmagamento e amputação traumática do membro superior"
* $BRCID10#T92.5 "Seqüelas de traumatismo de músculo e tendão do membro superior"
* $BRCID10#T92.4 "Seqüelas de traumatismo de nervo de membro superior"
* $BRCID10#T92.3 "Seqüelas de luxação, entorse e distensão do membro superior"
* $BRCID10#T92.2 "Seqüelas de fratura ao nível do punho e da mão"
* $BRCID10#T92.1 "Seqüelas de fratura do braço"
* $BRCID10#T92.0 "Seqüelas de ferimento do membro superior"
* $BRCID10#C32.1 "Neoplasia maligna da região supraglótica"
* $BRCID10#C32.2 "Neoplasia maligna da região subglótica"
* $BRCID10#C34.0 "Neoplasia maligna do brônquio principal"
* $BRCID10#C38.2 "Neoplasia maligna do mediastino posterior"
* $BRCID10#C38.1 "Neoplasia maligna do mediastino anterior"
* $BRCID10#C00.6 "Neoplasia maligna da comissura labial"
* $BRCID10#C02.4 "Neoplasia maligna da amígdala lingual"
* $BRCID10#C03.1 "Neoplasia maligna da gengiva inferior"
* $BRCID10#C05.1 "Neoplasia maligna do palato mole"
* $BRCID10#C05.0 "Neoplasia maligna do palato duro"
* $BRCID10#C08.1 "Neoplasia maligna da glândula sublingual"
* $BRCID10#C08.0 "Neoplasia maligna da glândula submandibular"
* $BRCID10#C07 "Neoplasia maligna da glândula parótida"
* $BRCID10#C06.0 "Neoplasia maligna da mucosa oral"
* $BRCID10#C09.0 "Neoplasia maligna da fossa amigdaliana"
* $BRCID10#C06.2 "Neoplasia maligna da área retromolar"
* $BRCID10#C10.4 "Neoplasia maligna da fenda branquial"
* $BRCID10#C13.0 "Neoplasia maligna da região pós-cricóidea"
* $BRCID10#C12 "Neoplasia maligna do seio piriforme"
* $BRCID10#C16.3 "Neoplasia maligna do antro pilórico"
* $BRCID10#T93 "Seqüelas de traumatismos do membro inferior"
* $BRCID10#T93.9 "Seqüelas de traumatismo não especificado do membro inferior"
* $BRCID10#T93.8 "Seqüelas de outros traumatismos especificados do membro inferior"
* $BRCID10#T93.6 "Seqüelas de esmagamento e amputação traumática do membro inferior"
* $BRCID10#T93.5 "Seqüelas de traumatismo de músculo e tendão do membro inferior"
* $BRCID10#T93.4 "Seqüelas de traumatismo de nervo do membro inferior"
* $BRCID10#T93.3 "Seqüelas de luxação, entorse e distensão do membro inferior"
* $BRCID10#T93.2 "Seqüelas de outras fraturas do membro inferior"
* $BRCID10#T93.1 "Seqüelas de fratura do fêmur"
* $BRCID10#T93.0 "Seqüelas de ferimento do membro inferior"
* $BRCID10#Z85 "História pessoal de neoplasia maligna"
* $BRCID10#C75.3 "Neoplasia maligna da glândula pineal"
* $BRCID10#C72.4 "Neoplasia maligna do nervo acústico"
* $BRCID10#C62.1 "Neoplasia maligna do testículo tópico"
* $BRCID10#C57.4 "Neoplasia maligna dos anexos uterinos"
* $BRCID10#C18.2 "Neoplasia maligna do cólon ascendente"
* $BRCID10#C03.0 "Neoplasia maligna da gengiva superior"
* $BRCID10#C18.4 "Neoplasia maligna do cólon transverso"
* $BRCID10#C31.2 "Neoplasia maligna do seio frontal"
* $BRCID10#C70.0 "Neoplasia maligna das meninges cerebrais"
* $BRCID10#C18.7 "Neoplasia maligna do cólon sigmóide"
* $BRCID10#C18.6 "Neoplasia maligna do cólon descendente"
* $BRCID10#C17 "Neoplasia maligna do intestino delgado"
* $BRCID10#C41.2 "Neoplasia maligna da coluna vertebral"
* $BRCID10#C31.3 "Neoplasia maligna do seio esfenoidal"
* $BRCID10#C31.1 "Neoplasia maligna do seio etmoidal"
* $BRCID10#C31.0 "Neoplasia maligna do seio maxilar"
* $BRCID10#C25.4 "Neoplasia maligna do pâncreas endócrino"
* $BRCID10#C51.1 "Neoplasia maligna dos pequenos lábios"
* $BRCID10#C71.4 "Neoplasia maligna do lobo occipital"
* $BRCID10#C71.3 "Neoplasia maligna do lobo parietal"
* $BRCID10#T98.3 "Seqüelas de complicações dos cuidados médicos e cirúrgicos não classificados em outra parte"
* $BRCID10#T98.2 "Seqüelas de algumas complicações precoces de traumatismos"
* $BRCID10#T98.1 "Seqüelas em outros efeitos de causas externas e os não especificados"
* $BRCID10#T98.0 "Seqüelas dos efeitos da penetração de corpo estranho através de orifício natural"
* $BRCID10#T98 "Seqüelas de outros efeitos de causas externas e dos não especificados"
* $BRCID10#T97 "Seqüelas de efeitos tóxicos de substâncias de origem predominantemente não-medicinal"
* $BRCID10#T96 "Seqüelas de intoxicação por drogas, medicamentos e substâncias biológicas"
* $BRCID10#T95.9 "Seqüelas de queimadura, corrosão e geladura de local não especificado"
* $BRCID10#T95.8 "Seqüelas de outra queimadura, corrosões e geladuras especificadas"
* $BRCID10#T95.4 "Seqüelas de queimadura e corrosão classificável só de acordo com a extensão da área corporal envolvida"
* $BRCID10#T95.3 "Seqüelas de queimadura, corrosão e geladura do membro inferior"
* $BRCID10#T95.2 "Seqüelas de queimadura, corrosão e geladura do membro superior"
* $BRCID10#T95.1 "Seqüelas de queimadura, corrosão e geladura do tronco"
* $BRCID10#T95.0 "Seqüelas de queimadura, corrosão e geladura da cabeça e pescoço"
* $BRCID10#T95 "Seqüelas de queimaduras, corrosões e geladuras"
* $BRCID10#T94.1 "Seqüelas de traumatismos não especificados por regiões do corpo"
* $BRCID10#T94.0 "Seqüelas de traumatismos envolvendo regiões múltiplas do corpo"
* $BRCID10#T94 "Seqüelas de traumatismos envolvendo múltiplas regiões do corpo e as não especificadas"
* $BRCID10#C68.1 "Neoplasia maligna da glândula parauretral"
* $BRCID10#Q99.9 "Anomalia cromossômica não especificada"
* $BRCID10#Q99.8 "Outras anomalias cromossômicas especificadas"
* $BRCID10#Q99.2 "Cromossomo X frágil"
* $BRCID10#Q99.1 "Hermafrodite verdadeiro 46, XX"
* $BRCID10#Q99.0 "Quimera 46, XX/46, XY"
* $BRCID10#Q99 "Outras anomalias dos cromossomos, não classificadas em outra parte"
* $BRCID10#Q98.9 "Anomalias não especificadas dos cromossomos sexuais, fenótipo masculino"
* $BRCID10#Q98.8 "Outras anomalias especificadas dos cromossomos sexuais, fenótipo masculino"
* $BRCID10#Q98.7 "Homem com mosaicismo dos cromossomos sexuais"
* $BRCID10#Q98.6 "Homem com cromossomos sexuais de estrutura anormal"
* $BRCID10#Q98.5 "Cariótipo 47, XYY"
* $BRCID10#Q98.4 "Síndrome de Klinefelter não especificada"
* $BRCID10#Q98.3 "Outro homem com cariótipo 46, XX"
* $BRCID10#Q98.2 "Síndrome de Klinefelter, homem com cariótipo 46, XX"
* $BRCID10#Q98.1 "Síndrome de Klinefelter, homem com mais de dois cromossomos X"
* $BRCID10#Q98.0 "Síndrome de Klinefelter, cariótipo 47, XXY"
* $BRCID10#Q98 "Outras anomalias dos cromossomos sexuais, fenótipo masculino, não classificadas em outra parte"
* $BRCID10#Q97.9 "Anomalias não especificadas dos cromossomos sexuais, fenótipo feminino"
* $BRCID10#Q97.8 "Outras anomalias especificadas dos cromossomos sexuais, fenótipo feminino"
* $BRCID10#Q97.3 "Mulher com cariótipo 46, XY"
* $BRCID10#Q97.2 "Mosaicismo cromossômico, linhagens com diversos números de cromossomos X"
* $BRCID10#Q97.1 "Mulher com mais de três cromossomos X"
* $BRCID10#Q97.0 "Cariótipo 47, XXX"
* $BRCID10#Q97 "Outras anomalias dos cromossomos sexuais, fenótipo feminino, não classificadas em outra parte"
* $BRCID10#Q96.9 "Síndrome de Turner não especificada"
* $BRCID10#Q96.8 "Outras variantes da síndrome de Turner"
* $BRCID10#Q96.4 "Mosaicismo cromossômico, 45, X/outra(s) linhagens celular(es) com cromossomo sexual anormal"
* $BRCID10#Q96.3 "Mosaicismo cromossômico, 45, X/46, XX ou XY"
* $BRCID10#Q96.2 "Cariótipo 46, X com cromossomo sexual anormal, salvo iso (Xq)"
* $BRCID10#Q96.1 "Cariótipo 46, X iso (Xq)"
* $BRCID10#Q96.0 "Cariótipo 45, X"
* $BRCID10#Q96 "Síndrome de Turner"
* $BRCID10#Q95.9 "Rearranjos e marcadores equilibrados não especificados"
* $BRCID10#Q95.8 "Outros rearranjos e marcadores equilibrados"
* $BRCID10#Q95.5 "Sujeito com sítio autossômico frágil"
* $BRCID10#Q95.4 "Sujeito com marcador de heterocromatina"
* $BRCID10#Q95.3 "Rearranjo sexual/autossômico equilibrado em sujeito anormal"
* $BRCID10#Q95.2 "Rearranjo autossômico equilibrado em sujeito anormal"
* $BRCID10#Q95.1 "Inversão cromossômica em sujeito normal"
* $BRCID10#Q95.0 "Translocação ou inserção equilibrada em sujeito normal"
* $BRCID10#Q95 "Rearranjos equilibrados e marcadores estruturais, não classificados em outra parte"
* $BRCID10#Q93.9 "Deleções não especificadas dos autossomos"
* $BRCID10#Q93.8 "Outras deleções dos autossomos"
* $BRCID10#Q93.7 "Deleções com outros rearranjos complexos"
* $BRCID10#Q93.6 "Deleções vistas somente na prometáfase"
* $BRCID10#Q93.5 "Outras deleções parciais de cromossomo"
* $BRCID10#Q93.4 "Deleção do braço curto do cromossomo 5"
* $BRCID10#Q93.3 "Deleção do braço curto do cromossomo 4"
* $BRCID10#Q93.2 "Cromossomo substituído por anel ou dicêntrico"
* $BRCID10#Q93.1 "Monossomia de cromossomo inteiro, mosaicismo cromossômico (não-disjunção mitótica)"
* $BRCID10#Q93.0 "Monossomia de cromossomo inteiro, não-disjunção meiótica"
* $BRCID10#Q93 "Monossomias e deleções dos autossomos, não classificadas em outra parte"
* $BRCID10#Q92.9 "Trissomia e trissomia parcial não especificada dos autossomos"
* $BRCID10#Q92.8 "Outras trissomias especificadas e trissomias parciais dos autossomos"
* $BRCID10#Q92.7 "Triploidia e poliploidia"
* $BRCID10#Q92.6 "Cromossomos marcadores suplementares"
* $BRCID10#Q92.5 "Duplicação com outros rearranjos complexos"
* $BRCID10#Q92.4 "Duplicações vistas somente na prometáfase"
* $BRCID10#Q92.3 "Trissomia parcial minor"
* $BRCID10#Q92.2 "Trissomia parcial major"
* $BRCID10#Q92.1 "Trissomia de um cromossomo inteiro, mosaicismo cromossômico (não-disjunção mitótica)"
* $BRCID10#Q92.0 "Trissomia de um cromossomo inteiro, não-disjunção meiótica"
* $BRCID10#Q92 "Outras trissomias e trissomias parciais dos autossomos, não classificadas em outra parte"
* $BRCID10#Q91.7 "Síndrome de Patau não especificada"
* $BRCID10#Q91.6 "Trissomia 13, translocação"
* $BRCID10#Q91.5 "Trissomia 13, mosaicismo cromossômico (não-disjunção mitótica)"
* $BRCID10#Q91.4 "Trissomia 13, não-disjunção meiótica"
* $BRCID10#Q91.3 "Síndrome de Edwards não especificada"
* $BRCID10#Q91.2 "Trissomia 18, translocação"
* $BRCID10#Q91.1 "Trissomia 18, mosaicismo cromossômico (não-disjunção mitótica)"
* $BRCID10#Q91.0 "Trissomia 18, não-disjunção meiótica"
* $BRCID10#Q91 "Síndrome de Edwards e síndrome de Patau"
* $BRCID10#Q90.9 "Síndrome de Down não especificada"
* $BRCID10#Q90.2 "Trissomia 21, translocação"
* $BRCID10#Q90.1 "Trissomia 21, mosaicismo (não-disjunção mitótica)"
* $BRCID10#Q90.0 "Trissomia 21, não-disjunção meiótica"
* $BRCID10#Q90 "Síndrome de Down"
* $BRCID10#C51.9 "Neoplasia maligna da vulva, não especificada"
* $BRCID10#C53 "Neoplasia maligna do colo do útero"
* $BRCID10#C54 "Neoplasia maligna do corpo do útero"
* $BRCID10#C54.0 "Neoplasia maligna do istmo do útero"
* $BRCID10#C54.3 "Neoplasia maligna do fundo do útero"
* $BRCID10#C57.0 "Neoplasia maligna da trompa de Falópio"
* $BRCID10#C60.9 "Neoplasia maligna do pênis, não especificado"
* $BRCID10#C60.2 "Neoplasia maligna do corpo do pênis"
* $BRCID10#C67.0 "Neoplasia maligna do trígono da bexiga"
* $BRCID10#C67.5 "Neoplasia maligna do colo da bexiga"
* $BRCID10#C74.0 "Neoplasia maligna do córtex da supra-renal"
* $BRCID10#C22.9 "Neoplasia maligna do fígado, não especificada"
* $BRCID10#C24.0 "Neoplasia maligna das vias biliares extra-hepáticas"
* $BRCID10#C25.2 "Neoplasia maligna da cauda do pâncreas"
* $BRCID10#C25.1 "Neoplasia maligna do corpo do pâncreas"
* $BRCID10#C25.0 "Neoplasia maligna da cabeça do pâncreas"
* $BRCID10#C31 "Neoplasia maligna dos seios da face"
* $BRCID10#C17.3 "Neoplasia maligna do divertículo de Meckel"
* $BRCID10#C18.9 "Neoplasia maligna do cólon, não especificado"
* $BRCID10#C21.0 "Neoplasia maligna do ânus, não especificado"
* $BRCID10#C32.3 "Neoplasia maligna das cartilagens da laringe"
* $BRCID10#C00.0 "Neoplasia maligna do lábio superior externo"
* $BRCID10#C44.0 "Neoplasia maligna da pele do lábio"
* $BRCID10#C00.1 "Neoplasia maligna do lábio inferior externo"
* $BRCID10#C01 "Neoplasia maligna da base da língua"
* $BRCID10#C00.9 "Neoplasia maligna do lábio, não especificado"
* $BRCID10#C02.9 "Neoplasia maligna da língua, não especificada"
* $BRCID10#C02.1 "Neoplasia maligna da borda da língua"
* $BRCID10#C04 "Neoplasia maligna do assoalho da boca"
* $BRCID10#C03.9 "Neoplasia maligna da gengiva, não especificada"
* $BRCID10#C05.9 "Neoplasia maligna do palato, não especificado"
* $BRCID10#F29 "Psicose não-orgânica não especificada"
* $BRCID10#F28 "Outros transtornos psicóticos não-orgânicos"
* $BRCID10#F25.9 "Transtorno esquizoafetivo não especificado"
* $BRCID10#F25.8 "Outros transtornos esquizoafetivos"
* $BRCID10#F25.2 "Transtorno esquizoafetivo do tipo misto"
* $BRCID10#F25.1 "Transtorno esquizoafetivo do tipo depressivo"
* $BRCID10#F25.0 "Transtorno esquizoafetivo do tipo maníaco"
* $BRCID10#F25 "Transtornos esquizoafetivos"
* $BRCID10#F24 "Transtorno delirante induzido"
* $BRCID10#F23.9 "Transtorno psicótico agudo e transitório não especificado"
* $BRCID10#F23.8 "Outros transtornos psicóticos agudos e transitórios"
* $BRCID10#F23.3 "Outros transtornos psicóticos agudos, essencialmente delirantes"
* $BRCID10#F23.2 "Transtorno psicótico agudo de tipo esquizofrênico (schizophrenia-like)"
* $BRCID10#F23.1 "Transtorno psicótico agudo polimorfo, com sintomas esquizofrênicos"
* $BRCID10#F23.0 "Transtorno psicótico agudo polimorfo, sem sintomas esquizofrênicos"
* $BRCID10#F23 "Transtornos psicóticos agudos e transitórios"
* $BRCID10#F22.9 "Transtorno delirante persistente não especificado"
* $BRCID10#F22.8 "Outros transtornos delirantes persistentes"
* $BRCID10#F22.0 "Transtorno delirante"
* $BRCID10#F22 "Transtornos delirantes persistentes"
* $BRCID10#F21 "Transtorno esquizotípico"
* $BRCID10#F20.9 "Esquizofrenia não especificada"
* $BRCID10#F20.8 "Outras esquizofrenias"
* $BRCID10#F20.6 "Esquizofrenia simples"
* $BRCID10#F20.5 "Esquizofrenia residual"
* $BRCID10#F20.4 "Depressão pós-esquizofrênica"
* $BRCID10#F20.3 "Esquizofrenia indiferenciada"
* $BRCID10#F20.2 "Esquizofrenia catatônica"
* $BRCID10#F20.1 "Esquizofrenia hebefrênica"
* $BRCID10#F20.0 "Esquizofrenia paranóide"
* $BRCID10#F20 "Esquizofrenia"
* $BRCID10#C06.9 "Neoplasia maligna da boca, não especificada"
* $BRCID10#C06.1 "Neoplasia maligna do vestíbulo da boca"
* $BRCID10#C10.9 "Neoplasia maligna da orofaringe, não especificada"
* $BRCID10#C11.9 "Neoplasia maligna da nasofaringe, não especificada"
* $BRCID10#C16.2 "Neoplasia maligna do corpo do estômago"
* $BRCID10#C16.1 "Neoplasia maligna do fundo do estômago"
* $BRCID10#C15.9 "Neoplasia maligna do esôfago, não especificado"
* $BRCID10#C14.0 "Neoplasia maligna da faringe, não especificada"
* $BRCID10#F31 "Transtorno afetivo bipolar"
* $BRCID10#F31.9 "Transtorno afetivo bipolar não especificado"
* $BRCID10#F31.8 "Outros transtornos afetivos bipolares"
* $BRCID10#F31.7 "Transtorno afetivo bipolar, atualmente em remissão"
* $BRCID10#F31.6 "Transtorno afetivo bipolar, episódio atual misto"
* $BRCID10#F31.5 "Transtorno afetivo bipolar, episódio atual depressivo grave com sintomas psicóticos"
* $BRCID10#F31.4 "Transtorno afetivo bipolar, episódio atual depressivo grave sem sintomas psicóticos"
* $BRCID10#F31.3 "Transtorno afetivo bipolar, episódio atual depressivo leve ou moderado"
* $BRCID10#F31.2 "Transtorno afetivo bipolar, episódio atual maníaco com sintomas psicóticos"
* $BRCID10#F31.1 "Transtorno afetivo bipolar, episódio atual maníaco sem sintomas psicóticos"
* $BRCID10#F31.0 "Transtorno afetivo bipolar, episódio atual hipomaníaco"
* $BRCID10#C50.9 "Neoplasia maligna da mama, não especificada"
* $BRCID10#C78.4 "Neoplasia maligna secundária do intestino delgado"
* $BRCID10#C71.9 "Neoplasia maligna do encéfalo, não especificado"
* $BRCID10#C69.9 "Neoplasia maligna do olho, não especificado"
* $BRCID10#C50.0 "Neoplasia maligna do mamilo e aréola"
* $BRCID10#C44.5 "Neoplasia maligna da pele do tronco"
* $BRCID10#Z99.0 "Dependência de aspirador"
* $BRCID10#Z99 "Dependência de máquinas e dispositivos capacitantes, não classificados em outra parte"
* $BRCID10#Z98.8 "Outros estados pós-cirúrgicos especificados"
* $BRCID10#Z98.2 "Presença de dispositivo de drenagem do líquor"
* $BRCID10#Z98.1 "Artrodese"
* $BRCID10#Z98.0 "Derivação intestinal ou anastomose intestinal"
* $BRCID10#Z98 "Outros estados pós-cirúrgicos"
* $BRCID10#Z97.8 "Presença de outros dispositivos especificados"
* $BRCID10#Z97.1 "Presença de membro artificial (completo) (parcial)"
* $BRCID10#Z97.0 "Presença de olho artificial"
* $BRCID10#Z97 "Presença de outros dispositivos protéticos"
* $BRCID10#Z96.9 "Presença de implante funcional não especificado"
* $BRCID10#Z96.8 "Presença de outros implantes funcionais especificados"
* $BRCID10#Z96.7 "Presença de outros implantes de osso e tendão"
* $BRCID10#Z96.6 "Presença de implantes articulares ortopédicos"
* $BRCID10#Z96.5 "Presença de raiz dentária e implantes mandibulares"
* $BRCID10#Z96.4 "Presença de implantes endócrinos"
* $BRCID10#Z96.2 "Presença de implante otológicos e audiológicos"
* $BRCID10#Z96.1 "Presença de lente intra-ocular"
* $BRCID10#Z96.0 "Presença de implantes urogenitais"
* $BRCID10#Z96 "Presença de outros implantes funcionais"
* $BRCID10#Z95.9 "Presença de implante e enxerto cardíaco e vascular não especificado"
* $BRCID10#Z95.8 "Presença de outros implantes e enxertos cardíacos e vasculares"
* $BRCID10#Z95.5 "Presença de implante e enxerto de angioplastia coronária"
* $BRCID10#Z95.4 "Presença de outras substituições valvares cardíacas"
* $BRCID10#Z95.3 "Presença de valva cardíaca xenógena"
* $BRCID10#Z95.2 "Presença de prótese de válvula cardíaca"
* $BRCID10#Z95.1 "Presença de enxerto de ponte [\"bypass\"] aortocoronária"
* $BRCID10#Z95.0 "Presença de marca-passo cardíaco"
* $BRCID10#Z95 "Presença de implantes e enxertos cardíacos e vasculares"
* $BRCID10#Z94.9 "Órgão e tecido não especificado transplantado"
* $BRCID10#Z94.8 "Outros órgãos e tecidos transplantados"
* $BRCID10#Z94.7 "Córnea transplantada"
* $BRCID10#Z94.6 "Osso transplantado"
* $BRCID10#Z94.5 "Pele transplantada"
* $BRCID10#Z94.4 "Fígado transplantado"
* $BRCID10#Z94.3 "Coração e pulmões transplantados"
* $BRCID10#Z94.2 "Pulmão transplantado"
* $BRCID10#Z94.1 "Coração transplantado"
* $BRCID10#Z94.0 "Rim transplantado"
* $BRCID10#Z94 "Órgãos e tecidos transplantados"
* $BRCID10#Z93.9 "Orifício artificial não especificado"
* $BRCID10#Z93.8 "Outros orifícios artificiais"
* $BRCID10#Z93.6 "Outros orifícios artificiais do aparelho urinário"
* $BRCID10#Z93.5 "Cistostomia"
* $BRCID10#Z93.4 "Outros orifícios artificiais do trato gastrointestinal"
* $BRCID10#Z93.3 "Colostomia"
* $BRCID10#Z93.2 "Ileostomia"
* $BRCID10#Z93.1 "Gastrostomia"
* $BRCID10#Z93.0 "Traqueostomia"
* $BRCID10#Z93 "Orifícios artificiais"
* $BRCID10#Z92.3 "História pessoal de irradiação"
* $BRCID10#Z90.8 "Ausência adquirida de outros órgãos"
* $BRCID10#Z90.7 "Ausência adquirida de órgão(s) genital(is)"
* $BRCID10#Z90.6 "Ausência adquirida de outras partes do trato urinário"
* $BRCID10#Z90.5 "Ausência adquirida do rim"
* $BRCID10#Z90.4 "Ausência adquirida de outras partes do trato digestivo"
* $BRCID10#Z90.3 "Ausência adquirida de parte do estômago"
* $BRCID10#Z90.2 "Ausência adquirida [de parte] do pulmão"
* $BRCID10#Z90.1 "Ausência adquirida da(s) mama(s)"
* $BRCID10#Z90.0 "Ausência adquirida de parte da cabeça e do pescoço"
* $BRCID10#Z90 "Ausência adquirida de órgãos não classificados em outra parte"
* $BRCID10#Z99.9 "Dependência de máquina e aparelho capacitante não especificado"
* $BRCID10#Z99.8 "Dependência de outras máquinas e aparelhos capacitantes"
* $BRCID10#Z99.3 "Dependência de cadeira de rodas"
* $BRCID10#Z99.2 "Dependência de diálise renal"
* $BRCID10#Z99.1 "Dependência de respirador"
* $BRCID10#C25.9 "Neoplasia maligna do pâncreas, não especificado"
* $BRCID10#C14.2 "Neoplasia maligna do anel de Waldeyer"
* $BRCID10#C13.9 "Neoplasia maligna da hipofaringe, não especificada"
* $BRCID10#C09.9 "Neoplasia maligna da amígdala, não especificada"
* $BRCID10#C16.9 "Neoplasia maligna do estômago, não especificado"
* $BRCID10#C24.1 "Neoplasia maligna da ampola de Vater"
* $BRCID10#C79 "Neoplasia maligna secundária de outras localizações"
* $BRCID10#C32.9 "Neoplasia maligna da laringe, não especificada"
* $BRCID10#C44.9 "Neoplasia maligna da pele, não especificada"
* $BRCID10#C70.9 "Neoplasia maligna da meninge, não especificada"
* $BRCID10#C69 "Neoplasia maligna do olho e anexos"
* $BRCID10#C67.1 "Neoplasia maligna da cúpula da bexiga"
* $BRCID10#C75.1 "Neoplasia maligna da glândula hipófise (pituitária)"
* $BRCID10#C74.1 "Neoplasia maligna da medula da supra-renal"
* $BRCID10#C47.5 "Neoplasia maligna dos nervos periféricos da pelve"
* $BRCID10#C48.1 "Neoplasia maligna de partes especificadas do peritônio"
* $BRCID10#Z89 "Ausência adquirida de membros"
* $BRCID10#Z89.9 "Ausência adquirida de membro não especificado"
* $BRCID10#Z89.8 "Ausência adquirida dos membros superiores e inferiores [qualquer nível]"
* $BRCID10#Z89.7 "Ausência adquirida de ambos membros inferiores [qualquer nível, exceto somente artelhos]"
* $BRCID10#Z89.6 "Ausência adquirida da perna acima do joelho"
* $BRCID10#Z89.5 "Ausência adquirida da perna ao nível ou abaixo do joelho"
* $BRCID10#Z89.4 "Ausência adquirida de pé e tornozelo"
* $BRCID10#Z89.3 "Ausência adquirida de ambos membros superiores [qualquer nível]"
* $BRCID10#Z89.2 "Ausência adquirida de braço acima do punho"
* $BRCID10#Z89.1 "Ausência adquirida de mão e punho"
* $BRCID10#Z89.0 "Ausência adquirida de dedo(s) da mão [inclusive polegar] unilateral"
* $BRCID10#T32.8 "Corrosões envolvendo 80 - 89% da superfície corporal"
* $BRCID10#T31.8 "Queimaduras envolvendo de 80 - 89% da superfície corporal"
* $BRCID10#C50.8 "Neoplasia maligna da mama com lesão invasiva"
* $BRCID10#C51.8 "Neoplasia maligna da vulva com lesão invasiva"
* $BRCID10#C60.8 "Neoplasia maligna do pênis com lesão invasiva"
* $BRCID10#C64 "Neoplasia maligna do rim, exceto pelve renal"
* $BRCID10#C67.3 "Neoplasia maligna da parede anterior da bexiga"
* $BRCID10#C71.8 "Neoplasia maligna do encéfalo com lesão invasiva"
* $BRCID10#C79.7 "Neoplasia maligna secundária das glândulas supra-renais (adrenais)"
* $BRCID10#C74 "Neoplasia maligna da glândula supra-renal [Glândula adrenal]"
* $BRCID10#C74.9 "Neoplasia maligna da glândula supra-renal, não especificada"
* $BRCID10#C75.9 "Neoplasia maligna de glândula endócrina, não especificada"
* $BRCID10#C76.0 "Neoplasia maligna da cabeça, face e pescoço"
* $BRCID10#C25.7 "Neoplasia maligna de outras partes do pâncreas"
* $BRCID10#C17.9 "Neoplasia maligna do intestino delgado, não especificado"
* $BRCID10#C18.5 "Neoplasia maligna da flexura (ângulo) esplênica(o)"
* $BRCID10#C18.8 "Neoplasia maligna do cólon com lesão invasiva"
* $BRCID10#C34 "Neoplasia maligna dos brônquios e dos pulmões"
* $BRCID10#C38 "Neoplasia maligna do coração, mediastino e pleura"
* $BRCID10#C38.3 "Neoplasia maligna do mediastino, porção não especificada"
* $BRCID10#C44.8 "Neoplasia maligna da pele com lesão invasiva"
* $BRCID10#C00.3 "Neoplasia maligna do lábio superior, face interna"
* $BRCID10#C00.2 "Neoplasia maligna do lábio externo, não especificado"
* $BRCID10#C02.0 "Neoplasia maligna da face dorsal da língua"
* $BRCID10#C00.8 "Neoplasia maligna do lábio com lesão invasiva"
* $BRCID10#C02.8 "Neoplasia maligna da língua com lesão invasiva"
* $BRCID10#C02.2 "Neoplasia maligna da face ventral da língua"
* $BRCID10#C04.0 "Neoplasia maligna do assoalho anterior da boca"
* $BRCID10#C04.1 "Neoplasia maligna do assoalho lateral da boca"
* $BRCID10#C05.8 "Neoplasia maligna do palato com lesão invasiva"
* $BRCID10#C10.8 "Neoplasia maligna da orofaringe com lesão invasiva"
* $BRCID10#C10.3 "Neoplasia maligna da parede posterior da orofaringe"
* $BRCID10#M24.6 "Ancilose articular"
* $BRCID10#C10.2 "Neoplasia maligna da parede lateral da orofaringe"
* $BRCID10#C10.1 "Neoplasia maligna da face anterior da epiglote"
* $BRCID10#C09.8 "Neoplasia maligna da amígdala com lesão invasiva"
* $BRCID10#C09.1 "Neoplasia maligna do pilar amigdaliano (anterior) (posterior)"
* $BRCID10#C13.1 "Neoplasia maligna da prega ariepiglótica, face hipofaríngea"
* $BRCID10#C11.3 "Neoplasia maligna da parede anterior da nasofaringe"
* $BRCID10#C11.2 "Neoplasia maligna da parede lateral da nasofaringe"
* $BRCID10#C11.1 "Neoplasia maligna da parede posterior da nasofaringe"
* $BRCID10#C11.0 "Neoplasia maligna da parede superior da nasofaringe"
* $BRCID10#C13.8 "Neoplasia maligna da hipofaringe com lesão invasiva"
* $BRCID10#C13.2 "Neoplasia maligna da parede posterior da hipofaringe"
* $BRCID10#C15.8 "Neoplasia maligna do esôfago com lesão invasiva"
* $BRCID10#C15.5 "Neoplasia maligna do terço inferior do esôfago"
* $BRCID10#C15.4 "Neoplasia maligna do terço médio do esôfago"
* $BRCID10#Z85.3 "História pessoal de neoplasia maligna de mama"
* $BRCID10#C67.2 "Neoplasia maligna da parede lateral da bexiga"
* $BRCID10#C62.9 "Neoplasia maligna do testículo, sem outras especificações"
* $BRCID10#C47.6 "Neoplasia maligna dos nervos periféricos do tronco"
* $BRCID10#C32.8 "Neoplasia maligna da laringe com lesão invasiva"
* $BRCID10#C15.3 "Neoplasia maligna do terço superior do esôfago"
* $BRCID10#C11.8 "Neoplasia maligna da nasofaringe com lesão invasiva"
* $BRCID10#C00.4 "Neoplasia maligna do lábio inferior, face interna"
* $BRCID10#C25.8 "Neoplasia maligna do pâncreas com lesão invasiva"
* $BRCID10#C18.3 "Neoplasia maligna da flexura (ângulo) hepática(o)"
* $BRCID10#C16.8 "Neoplasia maligna do estômago com lesão invasiva"
* $BRCID10#C41.3 "Neoplasia maligna das costelas, esterno e clavícula"
* $BRCID10#C24.9 "Neoplasia maligna da via biliar, não especificada"
* $BRCID10#M19.9 "Artrose não especificada"
* $BRCID10#M19.8 "Outras artroses especificadas"
* $BRCID10#M19.2 "Outras artroses secundárias"
* $BRCID10#M19.1 "Artrose pós-traumática de outras articulações"
* $BRCID10#M19.0 "Artrose primária de outras articulações"
* $BRCID10#M19 "Outras artroses"
* $BRCID10#M18.9 "Artrose não especificada da primeira articulação carpometacarpiana"
* $BRCID10#M18.5 "Outras artroses secundárias da primeira articulação carpometacarpiana"
* $BRCID10#M18.4 "Outras cartroses secundárias bilaterais das primeiras articulações carpometacarpianas"
* $BRCID10#M18.3 "Outras artroses pós-traumáticas da primeira articulação carpometacarpiana"
* $BRCID10#M18.2 "Artrose pós-traumática bilateral da primeira articulação carpometacarpiana"
* $BRCID10#M18.1 "Outras artroses primárias da primeira articulação carpometacarpiana"
* $BRCID10#M18.0 "Artrose primária bilateral das primeiras articulações carpometacarpianas"
* $BRCID10#M18 "Artrose da primeira articulação carpometacarpiana"
* $BRCID10#M17.9 "Gonartrose não especificada"
* $BRCID10#M17.5 "Outras gonartroses secundárias"
* $BRCID10#M17.4 "Outras gonartroses secundárias bilaterais"
* $BRCID10#M17.3 "Outras gonartroses pós-traumática"
* $BRCID10#M17.2 "Gonartrose pós-traumática bilateral"
* $BRCID10#M17.1 "Outras gonartroses primárias"
* $BRCID10#M17.0 "Gonartrose primária bilateral"
* $BRCID10#M17 "Gonartrose [artrose do joelho]"
* $BRCID10#M16.9 "Coxartrose não especificada"
* $BRCID10#M16.7 "Outras coxartroses secundárias"
* $BRCID10#M16.6 "Outras coxartroses secundárias bilaterais"
* $BRCID10#M16.5 "Outras coxartroses pós-traumáticas"
* $BRCID10#M16.4 "Coxartrose bilateral pós-traumática"
* $BRCID10#M16.3 "Outras coxartroses displásicas"
* $BRCID10#M16.2 "Coxartrose bilateral resultante de displasia"
* $BRCID10#M16.1 "Outras coxartroses primárias"
* $BRCID10#M16.0 "Coxartrose primária bilateral"
* $BRCID10#M16 "Coxartrose [artrose do quadril]"
* $BRCID10#M15.9 "Poliartrose não especificada"
* $BRCID10#M15.8 "Outras poliartroses"
* $BRCID10#M15.4 "(Osteo)artrose erosiva"
* $BRCID10#M15.3 "Artrose múltipla secundária"
* $BRCID10#M15.2 "Nódulos de Bouchard (com artropatia)"
* $BRCID10#M15.1 "Nódulos de Heberden (com artropatia)"
* $BRCID10#M15.0 "(Osteo)artrose primária generalizada"
* $BRCID10#M15 "Poliartrose"
* $BRCID10#M14.8 "Artropatias em outras doenças especificadas classificadas em outra parte"
* $BRCID10#M14.6 "Artropatia neuropática"
* $BRCID10#M14.5 "Artropatias em outras doenças endócrinas, nutricionais e metabólicas"
* $BRCID10#M14.4 "Artropatia na amiloidose"
* $BRCID10#M14.3 "Dermatoartrite lipóide"
* $BRCID10#M14.2 "Artropatia diabética"
* $BRCID10#M14.1 "Artropatia por depósito de cristais em outras doenças metabólicas classificadas em outra parte"
* $BRCID10#M14.0 "Artropatia gotosa devida a defeitos enzimáticos e a outras doenças hereditárias"
* $BRCID10#M14 "Artropatias em outras doenças classificadas em outra parte"
* $BRCID10#M13.9 "Artrite não especificada"
* $BRCID10#M13.8 "Outras artrites especificadas"
* $BRCID10#M13.1 "Monoartrites não classificadas em outra parte"
* $BRCID10#M13.0 "Poliartrite não especificada"
* $BRCID10#M13 "Outras artrites"
* $BRCID10#M12.8 "Outras artropatias específicas não classificadas em outra parte"
* $BRCID10#M12.5 "Artropatia traumática"
* $BRCID10#M12.4 "Hidrartrose intermitente"
* $BRCID10#M12.3 "Reumatismo palindrômico"
* $BRCID10#M12.2 "Sinovite vilonodular (pigmentada)"
* $BRCID10#M12.1 "Doença de Kashin-Beck"
* $BRCID10#M12.0 "Artropatia pós-reumática crônica [Jaccoud]"
* $BRCID10#M12 "Outras artropatias especificadas"
* $BRCID10#M11.9 "Artropatia por deposição de cristais, não especificada"
* $BRCID10#M11.8 "Outras artropatias especificadas por deposição de cristais"
* $BRCID10#M11.2 "Outras condrocalcinoses"
* $BRCID10#M11.1 "Condrocalcinose familiar"
* $BRCID10#M11.0 "Doença por deposição de hidroxiapatita"
* $BRCID10#M11 "Outras artropatias por deposição de cristais"
* $BRCID10#M10.9 "Gota, não especificada"
* $BRCID10#M10.4 "Outra gota secundária"
* $BRCID10#M10.3 "Gota devida à disfunção renal"
* $BRCID10#M10.2 "Gota induzida por drogas"
* $BRCID10#M10.1 "Gota induzida por chumbo"
* $BRCID10#M10.0 "Gota idiopática"
* $BRCID10#M10 "Gota"
* $BRCID10#C47.3 "Neoplasia maligna dos nervos periféricos do tórax"
* $BRCID10#C47.4 "Neoplasia maligna dos nervos periféricos do abdome"
* $BRCID10#C55 "Neoplasia maligna do útero, porção não especificada"
* $BRCID10#C69.5 "Neoplasia maligna da glândula e canal lacrimal"
* $BRCID10#C68.9 "Neoplasia maligna de órgão urinário, não especificado"
* $BRCID10#C67.9 "Neoplasia maligna da bexiga, sem outra especificações"
* $BRCID10#C67.8 "Neoplasia maligna da bexiga com lesão invasiva"
* $BRCID10#C67.4 "Neoplasia maligna da parede posterior da bexiga"
* $BRCID10#C79.8 "Neoplasia maligna secundária de outra localização especificada"
* $BRCID10#C76.7 "Neoplasia maligna de outras localizações mal definidas"
* $BRCID10#A16 "Tuberculose das vias respiratórias, sem confirmação bacteriológica ou histológica"
* $BRCID10#A16.9 "Tuberculose respiratória, não especificada, sem menção de confirmação bacteriológica ou histológica"
* $BRCID10#A16.8 "Outras formas de tuberculose das vias respiratórias, sem menção de confirmação bacteriológica ou histológica"
* $BRCID10#A16.7 "Tuberculosa respiratória primária sem menção de confirmação bacteriológica ou histológica"
* $BRCID10#A16.5 "Pleurisia tuberculosa, sem menção de confirmação bacteriológica ou histológica"
* $BRCID10#A16.4 "Tuberculose da laringe, da traquéia e dos brônquios, sem menção de confirmação bacteriológica ou histológica"
* $BRCID10#A16.3 "Tuberculose dos gânglios intratorácicos, sem menção de confirmação bacteriológica ou histológica"
* $BRCID10#A16.2 "Tuberculose pulmonar, sem menção de confirmação bacteriológica ou histológica"
* $BRCID10#A16.1 "Tuberculose pulmonar, sem realização de exame bacteriológico ou histológico"
* $BRCID10#A16.0 "Tuberculose pulmonar com exames bacteriológico e histológico negativos"
* $BRCID10#C50.2 "Neoplasia maligna do quadrante superior interno da mama"
* $BRCID10#C50.3 "Neoplasia maligna do quadrante inferior interno da mama"
* $BRCID10#C50.4 "Neoplasia maligna do quadrante superior externo da mama"
* $BRCID10#C50.5 "Neoplasia maligna do quadrante inferior externo da mama"
* $BRCID10#C53.9 "Neoplasia maligna do colo do útero, não especificado"
* $BRCID10#C63.9 "Neoplasia maligna de órgão genital masculino, não especificado"
* $BRCID10#C63.7 "Neoplasia maligna de outros órgãos genitais masculinos especificados"
* $BRCID10#C71.0 "Neoplasia maligna do cérebro, exceto lobos e ventrículos"
* $BRCID10#C75.5 "Neoplasia maligna do corpo aórtico e outros paragânglios"
* $BRCID10#C26.8 "Neoplasia maligna do aparelho digestivo com lesão invasiva"
* $BRCID10#C26.0 "Neoplasia maligna do trato intestinal, parte não especificada"
* $BRCID10#C31.9 "Neoplasia maligna do seio da face, não especificado"
* $BRCID10#G83.9 "Síndrome paralítica não especificada"
* $BRCID10#G83.8 "Outras síndromes paralíticas especificadas"
* $BRCID10#G83.4 "Síndrome da cauda eqüina"
* $BRCID10#G83.3 "Monoplegia não especificada"
* $BRCID10#G83.2 "Monoplegia do membro superior"
* $BRCID10#G83.1 "Monoplegia do membro inferior"
* $BRCID10#G83.0 "Diplegia dos membros superiores"
* $BRCID10#G83 "Outras síndromes paralíticas"
* $BRCID10#G82.5 "Tetraplegia não especificada"
* $BRCID10#G82.4 "Tetraplegia espástica"
* $BRCID10#G82.3 "Tetraplegia flácida"
* $BRCID10#G82.2 "Paraplegia não especificada"
* $BRCID10#G82.1 "Paraplegia espástica"
* $BRCID10#G82.0 "Paraplegia flácida"
* $BRCID10#G82 "Paraplegia e tetraplegia"
* $BRCID10#G81.9 "Hemiplegia não especificada"
* $BRCID10#G81.1 "Hemiplegia espástica"
* $BRCID10#G81.0 "Hemiplegia flácida"
* $BRCID10#G81 "Hemiplegia"
* $BRCID10#C96 "Outras neoplasias malignas e as não especificadas dos tecidos linfático, hematopoético e tecidos correlatos"
* $BRCID10#B21.3 "Doença pelo HIV resultando em outras neoplasias malignas dos tecidos linfático, hematopoético e correlatos"
* $BRCID10#A80 "Poliomielite aguda"
* $BRCID10#A80.9 "Poliomielite aguda não especificada"
* $BRCID10#A80.4 "Poliomielite aguda não-paralítica"
* $BRCID10#A80.3 "Poliomielites paralíticas agudas, outras e não especificadas"
* $BRCID10#A80.2 "Poliomielite paralítica aguda, vírus selvagem indígena"
* $BRCID10#A80.1 "Poliomielite paralítica aguda, vírus selvagem importado"
* $BRCID10#A80.0 "Poliomielite paralítica aguda, associada ao vírus vacinal"
* $BRCID10#S23.0 "Ruptura traumática de disco intervertebral torácico"
* $BRCID10#S13.0 "Ruptura traumática de disco intervertebral cervical"
* $BRCID10#M99.5 "Estenose de disco intervertebral do canal medular"
* $BRCID10#C46.7 "Sarcoma de Kaposi de outras localizações"
* $BRCID10#G30.8 "Outras formas de doença de Alzheimer"
* $BRCID10#G30.1 "Doença de Alzheimer de início tardio"
* $BRCID10#F01 "Demência vascular"
* $BRCID10#F03 "Demência não especificada"
* $BRCID10#F01.2 "Demência vascular subcortical"
* $BRCID10#F01.8 "Outra demência vascular"
* $BRCID10#F01.1 "Demência por infartos múltiplos"
* $BRCID10#F01.9 "Demência vascular não especificada"
* $BRCID10#F00 "Demência na doença de Alzheimer"
* $BRCID10#F02.0 "Demência da doença de Pick"
* $BRCID10#F02.2 "Demência na doença de Huntington"
* $BRCID10#F05.1 "Delirium superposto a uma demência"
* $BRCID10#F02.3 "Demência na doença de Parkinson"
* $BRCID10#M54.9 "Dorsalgia não especificada"
* $BRCID10#M54.8 "Outra dorsalgia"
* $BRCID10#M54.6 "Dor na coluna torácica"
* $BRCID10#M54.5 "Dor lombar baixa"
* $BRCID10#M54.4 "Lumbago com ciática"
* $BRCID10#M54.3 "Ciática"
* $BRCID10#M54.2 "Cervicalgia"
* $BRCID10#M54.1 "Radiculopatia"
* $BRCID10#M54.0 "Paniculite atingindo regiões do pescoço e do dorso"
* $BRCID10#M54 "Dorsalgia"
* $BRCID10#M53.9 "Dorsopatia não especificada"
* $BRCID10#M53.8 "Outras dorsopatias especificadas"
* $BRCID10#M53.3 "Transtornos sacroccígeos não classificados em outra parte"
* $BRCID10#M53.2 "Instabilidades da coluna vertebral"
* $BRCID10#M53.1 "Síndrome cervicobraquial"
* $BRCID10#M53.0 "Síndrome cervicocraniana"
* $BRCID10#M53 "Outras dorsopatias não classificadas em outra parte"
* $BRCID10#M51.9 "Transtorno não especificado de disco intervertebral"
* $BRCID10#M51.8 "Outros transtornos especificados de discos intervertebrais"
* $BRCID10#M51.4 "Nódulos de Schmorl"
* $BRCID10#M51.3 "Outra degeneração especificada de disco intervertebral"
* $BRCID10#M51.2 "Outros deslocamentos discais intervertebrais especificados"
* $BRCID10#M51.1 "Transtornos de discos lombares e de outros discos intervertebrais com radiculopatia"
* $BRCID10#M51.0 "Transtornos de discos lombares e de outros discos intervertebrais com mielopatia"
* $BRCID10#M51 "Outros transtornos de discos intervertebrais"
* $BRCID10#M50.9 "Transtorno não especificado de disco cervical"
* $BRCID10#M50.8 "Outros transtornos de discos cervicais"
* $BRCID10#M50.3 "Outra degeneração de disco cervical"
* $BRCID10#M50.2 "Outro deslocamento de disco cervical"
* $BRCID10#M50.1 "Transtorno do disco cervical com radiculopatia"
* $BRCID10#M50.0 "Transtorno do disco cervical com mielopatia"
* $BRCID10#M50 "Transtornos dos discos cervicais"
* $BRCID10#F01.0 "Demência vascular de início agudo"
* $BRCID10#F02.1 "Demência na doença de Creutzfeldt-Jakob"
* $BRCID10#F01.3 "Demência vascular mista, cortical e subcortical"
* $BRCID10#F00.9 "Demência não especificada na doença de Alzheimer"
* $BRCID10#F02 "Demência em outras doenças classificadas em outra parte"
* $BRCID10#F00.1 "Demência na doença de Alzheimer de início tardio"
* $BRCID10#F05.0 "Delirium não superposto a uma demência, assim descrito"
* $BRCID10#F00.0 "Demência na doença de Alzheimer de início precoce"
* $BRCID10#F02.8 "Demência em outras doenças especificadas classificadas em outra parte"
* $BRCID10#F02.4 "Demência na doença pelo vírus da imunodeficiência humana [HIV]"
* $BRCID10#F00.2 "Demência na doença de Alzheimer, forma atípica ou mista"
* $BRCID10#N18 "Insuficiência renal crônica"
* $BRCID10#N18.9 "Insuficiência renal crônica não especificada"
* $BRCID10#N18.8 "Outra insuficiência renal crônica"
* $BRCID10#N18.0 "Doença renal em estádio final"
* $BRCID10#Y70.2 "Dispositivos (aparelhos) de anestesiologia, associados a incidentes adversos - próteses e outros implantes, incluindo materiais"
* $BRCID10#Y71.2 "Dispositivos (aparelhos) cardiovasculares, associados a incidentes adversos - próteses e outros implantes, incluindo materiais e"
* $BRCID10#Y72.2 "Dispositivos (aparelhos) utilizados em otorrinolaringologia, associados a incidentes adversos - próteses e outros implantes, inc"
* $BRCID10#Y77.2 "Dispositivos (aparelhos) utilizados em oftalmologia, associados a incidentes adversos - próteses e outros implantes, incluindo m"
* $BRCID10#Y78.2 "Dispositivos (aparelhos) utilizados em radiologia, associados a incidentes adversos - próteses e outros implantes, incluindo mat"
* $BRCID10#Y79.2 "Dispositivos (aparelhos) ortopédicos, associado a incidentes adversos - próteses e outros implantes, incluindo materiais e acess"
* $BRCID10#Y80.2 "Dispositivos (aparelhos) utilizados em medicina física (fisiatria), associado a incidentes adversos - próteses e outros implante"
* $BRCID10#Y75.2 "Dispositivos (aparelhos) utilizados em neurologia, associados a incidentes adversos - próteses e outros implantes, incluindo mat"
* $BRCID10#Y82.2 "Outros dispositivos (aparelhos) associados a incidentes adversos e os não especificados - próteses e outros implantes, incluindo"
* $BRCID10#Y76.2 "Dispositivos (aparelhos) utilizados em obstetrícia e em ginecologia, associados a incidentes adversos - próteses e outros implan"
* $BRCID10#Y73.2 "Dispositivos (aparelhos) usados em gastroenterologia e em urologia, associados a incidentes adversos - próteses e outros implant"
* $BRCID10#Y81.2 "Dispositivos (aparelhos) utilizados em cirurgia geral ou cirurgia plástica, associados a incidente adversos - próteses e outros"
* $BRCID10#Y74.2 "Dispositivos (aparelhos) gerais de uso hospitalar ou pessoal, associados a incidentes adversos - próteses e outros implantes, in"
* $BRCID10#G56 "Mononeuropatias dos membros superiores"
* $BRCID10#G56.9 "Mononeuropatia dos membros superiores, não especificada"
* $BRCID10#G56.8 "Outras mononeuropatias dos membros superiores"
* $BRCID10#G56.4 "Causalgia"
* $BRCID10#G56.3 "Lesão do nervo radial"
* $BRCID10#G56.2 "Lesões do nervo cubital [ulnar]"
* $BRCID10#G56.1 "Outras lesões do nervo mediano"
* $BRCID10#G56.0 "Síndrome do túnel do carpo"
* $BRCID10#G13.0 "Neuromiopatia e neuropatia paraneoplásicas"
* $BRCID10#G60.0 "Neuropatia hereditária motora e sensorial"
* $BRCID10#G60.2 "Neuropatia associada a ataxia hereditária"
* $BRCID10#G99.0 "Neuropatia autonômica em doenças endócrinas e metabólicas"
* $BRCID10#M06 "Outras artrites reumatóides"
* $BRCID10#M06.9 "Artrite reumatóide não especificada"
* $BRCID10#M06.8 "Outras artrites reumatóides especificadas"
* $BRCID10#M06.4 "Poliartropatia inflamatória"
* $BRCID10#M06.3 "Nódulo reumatóide"
* $BRCID10#M06.2 "Bursite reumatóide"
* $BRCID10#M06.1 "Doença de Still do adulto"
* $BRCID10#M06.0 "Artrite reumatóide soro-negativa"
* $BRCID10#B23 "Doença pelo vírus da imunodeficiência humana [HIV] resultando em outras doenças"
* $BRCID10#B21 "Doença pelo vírus da imunodeficiência humana [HIV], resultando em neoplasias malignas"
* $BRCID10#B22 "Doença pelo vírus da imunodeficiência humana [HIV] resultando em outras doenças especificadas"
* $BRCID10#B22.7 "Doença pelo HIV resultando em doenças múltiplas classificadas em outra parte"
* $BRCID10#M77 "Outras entesopatias"
* $BRCID10#M77.9 "Entesopatia não especificada"
* $BRCID10#M77.8 "Outras entesopatias não classificadas em outra parte"
* $BRCID10#M77.5 "Outra entesopatia do pé"
* $BRCID10#M77.4 "Metatarsalgia"
* $BRCID10#M77.3 "Esporão do calcâneo"
* $BRCID10#M77.2 "Periartrite do punho"
* $BRCID10#M77.1 "Epicondilite lateral"
* $BRCID10#M77.0 "Epicondilite medial"
* $BRCID10#H44.2 "Miopia degenerativa"
* $BRCID10#G23.9 "Doença degenerativa dos gânglios da base, não especificada"
* $BRCID10#H44.5 "Afecções degenerativas do globo ocular"
* $BRCID10#G23 "Outras doenças degenerativas dos gânglios da base"
* $BRCID10#G23.8 "Outras doenças degenerativas especificadas dos gânglios da base"
* $BRCID10#Q86 "Síndromes com malformações congênitas devidas a causas exógenas conhecidas, não classificadas em outra parte"
* $BRCID10#Q86.8 "Outras síndromes com malformações congênitas devidas a causas exógenas conhecidas"
* $BRCID10#Q86.2 "Dismorfismo devido ao Warfarin"
* $BRCID10#Q86.1 "Síndrome fetal devida à hidantoína"
* $BRCID10#Q86.0 "Síndrome fetal alcoólico (dismórfico)"
* $BRCID10#M96.0 "Pseudo-artrose após fusão ou artrodese"
* $BRCID10#Q87 "Outras síndromes com malformações congênitas que acometem múltiplos sistemas"
* $BRCID10#Q87.8 "Outras síndromes com malformações congênitas especificadas, não classificadas em outra parte"
* $BRCID10#Q87.5 "Outras síndromes com malformações congênitas com outras alterações do esqueleto"
* $BRCID10#Q87.4 "Síndrome de Marfan"
* $BRCID10#Q87.3 "Síndromes com malformações congênitas com hipercrescimento precoce"
* $BRCID10#Q87.2 "Síndromes com malformações congênitas afetando predominantemente os membros"
* $BRCID10#Q87.1 "Síndromes com malformações congênitas associadas predominantemente com nanismo"
* $BRCID10#Q87.0 "Síndromes com malformações congênitas afetando predominantemente o aspecto da face"
* $BRCID10#M88.8 "Doença de Paget de outros ossos"
* $BRCID10#M88.0 "Doença de Paget do crânio"
* $BRCID10#M88.9 "Doença de Paget de osso não especificado"
* $BRCID10#M88 "Doença de Paget do osso (osteíte deformante)"
* $BRCID10#B24 "Doença pelo vírus da imunodeficiência humana [HIV] não especificada"
* $BRCID10#Q68.2 "Deformidade congênita do joelho"
* $BRCID10#Q68.1 "Deformidade congênita da mão"
* $BRCID10#Q68.0 "Deformidade congênita do músculo esternocleidomastoideu"
* $BRCID10#Q65.9 "Deformidade congênita não especificada do quadril"
* $BRCID10#Q66.9 "Deformidade congênita não especificada do pé"
* $BRCID10#Q66 "Deformidades congênitas do pé"
* $BRCID10#Q67.8 "Outras deformidades congênitas do tórax"
* $BRCID10#Q65.8 "Outras deformidades congênitas do quadril"
* $BRCID10#Q67.5 "Deformidades congênitas da coluna vertebral"
* $BRCID10#Q66.8 "Outras deformidades congênitas do pé"
* $BRCID10#Q66.6 "Outras deformidades congênitas dos pés em valgo"
* $BRCID10#Q66.3 "Outras deformidades congênitas dos pés em varo"
* $BRCID10#Z87.7 "História pessoal de malformações e deformidades congênitas e anomalias cromossômicas"
* $BRCID10#Q67.4 "Outras deformidades congênitas do crânio, da face e da mandíbula"
* $BRCID10#B18 "Hepatite viral crônica"
* $BRCID10#B18.9 "Hepatite viral crônica não especificada"
* $BRCID10#B18.8 "Outras hepatites crônicas virais"
* $BRCID10#B18.2 "Hepatite viral crônica C"
* $BRCID10#B18.1 "Hepatite crônica viral B sem agente Delta"
* $BRCID10#B18.0 "Hepatite viral crônica B com agente Delta"
* $BRCID10#I12.0 "Doença renal hipertensiva com insuficiência renal"
* $BRCID10#I12.9 "Doença renal hipertensiva sem insuficiência renal"
* $BRCID10#P96.0 "Insuficiência renal congênita"
* $BRCID10#Q60.4 "Hipoplasia renal bilateral"
* $BRCID10#I12 "Doença renal hipertensiva"
* $BRCID10#Q60.3 "Hipoplasia renal unilateral"
* $BRCID10#I13.1 "Doença cardíaca e renal hipertensiva com insuficiência renal"
* $BRCID10#Q60.2 "Agenesia renal não especificada"
* $BRCID10#E84 "Fibrose cística"
* $BRCID10#E84.9 "Fibrose cística não especificada"
* $BRCID10#E84.8 "Fibrose cística com outras manifestações"
* $BRCID10#E84.1 "Fibrose cística com manifestações intestinais"
* $BRCID10#E84.0 "Fibrose cística com manifestações pulmonares"
* $BRCID10#I25.5 "Miocardiopatia isquêmica"
* $BRCID10#G31 "Outras doenças degenerativas do sistema nervoso não classificadas em outra parte"
* $BRCID10#G31.9 "Doença degenerativa do sistema nervoso, não especificada"
* $BRCID10#G31.8 "Outras doenças degenerativas especificadas do sistema nervoso"
* $BRCID10#G31.2 "Degeneração do sistema nervoso devida ao álcool"
* $BRCID10#G31.1 "Degeneração cerebral senil, não classificadas em outra parte"
* $BRCID10#G31.0 "Atrofia cerebral circunscrita"
* $BRCID10#I42.8 "Outras cardiomiopatias"
* $BRCID10#I27.1 "Cardiopatia cifoescoliótica"
* $BRCID10#I42 "Cardiomiopatias"
* $BRCID10#I27.9 "Cardiopatia pulmonar não especificada"
* $BRCID10#I42.6 "Cardiomiopatia alcoólica"
* $BRCID10#I42.9 "Cardiomiopatia não especificada"
* $BRCID10#I42.0 "Cardiomiopatia dilatada"
* $BRCID10#I42.2 "Outras cardiomiopatias hipertróficas"
* $BRCID10#I42.1 "Cardiomiopatia obstrutiva hipertrófica"
* $BRCID10#I42.5 "Outras cardiomiopatias restritivas"
* $BRCID10#I43.2 "Cardiomiopatia em doenças nutricionais"
* $BRCID10#I43 "Cardiomiopatia em doenças classificadas em outra parte"
* $BRCID10#I25.0 "Doença cardiovascular aterosclerótica, descrita desta maneira"
* $BRCID10#F99 "Transtorno mental não especificado em outra parte"
* $BRCID10#G98 "Outros transtornos do sistema nervoso não classificados em outra parte"
* $BRCID10#K70.3 "Cirrose hepática alcoólica"
* $BRCID10#K74.3 "Cirrose biliar primária"
* $BRCID10#K74.4 "Cirrose biliar secundária"
* $BRCID10#K74 "Fibrose e cirrose hepáticas"
* $BRCID10#K74.5 "Cirrose biliar, sem outra especificação"
* $BRCID10#K71.7 "Doença hepática tóxica com fibrose e cirrose hepáticas"
* $BRCID10#K74.6 "Outras formas de cirrose hepática e as não especificadas"
* $BRCID10#R23.0 "Cianose"
* $BRCID10#E14.9 "Diabetes mellitus não especificado - sem complicações"
* $BRCID10#E14.8 "Diabetes mellitus não especificado - com complicações não especificadas"
* $BRCID10#E14.7 "Diabetes mellitus não especificado - com complicações múltiplas"
* $BRCID10#E14.6 "Diabetes mellitus não especificado - com outras complicações especificadas"
* $BRCID10#E14.5 "Diabetes mellitus não especificado - com complicações circulatórias periféricas"
* $BRCID10#E14.4 "Diabetes mellitus não especificado - com complicações neurológicas"
* $BRCID10#E14.3 "Diabetes mellitus não especificado - com complicações oftálmicas"
* $BRCID10#E14.2 "Diabetes mellitus não especificado - com complicações renais"
* $BRCID10#E14.1 "Diabetes mellitus não especificado - com cetoacidose"
* $BRCID10#I36.2 "Estenose (da valva) tricúspide com insuficiência, não-reumática"
* $BRCID10#M75.1 "Síndrome do manguito rotador"
* $BRCID10#I50 "Insuficiência cardíaca"
* $BRCID10#I50.0 "Insuficiência cardíaca congestiva"
* $BRCID10#I52 "Outras afecções cardíacas em doenças classificadas em outra parte"
* $BRCID10#I52.0 "Outras afecções cardíacas em doenças bacterianas classificadas em outra parte"
* $BRCID10#I52.8 "Outras afecções cardíacas em outras doenças classificadas em outra parte"
* $BRCID10#I52.1 "Outras afecções cardíacas em outras doenças infecciosas e parasitárias classificadas em outra parte"
* $BRCID10#I50.9 "Insuficiência cardíaca não especificada"
* $BRCID10#I50.1 "Insuficiência ventricular esquerda"
* $BRCID10#E34.3 "Nanismo, não classificado em outra parte"
* $BRCID10#M96.5 "Escoliose pós-radiação"
* $BRCID10#Q76.3 "Escoliose congênita devida à malformação óssea congênita"
* $BRCID10#Q76.4 "Outras malformações congênitas da coluna vertebral não-associadas com escoliose"
* $BRCID10#M70 "Transtornos dos tecidos moles relacionados com o uso, uso excessivo e pressão"
* $BRCID10#M70.9 "Transtorno não especificado dos tecidos moles relacionados com o uso, uso excessivo e pressão"
* $BRCID10#M70.8 "Outros transtornos dos tecidos moles relacionados com o uso, uso excessivo e pressão"
* $BRCID10#M70.7 "Outras bursites do quadril"
* $BRCID10#M70.6 "Bursite trocantérica"
* $BRCID10#M70.5 "Outras bursites do joelho"
* $BRCID10#M70.4 "Bursite pré-patelar"
* $BRCID10#M70.3 "Outras bursites do cotovelo"
* $BRCID10#M70.2 "Bursite do olécrano"
* $BRCID10#M70.1 "Bursite da mão"
* $BRCID10#M70.0 "Sinovite crepitante crônica da mão e do punho"
* $BRCID10#M07 "Artropatias psoriásicas e enteropáticas"
* $BRCID10#M07.0 "Artropatia psoriásica interfalangiana distal"
* $BRCID10#M36.1 "Artropatia em doenças neoplásicas classificadas"
* $BRCID10#G35 "Esclerose múltipla"
* $BRCID10#M08.0 "Artrite reumatóide juvenil"
* $BRCID10#J99.0 "Doença pulmonar reumatóide"
* $BRCID10#A30 "Hanseníase [doença de Hansen] [lepra]"
* $BRCID10#A30.9 "Hanseníase [lepra] não especificada"
* $BRCID10#A30.8 "Outras formas de hanseníase [lepra]"
* $BRCID10#A30.5 "Hanseníase [lepra] lepromatosa"
* $BRCID10#A30.4 "Hanseníase [lepra] lepromatosa borderline"
* $BRCID10#A30.3 "Hanseníase [lepra] dimorfa"
* $BRCID10#A30.2 "Hanseníase [lepra] tuberculóide borderline"
* $BRCID10#A30.1 "Hanseníase [lepra] tuberculóide"
* $BRCID10#A30.0 "Hanseníase [lepra] indeterminada"
* $BRCID10#G21.3 "Parkinsonismo pós-encefalítico"
* $BRCID10#G22 "Parkinsonismo em doenças classificadas em outra parte"
* $BRCID10#G23.2 "Degeneração estrionígrica"
* $BRCID10#C85 "Linfoma não-Hodgkin de outros tipos e de tipo não especificado"
* $BRCID10#C85.9 "Linfoma não-Hodgkin de tipo não especificado"
* $BRCID10#C85.7 "Outros tipos especificados de linfoma não-Hodgkin"
* $BRCID10#C85.1 "Linfoma de células B, não especificado"
* $BRCID10#C85.0 "Linfossarcoma"
* $BRCID10#G20 "Doença de Parkinson"
* $BRCID10#M41 "Escoliose"
* $BRCID10#M41.9 "Escoliose não especificada"
* $BRCID10#M41.8 "Outras formas de escoliose"
* $BRCID10#M41.5 "Outras escolioses secundárias"
* $BRCID10#M41.4 "Escoliose neuromuscular"
* $BRCID10#M41.3 "Escoliose toracogênica"
* $BRCID10#M41.2 "Outras escolioses idiopáticas"
* $BRCID10#M41.1 "Escoliose idiopática juvenil"
* $BRCID10#M41.0 "Escoliose idiopática infantil"
* $BRCID10#I51 "Complicações de cardiopatias e doenças cardíacas mal definidas"
* $BRCID10#I51.9 "Doença não especificada do coração"
* $BRCID10#I51.8 "Outras doenças mal definidas do coração"
* $BRCID10#I51.7 "Cardiomegalia"
* $BRCID10#I51.6 "Doença cardiovascular não especificada"
* $BRCID10#I51.5 "Degeneração miocárdica"
* $BRCID10#I51.4 "Miocardite não especificada"
* $BRCID10#I51.3 "Trombose intracardíaca, não classificada em outra parte"
* $BRCID10#I51.2 "Ruptura de músculo papilar, não classificada em outra parte"
* $BRCID10#I51.1 "Ruptura de cordoalha tendínea, não classificada em outra parte"
* $BRCID10#I51.0 "Defeito adquirido de septo cardíaco"
* $BRCID10#K76 "Outras doenças do fígado"
* $BRCID10#K76.9 "Doença hepática, sem outra especificação"
* $BRCID10#K76.8 "Outras doenças especificadas do fígado"
* $BRCID10#K76.7 "Síndrome hepatorrenal"
* $BRCID10#K76.6 "Hipertensão portal"
* $BRCID10#K76.5 "Doença hepática veno-oclusiva"
* $BRCID10#K76.4 "Peliose hepática"
* $BRCID10#K76.3 "Infarto do fígado"
* $BRCID10#K76.2 "Necrose hemorrágica central do fígado"
* $BRCID10#K76.1 "Congestão passiva crônica do fígado"
* $BRCID10#K76.0 "Degeneração gordurosa do fígado não classificada em outra parte"
* $BRCID10#M21 "Outras deformidades adquiridas dos membros"
* $BRCID10#M21.9 "Deformidade adquirida não especificada de membro"
* $BRCID10#M21.8 "Outras deformidades adquiridas especificadas dos membros"
* $BRCID10#M21.7 "Desigualdade (adquirida) do comprimento dos membros"
* $BRCID10#M21.6 "Outras deformidades adquiridas do tornozelo e do pé"
* $BRCID10#M21.5 "Mão e pé em garra e mão e pé tortos adquiridos"
* $BRCID10#M21.4 "Pé chato [pé plano] (adquirido)"
* $BRCID10#M21.3 "Mão (pulso) ou pé pendente (adquirido)"
* $BRCID10#M21.2 "Deformidade em flexão"
* $BRCID10#M21.1 "Deformidade em varo não classificada em outra parte"
* $BRCID10#M21.0 "Deformidade em valgo não classificada em outra parte"
* $BRCID10#C80 "Neoplasia maligna, sem especificação de localização"
* $BRCID10#I64 "Acidente vascular cerebral, não especificado como hemorrágico ou isquêmico"
* $BRCID10#T66 "Efeitos não especificados de radiação"
* $BRCID10#M79.7 "Fibromialgia"
* $BRCID10#M79.0 "Reumatismo não especificado"
* $BRCID10#M72.9 "Transtorno fibroblástico não especificado"
* $BRCID10#M72.8 "Outros transtornos fibroblásticos"
* $BRCID10#M72.6 "Fasciíte necrosante"
* $BRCID10#M71.9 "Bursopatia não especificada"
* $BRCID10#M71.8 "Outras bursopatias especificadas"
* $BRCID10#M71.5 "Outras bursites não classificadas em outra parte"
* $BRCID10#Q89 "Outras malformações congênitas não classificadas em outra parte"
* $BRCID10#Q89.9 "Malformações congênitas não especificadas"
* $BRCID10#Q89.8 "Outras malformações congênitas especificadas"
* $BRCID10#Q89.7 "Malformações congênitas múltiplas, não classificadas em outra parte"
* $BRCID10#Q89.4 "Reunião de gêmeos"
* $BRCID10#Q89.3 "Situs inversus"
* $BRCID10#Q89.2 "Malformações congênitas de outras glândulas endócrinas"
* $BRCID10#Q89.1 "Malformações congênitas das supra-renais"
* $BRCID10#Q89.0 "Malformações congênitas do baço"
* SNOMED_CT#160245001