ValueSet: BRDose
Id: BRDose
Title: "BR Dose"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRDose#23 "Tratamento com treze doses"
* BRDose#60 "Profilaxia com 2 frascos-ampolas/ampolas"
* BRDose#22 "Tratamento com doze doses"
* BRDose#2 "2ª Dose"
* BRDose#57 "Dose Zero"
* BRDose#6 "1º Reforço"
* BRDose#20 "Tratamento com dez doses"
* BRDose#21 "Tratamento com onze doses"
* BRDose#59 "Profilaxia com 1 frasco-ampola/ampola"
* BRDose#19 "Tratamento com nove doses"
* BRDose#18 "Tratamento com oito doses"
* BRDose#17 "Tratamento com sete doses"
* BRDose#16 "Tratamento com seis doses"
* BRDose#52 "4ª Dose Dobrada"
* BRDose#15 "Tratamento com cinco doses"
* BRDose#51 "3ª Dose Dobrada"
* BRDose#14 "Tratamento com quatro doses"
* BRDose#49 "1ª Dose Dobrada"
* BRDose#12 "Tratamento com duas doses"
* BRDose#11 "Tratamento com uma dose"
* BRDose#48 "5ª Dose Fracionada"
* BRDose#10 "Revacinação"
* BRDose#47 "4ª Dose Fracionada"
* BRDose#1 "1ª Dose"
* BRDose#50 "2ª Dose Dobrada"
* BRDose#13 "Tratamento com três doses"
* BRDose#5 "5ª Dose"
* BRDose#35 "4ª Dose Revacinação"
* BRDose#71 "Profilaxia com 13 frascos-ampolas/ampolas"
* BRDose#34 "3ª Dose Revacinação"
* BRDose#70 "Profilaxia com 12 frascos-ampolas/ampolas"
* BRDose#7 "2º Reforço"
* BRDose#33 "2ª Dose Revacinação"
* BRDose#32 "1ª Dose Revacinação"
* BRDose#31 "Tratamento com vinte e quatro doses"
* BRDose#28 "Tratamento com dezoito doses"
* BRDose#68 "Profilaxia com 10 frascos-ampolas/ampolas"
* BRDose#69 "Profilaxia com 11 frascos-ampolas/ampolas"
* BRDose#66 "Profilaxia com 8 frascos-ampolas/ampolas"
* BRDose#3 "3ª Dose"
* BRDose#30 "Tratamento com vinte doses"
* BRDose#65 "Profilaxia com 7 frascos-ampolas/ampolas"
* BRDose#67 "Profilaxia com 9 frascos-ampolas/ampolas"
* BRDose#29 "Tratamento com dezenove doses"
* BRDose#64 "Profilaxia com 6 frascos-ampolas/ampolas"
* BRDose#27 "Tratamento com dezessete doses"
* BRDose#63 "Profilaxia com 5 frascos-ampolas/ampolas"
* BRDose#26 "Tratamento com dezesseis doses"
* BRDose#25 "Tratamento com quinze doses"
* BRDose#62 "Profilaxia com 4 frascos-ampolas/ampolas"
* BRDose#61 "Profilaxia com 3 frascos-ampolas/ampolas"
* BRDose#24 "Tratamento com quartorze doses"
* BRDose#75 "Profilaxia com 17 frascos-ampolas/ampolas"
* BRDose#38 "Reforço"
* BRDose#37 "Dose Adicional"
* BRDose#74 "Profilaxia com 16 frascos-ampolas/ampolas"
* BRDose#36 "Dose Inicial"
* BRDose#73 "Profilaxia com 15 frascos-ampolas/ampolas"
* BRDose#72 "Profilaxia com 14 frascos-ampolas/ampolas"
* BRDose#39 "3º Reforço"
* BRDose#76 "Profilaxia com 18 frascos-ampolas/ampolas"
* BRDose#4 "4ª Dose"
* BRDose#77 "Profilaxia com 19 frascos-ampolas/ampolas"
* BRDose#40 "4º Reforço"
* BRDose#78 "Profilaxia com 20 frascos-ampolas/ampolas"
* BRDose#41 "5º Reforço"
* BRDose#79 "Profilaxia com 21 frascos-ampolas/ampolas"
* BRDose#42 "6º Reforço"
* BRDose#8 "Dose"
* BRDose#43 "5ª Dose Revacinação"
* BRDose#80 "Profilaxia com 22 frascos-ampolas/ampolas"
* BRDose#44 "1ª Dose Fracionada"
* BRDose#81 "Profilaxia com 23 frascos-ampolas/ampolas"
* BRDose#45 "2ª Dose Fracionada"
* BRDose#82 "Profilaxia com 24 frascos-ampolas/ampolas"
* BRDose#46 "3ª Dose Fracionada"
* BRDose#9 "Única"
* BRDose#58 "Reforço Zero"
* BRDose#56 "4ª Dose Revacinação Dobrada"
* BRDose#55 "3ª Dose Revacinação Dobrada"
* BRDose#54 "2ª Dose Revacinação Dobrada"
* BRDose#53 "1ª Dose Revacinação Dobrada"