ValueSet: BRExameHPV
Id: BRExameHPV
Title: "BRExameHPV"
* ^version = "HEAD"
* ^status = #active
* ^publisher = "MS"
* $BRExameHPVCEPHEID#OUT "Outros HPV ( 31, 33, 35, 39, 51, 52, 56, 58, 59, 66 e 68)"
* $BRExameHPVCEPHEID#HPV1845 "Human papilloma virus 18+45 mRNA"
* $loinc#17399-7 "Human papilloma virus 16 Ag"
* $BRCID10#M54.9 "Dorsalgia não especificada"
* $BRCID10#M54.8 "Outra dorsalgia"
* $BRCID10#M54.6 "Dor na coluna torácica"
* $BRCID10#M54.5 "Dor lombar baixa"
* $BRCID10#M54.4 "Lumbago com ciática"
* $BRCID10#M54.3 "Ciática"
* $BRCID10#M54.2 "Cervicalgia"
* $BRCID10#M54.1 "Radiculopatia"
* $BRCID10#M54.0 "Paniculite atingindo regiões do pescoço e do dorso"
* $BRCID10#M54 "Dorsalgia"
* $BRCID10#M53.9 "Dorsopatia não especificada"
* $BRCID10#M53.8 "Outras dorsopatias especificadas"
* $BRCID10#M53.3 "Transtornos sacroccígeos não classificados em outra parte"
* $BRCID10#M53.2 "Instabilidades da coluna vertebral"
* $BRCID10#M53.1 "Síndrome cervicobraquial"
* $BRCID10#M53.0 "Síndrome cervicocraniana"
* $BRCID10#M53 "Outras dorsopatias não classificadas em outra parte"
* $BRCID10#M51.9 "Transtorno não especificado de disco intervertebral"
* $BRCID10#M51.8 "Outros transtornos especificados de discos intervertebrais"
* $BRCID10#M51.4 "Nódulos de Schmorl"
* $BRCID10#M51.3 "Outra degeneração especificada de disco intervertebral"
* $BRCID10#M51.2 "Outros deslocamentos discais intervertebrais especificados"
* $BRCID10#M51.1 "Transtornos de discos lombares e de outros discos intervertebrais com radiculopatia"
* $BRCID10#M51.0 "Transtornos de discos lombares e de outros discos intervertebrais com mielopatia"
* $BRCID10#M51 "Outros transtornos de discos intervertebrais"
* $BRCID10#M50.9 "Transtorno não especificado de disco cervical"
* $BRCID10#M50.8 "Outros transtornos de discos cervicais"
* $BRCID10#M50.3 "Outra degeneração de disco cervical"
* $BRCID10#M50.2 "Outro deslocamento de disco cervical"
* $BRCID10#M50.1 "Transtorno do disco cervical com radiculopatia"
* $BRCID10#M50.0 "Transtorno do disco cervical com mielopatia"
* $BRCID10#M50 "Transtornos dos discos cervicais"