ValueSet: BRImunobiologico
Id: BRImunobiologico
Title: "BR Imunobiologico"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRImunobiologico#107 "VPC20"
* BRImunobiologico#108 "VVSR-Rec"
* BRImunobiologico#111 "dTpa/VIP"
* BRImunobiologico#110 "Vacina Influenza Tetravalente - Alta Dosagem"
* BRImunobiologico#109 "VVSR-RecAdj"
* BRImunobiologico#106 "VPC15"
* BRImunobiologico#105 "COVID-19 MODERNA - SPIKEVAX BIVALENTE"
* BRImunobiologico#104 "DNG"
* BRImunobiologico#65 "ROTA5"
* BRImunobiologico#66 "MEN BC"
* BRImunobiologico#18 "VR"
* BRImunobiologico#19 "IGHV"
* BRImunobiologico#67 "HPV4"
* BRImunobiologico#64 "FLU ID"
* BRImunobiologico#17 "Hib"
* BRImunobiologico#63 "HAeHB"
* BRImunobiologico#16 "SACROT"
* BRImunobiologico#15 "BCG"
* BRImunobiologico#62 "HAeHBped"
* BRImunobiologico#61 "TT"
* BRImunobiologico#60 "HPV2"
* BRImunobiologico#11 "SABOCR"
* BRImunobiologico#12 "SABOLA"
* BRImunobiologico#58 "TETRA acelular"
* BRImunobiologico#6 "SAELAP"
* BRImunobiologico#103 "COVID-19 PFIZER - COMIRNATY BIVALENTE"
* BRImunobiologico#57 "dTpa"
* BRImunobiologico#102 "COVID-19 PFIZER - COMIRNATY PEDIÁTRICA MENOR DE 5 ANOS"
* BRImunobiologico#100 "VVBN"
* BRImunobiologico#55 "HepAinf"
* BRImunobiologico#1 "IGHT"
* BRImunobiologico#53 "DILSR"
* BRImunobiologico#54 "DILVAR"
* BRImunobiologico#10 "SAD"
* BRImunobiologico#2 "SAT"
* BRImunobiologico#20 "IGHHB"
* BRImunobiologico#21 "VPP23"
* BRImunobiologico#69 "SABOT"
* BRImunobiologico#22 "VIP"
* BRImunobiologico#7 "SAR"
* BRImunobiologico#23 "IGHR"
* BRImunobiologico#70 "Sarampo"
* BRImunobiologico#24 "SCR"
* BRImunobiologico#71 "Rubeola"
* BRImunobiologico#25 "dT"
* BRImunobiologico#72 "Gripe Sazonal"
* BRImunobiologico#26 "VPC10"
* BRImunobiologico#14 "VFA"
* BRImunobiologico#73 "Quadrupla Viral"
* BRImunobiologico#27 "SLATRO"
* BRImunobiologico#74 "MenACWY"
* BRImunobiologico#28 "VOP"
* BRImunobiologico#29 "PENTA acelular"
* BRImunobiologico#75 "COLERA"
* BRImunobiologico#30 "FTp"
* BRImunobiologico#101 "VZR"
* BRImunobiologico#59 "VPC13"
* BRImunobiologico#3 "SARC"
* BRImunobiologico#76 "VHZ"
* BRImunobiologico#13 "Meningo AC"
* BRImunobiologico#68 "HPV Bi"
* BRImunobiologico#56 "SCRV"
* BRImunobiologico#41 "MenC"
* BRImunobiologico#42 "PENTA"
* BRImunobiologico#87 "COVID-19 PFIZER - COMIRNATY"
* BRImunobiologico#86 "COVID-19 SINOVAC/BUTANTAN - CORONAVAC"
* BRImunobiologico#85 "COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD"
* BRImunobiologico#84 "VFA-F"
* BRImunobiologico#4 "SAESCOR"
* BRImunobiologico#79 "DILBCG"
* BRImunobiologico#83 "HEPAad"
* BRImunobiologico#77 "INF4"
* BRImunobiologico#39 "Tetra"
* BRImunobiologico#82 "Dengue"
* BRImunobiologico#37 "Vero"
* BRImunobiologico#38 "SBOTULTRI"
* BRImunobiologico#81 "DILMenC"
* BRImunobiologico#80 "DILVRvero"
* BRImunobiologico#36 "SR"
* BRImunobiologico#40 "Pncc7V"
* BRImunobiologico#35 "HA"
* BRImunobiologico#78 "MenB"
* BRImunobiologico#31 "SALOXO"
* BRImunobiologico#8 "SABOTR"
* BRImunobiologico#33 "INF3"
* BRImunobiologico#32 "SALONO"
* BRImunobiologico#88 "COVID-19 JANSSEN - Ad26.COV2.S"
* BRImunobiologico#43 "HEXA"
* BRImunobiologico#92 "VRvero"
* BRImunobiologico#44 "H1N1"
* BRImunobiologico#46 "DTP"
* BRImunobiologico#9 "HepB"
* BRImunobiologico#91 "DILVR"
* BRImunobiologico#45 "ROTA"
* BRImunobiologico#89 "COVID-19 ASTRAZENECA - ChAdOx1-S"
* BRImunobiologico#47 "DTPa"
* BRImunobiologico#48 "DILSRC"
* BRImunobiologico#90 "DILSCRV"
* BRImunobiologico#49 "DILVFA"
* BRImunobiologico#97 "COVID-19 MODERNA"
* BRImunobiologico#50 "DILHib"
* BRImunobiologico#93 "HPV9"
* BRImunobiologico#99 "COVID-19 PFIZER - COMIRNATY PEDIÁTRICA"
* BRImunobiologico#34 "VAR"
* BRImunobiologico#5 "DT"
* BRImunobiologico#52 "DilMengAC"
* BRImunobiologico#51 "Fta"
* BRImunobiologico#96 "COVID-19 BHARAT - COVAXIN"
* BRImunobiologico#94 "DILCOV"
* BRImunobiologico#95 "COVID-19 GAMALEYA - SPUTNIK V"
* BRImunobiologico#98 "COVID-19 SINOVAC - CORONAVAC"