ValueSet: BRInstalacoesFisicas
Id: BRInstalacoesFisicas
Title: "BR Instalacoes Fisicas"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRInstalacoesFisicas#22 "SALA DE REPOUSO/OBSERVACAO - INDIFERENCIADO"
* BRInstalacoesFisicas#21 "SALA REPOUSO/OBSERVACAO - PEDIATRICA"
* BRInstalacoesFisicas#43 "BRINQUEDOTECA"
* BRInstalacoesFisicas#20 "SALA REPOUSO/OBSERVACAO - MASCULINO"
* BRInstalacoesFisicas#42 "SALA DE ACOLHIMENTO COM CLASSIFICACAO DE RISCO"
* BRInstalacoesFisicas#19 "SALA REPOUSO/OBSERVACAO - FEMININO"
* BRInstalacoesFisicas#41 "SALA DE ATENDIMENTO A PACIENTE CRITICO/SALA DE ESTABILIZACAO"
* BRInstalacoesFisicas#18 "OUTROS CONSULTORIOS NAO MEDICOS"
* BRInstalacoesFisicas#40 "LEITOS DE ALOJAMENTO CONJUNTO"
* BRInstalacoesFisicas#17 "CLINICAS INDIFERENCIADO"
* BRInstalacoesFisicas#39 "LEITOS RN PATOLOGICO"
* BRInstalacoesFisicas#16 "CLINICAS ESPECIALIZADAS"
* BRInstalacoesFisicas#38 "LEITOS RN NORMAL"
* BRInstalacoesFisicas#15 "CLINICAS BASICAS"
* BRInstalacoesFisicas#37 "SALA DE CIRURGIA"
* BRInstalacoesFisicas#14 "CONSULTORIOS MEDICOS"
* BRInstalacoesFisicas#36 "SALA DE CURETAGEM"
* BRInstalacoesFisicas#13 "SALA PEQUENA CIRURGIA"
* BRInstalacoesFisicas#35 "SALA DE PARTO NORMAL"
* BRInstalacoesFisicas#12 "SALA DE CURATIVO"
* BRInstalacoesFisicas#34 "SALA DE PREPARTO"
* BRInstalacoesFisicas#11 "SALA DE GESSO"
* BRInstalacoesFisicas#33 "SALA DE CIRURGIA AMBULATORIAL"
* BRInstalacoesFisicas#10 "SALA DE HIGIENIZACAO"
* BRInstalacoesFisicas#32 "SALA DE RECUPERACAO"
* BRInstalacoesFisicas#09 "ODONTOLOGIA"
* BRInstalacoesFisicas#31 "SALA DE CIRURGIA"
* BRInstalacoesFisicas#08 "SALA REPOUSO/OBSERVACAO - INDIFERENCIADO"
* BRInstalacoesFisicas#30 "SALA DE CIRURGIA AMBULATORIAL"
* BRInstalacoesFisicas#07 "SALA REPOUSO/OBSERVACAO - MASCULINO"
* BRInstalacoesFisicas#29 "SALA DE CURATIVO"
* BRInstalacoesFisicas#06 "SALA REPOUSO/OBSERVACAO - FEMININO"
* BRInstalacoesFisicas#28 "SALA DE GESSO"
* BRInstalacoesFisicas#05 "SALA REPOUSO/OBSERVACAO - PEDIATRICA"
* BRInstalacoesFisicas#27 "SALA DE NEBULIZACAO"
* BRInstalacoesFisicas#04 "SALA DE ATENDIMENTO INDIFERENCIADO"
* BRInstalacoesFisicas#26 "SALA DE IMUNIZACAO"
* BRInstalacoesFisicas#03 "SALA DE ATENDIMENTO MASCULINO"
* BRInstalacoesFisicas#25 "SALA DE ENFERMAGEM - SERVICOS"
* BRInstalacoesFisicas#02 "SALA DE ATENDIMENTO FEMININO"
* BRInstalacoesFisicas#24 "SALA DE PEQUENA CIRURGIA"
* BRInstalacoesFisicas#23 "ODONTOLOGIA"
* BRInstalacoesFisicas#01 "SALA DE ATENDIMENTO PEDIATRICO"