ValueSet: BRMunicipio
Id: BRMunicipio
Title: "BR Municipio"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRDivisaoGeograficaBrasil#28 "Sergipe"
* BRDivisaoGeograficaBrasil#27 "Alagoas"
* BRDivisaoGeograficaBrasil#53 "Distrito Federal"
* BRDivisaoGeograficaBrasil#26 "Pernambuco"
* BRDivisaoGeograficaBrasil#52 "Goiás"
* BRDivisaoGeograficaBrasil#25 "Paraíba"
* BRDivisaoGeograficaBrasil#51 "Mato Grosso"
* BRDivisaoGeograficaBrasil#24 "Rio Grande do Norte"
* BRDivisaoGeograficaBrasil#50 "Mato Grosso do Sul"
* BRDivisaoGeograficaBrasil#23 "Ceará"
* BRDivisaoGeograficaBrasil#5 "Centro-Oeste"
* BRDivisaoGeograficaBrasil#22 "Piauí"
* BRDivisaoGeograficaBrasil#43 "Rio Grande do Sul"
* BRDivisaoGeograficaBrasil#21 "Maranhão"
* BRDivisaoGeograficaBrasil#42 "Santa Catarina"
* BRDivisaoGeograficaBrasil#2 "Nordeste"
* BRDivisaoGeograficaBrasil#41 "Paraná"
* BRDivisaoGeograficaBrasil#17 "Tocantins"
* BRDivisaoGeograficaBrasil#4 "Sul"
* BRDivisaoGeograficaBrasil#16 "Amapá"
* BRDivisaoGeograficaBrasil#34 "São Paulo"
* BRDivisaoGeograficaBrasil#15 "Pará"
* BRDivisaoGeograficaBrasil#33 "Rio de Janeiro"
* BRDivisaoGeograficaBrasil#14 "Roraima"
* BRDivisaoGeograficaBrasil#32 "Espírito Santo"
* BRDivisaoGeograficaBrasil#13 "Amazonas"
* BRDivisaoGeograficaBrasil#315780 "Santa Luzia"
* BRDivisaoGeograficaBrasil#12 "Acre"
* BRDivisaoGeograficaBrasil#31 "Minas Gerais"
* BRDivisaoGeograficaBrasil#11 "Rondônia"
* BRDivisaoGeograficaBrasil#3 "Sudeste"
* BRDivisaoGeograficaBrasil#1 "Norte"
* BRDivisaoGeograficaBrasil#29 "Bahia"