ValueSet: BRNomeExameLOINC
Id: BRNomeExameLOINC
Title: "BRNomeExameLOINC"
* ^version = "HEAD"
* ^status = #active
* ^publisher = "MS"
* $BRNomeExameLOINC#95689-6 "Vírus Mayaro Anticorpos IgM [Presença] na amostra por imunoensaio"
* $BRNomeExameLOINC#38166-5 "Vírus do Nilo Ocidental Anticorpos IgM [unidades/volume] no soro por imunoensaio"
* $BRNomeExameLOINC#39573-1 "Vírus do Nilo Ocidental Anticorpos IgM [unidades/volume] em líquido cerebroespinhal por imunoensaio"
* $BRNomeExameLOINC#33331-0 "Vírus do Nilo Ocidental Anticorpos IgM [Título] no soro"
* $BRNomeExameLOINC#29567-5 "Vírus do Nilo Ocidental Anticorpos IgM [presença] no soro por imunoensaio"
* $BRNomeExameLOINC#95707-6 "Vírus Mayaro IgA Ac [Presença] na amostra por imunoensaio"
* $BRNomeExameLOINC#31703-2 "Vírus do Nilo Ocidental Igm Ac [presença] no fluido espinhal cerebral"
* $BRNomeExameLOINC#95674-8 "Anticorpos IgG contra vírus Mayaro [Presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#29778-8 "Vírus do Nilo Ocidental IgM Ac [Presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#81650-4 "Vírus do Nilo Ocidental Kunjin Strain RNA [presença] em amostra por NaA com detecção de sonda"
* $BRNomeExameLOINC#74857-4 "RNA do vírus do Nilo Ocidental [presença] no soro ou plasma do doador pela NAA com detecção de sonda"
* $BRNomeExameLOINC#34461-4 "RNA do vírus do Nilo Ocidental [presença] no líquido espinhal cerebral por NaA com detecção de sonda"
* $BRNomeExameLOINC#87395-0 "RNA do vírus do Nilo Ocidental [limiar de ciclo #] em amostras por NaA com detecção de sonda"
* $BRNomeExameLOINC#41212-2 "RNA do vírus do Nilo Ocidental [presença] no soro do doador pela NAA com detecção de sonda"
* $BRNomeExameLOINC#29569-1 "Vírus do Nilo Ocidental Anticorpos IgM [Presença] no líquido cerebroespinhal por imunoensaio"
* $BRNomeExameLOINC#103721-7 "RNA do vírus do Nilo Ocidental [presença] no sangue por NAA com detecção sem probe"
* $BRNomeExameLOINC#34460-6 "RNA do vírus do Nilo Ocidental [presença] no sangue por NaA com detecção de sonda"
* $BRNomeExameLOINC#97185-3 "RNA do vírus do Nilo Ocidental [presença] na urina por NaA com detecção de sonda"
* $BRNomeExameLOINC#32370-9 "RNA do vírus do Nilo Ocidental [presença] em tecido por NAA com detecção de sonda"
* $BRNomeExameLOINC#32361-8 "RNA do vírus do Nilo Ocidental [presença] no soro por NaA com detecção de sonda"
* $BRNomeExameLOINC#29570-9 "Anticorpo neutralizante do vírus do Nilo Ocidental [Título] no líquido espinhal cerebral por teste de neutralização"
* $BRNomeExameLOINC#38997-3 "Vírus do Nilo Ocidental Anticorpos IgG [unidades/volume] no soro por imunoensaio"
* $BRNomeExameLOINC#29537-8 "Vírus do Nilo Ocidental IgG Ac [unidades/volume] em líquido espinhal cerebral"
* $BRNomeExameLOINC#43342-5 "Vírus do Nilo Ocidental Igm Ac [Título] em líquido espinhal cerebral por imunoensaio"
* $BRNomeExameLOINC#39572-3 "Vírus do Nilo Ocidental Anticorpos IgG [unidades/volume] em líquido cerebroespinhal por imunoensaio"
* $BRNomeExameLOINC#33329-4 "Vírus do Nilo Ocidental Anticorpos IgG [Título] no soro"
* $BRNomeExameLOINC#94289-6 "Vírus do Nilo Ocidental IgG Ac [Título] no soro"
* $BRNomeExameLOINC#33328-6 "Vírus do Nilo Ocidental Anticorpos IgG [Título] no líquido cerebroespinhal"
* $BRNomeExameLOINC#41642-0 "Vírus do Nilo Ocidental Igm Ac [presença] em amostra por imunofluorescência"
* $BRNomeExameLOINC#41236-1 "Vírus do Nilo Ocidental IgG Ac [presença] no fluido espinhal cerebral"
* $BRNomeExameLOINC#62436-1 "Vírus do Nilo Ocidental Igm Ac [presença] no líquido corporal por imunoensaio"
* $BRNomeExameLOINC#60029-6 "Vírus do Nilo Ocidental IgG Ac Avidez [presença] no soro por imunofluorescência"
* $BRNomeExameLOINC#29566-7 "Vírus do Nilo Ocidental Anticorpos IgG [presença] no soro por imunoensaio"
* $BRNomeExameLOINC#41196-7 "Vírus do Nilo Ocidental IgG Ac [Título] no fluido corporal"
* $BRNomeExameLOINC#36898-5 "Vírus do Nilo Ocidental NS5 Ac [presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#41643-8 "Vírus do Nilo Ocidental AG [presença] em amostra por imunofluorescência"
* $BRNomeExameLOINC#50015-7 "Vírus do Nilo Ocidental AG [presença] em sangue ou medula de doador"
* $BRNomeExameLOINC#41206-4 "Vírus do Nilo Ocidental Ac [unidades/volume] em líquido espinhal cerebral"
* $BRNomeExameLOINC#94602-0 "Vírus do Nilo Ocidental IgM AB/Controle positivo no soro por imunoensaio"
* $BRNomeExameLOINC#33330-2 "Vírus do Nilo Ocidental Anticorpos IgM [Título] em líquido cerebroespinhal"
* $BRNomeExameLOINC#41195-9 "Vírus do Nilo Ocidental Igm Ac [Título] no fluido corporal"
* $BRNomeExameLOINC#97917-9 "RNA do vírus Oropouche [Presença] em espécime por AAN com detecção por sonda"
* $BRNomeExameLOINC#30178-8 "Vírus do Nilo Ocidental IgG Ac [presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#60030-4 "Vírus do Nilo Ocidental IgG Ac [presença] no soro por imunofluorescência"
* $BRNomeExameLOINC#95703-5 "Vírus do Nilo Ocidental IGA Ac [presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#81096-0 "Vírus do Nilo Ocidental Kunjin Strain igm Ac [presença] no soro"
* $BRNomeExameLOINC#43343-3 "Vírus do Nilo Ocidental Igm Ac [Título] no soro por imunoensaio"
* $BRNomeExameLOINC#29780-4 "Vírus do Nilo Ocidental Igm Ac [Presença] em amostra"
* $BRNomeExameLOINC#97931-0 "RNA do vírus Mayaro [Presença] em espécime por AAN com detecção por sonda"
* $BRNomeExameLOINC#37985-9 "RNA do vírus do Nilo Ocidental [presença] em amostra por sonda"
* $BRNomeExameLOINC#29538-6 "Vírus do Nilo Ocidental Igm Ac [unidades/volume] em líquido espinhal cerebral"
* $BRNomeExameLOINC#60028-8 "Vírus do Nilo Ocidental IgG Ac Avidez [Presença] no soro por imunoensaio"
* $BRNomeExameLOINC#94854-7 "Painel de IgG e IgM do vírus do Nilo Ocidental - qualitativo sérico"
* $BRNomeExameLOINC#77953-8 "Vírus do Nilo Ocidental Anticorpos IgG [Presença] no líquido cerebroespinhal por imunoensaio"
* $BRNomeExameLOINC#94853-9 "Painel de IgG e IgM do Vírus do Nilo Ocidental - qualitativa de líquido espinhal cerebral"
* $BRNomeExameLOINC#96531-9 "Anticorpos IgM contra vírus Oropouche [Presença] em espécime por imunoensaio"
* $BRNomeExameLOINC#41224-7 "Vírus do Nilo Ocidental Ac [Título] no líquido espinhal cerebral"
* $BRNomeExameLOINC#96506-1 "Anticorpos IgG contra vírus Oropouche [Presença] em espécime por imunoensaio"
* $BRNomeExameLOINC#99120-8 "Anticorpos neutralizantes contra vírus Oropouche [Título] em amostra por teste de neutralização"
* $BRNomeExameLOINC#95650-8 "Anticorpos neutralizantes contra vírus Mayaro [Título] em amostra por teste de neutralização"
* $BRNomeExameLOINC#36897-7 "Vírus do Nilo Ocidental Ac [presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#55402-2 "Painel IgG e IgM do vírus do Nilo Ocidental - soro"
* $BRNomeExameLOINC#39558-2 "Vírus do Nilo Ocidental Ac [presença] no fluido espinhal cerebral"
* $BRNomeExameLOINC#36901-7 "Vírus do Nilo Ocidental NS5 Ac [Presença] em amostras"
* $BRNomeExameLOINC#32371-7 "Vírus do Nilo Ocidental AG [presença] em tecido por mancha imunológica"
* $BRNomeExameLOINC#41211-4 "Vírus do Nilo Ocidental IgG+IgM Ac [Presença] no soro"
* $BRNomeExameLOINC#31702-4 "Vírus do Nilo Ocidental IgG Ac [presença] em amostra"
* $BRNomeExameLOINC#55380-0 "Vírus do Nilo Ocidental Ac [Título] em soro por inibição da hemaglutinação"
* $BRNomeExameLOINC#29781-2 "Vírus do Nilo Ocidental Ac [Título] na amostra"
* $BRNomeExameLOINC#34892-0 "RNA do vírus do Nilo Ocidental [presença] em amostra por AAN com detecção por sonda"
* $BRNomeExameLOINC#41194-2 "Vírus do Nilo Ocidental Ac [unidades/volume] em soro por imunoensaio"
* $BRNomeExameLOINC#36896-9 "Vírus do Nilo Ocidental polivalente E Ac [presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#29779-6 "Anticorpo neutralizante do vírus do Nilo Ocidental [Título] em amostra por teste de neutralização"
* $BRNomeExameLOINC#81097-8 "Vírus do Nilo Ocidental Kunjin Strain Ac [presença] no soro"
* $BRNomeExameLOINC#29568-3 "Anticorpos neutralizantes contra vírus do Nilo Ocidental [Título] no soro por teste de neutralização"
* $BRNomeExameLOINC#33468-0 "Vírus do Nilo Ocidental Ac [presença] em amostra"
* $BRNomeExameLOINC#31700-8 "Vírus do Nilo Ocidental Ac [unidades/volume] em amostra"
* $BRNomeExameLOINC#75404-4 "Vírus do Nilo Ocidental Ac [presença] no soro por inibição da hemaglutinação"
* $BRNomeExameLOINC#29535-2 "Vírus do Nilo Ocidental IgG Ac [unidades/volume] no soro"
* $BRNomeExameLOINC#29536-0 "Vírus do Nilo Ocidental IgM Ac [unidades/volume] no soro"
* $BRNomeExameLOINC#31704-0 "Vírus do Nilo Ocidental Igm Ac [presença] no soro"
* $BRNomeExameLOINC#31701-6 "Vírus do Nilo Ocidental IgG Ac [presença] no soro"
* $BRNomeExameLOINC#39555-8 "Vírus do Nilo Ocidental Ac [unidades/volume] no soro"
* $BRNomeExameLOINC#41225-4 "Vírus do Nilo Ocidental Ac [Título] no soro"
* $BRNomeExameLOINC#36900-9 "Vírus do Nilo Ocidental polivalente E Ac [presença] em amostra"
* $BRNomeExameLOINC#86190-6 "RNA do vírus Zika [Presença] no Plasma do Doador por NAA com detecção por sonda"
* $BRNomeExameLOINC#89368-5 "Painel IgM de proteína não estrutural 1 contra o vírus Zika - Soro ou Plasma por imunoensaio"
* $BRNomeExameLOINC#89369-3 "Anticorpo IgM Proteína não estrutural 1 contra o vírus Zika [Unidades/volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#89370-1 "Proteína não estrutural 1 IgM Anticorpo contra o vírus Zika [Interpretação] em soro por imunoensaio"
* $BRNomeExameLOINC#83069-5 "Proteína não estrutural 1 IgG Anticorpo contra o vírus Zika [Unidades/volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#86321-7 "Anticorpo neutralizante contra o vírus Zika [Título] em espécime por teste de neutralização"
* $BRNomeExameLOINC#80623-2 "Anticorpo neutralizante contra o vírus Zika [Título] em soro por teste de neutralização --2ª amostra"
* $BRNomeExameLOINC#80622-4 "Anticorpo neutralizante contra o vírus Zika [Título] em soro por teste de neutralização --1ª amostra"
* $BRNomeExameLOINC#80620-8 "Anticorpo neutralizante contra o vírus Zika [Título] no soro por teste de neutralização"
* $BRNomeExameLOINC#80625-7 "Anticorpo neutralizante contra o vírus Zika [Título] no líquido cefalorraquidiano por teste de neutralização --2ª amostra"
* $BRNomeExameLOINC#80624-0 "Anticorpo neutralizante contra o vírus Zika [Título] no líquido cefalorraquidiano por teste de neutralização --1ª amostra"
* $BRNomeExameLOINC#80621-6 "Anticorpo neutralizante contra o vírus Zika [Título] no líquido cefalorraquidiano por teste de neutralização"
* $BRNomeExameLOINC#86320-9 "Anticorpo neutralizante contra o vírus Zika [Presença] em espécime por teste de neutralização"
* $BRNomeExameLOINC#80822-0 "Anticorpo neutralizante contra o vírus Zika [Presença] no soro por teste de neutralização"
* $BRNomeExameLOINC#80821-2 "Anticorpo neutralizante contra o vírus Zika [Presença] no fluido espinhal cerebral por teste de neutralização"
* $BRNomeExameLOINC#103963-5 "LinhAntígeno em contra o vírus Zika [Identificador] em espécime pelo método de genética molecular"
* $BRNomeExameLOINC#87622-7 "Anticorpo contra o vírus da Dengue[Presença] em espécime por imunoensaio"
* $BRNomeExameLOINC#82731-1 "Anticorpo IgM contra o vírus Zika [Presença] no Soro por Imunofluorescência"
* $BRNomeExameLOINC#104476-7 "Anticorpo IgG contra o vírus Zika [Título] em soro por imunoensaio – 2ª amostra"
* $BRNomeExameLOINC#104475-9 "Anticorpo IgG contra o vírus Zika [Título] em soro por imunoensaio – 1ª amostra"
* $BRNomeExameLOINC#87439-6 "Anticorpo contra o vírus Zika IgA+IgG+IgM [Interpretação] em espécime qualitativo por imunoensaio"
* $BRNomeExameLOINC#81148-9 "Gene E do envelope contra o vírus Zika [Presença] na urina por NAA com detecção por sonda"
* $BRNomeExameLOINC#81149-7 "Gene E do envelope contra o vírus Zika [Presença] no líquido amniótico por NAA com detecção por sonda"
* $BRNomeExameLOINC#80825-3 "Gene E do envelope contra o vírus Zika [Presença] no soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#80826-1 "Gene E do envelope contra o vírus Zika [Presença] no fluido espinhal cerebral por NAA com detecção por sonda"
* $BRNomeExameLOINC#103722-5 "RNA do vírus da Febre Amarela [Presença] no sangue por NAA com detecção sem sonda"
* $BRNomeExameLOINC#77959-5 "Gene ns5 contra o vírus da Febre Amarela [Presença] no fluido espinhal cerebral por NAA com detecção sem sonda"
* $BRNomeExameLOINC#6591-2 "Anticorpo neutralizante contra o vírus da Febre Amarela [Unidades/volume] em soro por teste de neutralização"
* $BRNomeExameLOINC#95651-6 "Anticorpo neutralizante contra o vírus da Febre Amarela [Título] em amostra por teste de neutralização"
* $BRNomeExameLOINC#71783-5 "Anticorpo neutralizante contra o vírus da Febre Amarela [Título] no líquido cefalorraquidiano por teste de neutralização"
* $BRNomeExameLOINC#8056-4 "Anticorpo IgM contra o vírus da Febre Amarela [Unidades/volume] em soro"
* $BRNomeExameLOINC#41216-3 "Anticorpo IgM vírus da Febre Amarela [Presença] no Soro"
* $BRNomeExameLOINC#8055-6 "Anticorpo IgG contra o vírus da Febre Amarela [Unidades/volume] no soro"
* $BRNomeExameLOINC#104463-5 "Anticorpo IgG contra o vírus da Febre Amarela [Título] em soro por imunoensaio - 2ª amostra"
* $BRNomeExameLOINC#104461-9 "Anticorpo IgG contra o vírus da Febre Amarela [Título] em soro por imunoensaio"
* $BRNomeExameLOINC#41217-1 "Anticorpo IgG vírus da Febre Amarela [Presença] no Soro"
* $BRNomeExameLOINC#95708-4 "Anticorpo IgA contra o vírus da Febre Amarela [Presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#8054-9 "Anticorpo contra o vírus da Febre Amarela [Unidades/volume] em soro"
* $BRNomeExameLOINC#6589-6 "Anticorpo contra o vírus da Febre Amarela [Título] em soro por imunofluorescência"
* $BRNomeExameLOINC#41246-0 "Anticorpo contra o vírus da Febre Amarela [Título] em soro - 2ª amostra"
* $BRNomeExameLOINC#41247-8 "Anticorpo contra o vírus da Febre Amarela [Título] em soro - 1ª amostra"
* $BRNomeExameLOINC#41249-4 "Anticorpo contra o vírus da Febre Amarela [Presença] no soro"
* $BRNomeExameLOINC#22618-3 "Anticorpo contra o vírus da Febre Amarela [Título] em soro"
* $BRNomeExameLOINC#80206-6 "Encefalite japonesa+encefalite transmitida por carrapatos+Nilo Ocidental+Vírus da febre amarela IgM Ac [presença] no soro por imunofluorescência"
* $BRNomeExameLOINC#80205-8 "Encefalite japonesa+encefalite transmitida por carrapatos+Nilo Ocidental+Vírus da Febre Amarela IgG [presença] no soro ou plasma por imunofluorescência"
* $BRNomeExameLOINC#85584-1 "RNA do vírus da Dengue [presença] no plasma do doador pela NAA com detecção por sonda"
* $BRNomeExameLOINC#82383-1 "RNA do vírus da Dengue 2+4 [Presença] no soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#99111-7 "Anticorpo neutralizante contra o vírus da Dengue [Título] em espécime por teste de neutralização"
* $BRNomeExameLOINC#50036-3 "Anticorpo neutralizante contra o vírus da Dengue [Presença] em espécime por teste de neutralização"
* $BRNomeExameLOINC#82384-9 "RNA do vírus da Dengue 1+3 [Presença] no soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#23968-1 "Anticorpo IgM contra o vírus da Dengue [unidades/volume] no soro"
* $BRNomeExameLOINC#104387-6 "Anticorpo IgM contra o vírus da Dengue [Título] em soro por imunoensaio --2ª amostra"
* $BRNomeExameLOINC#104386-8 "Anticorpo IgM contra o vírus da Dengue [Título] em soro por imunoensaio --1ª amostra"
* $BRNomeExameLOINC#6812-2 "Anticorpo IgM contra o vírus da Dengue [Título] no soro"
* $BRNomeExameLOINC#25392-2 "Anticorpo IgM contra o vírus da Dengue [Presença] no soro por imunoblot"
* $BRNomeExameLOINC#25338-5 "Anticorpo IgM contra o vírus da Dengue [Presença] no soro"
* $BRNomeExameLOINC#101304-4 "RNA do vírus da Dengue 1+2+3+4 [Presença] no sangue por NAA com detecção sem sonda"
* $BRNomeExameLOINC#87546-8 "Painel IgG e IgM contra o vírus da Dengue - Soro Qualitativo"
* $BRNomeExameLOINC#51785-4 "Anticorpo IgG e IgM contra o vírus da Dengue [Interpretação] em soro"
* $BRNomeExameLOINC#23958-2 "Anticorpo IgG contra o vírus da Dengue [unidades/volume] no soro"
* $BRNomeExameLOINC#104384-3 "Anticorpo IgG contra o vírus da Dengue [Título] em soro por imunoensaio -- 2ª amostra"
* $BRNomeExameLOINC#104383-5 "Anticorpo IgG contra o vírus da Dengue [Título] em soro por imunoensaio --1ª amostra"
* $BRNomeExameLOINC#6811-4 "Anticorpo IgG contra o vírus da Dengue [Título] no soro"
* $BRNomeExameLOINC#88203-5 "RNA do vírus da Dengue 1 e 2 e 3 e 4 [Identificador] em soro ou sangue por NAA com detecção por sonda"
* $BRNomeExameLOINC#29676-4 "Anticorpo IgG contra o vírus da Dengue [Presença] no soro"
* $BRNomeExameLOINC#100965-3 "Anticorpo IgG contra o vírus da Dengue [interpretação] em soro, plasma ou sangue"
* $BRNomeExameLOINC#95706-8 "Anticorpo IgA contra o vírus da Dengue [Presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#6387-5 "DNA do vírus da Dengue [Presença] em espécime por sonda"
* $BRNomeExameLOINC#6386-7 "DNA do vírus da Dengue [presença] no soro por sonda"
* $BRNomeExameLOINC#31799-0 "Antígeno  contra o vírus da Dengue [Presença] em Amostra"
* $BRNomeExameLOINC#6385-9 "Dengue vírus Antígeno  [Presença] em espécime por imunofluorescência"
* $BRNomeExameLOINC#6384-2 "Dengue vírus Antígeno  [Presença] em Soro por Imunofluorescência"
* $BRNomeExameLOINC#31798-2 "Antígeno  contra o vírus da Dengue [presença] no soro"
* $BRNomeExameLOINC#100962-0 "Anticorpo IgG painel contra o vírus da Dengue - Soro, Plasma ou Sangue"
* $BRNomeExameLOINC#31342-9 "Anticorpo contra o vírus da Dengue [Unidades/volume] em espécime"
* $BRNomeExameLOINC#7859-2 "Anticorpo contra o vírus da Dengue [unidades/volume] no soro"
* $BRNomeExameLOINC#40515-9 "Anticorpo contra o vírus da Dengue [Título] no soro por fixação do complemento"
* $BRNomeExameLOINC#33606-5 "Anticorpo contra o vírus da Dengue [Título] em soro"
* $BRNomeExameLOINC#31343-7 "Anticorpo contra o vírus da Dengue [Presença] em espécime"
* $BRNomeExameLOINC#16740-3 "Anticorpo contra o vírus da Dengue [Presença] no soro"
* $BRNomeExameLOINC#40748-6 "Anticorpo contra o vírus da Dengue [Presença] no soro por inibição da Hemaglutinação"
* $BRNomeExameLOINC#82519-0 "Painel de vírus da Dengue 1+3 e 2+4 - Soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#86861-2 "Anticorpo neutralizante contra o vírus da Dengue 4 [Título] em amostra por teste de neutralização"
* $BRNomeExameLOINC#31341-1 "Anticorpo contra o vírus da Dengue 4 [Unidades/volume] em soro"
* $BRNomeExameLOINC#16739-5 "Anticorpo contra o vírus da Dengue 4 [Título] em soro"
* $BRNomeExameLOINC#7858-4 "Anticorpo contra o vírus da Dengue 4 [Presença] no soro por imunoensaio"
* $BRNomeExameLOINC#22253-9 "Anticorpo contra o vírus da Dengue 4 [Presença] no soro"
* $BRNomeExameLOINC#86862-0 "Anticorpo neutralizante contra o vírus da Dengue 4 [Presença] em amostra por teste de neutralização"
* $BRNomeExameLOINC#86859-6 "Anticorpo neutralizante contra o vírus da Dengue 3 [Título] em amostra por teste de neutralização"
* $BRNomeExameLOINC#86863-8 "Anticorpo neutralizante contra o vírus da Dengue 3 [Presença] em amostra por teste de neutralização"
* $BRNomeExameLOINC#31340-3 "Anticorpo contra o vírus da Dengue 3 [Unidades/volume] em soro"
* $BRNomeExameLOINC#16738-7 "Anticorpo contra o vírus da Dengue 3 [Título] em soro"
* $BRNomeExameLOINC#7857-6 "Anticorpo contra o vírus da Dengue 3 [Presença] no soro por imunoensaio"
* $BRNomeExameLOINC#22252-1 "Anticorpo contra o vírus da Dengue 3 [Presença] no soro"
* $BRNomeExameLOINC#86858-8 "Anticorpo neutralizante contra o vírus da Dengue 2 [Título] em amostra por teste de neutralização"
* $BRNomeExameLOINC#86864-6 "Anticorpo neutralizante contra o vírus da Dengue 2 [Presença] em amostra por teste de neutralização"
* $BRNomeExameLOINC#86860-4 "Anticorpo neutralizante contra o vírus da Dengue 1 [Título] em amostra por teste de neutralização"
* $BRNomeExameLOINC#86865-3 "Anticorpo neutralizante contra o vírus da Dengue 1 [Presença] em amostra por teste de neutralização"
* $BRNomeExameLOINC#31339-5 "Anticorpo contra o vírus da Dengue 2 [Unidades/volume] em soro"
* $BRNomeExameLOINC#16737-9 "Anticorpo contra o vírus da Dengue 2 [Título] em soro"
* $BRNomeExameLOINC#7856-8 "Anticorpo contra o vírus da Dengue 2 [Presença] no soro por imunoensaio"
* $BRNomeExameLOINC#22251-3 "Anticorpo contra o vírus da Dengue 2 [Presença] no soro"
* $BRNomeExameLOINC#55438-6 "Anticorpo neutralizante contra o vírus da Dengue [Título] em soro por teste de neutralização"
* $BRNomeExameLOINC#100963-8 "Anticorpo IgG nsP1 contra o vírus da Dengue 1+2+3+4 nsP1 [Unidades/volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#100846-5 "Anticorpo IgG nsP1 contra o vírus da Dengue 1+2+3+4 [Presença] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#95688-8 "Anticorpo IgM contra o vírus da Dengue 1+2+3+4 [Presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#95673-0 "Anticorpo IgG contra o vírus da Dengue 1+2+3+4 [Presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#87440-4 "Anticorpo IgA+IgG+IgM vírus da Dengue 1+2+3+4 [Interpretação] em espécime qualitativo por imunoensaio"
* $BRNomeExameLOINC#87441-2 "Painel IgA+IgG+IgM contra o vírus da Dengue 1+2+3+4 e contra o vírus Zika - Amostra por imunoensaio"
* $BRNomeExameLOINC#87438-8 "Anticorpo IIgA+IgG+IgM  contra o vírus da Dengue 1+2+3+4 e vírus Zika [Interpretação] em espécime por imunoensaio"
* $BRNomeExameLOINC#81151-3 "5' UTR RNA vírus da Dengue 1+2+3+4 [Presença] no fluido espinhal cerebral por NAA com detecção por sonda"
* $BRNomeExameLOINC#81150-5 "5' UTR RNA vírus da Dengue 1+2+3+4 [Presença] no soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#94426-4 "3' UTR RNA do vírus da Dengue 1+2+3+4 [Presença] no fluido espinhal cerebral por NAA com detecção por sonda"
* $BRNomeExameLOINC#94427-2 "3' UTR RNA do vírus da Dengue 1+2+3+4 [Presença] no soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#31338-7 "Anticorpo contra o vírus da Dengue 1 [Unidades/volume] em soro"
* $BRNomeExameLOINC#16736-1 "Anticorpo contra o vírus da Dengue 1 [Título] em soro"
* $BRNomeExameLOINC#7854-3 "Anticorpo contra o vírus da Dengue 1 [Presença] no soro por imunoensaio"
* $BRNomeExameLOINC#22250-5 "Anticorpo contra o vírus da Dengue 1 [Presença] no soro"
* $BRNomeExameLOINC#83067-9 "Anticorpo IgM Proteínas estruturais do vírus Chikungunya (E1+E2) [Unidades/volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#83068-7 "Anticorpo IgG Proteínas estruturais do vírus Chikungunya (E1+E2) [Unidades/volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#82297-3 "Anticorpo IgG Proteínas estruturais do vírus Chikungunya (E1+E2) [Presença] no soro por imunoensaio"
* $BRNomeExameLOINC#85582-5 "RNA do vírus Chikungunya + RNA do vírus Dengue [Presença] no Plasma do Doador por NAA com detecção por sonda"
* $BRNomeExameLOINC#85583-3 "RNA do vírus Chikungunya [Presença] no Plasma do Doador por NAA com detecção por sonda"
* $BRNomeExameLOINC#101303-6 "RNA do vírus Chikungunya [Presença] no Sangue por NAA com detecção sem sonda"
* $BRNomeExameLOINC#81152-1 "RNA da proteína não estrutural 1 contra o vírus Chikungunya (nsP1) [Presença] no soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#81153-9 "RNA da proteína não estrutural 1 contra o vírus Chikungunya (nsP1) [Presença] no líquido cefalorraquidiano por NAA com detecção por sonda"
* $BRNomeExameLOINC#95649-0 "Anticorpo neutralizante contra o vírus Chikungunya [Título] em amostra por teste de neutralização"
* $BRNomeExameLOINC#95687-0 "Anticorpo IgM contra o vírus Chikungunya [Presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#56131-6 "Anticorpo IgM contra o vírus Chikungunya [Presença] em Soro ou Plasma por Imunofluorescência"
* $BRNomeExameLOINC#57934-2 "Anticorpo IgM contra o vírus Chikungunya [Presença] no Soro ou Plasma"
* $BRNomeExameLOINC#104364-5 "Anticorpo IgG contra o vírus Chikungunya [Título] em soro por imunoensaio --1ª amostra"
* $BRNomeExameLOINC#95672-2 "Anticorpo IgG contra o vírus Chikungunya [Presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#56129-0 "Anticorpo IgG contra o vírus Chikungunya [Presença] em Soro ou Plasma por Imunofluorescência"
* $BRNomeExameLOINC#93979-3 "Anticorpo IgG contra o vírus Chikungunya [Presença] no Soro ou Plasma"
* $BRNomeExameLOINC#95705-0 "Anticorpo IgA contra o vírus Chikungunya [Presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#43064-5 "Anticorpo contra o vírus Chikungunya [Título] em Soro"
* $BRNomeExameLOINC#74821-0 "Anticorpo contra o vírus Chikungunya [Presença] no Soro por Inibição da Hemaglutinação"
* $BRNomeExameLOINC#26623-9 "Anticorpo contra o vírus Chikungunya [Presença] no Soro"
* $BRNomeExameLOINC#85623-7 "RNA do vírus Zika [Presença] na urina por NAA com detecção por sonda"
* $BRNomeExameLOINC#79190-5 "RNA do vírus Zika [Presença] em espécime por NAA com detecção por sonda"
* $BRNomeExameLOINC#91079-4 "RNA do vírus Zika [Presença] na placenta por NAA com detecção por sonda"
* $BRNomeExameLOINC#85622-9 "RNA do vírus Zika [Presença] no Soro ou Plasma por NAA com detecção por sonda"
* $BRNomeExameLOINC#90462-3 "RNA do vírus Zika [Presença] no sangue do cordão umbilical por NAA com detecção por sonda"
* $BRNomeExameLOINC#86594-9 "RNA do vírus Zika [Presença] no líquido cefalorraquidiano por NAA com detecção por sonda"
* $BRNomeExameLOINC#91078-6 "RNA do vírus Zika [Presença] no sangue por NAA com detecção por sonda"
* $BRNomeExameLOINC#85621-1 "RNA do vírus Zika [Presença] no líquido amniótico por NAA com detecção por sonda"
* $BRNomeExameLOINC#80619-0 "Anticorpo IgM contra o vírus Zika [Unidades/volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#80618-2 "Anticorpo IgM contra o vírus Zika [Unidades/volume] no fluido espinhal cerebral por imunoensaio"
* $BRNomeExameLOINC#89591-2 "Anticorpo IgM contra o vírus Zika [título] no soro por imunofluorescência"
* $BRNomeExameLOINC#91678-3 "Anticorpo IgM contra o vírus Zika [Presença] em Soro, Plasma ou Sangue por Imunoensaio Rápido"
* $BRNomeExameLOINC#80824-6 "Anticorpo IgM contra o vírus Zika[Presença] em Soro ou Plasma por Imunoensaio"
* $BRNomeExameLOINC#80823-8 "Anticorpo IgM contra o vírus Zika [Presença] no fluido espinhal cerebral por imunoensaio"
* $BRNomeExameLOINC#97870-0 "Anticorpo IgG contra o vírus Zika [Unidades/volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#89590-4 "Anticorpo IgG contra o vírus Zika [Título] em soro por imunofluorescência"
* $BRNomeExameLOINC#95663-1 "Anticorpo IgG contra o vírus Zika [Presença] em espécime por imunoensaio"
* $BRNomeExameLOINC#91080-2 "Anticorpo IgG contra o vírus Zika [Presença] em Soro ou Plasma por Imunoensaio"
* $BRNomeExameLOINC#94184-9 "RNA do vírus da Febre Amarela [Presença] em espécime por NAA com detecção por sonda"
* $BRNomeExameLOINC#97869-2 "Painel de anticorpos contra o vírus Zika - Soro ou Plasma"
* $BRNomeExameLOINC#90459-9 "RNA do vírus da Febre Amarela [Presença] no sangue por NAA com detecção por sonda"
* $BRNomeExameLOINC#8057-2 "RNA do vírus da Febre Amarela [Presença] no soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#6593-8 "Anticorpo IgM vírus da Febre Amarela [Unidades/volume] no soro por imunoensaio"
* $BRNomeExameLOINC#95690-4 "Anticorpo IgM contra o vírus da Febre Amarela [Presença] em amostra por imunoensaio"
* $BRNomeExameLOINC#77955-3 "Anticorpo IgM vírus da Febre Amarela [Presença] no soro por imunofluorescência"
* $BRNomeExameLOINC#71782-7 "Anticorpo IgM vírus da Febre Amarela [Presença] no líquido cefalorraquidiano por imunoensaio"
* $BRNomeExameLOINC#6592-0 "Anticorpo IgG contra o vírus da Febre Amarela [Unidades/volume] no soro por imunoensaio"
* $BRNomeExameLOINC#95675-5 "Anticorpo IgG contra o vírus da Febre Amarela [Presença] na amostra por imunoensaio"
* $BRNomeExameLOINC#77954-6 "Anticorpo IgG contra o vírus da Febre Amarela [Presença] no soro por imunofluorescência"
* $BRNomeExameLOINC#97868-4 "Painel de anticorpos contra o vírus da Febre Amarela - Soro ou Plasma"
* $BRNomeExameLOINC#41239-5 "Anticorpo contra o vírus da Febre Amarela [Presença] no líquido cefalorraquidiano"
* $BRNomeExameLOINC#60418-1 "RNA do vírus da Dengue 4 [Presença] no soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#60419-9 "RNA do vírus da Dengue 3 [Presença] no soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#60420-7 "RNA do vírus da Dengue 2 [Presença] no soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#7855-0 "RNA do vírus da Dengue 1+2+3+4 [Presença] no soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#88189-6 "RNA do vírus da Dengue 1+2+3+4 [Presença] no sangue por NAA com detecção por sonda"
* $BRNomeExameLOINC#77958-7 "RNA do vírus da Dengue 1 e 2 e 3 e 4 [identificador] no líquido cefalorraquidiano por NAA com detecção por sonda"
* $BRNomeExameLOINC#94837-2 "RNA do vírus da Dengue 1+2+3+4 [Presença] no líquido amniótico por NAA com detecção por sonda"
* $BRNomeExameLOINC#88188-8 "RNA do vírus da Dengue 1+2+3+4 [Presença] na urina por NAA com detecção por sonda"
* $BRNomeExameLOINC#33578-6 "Anticorpo contra o vírus da Dengue [Título] no soro por imunofluorescência"
* $BRNomeExameLOINC#60262-3 "RNA do vírus da Dengue 1 [presença] no soro por NAA com detecção por sonda"
* $BRNomeExameLOINC#41878-0 "Painel IgG e IgM contra o vírus Dengue - Soro por Imunoensaio"
* $BRNomeExameLOINC#101206-1 "Antígeno  NS1 do vírus da Dengue [unidades/volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#75377-2 "Antígeno  NS1 do vírus da Dengue [Presença] em soro, plasma ou sangue por imunoensaio rápido"
* $BRNomeExameLOINC#34721-1 "Anticorpo IgM contra o vírus da Dengue [Presença] no fluido espinhal cerebral"
* $BRNomeExameLOINC#91064-6 "Antígeno  NS1 do vírus da Dengue [Presença] em Soro ou Plasma por Imunoensaio"
* $BRNomeExameLOINC#23992-1 "Anticorpo IgM contra o vírus da Dengue [unidades/volume] no soro por imunoensaio"
* $BRNomeExameLOINC#29663-2 "Anticorpo IgM contra o vírus da Dengue [Presença] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#75223-8 "Anticorpo IgG e IgM contra vírus da Dengue [identificador] em soro, plasma ou sangue por imunoensaio rápido"
* $BRNomeExameLOINC#23991-3 "Anticorpo IgG contra o vírus da Dengue [unidades/volume] no soro por imunoensaio"
* $BRNomeExameLOINC#100964-6 "Anticorpo IgG contra o vírus da Dengue [presença] em soro, plasma ou sangue por imunoensaio rápido"
* $BRNomeExameLOINC#29661-6 "Anticorpo IgG contra o vírus da Dengue [Presença] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#86515-4 "RNA do vírus Chikungunya [Presença] na urina por NAA com detecção por sonda"
* $BRNomeExameLOINC#81154-7 "Painel de vírus da Dengue e chikungunya e zika pela NAA com detecção por sonda"
* $BRNomeExameLOINC#55369-3 "Anticorpo contra o vírus da Dengue [título] no soro por inibição da hemaglutinação"
* $BRNomeExameLOINC#51664-1 "RNA do vírus Chikungunya [Presença] em espécime por NAA com detecção por sonda"
* $BRNomeExameLOINC#60260-7 "RNA do vírus Chikungunya [Presença] no soro ou plasma por NAA com detecção por sonda"
* $BRNomeExameLOINC#86514-7 "RNA do vírus Chikungunya [Presença] no líquido amniótico por NAA com detecção por sonda"
* $BRNomeExameLOINC#97867-6 "Anticorpo IgM contra o vírus Chikungunya [Unidades/volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#56130-8 "Anticorpo IgM contra o vírus Chikungunya [Título] em soro ou plasma por imunofluorescência"
* $BRNomeExameLOINC#56128-2 "Anticorpo IgG contra o vírus Chikungunya [Título] em soro ou plasma por imunofluorescência"
* $BRNomeExameLOINC#97866-8 "Anticorpo IgG contra o vírus Chikungunya [Unidades/volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#88629-1 "Anticorpo IgM contra o vírus Chikungunya [Presença] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#88630-9 "Anticorpo IgG contra o vírus Chikungunya [Presença] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#93976-9 "Painel Anticorpo IgM e IgG contra o vírus Chikungunya - Soro ou Plasma"
* $BRNomeExameLOINC#40505-0 "Anticorpo contra o vírus Chikungunya [Título] em Soro por Inibição de Hemaglutinação"
* $BRNomeExameLOINC#98493-0 "SARS coronavirus 2 região anticorpos ORF1b (Fases de leitura aberta-1b) [Presença] em saliva (fluído oral)  por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#99597-7 "SARS Coronavirus 2  proteína S [Presença] anticorpos IgG em soro ou plasma por Imunoensaio"
* $BRNomeExameLOINC#94503-0 "SARS Coronavírus 2 painel -  anticorpos em Soro, Plasma ou Sangue por Imunoensaio rápido"
* $BRNomeExameLOINC#94310-0 "SARS (como) Coronavírus  [Presença de] gene N em Amostra Inespecífica por Amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96118-5 "SARS Coronavírus 2 painel de anticorpos -  Amostra de sangue seco por Imunoensaio"
* $BRNomeExameLOINC#95423-0 "Vírus da Influenza A e B e SARS Coronavírus 2 identificado em  Amostra respiratória por Amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#95972-6 "SARS Coronavírus 2 estimulado por  interferon gama liberação por células T [Unidades/Volumes] corrigido para fundo em sangue"
* $BRNomeExameLOINC#95608-6 "SARS Coronavírus 2  [Presença de] RNA em amostra respiraória por Amplificação de ácido nucleico com detecção sem sonda"
* $BRNomeExameLOINC#95125-1 "SARS Coronavírus 2  [Presença de] IgA+IgM em Soro ou Plasma por Imunoensaio"
* $BRNomeExameLOINC#95409-9 "SARS Coronavírus 2, [Presença de] gene N em Nariz por  Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94508-9 "SARS Coronavírus 2, [presença de] anticorpos IgM em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#94507-1 "SARS Coronavírus 2, [presença de] anticorpos IgG em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#96896-6 "SARS coronavirus 2 clade [tipo] em amostra pelo método de genética molecular"
* $BRNomeExameLOINC#94639-2 "SARS Coronavírus 2 [Presença de] região anticorpos ORF1 em Amostra Inespecífica por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96755-4 "SARS Coronavirus 2 interpetação de variante em Amostra narrativa"
* $BRNomeExameLOINC#94565-9 "SARS Coronavírus 2, [presença de] DNA em rinofaringe por NAA por detecção sem sonda"
* $BRNomeExameLOINC#95942-9 "Vírus da Influenza A e B e SARS Coronavírus + SARS Coronavírus 2 painel de antígeno - Amostra de trato respiratório superior por Imunoensaio rápido"
* $BRNomeExameLOINC#94745-7 "SARS Coronavírus 2 [Limiar de ciclo de] RNA em Amostra respiratória por Amplificação do ácido nucleico"
* $BRNomeExameLOINC#94640-0 "SARS Coronavírus 2 [Presença de] gene S em Amostra respiratória por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94647-5 "SARS Coronavírus relacionado [Presença de] RNA em Amosta Inespecífica por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96763-8 "SARS Coronavírus 2 gene E [Presença] em amostra respiratória por Amplificação de ácido nucléico com detecção por sonda"
* $BRNomeExameLOINC#96752-1 "SARS Coronavírus 2 gene S mutação detectada [Presença de] em amostra por método genética molecular"
* $BRNomeExameLOINC#94562-6 "SARS Coronavírus 2, [presença de] anticorpos IgA Ab em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#94564-2 "SARS Coronavírus 2, [presença de] anticorpos IgM Ab em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#96119-3 "SARS Coronavírus 2 antígenos [Presença de] Amostra de trato respiratório superior por Imunoensaio"
* $BRNomeExameLOINC#94563-4 "SARS Coronavírus 2, [presença de] anticorpos IgG Ab em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#96742-2 "SARS Coronavírus 2 anticorpos IgG [Massa/Volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#94558-4 "SARS Coronavírus 2, [presença de] antígenos Ag em amostra respiratória por imunoensaio rápido"
* $BRNomeExameLOINC#94559-2 "SARS Coronavírus 2, [presença de] gene da regição ORF1ab em amostra respiratória por amplificação do ácido nucléico com detecção por sonda"
* $BRNomeExameLOINC#94531-1 "SARS Coronavírus 2 painel RNA - em Amostra respiratória por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96741-4 "SARS Coronavírus 2 variante [Tipo] em espécie por sequenciação"
* $BRNomeExameLOINC#94547-7 "SARS Coronavírus 2, [presença de] anticorpos IgG e IgM em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#96603-6 "SARS Coronavírus 2 proteína S domínio de ligação ao RNA anticorpo neutralizante [Presença] em soro ou plasma por imunonensaio"
* $BRNomeExameLOINC#96123-5 "SARS Coronavírus 2 gene RdRp [Presença de] em Amostra de trato respiratório superior por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96448-6 "SARS Coronavírus 2 gene N [Presença de] em saliva (fluído oral) por amplicação de ácido nucleico usando sonda primer set N1"
* $BRNomeExameLOINC#94534-5 "SARS Coronavírus 2, [presença de] gene RdRp em amostra respiratória por amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94532-9 "SARS Coronavírus relacionado + MERS Coronavírus, [presença de] RNA em amostra respiratória por amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94533-7 "SARS Coronavírus 2, [presença de] gene N em amostra respiratória por amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96121-9 "SARS Coronavírus relacionado gene E [Presença de] em Amostra de trato respiratório inferior por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94511-3 "SARS Coronavírus 2, [limiar de ciclo da] região ORF1ab em amostra não especificada por amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96122-7 "SARS Coronavírus relacionado gene E [Presença de] em Amostra de trato respiratório superior por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96120-1 "SARS Coronavírus 2 gene RdRp [Presença de] em Amostra de trato respiratório inferior por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96900-6 "SARS coronavirus 2 gene S [Limiar de ciclo#] em lavagem orofaríngea (gargarejo) por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#98131-6 "SARS coronavirus 2 região anticorpos ORF1b (Fases de leitura aberta-1b) [Presença] em amostra respiratória por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#98069-8 "SARS coronavirus 2 anticorpos [Presença] em Saliva (fluído oral) por imoensaio rápido"
* $BRNomeExameLOINC#94767-1 "SARS Coronavírus 2 [Presença de] gene S em Soro ou Plasma por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94766-3 "SARS Coronavírus 2 [Presença de] gene N em Soro ou Plasma por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94765-5 "SARS Coronavírus relacionado [Presença de] gene E em Soro ou Plasma por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94764-8 "SARS Coronavírus 2 [sequência de bases] genôma inteiro em isolado por sequenciamento"
* $BRNomeExameLOINC#97098-8 "SARS coronavirus 2 gene de proteína não estruturada-2 [Presença] em amostra de Trato respiratório superior por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#98080-5 "SARS coronavírus 2 e SARS-relacionado coronavírus painel de RNA - Saliva (fluído oral) por Amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94762-2 "SARS Coronavírus 2 [Presença de] anticorpos em Soro ou Plasma por Imunoensaio"
* $BRNomeExameLOINC#98062-3 "Identificador de estudo de sequenciamento"
* $BRNomeExameLOINC#97104-4 "SARS coronavirus 2 região anticorpos ORF1 (Fases de leitura aberta-1) [Unidades/Volumes] (carga viral) em amostra de trato respiratório superior por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94760-6 "SARS Coronavírus 2 [Presença de] gene N em Nasofaringe por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94761-4 "SARS Coronavírus 2 [Presença de] anticorpos IgG em teste em Amostra de sangue seco por Imunoensaio"
* $BRNomeExameLOINC#94746-5 "SARS Coronavírus 2 [Limiar de ciclo de] RNA em Amostra Inespecífica por Amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96986-5 "SARS coronavirus 2 gene N [Presença de] no nariz por Amplificação do ácido nucleico com detecção sem sonda"
* $BRNomeExameLOINC#94759-8 "SARS Coronavírus 2 [Presença de] RNA em Nasofaringe por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96957-6 "SARS Coronavirus 2 gene M [Presença de] em amostra de trato respiratório superior por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#97099-6 "Vírus da Influenza A e B e SARS Coronavírus 2 painel de antígenos - Amostra de trato respiratório superior por imunoensaio rápido"
* $BRNomeExameLOINC#97097-0 "SARS coronavirus 2 [Presença] antígenos em amostra de Trato respiratório superior por imunoensaio rápido"
* $BRNomeExameLOINC#96958-4 "SARS Coronavirus 2 gene N [Presença] em saliva (fluído oral) por Amplicação de ácido nucleico usando sonda primer CDC set N2"
* $BRNomeExameLOINC#94763-0 "SARS Coronavírus 2 [Presença de] em Amostra não específica por cultura em organismo específico"
* $BRNomeExameLOINC#94757-2 "SARS Coronavírus 2 [Presença de] gene N em Amostra respiratória por Amplificação do ácido nucleico usando sonda primer set N2"
* $BRNomeExameLOINC#94758-0 "SARS Coronavírus relacionado [Presença de] gene E em Amostra respiratória por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94756-4 "SARS Coronavírus 2 [Presença de] gene N em Amostra respiratória por Amplificação do ácido nucleido usando sonda primer set N1"
* $BRNomeExameLOINC#94768-9 "SARS Coronavírus 2 [Presença de] anticorpos IgA em Soro Plasma ou Sangue por Imunoensaio rápido"
* $BRNomeExameLOINC#94769-7 "SARS Coronavírus 2 [dosagem de] anticorpos em Soro ou Plasma por Imunoensaio"
* $BRNomeExameLOINC#98132-4 "SARS coronavirus 2 região anticorpos ORF1a (Fases de leitura aberta-1b) [Presença] em amostra respiratória por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#99314-7 "SARS Coronavirus 2 gene RdRp mutação detectada [Identificador] em amostra pelo método de genética molecular"
* $BRNomeExameLOINC#98734-7 "SARS Coronavirus 2 proteína S Domínio de Ligação ao RNA anticorpo neutralizante [Unidades/Volume] em soro ou plasma por imunonensaio"
* $BRNomeExameLOINC#95380-2 "Vírus da Influenza A e B e SARS Coronavírus 2 e SARS Coronavírus relacionado painel de RNA por Amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#98847-7 "SARS Coronavirus 2 interferon gama estimulado liberação por linfócitos [Unidades/volume] corrigido para sangue de fundo por imunoensaio"
* $BRNomeExameLOINC#94822-4 "SARS Coronavírus 2 [Presença de] RNA em Saliva (fluido oral) por sequenciamento"
* $BRNomeExameLOINC#94845-5 "SARS Coronavírus 2 [Presença de] RNA em Saliva (fluido oral) por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#98494-8 "SARS coronavirus 2 região anticorpos ORF1a (Fases de leitura aberta-1a) [Presença] em saliva (fluído oral) por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#95209-3 "SARS Coronavírus + SARS Coronavírus 2 [Presença de] antígeno em Amostra respiratória por Imunoensaio rápido"
* $BRNomeExameLOINC#98733-9 "Percentual de neutralização por SARS coronavirus 2 proteína spike Domínio de Ligação ao RNA anticorpo neutralizante em soro ou plasma por imunonensaio"
* $BRNomeExameLOINC#99596-9 "SARS Coronavirus 2 proteína N [Presença] anticorpos IgG em soro ou plasma por Imunoensaio"
* $BRNomeExameLOINC#95406-5 "SARS Coronavírus 2, [Presença de] RNA no Nariz por Amplificação de ácido nucléico com detecção por sonda"
* $BRNomeExameLOINC#98732-1 "SARS Coronavirus 2 proteína S Domínio de Ligação ao RNA anticorpo neutralizante [Fator de diluição] em soro ou plasma por imunonensaio"
* $BRNomeExameLOINC#98846-9 "SARS Coronavirus 2 interferon gama estimulado liberação por células T auxiliares (CD4+) [Unidades/volume] corrigido para sangue de fundo por imunoensaio"
* $BRNomeExameLOINC#94819-0 "SARS Coronavírus 2 [dosagem de] (carga viral) RNA em Amostra Inespecífica por Amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#99771-8 "SARS Coronavirus 2 proteína spike e proteína de nucleocapsídeo painel de interferon gama estimulado - Sangue"
* $BRNomeExameLOINC#99772-6 "SARS Coronavirus 2 interferon gama estimulado [Interpretação] em Sangue Qualitativo"
* $BRNomeExameLOINC#99773-4 "SARS Coronavirus 2 interferon gama estimulado liberado por células T. Antígeno spike área de contagem [#] corrigido para fundo em Sangue"
* $BRNomeExameLOINC#99774-2 "SARS Coronavirus 2 interferon gama estimulado liberado por células T. Antígeno nucleocapsídeo área de contagem [#] corrigido para fundo em Sangue"
* $BRNomeExameLOINC#96899-0 "SARS coronavirus 2 [Limiar de ciclo#] região anticorpos ORF1 (Fases de leitura aberta-1) em lavagem orofaríngea (gargarejo) por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94720-0 "SARS Coronavírus 2 [dosagem de] anticorpos IgA em Soro ou Plasma por Imunoensaio"
* $BRNomeExameLOINC#96898-2 "SARS coronavirus 2 gene N [Limiar de ciclo#] em lavagem orofaríngea (gargarejo) por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94661-6 "SARS Coronavírus 2 [Interpretação de] anticorpos em Soro ou Plasma"
* $BRNomeExameLOINC#96897-4 "SARS coronavirus 2 painel de RNA - lavagem orofaríngea (gargarejo) por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94660-8 "SARS Coronavírus 2 [Presença de] em Soro ou Plasma por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96895-8 "SARS coronavirus 2 linhagem [tipo] em amostra pelo método de genética molecular"
* $BRNomeExameLOINC#94646-7 "SARS Coronavírus 2 [Limiar de ciclo de] gene RdRp em Amostra respiratória por Amplificação do ácido nucleico"
* $BRNomeExameLOINC#96894-1 "SARS coronavirus 2 painel de sequenciamento e identificação - Amostra pelo método de genética molecular"
* $BRNomeExameLOINC#94645-9 "SARS Coronavírus 2 [Limiar de ciclo de] gene RdRp em Amostra Inespecífica por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96829-7 "SARS coronavirus 2 RNA [Presença de] em Amostra de doador por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94644-2 "SARS Coronavírus 2 [Limiar de ciclo de] região anticorpos ORF1 em Amostra respiratória por Amplificação do ácido nucleico"
* $BRNomeExameLOINC#96797-6 "SARS coronavirus 2 RNA [Presença] em lavagem orofaríngea (gargarejo) por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94643-4 "SARS Coronavírus 2 [Limiar de ciclo de] gene S em Amostra Inespecífica por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96766-1 "Sequencia GISAID número de registro"
* $BRNomeExameLOINC#94642-6 "SARS Coronavírus 2 [Limiar de ciclo de] gene S em Amostra respiratória por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96765-3 "SARS Coronavírus 2 gene S [Presença] em saliva (fluído oral) por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94641-8 "SARS Coronavírus 2 [Presença de] gene S em Amostra Inespecífica por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96764-6 "SARS Coronavírus 2 gene E [Limiar de ciclo #] em Amostra respiratória por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96751-3 "SARS Coronavírus 2 gene S mutação detectada [Identificador] em specime por método genética molecular"
* $BRNomeExameLOINC#94510-5 "SARS Coronavírus 2, [limiar de ciclo de] gene 2 N em amostra não especificada por amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94509-7 "SARS Coronavírus 2, [limiar de ciclo de] gene E em amostra não especificada por amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96094-8 "SARS Coronavírus 2 e SARS Coronavírus relacionado painel de RNA - Amostra respiratória por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#96091-4 "SARS Coronavírus 2 gene RdRp [Presença de] em saliva (fluído oral) por Amostra respiratória por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#95974-2 "SARS Coronavírus 2 estimulado por interferon gama painel - Sangue"
* $BRNomeExameLOINC#94506-3 "SARS Coronavírus 2, [dosagem de] anticorpos IgM [Unidades/Volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#95973-4 "SARS Coronavírus 2 estimulado por interferon gama liberação por células T (Unidades/Volume] em sangue"
* $BRNomeExameLOINC#94505-5 "SARS Coronavírus 2, [dosagem de] anticorpos IgG [Unidades/Volume] em soro ou plasma por imunoensaio"
* $BRNomeExameLOINC#94504-8 "SARS Coronavírus 2 painel - anticorpos, Soro ou Plasma por Imunoensaio rápido"
* $BRNomeExameLOINC#95971-8 "SARS Coronavírus 2 estimulado por interferon gama [Presença de] em sangue"
* $BRNomeExameLOINC#95970-0 "SARS Coronavírus 2 rearranjos específicos de genes de células T de receptor beta [Presença de] em sangue por sequenciamento"
* $BRNomeExameLOINC#94502-2 "SARS Coronavírus relacionado, [presença de] RNA em amostra respiratória por amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94500-6 "SARS Coronavírus 2, [presença de] RNA em amostra respiratória por amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#95941-1 "Vírus da Influenza A e B e SARS Coronavírus 2 e Vírus sinciciais respiratórios painel de RNA - Amostra respiratória por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94316-7 "SARS Coronavírus 2, [presença de] gene N em amostra não especificada por amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#95826-4 "SARS Coronavírus 2 painel de RNA - Saliva (fluido oral) por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94315-9 "SARS Coronavírus 2, [presença de] gene E em amostra não especificada por amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#95825-6 "SARS Coronavírus 2 [Presença de] anticorpos em Amostra de Sangue seco por Imunoensaio"
* $BRNomeExameLOINC#94314-2 "SARS Coronavírus 2, [presença de] gene RdRp em amostra não especificada por amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#95824-9 "SARS Coronavírus 2 [Presença de] região anticorpos ORF1 em Saliva (fluido oral) por Amplificação de ácido nucléico com detecção por sonda"
* $BRNomeExameLOINC#94313-4 "SARS (como) Coronavírus [Limiar de ciclo de] gene N em Amostra Inespecífica por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#95823-1 "SARS Coronavírus relacionado [Presença de] gene E em Saliva (fluido oral) por Amplificação de àcido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94312-6 "SARS Coronavírus 2, [limiar de ciclo] de gene N em amostra não especificada por amplificação de ácido nucleico usando conjunto de sonda / primer N2"
* $BRNomeExameLOINC#95609-4 "SARS Coronavírus 2 [Presença de] gene S em amostra respiratória por sequenciação"
* $BRNomeExameLOINC#94311-8 "SARS Coronavírus 2, [limiar de ciclo] de gene N em amostra não especificada por amplificação de ácido nucleico usando conjunto de sonda / primer N1"
* $BRNomeExameLOINC#95542-7 "SARS Coronavírus 2 anticorposs IgG+IgM [Presença de] em Soro Plasma ou Sangue por Imunoensaio rápido"
* $BRNomeExameLOINC#94309-2 "SARS Coronavírus 2, [presença de] RNA em amostra não especificada, por amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#95522-9 "SARS Coronavírus 2 [dosagem de] (carga viral ) gene N em Amostra respiratória por Amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94308-4 "SARS Coronavírus 2, [presença de] gene N em amostra não especificada, por amplificação de ácido nucleico usando conjunto de sonda / primer N2"
* $BRNomeExameLOINC#95521-1 "SARS Coronavírus 2 [#/volume] (carga viral) gene N em Amostra respiratória por Amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#94307-6 "SARS Coronavírus, [presença de] gene 2 N em amostra não especificada por amplificação de ácido nucleico usando conjunto de sonda / primer N1"
* $BRNomeExameLOINC#95429-7 "SARS Coronavírus 2 [Concentração de] anticorpos IgG em Soro ou Plasma por imunofluorescência"
* $BRNomeExameLOINC#94306-8 "SARS Coronavírus 2 Painel de RNA - Amostra Inespecífica por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#95428-9 "SARS Coronavírus 2 [Concentração de] anticorpos IgM em Soro ou Plasma por imunofluorescência"
* $BRNomeExameLOINC#41853-3 "Orthopoxvirus DNA [Presença de] em Amostra por Amplificação de Ácido Nucleico com detecção por sonda"
* $BRNomeExameLOINC#95427-1 "SARS Coronavírus 2 [Concentração de] anticorpos IgA em Soro ou Plasma por imunofluorescência"
* $BRNomeExameLOINC#100893-7 "Orthopoxvirus IgG e IgM Ab panel - Soro ou Plasma"
* $BRNomeExameLOINC#95425-5 "SARS Coronavírus 2 [Presença de] gene N em Saliva (fluido oral) por Amplificação de ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#100892-9 "Orthopoxvirus IgM Ab [Presença] em soro ou plasma por Imunoensaio"
* $BRNomeExameLOINC#95424-8 "SARS Coronavírus 2 [Presença de] RNA em Amostra respiratória por sequenciamento"
* $BRNomeExameLOINC#100891-1 "Orthopoxvirus IgG Ab [Presença] em Soro ou Plasma por Imunoensaio"
* $BRNomeExameLOINC#100889-5 "Vírus Monkeypox da Bacia do Congo DNA [Presença de] em Amostra por Amplificação de Ácido Nucleico com detecção por sonda"
* $BRNomeExameLOINC#95422-2 "Vírus da Influenza A e B RNA e SARS Coronavírus 2 painel de gene N - Amostra respiratória por Amplificação do ácido nucleico com detecção por sonda"
* $BRNomeExameLOINC#100888-7 "Vírus Monkeypox da Africa Ocidental DNA [Presença de] em Amostra por Amplificação de Ácido Nucleico com detecção por sonda"
* $BRNomeExameLOINC#95416-4 "SARS Coronavírus 2, [Presença de] anticorpos IgM teste em Amostra de Sangue seco por Imunoensaio"
* $BRNomeExameLOINC#100887-9 "Vírus da pseudovaríola DNA [Presença] em Amostra por Amplficação de Ácido Nucleio com detecção por sonda"
* $BRNomeExameLOINC#95411-5 "SARS Coronavírus 2, [Presença de] neutralização de anticorpos em Soro por teste de neutralização de pseudovírus"
* $BRNomeExameLOINC#100886-1 "Vírus Orf DNA [Presença de] em Amostra por Amplificação de Ácido Nucleio com detecção por sonda"
* $BRNomeExameLOINC#95410-7 "SARS Coronavírus 2, [Concentração de] neutralização de anticorpos em Soro por teste de neutralização de pseudovírus"
* $BRNomeExameLOINC#100885-3 "Parapoxvirus DNA [Presença de] em Amostra por Amplificação de Ácido Nucleico com detecção por sonda"
* $BRNomeExameLOINC#100434-0 "Orthopoxvirus não-varíola DNA [Presença de] em Amostra por Amplificação de Ácido Nucleico com detecção por sonda"
* $BRNomeExameLOINC#100383-9 "Vírus Monkeypox DNA [Presença de] em Amostra por Amplificação de Ácido Nucleico com detecção por sonda"