ValueSet: BROrgaoExpedidor
Id: BROrgaoExpedidor
Title: "BR Orgao Expedidor"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BROrgaoExpedidor#CRM "Conselho Regional de Medicina (CRM)"
* BROrgaoExpedidor#CRFA "Conselho Regional de Fonoaudiologia (CRFa/CREFONO)"
* BROrgaoExpedidor#other "Outro órgão não listado"
* BROrgaoExpedidor#CRF "Conselho Regional de Farmácia (CRF)"
* BROrgaoExpedidor#SSP "Serviço de Segurança Pública"
* BROrgaoExpedidor#CRESS "Conselho Regional de Serviço Social (CRESS)"
* BROrgaoExpedidor#RFB "Receita Federal do Brasil"
* BROrgaoExpedidor#CREFITO "Conselho Regional de Fisioterapia e Terapia Ocupacional (CREFITO)"
* BROrgaoExpedidor#PM "Polícia Militar"
* BROrgaoExpedidor#CREF "Conselho Regional de Educação Física (CREF)"
* BROrgaoExpedidor#PF "Polícia Federal"
* BROrgaoExpedidor#CRECI "Conselho Regional de Corretores de Imóveis (CRECI)"
* BROrgaoExpedidor#PCE "Polícia Civil do Estado"
* BROrgaoExpedidor#CREA "Conselho Regional de Engenharia e Agronomia (CREA)"
* BROrgaoExpedidor#OAB "Ordem dos Advogados do BRAasil (OAB)"
* BROrgaoExpedidor#CRC "Conselho Regional de Contabilidade (CRC)"
* BROrgaoExpedidor#MS "Ministério da Saúde"
* BROrgaoExpedidor#MC "Ministério da Cidadania"
* BROrgaoExpedidor#CRBM "Conselho Regional de Biomedicina (CRBM)"
* BROrgaoExpedidor#MB "Marinha do Brasil"
* BROrgaoExpedidor#CRBIO "Conselho Regional de Biologia (CRBio)"
* BROrgaoExpedidor#II "Instituto de Identificação"
* BROrgaoExpedidor#CRB "Conselho Regional de Biblioteconomia (CRB)"
* BROrgaoExpedidor#FAB "Força Aérea Brasileira"
* BROrgaoExpedidor#CRA "Conselho Regional de Administração (CRA)"
* BROrgaoExpedidor#EB "Exército Brasileiro"
* BROrgaoExpedidor#COREN "Conselho Regional de Enfermagem (COREn)"
* BROrgaoExpedidor#DETRAN "Departamento Estadual de Trânsito"
* BROrgaoExpedidor#CORECON "Conselho Regional de Economia (CORECON)"
* BROrgaoExpedidor#CRTR "Conselho Regional de Técnicos em Radiologia (CRTR)"
* BROrgaoExpedidor#CORE "Conselho Regional de Representantes Comerciais (CORE)"
* BROrgaoExpedidor#CRT "Conselho Regional dos Técnicos Industriais (CRT)"
* BROrgaoExpedidor#CONRERP "Conselho Regional de Reçações Públicas (CONRERP)"
* BROrgaoExpedidor#CRQ "Conselho Regional de Química (CRQ)"
* BROrgaoExpedidor#CONFRE "Conselho Regional de Estatística (CONRE)"
* BROrgaoExpedidor#CRP "Conselho Regional de Psicologia (CRP)"
* BROrgaoExpedidor#CBM "Corpo de Bombeiros Militar"
* BROrgaoExpedidor#CRO "Conselho Regional de Odontologia (CRO)"
* BROrgaoExpedidor#CAU "Conselho Regional de Arquitetura e Urbanismo (CAU)"
* BROrgaoExpedidor#CRN "Conselho Regional de Nutrição (CRN)"
* BROrgaoExpedidor#CRMV "Conselho Regional de Medicina Veterinária (CRMV)"
* BROrgaoExpedidor#CARTORIO "Cartório de Registro Civil"