ValueSet: BROrtesesProtesesImplantaveis
Id: BROrtesesProtesesImplantaveis
Title: "BROrtesesProtesesImplantaveis"
* ^version = "HEAD"
* ^status = #active
* ^publisher = "MS"
* $BROrtesesProtesesImplantaveis#0000000143 "Órtese brônquica reta expansível sintética"
* $BROrtesesProtesesImplantaveis#0000000142 "Órtese brônquica reta não\nexpansível sintética"
* $BROrtesesProtesesImplantaveis#0000000285 "Válvula brônquica para\ntratamento de fuga aérea e  sintética"
* $BROrtesesProtesesImplantaveis#0000000141 "Órtese auto-expansível de vias\nbilio-pancreáticas auto-expansível metálica"
* $BROrtesesProtesesImplantaveis#0000000284 "Tubo de ventilação para\nouvido médio permanente sintético"
* $BROrtesesProtesesImplantaveis#0000000140 "Órtese auto-expansível de vias\nbilio-pancreáticas auto-expansível\nvários tamanhos sintética"
* $BROrtesesProtesesImplantaveis#0000000283 "Tubo de ventilação para\nouvido médio temporário sintético"
* $BROrtesesProtesesImplantaveis#0000000139 "Órtese auto-expansível de  sintética"
* $BROrtesesProtesesImplantaveis#0000000282 "Tela para correção de incontinência\nurinária masculina sintética"
* $BROrtesesProtesesImplantaveis#0000000138 "Órtese auto-expansível de reto auto-expansível metálica"
* $BROrtesesProtesesImplantaveis#0000000281 "Tela para correção de incontinência\nurinária feminina sintética"
* $BROrtesesProtesesImplantaveis#0000000137 "Órtese auto-expansível de intestino delgado auto-expansível metálica"
* $BROrtesesProtesesImplantaveis#0000000280 "Tela  absorvível"
* $BROrtesesProtesesImplantaveis#0000000136 "Órtese auto-expansível de estômago auto-expansível metálica"
* $BROrtesesProtesesImplantaveis#0000000279 "Tela  sintética / biológica"
* $BROrtesesProtesesImplantaveis#0000000135 "Órtese auto-expansível de auto-expansível plástica"
* $BROrtesesProtesesImplantaveis#0000000278 "Tela  inorgânica e sintética"
* $BROrtesesProtesesImplantaveis#0000000134 "Órtese auto-expansível de esôfago auto-expansível metálica"
* $BROrtesesProtesesImplantaveis#0000000277 "Suspensor palpebral vários tamanhos biológica/sintética"
* $BROrtesesProtesesImplantaveis#0000000133 "Órtese auto-expansível de duodeno auto-expansível metálica"
* $BROrtesesProtesesImplantaveis#0000000276 "Stent vascular vários tamanhos metálico/sintético"
* $BROrtesesProtesesImplantaveis#0000000132 "Órtese auto-expansível de cólon auto-expansível metálica"
* $BROrtesesProtesesImplantaveis#0000000275 "Stent vascular artérias ilíacas metálico/sintético"
* $BROrtesesProtesesImplantaveis#0000000131 "Molde laríngeo  sintética"
* $BROrtesesProtesesImplantaveis#0000000274 "Stent vascular artérias viscerais metálico/sintético"