ValueSet: BRPopulacaoTradicional
Id: BRPopulacaoTradicional
Title: "BR Populacao Tradicional"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRPopulacaoTradicional#XIV "Isqueiros"
* BRPopulacaoTradicional#XXVIII "Varjeiros"
* BRPopulacaoTradicional#XIII "Jangadeiros"
* BRPopulacaoTradicional#XXVII "Vazanteiros"
* BRPopulacaoTradicional#XII "Geraizeiros"
* BRPopulacaoTradicional#XXVI "Seringueiros"
* BRPopulacaoTradicional#XI "Faxinalenses"
* BRPopulacaoTradicional#XXV "Ribeirinhos"
* BRPopulacaoTradicional#X "Extrativistas"
* BRPopulacaoTradicional#XXIV "Retireiros"
* BRPopulacaoTradicional#VIII "Ciganos"
* BRPopulacaoTradicional#XXIII "Quebradeiras de coco babaçu"
* BRPopulacaoTradicional#VII "Cerrado"
* BRPopulacaoTradicional#XXII "Povos de terreiro/matriz africana"
* BRPopulacaoTradicional#XXI "Povos quilombolas"
* BRPopulacaoTradicional#VI "Catadores de mangaba"
* BRPopulacaoTradicional#XX "Povos indígenas"
* BRPopulacaoTradicional#V "Castanheiras"
* BRPopulacaoTradicional#XVIII "Pescadores artesanais"
* BRPopulacaoTradicional#IX "Comunidades de fundo e fecho de pasto"
* BRPopulacaoTradicional#XVII "Pantaneiros"
* BRPopulacaoTradicional#IV "Caiçaras"
* BRPopulacaoTradicional#XVI "Marisqueiros"
* BRPopulacaoTradicional#III "Caatingueiros"
* BRPopulacaoTradicional#XV "Morroquianos"
* BRPopulacaoTradicional#II "Agroextrativistas"
* BRPopulacaoTradicional#XIX "Pomeranos"
* BRPopulacaoTradicional#I "Andirobeiras"