ValueSet: BRProgramaSaude
Id: BRProgramaSaude
Title: "BR Programa Saude"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRProgramaSaude#501 "Estratégicos"
* BRProgramaSaude#981 "Alimentação e Nutrição"
* BRProgramaSaude#5 "Hipertensão"
* BRProgramaSaude#961 "Estratégico"
* BRProgramaSaude#481 "Assistência Social"
* BRProgramaSaude#941 "Malária"
* BRProgramaSaude#461 "Cólera"
* BRProgramaSaude#923 "Infecções Oportunistas"
* BRProgramaSaude#441 "UPA"
* BRProgramaSaude#922 "Influenza"
* BRProgramaSaude#421 "Especializado"
* BRProgramaSaude#921 "Chagas"
* BRProgramaSaude#401 "SAMU"
* BRProgramaSaude#903 "Meningite"
* BRProgramaSaude#4 "Judicialização"
* BRProgramaSaude#902 "Leishmaniose"
* BRProgramaSaude#381 "Saúde da Criança"
* BRProgramaSaude#901 "Tracoma"
* BRProgramaSaude#361 "Assitência Farmacêutica"
* BRProgramaSaude#882 "Epidemias"
* BRProgramaSaude#341 "Assistência Farmacêutica Básica"
* BRProgramaSaude#881 "Edemias Focais"
* BRProgramaSaude#3 "DST/AIDS"
* BRProgramaSaude#861 "Saúde Prisional"
* BRProgramaSaude#281 "Tabagismo"
* BRProgramaSaude#801 "Doença Enxerto Hospedeiro"
* BRProgramaSaude#261 "Tuberculose"
* BRProgramaSaude#8 "Hospitalar"
* BRProgramaSaude#2 "Diabetes"
* BRProgramaSaude#781 "Atenção Secundária"
* BRProgramaSaude#1421 "Órteses e Prósteses"
* BRProgramaSaude#767 "Suplementos Alimentares"
* BRProgramaSaude#1401 "Multidroga Resistente"
* BRProgramaSaude#766 "Fraldas"
* BRProgramaSaude#1381 "SESAI"
* BRProgramaSaude#765 "Administrativos"
* BRProgramaSaude#1361 "Calamidade Pública"
* BRProgramaSaude#764 "Diversos"
* BRProgramaSaude#1341 "DPOC"
* BRProgramaSaude#763 "Oncologia"
* BRProgramaSaude#1321 "DPOC"
* BRProgramaSaude#762 "Alzheimer"
* BRProgramaSaude#1301 "Assistência Farmacêutica SESAI"
* BRProgramaSaude#761 "DPOC"
* BRProgramaSaude#1281 "Assitência Farmacêutica SESAI"
* BRProgramaSaude#721 "Mieloma Múltiplo"
* BRProgramaSaude#1261 "Peste"
* BRProgramaSaude#701 "Antimicrobianos"
* BRProgramaSaude#1241 "Micoses Sistêmicas"
* BRProgramaSaude#7 "Saúde Mental"
* BRProgramaSaude#1221 "Micoses Sistêmicas"
* BRProgramaSaude#683 "Lúpus Eritematoso Sistêmico"
* BRProgramaSaude#1202 "Coagulopatias"
* BRProgramaSaude#682 "Infecções Oportunistas DST/AIDS"
* BRProgramaSaude#1201 "Filariose"
* BRProgramaSaude#681 "Suplementos Alimentares"
* BRProgramaSaude#1181 "Remédio em Casa"
* BRProgramaSaude#662 "Insumos"
* BRProgramaSaude#1161 "Toxoplasmose"
* BRProgramaSaude#661 "Lúpus Eritematoso Sistêmico"
* BRProgramaSaude#1141 "Imunização"
* BRProgramaSaude#641 "Infecções Oportunistas DST/AIDS"
* BRProgramaSaude#1121 "Nutrição"
* BRProgramaSaude#621 "Ação Civil Pública"
* BRProgramaSaude#1102 "Esquitossomose"
* BRProgramaSaude#601 "Estratégicos - Estado"
* BRProgramaSaude#1101 "Dengue"
* BRProgramaSaude#6 "Saúde da Mulher"
* BRProgramaSaude#1081 "Cólera"
* BRProgramaSaude#581 "Suplementação de Ferro"
* BRProgramaSaude#1021 "Insulino-Dependente- DM II"
* BRProgramaSaude#561 "Sem dor"
* BRProgramaSaude#1001 "Insulino-Dependente- DM I"
* BRProgramaSaude#541 "Glaucoma"
* BRProgramaSaude#521 "Urgência e Emergência"
* BRProgramaSaude#1 "Hanseníase"