ValueSet: BRResultadoQualitativoExame
Id: BRResultadoQualitativoExame
Title: "BR Resultado Qualitativo Exame"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRTipoResultadoDTNT#1 "Detectable"
* BRTipoResultadoDTNT#2 "Não Detectável"
* BRTipoResultadoDTNT#3 "Indeterminado        "
* BRTipoResultadoHISPT#2 "Não Compatível"
* BRTipoResultadoHISPT#1 "Compatível"
* BRTipoResultadoHISPT#3 "Inconclusivo"
* BRTipoResultadoPRAU#2 "Ausência"
* BRTipoResultadoPRAU#1 "Presença"
* BRTipoResultadoPRAU#3 "Inconclusivo"
* BRTipoResultadoRSBAC#2 "Não Foram visualizados"
* BRTipoResultadoRSBAC#3 "Inconclusivo"
* BRTipoResultadoRSBAC#1 "Foram visualizados"
* BRTipoResultadoAVIDEZ#2 "Alta Avidez"
* BRTipoResultadoAVIDEZ#1 "Baixa Avidez"
* BRTipoResultadoAVIDEZ#3 "Indeterminado        "
* BRTipoResultadoRGNR#2 "Não Reagente"
* BRTipoResultadoRGNR#1 "Reagente"
* BRTipoResultadoRGNR#3 "Indeterminado"
* BRTipoResultadoRSCUL#2 "Houve crescimento"
* BRTipoResultadoRSCUL#3 "Inconclusivo"
* BRTipoResultadoRSCUL#1 "Não houve crescimento"
* BRResultadoQualitativoExame#1 "Detectável"
* BRResultadoQualitativoExame#3 "Inconclusivo"
* BRResultadoQualitativoExame#2 "Não Detectável"
* BRTipoResultadoPSNG#2 "Negativo"
* BRTipoResultadoPSNG#1 "Positivo"
* BRTipoResultadoPSNG#3 "Inconclusivo"