ValueSet: BRTipoAmostra
Id: BRTipoAmostra
Title: "BR Tipo Amostra"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRTipoAmostraGAL#SECORF "Secreção Orofaríngea"
* BRTipoAmostraGAL#SGHEM "Sangue"
* BRTipoAmostraGAL#ASNAFA "Aspirado Nasofaríngeo"
* BRTipoAmostraGAL#MTBIO "Material Não Biológico"
* BRTipoAmostraGAL#FRACOR "Fragmentos de coração"
* BRTipoAmostraGAL#FRAFIG "Fragmentos de fígado"
* BRTipoAmostraGAL#FLUORA "Fluido oral"
* BRTipoAmostraGAL#FRABAC "Fragmentos de baço"
* BRTipoAmostraGAL#SGEDT "Sangue com EDTA"
* BRTipoAmostraGAL#SECTRA "Secreção Traqueal"
* BRTipoAmostraGAL#ASPBRO "Aspirado Brônquico"
* BRTipoAmostraGAL#FRAAMI "Fragmentos de ampigdalas"
* BRTipoAmostraGAL#RASPEL "Raspado de pele"
* BRTipoAmostraGAL#FGMT "Fragmento"
* BRTipoAmostraGAL#SECPEN "Secreção peniana"
* BRTipoAmostraGAL#EXSORO "Exsudato de Orofaringe"
* BRTipoAmostraGAL#CORIZA "Coriza"
* BRTipoAmostraGAL#SECBRO "Secreção brônquica"
* BRTipoAmostraGAL#FGMP "Fragmentos do pulmão"
* BRTipoAmostraGAL#SECONF "Secreção Orofaríngea e Nasofaríngea"
* BRTipoAmostraGAL#SECNAS "Secreção Nasofaríngea"
* BRTipoAmostraGAL#EXSNAS "Exsudato de Nasofaringe"
* BRTipoAmostraGAL#SECOC "Secreção ocular"
* BRTipoAmostraGAL#SNCCEB "Fragmento do tecido do SNC - cérebro"
* BRTipoAmostraGAL#FRBRON "Fragmentos de brônquio"
* BRTipoAmostraGAL#FRAGT "Fragmento de tecido"
* BRTipoAmostraGAL#FRATRA "Fragmentos de traquéia"
* BRTipoAmostraGAL#SWLES "Swab de lesão"
* BRTipoAmostraGAL#SWBAN "Swab Anal"
* BRTipoAmostraGAL#FRAPAN "Fragmentos de pâncreas"
* BRTipoAmostraGAL#FRAMOR "Fragmentos de múltiplos órgãos"
* BRTipoAmostraGAL#FRARIM "Fragmentos de rim"
* BRTipoAmostraGAL#SWAB "Swab"
* BRTipoAmostraGAL#SWNAFA "Swab Nasofaríngeo"
* BRTipoAmostraGAL#SNOF "Swab Naso-Orofaríngeo"
* BRTipoAmostraGAL#SWOCU "Swab Ocular"
* BRTipoAmostraGAL#INFP "Infiltrado pulmonar"
* BRTipoAmostraGAL#SWNAS "Swab Nasal"
* BRTipoAmostraGAL#SWLSP "Swab de lesão de pele"
* BRTipoAmostraGAL#INODER "Inoculação intradérmica"
* BRTipoAmostraGAL#LAVBRO "Lavado Brônquico"
* BRTipoAmostraGAL#LAVBRA "Lavado Brônquico Alveolar"
* BRTipoAmostraGAL#SWRET "Swab retal"
* BRTipoAmostraGAL#SWORA "Swab Oral"
* BRTipoAmostraGAL#LAVORO "Lavado de orofaringe"
* BRTipoAmostraGAL#SWORO "Swab Orofaríngeo"
* BRTipoAmostraGAL#LAVTBR "Lavado Traqueo-Brônquico"
* BRTipoAmostraGAL#TECPM "Tecido pós-mortem"
* $v2-0487#TASP "Aspirate, Tracheal"
* $v2-0487#SPUTIN "Sputum, Inducted"
* $v2-0487#WASH "Wash"
* $v2-0487#WB "Whole, Blood"
* $v2-0487#SPT "Sputum"
* $v2-0487#UR "Urine"
* $v2-0487#SER "Serum"
* $v2-0487#GENV "Genital vaginal"
* $v2-0487#SECRE "Secretion(s)"
* $v2-0487#SAL "Saliva"
* $v2-0487#FRS "Fluid, Respiratory"
* $v2-0487#PLAS "Plasma"
* $v2-0487#NSECR "Secretion, Nasal"
* $v2-0487#CSF "Cerebral spinal fluid"
* $v2-0487#LAVG "Lavage, Bronhial"
* $v2-0487#ASP "Aspirate"