ValueSet: BRTipoEstabelecimentoSaude
Id: BRTipoEstabelecimentoSaude
Title: "BR Tipo Estabelecimento Saude"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRTipoEstabelecimentoSaude#67 "LABORATORIO CENTRAL DE SAUDE PUBLICA LACEN"
* BRTipoEstabelecimentoSaude#64 "CENTRAL DE REGULACAO DE SERVICOS DE SAUDE"
* BRTipoEstabelecimentoSaude#85 "CENTRO DE IMUNIZACAO"
* BRTipoEstabelecimentoSaude#84 "CENTRAL DE ABASTECIMENTO"
* BRTipoEstabelecimentoSaude#62 "HOSPITAL/DIA - ISOLADO"
* BRTipoEstabelecimentoSaude#61 "CENTRO DE PARTO NORMAL - ISOLADO"
* BRTipoEstabelecimentoSaude#83 "POLO DE PREVENCAO DE DOENCAS E AGRAVOS E PROMOCAO DA SAUDE"
* BRTipoEstabelecimentoSaude#60 "COOPERATIVA OU EMPRESA DE CESSAO DE TRABALHADORES NA SAUDE"
* BRTipoEstabelecimentoSaude#82 "CENTRAL DE NOTIFICACAO,CAPTACAO E DISTRIB DE ORGAOS ESTADUAL"
* BRTipoEstabelecimentoSaude#50 "UNIDADE DE VIGILANCIA EM SAUDE"
* BRTipoEstabelecimentoSaude#81 "CENTRAL DE REGULACAO DO ACESSO"
* BRTipoEstabelecimentoSaude#5 "HOSPITAL GERAL"
* BRTipoEstabelecimentoSaude#80 "LABORATORIO DE SAUDE PUBLICA"
* BRTipoEstabelecimentoSaude#43 "FARMACIA"
* BRTipoEstabelecimentoSaude#79 "OFICINA ORTOPEDICA"
* BRTipoEstabelecimentoSaude#42 "UNIDADE MOVEL DE NIVEL PRE-HOSPITALAR NA AREA DE URGENCIA"
* BRTipoEstabelecimentoSaude#78 "UNIDADE DE ATENCAO EM REGIME RESIDENCIAL"
* BRTipoEstabelecimentoSaude#40 "UNIDADE MOVEL TERRESTRE"
* BRTipoEstabelecimentoSaude#77 "SERVICO DE ATENCAO DOMICILIAR ISOLADO(HOME CARE)"
* BRTipoEstabelecimentoSaude#76 "CENTRAL DE REGULACAO MEDICA DAS URGENCIAS"
* BRTipoEstabelecimentoSaude#4 "POLICLINICA"
* BRTipoEstabelecimentoSaude#75 "TELESSAUDE"
* BRTipoEstabelecimentoSaude#39 "UNIDADE DE APOIO DIAGNOSE E TERAPIA (SADT ISOLADO)"
* BRTipoEstabelecimentoSaude#74 "POLO ACADEMIA DA SAUDE"
* BRTipoEstabelecimentoSaude#36 "CLINICA/CENTRO DE ESPECIALIDADE"
* BRTipoEstabelecimentoSaude#73 "PRONTO ATENDIMENTO"
* BRTipoEstabelecimentoSaude#32 "UNIDADE MOVEL FLUVIAL"
* BRTipoEstabelecimentoSaude#72 "UNIDADE DE ATENCAO A SAUDE INDIGENA"
* BRTipoEstabelecimentoSaude#22 "CONSULTORIO ISOLADO"
* BRTipoEstabelecimentoSaude#71 "CENTRO DE APOIO A SAUDE DA FAMILIA"
* BRTipoEstabelecimentoSaude#21 "PRONTO SOCORRO ESPECIALIZADO"
* BRTipoEstabelecimentoSaude#70 "CENTRO DE ATENCAO PSICOSSOCIAL"
* BRTipoEstabelecimentoSaude#20 "PRONTO SOCORRO GERAL"
* BRTipoEstabelecimentoSaude#7 "HOSPITAL ESPECIALIZADO"
* BRTipoEstabelecimentoSaude#2 "CENTRO DE SAUDE/UNIDADE BASICA"
* BRTipoEstabelecimentoSaude#69 "CENTRO DE ATENCAO HEMOTERAPIA E OU HEMATOLOGICA"
* BRTipoEstabelecimentoSaude#15 "UNIDADE MISTA"
* BRTipoEstabelecimentoSaude#68 "CENTRAL DE GESTAO EM SAUDE"
* BRTipoEstabelecimentoSaude#1 "POSTO DE SAUDE"