ValueSet: BRTipoObservacao
Id: BRTipoObservacao
Title: "BR Tipo Observacao"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRTipoObservacao#IAC "Informações Adicionais/Complementares"
* BRTipoObservacao#RECIDI "Resumo da evolução clínica do indivíduo durante a internação"
* BRTipoObservacao#DSIA "Declaração Subjetiva do Indivíudo para o Atendimento"
* BRTipoObservacao#DF "Dados do desfecho"
* BRTipoObservacao#PC "Perímetro Cefálico"
* BRTipoObservacao#CA "Circunferência Abdominal"
* BRTipoObservacao#PA "Pressão Arterial"
* BRTipoObservacao#P "Peso"
* BRTipoObservacao#A "Altura"
* LOINC#8652-0 "Hospital discharge history"
* LOINC#8650-4 "Hospital discharge disposition"
* LOINC#8648-8 "Hospital course"
* LOINC#46696-1 "Additional comments"
* LOINC#11329-0 "History general"
* LOINC#9843-4 "Circumference.occipital-frontal"
* LOINC#8665-2 "Date last menstrual period"
* LOINC#8480-6 "Intravascular systolic"
* LOINC#8462-4 "Intravascular diastolic"
* LOINC#8302-2 "Body height"
* LOINC#8280-0 "Circumference.at umbilicus"
* LOINC#63895-7 "Breastfeeding status"
* LOINC#48767-8 "Annotation comment"
* LOINC#56832-9 "Substance abused"
* LOINC#29463-7 "Body weight"
* LOINC#11996-6 "Pregnancies"
* LOINC#11885-1 "Gestational age"
* LOINC#11612-9 "Abortions"
* LOINC#18842-5 "Discharge summary note"