ValueSet: BRTipoIdentificador
Id: BRTipoIdentificador
Title: "BR Tipo Identificador"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRTipoIdentificador#AUTH "Código de Autorização"
* BRTipoIdentificador#BRACRECI "Número de inscrição no Conselho Regional de Corretores de Imóveis (CRECI)"
* BRTipoIdentificador#BRACREA "Número de inscrição no Conselho Regional de Engenharia e Agronomia (CREA)"
* BRTipoIdentificador#BRAOAB "Número de inscrição na Ordem dos Advogados do BRAasil (OAB)"
* BRTipoIdentificador#BRACRC "Número de inscrição no Conselho Regional de Contabilidade (CRC)"
* BRTipoIdentificador#BRAIDMIL "Número da Identidade Militar"
* BRTipoIdentificador#BRAIDFUNC "Número da Identidade Funcional"
* BRTipoIdentificador#BRACRBM "Número da inscrição no Conselho Regional de Biomedicina (CRBM)"
* BRTipoIdentificador#BRACRTR "Número da inscrição no Conselho Regional de Técnicos em Radiologia (CRTR)"
* BRTipoIdentificador#BRACRBIO "Número de inscrição no Conselho Regional de Biologia (CRBio)"
* BRTipoIdentificador#BRACRT "Número da inscrição no Conselho Regional dos Técnicos Industriais (CRT)"
* BRTipoIdentificador#BRACRB "Número de inscrição no Conselho Regional de Biblioteconomia (CRB)"
* BRTipoIdentificador#BRACRQ "Número de inscrição no Conselho Regional de Química (CRQ)"
* BRTipoIdentificador#BRACRA "Número de inscrição no Conselho Regional de Administração (CRA)"
* BRTipoIdentificador#BRACRP "Número de inscrição no Conselho Regional de Psicologia (CRP)"
* BRTipoIdentificador#BRACORECON "Número de inscrição no Conselho Regional de Economia (CORECON)"
* BRTipoIdentificador#BRACRN "Número de inscrição no Conselho Regional de Nutrição (CRN)"
* BRTipoIdentificador#BRACORE "Número de inscrição no Conselho Regional de Representantes Comerciais (CORE)"
* BRTipoIdentificador#BRACRMV "Número de inscrição no Conselho Regional de Medicina Veterinária (CRMV)"
* BRTipoIdentificador#BRACONRERP "Número de inscrição no Conselho Regional de Reçações Públicas (CONRERP)"
* BRTipoIdentificador#BRACRFA "Número da inscrição no Conselho Regional de Fonoaudiologia (CRFa/CREFONO)"
* BRTipoIdentificador#BRACONFRE "Número de inscrição no Conselho Regional de Estatística (CONRE)"
* BRTipoIdentificador#BRACNPJ "Número de inscrição no Cadastro Nacional da Pessoa Jurídica (CNPJ)"
* BRTipoIdentificador#BRACRESS "Número de inscrição no Conselho Regional de Serviço Social (CRESS)"
* $v2-0203#BR "Birth registry number"
* $v2-0203#RI "Resource identifier"
* $v2-0203#RPH "Pharmacist license number"
* $v2-0203#TAX "Tax ID number"
* $v2-0203#DDS "Dentist license number"
* $v2-0203#MD "Medical License number"
* $v2-0203#IND "Indigenous/Aboriginal"
* $v2-0203#BCT "Birth Certificate"
* $v2-0203#DL "Driver's license number"
* $v2-0203#SS "Social Security number"
* $v2-0203#RN "Registered Nurse Number"
* $v2-0203#PPN "Passport number"
* $v2-0203#MCT "Marriage Certificate"
* $v2-0203#RRI "Regional registry ID"
* $v2-0203#MI "Military ID number"
* $v2-0203#HC "Health Card Number"
* $v2-0203#MRT "Temporary Medical Record Number"
* $v2-0203#MR "Medical record number"
* $v2-0203#MCR "Practitioner Medicare number"
* $v2-0203#MCN "Microchip Number"
* $v2-0203#MCD "Practitioner Medicaid number"
* $v2-0203#MC "Patient's Medicare number"
* $v2-0203#MB "Member Number"
* $v2-0203#MA "Patient Medicaid number"
* $v2-0203#LR "Local Registry ID"