ValueSet: BRUnidadeMedidaMedicamento
Id: BRUnidadeMedidaMedicamento
Title: "BR Unidade Medida Medicamento"
* ^version = "1.0.0"
* ^status = #active
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* BRUnidadeMedida#82 "Glóbulo"
* BRUnidadeMedida#43 "mg (Miligrama)"
* BRUnidadeMedida#42 "mEq (Miliequivalente)"
* BRUnidadeMedida#41 "m (Metro)"
* BRUnidadeMedida#9 "Bisnaga"
* BRUnidadeMedida#40 "Lata"
* BRUnidadeMedida#80 "Tubo"
* BRUnidadeMedida#4 "Aplicação"
* BRUnidadeMedida#8 "Barra"
* BRUnidadeMedida#39 "L (Litro)"
* BRUnidadeMedida#79 "Tubete"
* BRUnidadeMedida#38 "kg (Quilograma)"
* BRUnidadeMedida#78 "Tablete"
* BRUnidadeMedida#37 "Implante"
* BRUnidadeMedida#77 "Seringa preenchida"
* BRUnidadeMedida#36 "Hora"
* BRUnidadeMedida#76 "Sachê"
* BRUnidadeMedida#35 "Gota"
* BRUnidadeMedida#75 "Pote"
* BRUnidadeMedida#34 "Goma"
* BRUnidadeMedida#74 "Drágea"
* BRUnidadeMedida#33 "g (Grama)"
* BRUnidadeMedida#71 "Cartela"
* BRUnidadeMedida#70 "Cartão"
* BRUnidadeMedida#32 "Frasco-ampola"
* BRUnidadeMedida#7 "Bandagem"
* BRUnidadeMedida#31 "Frasco"
* BRUnidadeMedida#69 "Capsula inalante"
* BRUnidadeMedida#30 "Flaconete"
* BRUnidadeMedida#66 "Bastão"
* BRUnidadeMedida#3 "Anel"
* BRUnidadeMedida#64 "Óvulo"
* BRUnidadeMedida#29 "Filme"
* BRUnidadeMedida#63 "UTR (Unidade Redutora da Turbidez)"
* BRUnidadeMedida#28 "Estojo"
* BRUnidadeMedida#62 "Unidade"
* BRUnidadeMedida#27 "Envelope"
* BRUnidadeMedida#61 "UIC (Unidade Inibidora de Calicreína)"
* BRUnidadeMedida#26 "Enema"
* BRUnidadeMedida#60 "UI (Unidade Internacional)"
* BRUnidadeMedida#25 "Endosporos"
* BRUnidadeMedida#6 "Atomização"
* BRUnidadeMedida#24 "Emplastro"
* BRUnidadeMedida#59 "Supositório"
* BRUnidadeMedida#23 "Dose"
* BRUnidadeMedida#58 "Strip"
* BRUnidadeMedida#22 "Dispositivo de injeção pré-carregado"
* BRUnidadeMedida#57 "Seringa"
* BRUnidadeMedida#21 "Dispositivo"
* BRUnidadeMedida#56 "Saco"
* BRUnidadeMedida#20 "Desconhecido"
* BRUnidadeMedida#55 "Pílula"
* BRUnidadeMedida#2 "Ampola"
* BRUnidadeMedida#54 "Pastilha gomosa"
* BRUnidadeMedida#19 "Comprimido"
* BRUnidadeMedida#53 "Pastilha dura"
* BRUnidadeMedida#18 "cm² (Centímetro Quadrado)"
* BRUnidadeMedida#52 "Pastilha"
* BRUnidadeMedida#17 "cm (Centímetro)"
* BRUnidadeMedida#51 "nL (Nanolitro)"
* BRUnidadeMedida#50 "ng (Nanograma)"
* BRUnidadeMedida#16 "Catéter"
* BRUnidadeMedida#5 "Aplicador"
* BRUnidadeMedida#15 "Cartucho"
* BRUnidadeMedida#49 "mm (Milímetro)"
* BRUnidadeMedida#14 "Carpule"
* BRUnidadeMedida#48 "mL (Mililitro)"
* BRUnidadeMedida#13 "Cápsula"
* BRUnidadeMedida#47 "MUI (Milhões de unidades internacionais)"
* BRUnidadeMedida#12 "Caixa"
* BRUnidadeMedida#46 "Milhões"
* BRUnidadeMedida#11 "Bolsa"
* BRUnidadeMedida#10 "Blíster"
* BRUnidadeMedida#45 "Microlitro"
* BRUnidadeMedida#44 "Micrograma"
* BRUnidadeMedida#1 "Adesivo"