ValueSet: OCIOtorrino
Id: OCIOtorrino
Title: "OCIOtorrino"
* ^version = "HEAD"
* ^status = #active
* ^publisher = "MS"
* $BRTabelaSUS#0904010015 "OCI AVALIAÇÃO INICIAL DIAGNÓSTICA DE DÉFICIT AUDITIVO"
* $BRTabelaSUS#0904010031 "OCI AVALIAÇÃO DIAGNÓSTICA DE NASOFARINGE E DE OROFARINGE"
* $BRTabelaSUS#0904010023 "OCI PROGRESSÃO DA AVALIAÇÃO DIAGNÓSTICA DE DÉFICIT AUDITIVO"