ValueSet: OCIOrtopedia
Id: OCIOrtopedia
Title: "OCIOrtopedia"
* ^version = "HEAD"
* ^status = #active
* ^publisher = "MS"
* $BRTabelaSUS#0903010011 "OCI AVALIAÇÃO DIAGNÓSTICA EM ORTOPEDIA COM RECURSOS DE RADIOLOGIA"
* $BRTabelaSUS#0903010020 "OCI AVALIAÇÃO DIAGNÓSTICA EM ORTOPEDIA COM RECURSOS DE RADIOLOGIA E ULTRASSONOGRAFIA"
* $BRTabelaSUS#0903010046 "OCI AVALIAÇÃO DIAGNÓSTICA EM ORTOPEDIA COM RECURSOS DE RADIOLOGIA E RESSONÂNCIA MAGNÉTICA"
* $BRTabelaSUS#0903010038 "OCI AVALIAÇÃO DIAGNÓSTICA EM ORTOPEDIA COM RECURSOS DE RADIOLOGIA E TOMOGRAFIA COMPUTADORIZADA"