services:
  fhir-ig-publisher:
    build: .
    volumes:
      - .:/app
      - ../packages:/root/.fhir/packages
      - ./rootCA.pem:/app/rootCA.pem:ro
    environment:
      - JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=/app/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
      - NO_PROXY=localhost,127.0.0.1,host.docker.internal
      - no_proxy=localhost,127.0.0.1,host.docker.internal
    command: >
        bash -c "
                 # truststore combinado = cacerts padrão + mkcert
                 cp /etc/ssl/certs/java/cacerts /app/truststore.jks && keytool -importcert -noprompt -trustcacerts -alias mkcert-local -file /app/rootCA.pem -keystore /app/truststore.jks -storepass changeit || true;
                 echo Limpando pasta do FSH...;
                 rm -rf /app/fsh-generated;
                 echo Gerando FSH...;
                 npx sushi .;                  
                 echo clonando ig-history...;                
                 git clone https://github.com/HL7/fhir-ig-history-template.git /app/ig-history;
                 echo clonando ig-registry...;                
                 git clone https://github.com/FHIR/ig-registry.git /app/ig-registry;
                 echo Iniciando IG-Publisher...;                
                 java -Xms4g -Xmx8g -Dfile.encoding=UTF-8 -jar /app/input-cache/publisher.jar -ig /app -tx 'https://host.docker.internal/r4' -authorise-non-conformant-tx-servers" 