server {

    # SSL configuration

    listen 443 ssl http2 ;
    listen [::]:443 ssl http2 ;
    include snippets/self-signed.conf;
    include snippets/ssl-params.conf;
    
    server_name terminologia.saude.gov.br; # managed by Certbot

#    ssl_certificate /etc/letsencrypt/live/terminologia.saude.gov.br/fullchain.pem; # managed by Certbot
#    ssl_certificate_key /etc/letsencrypt/live/terminologia.saude.gov.br/privkey.pem; # managed by Certbot


    error_log   /var/log/nginx/terminologia.saude.gov.br_error.log;
    access_log  /var/log/nginx/terminologia.saude.gov.br_access.log;  

    root /var/www/html;

    location ~ ^/fhir/([^/]+)/([^/]+)$ {
        return 303 /fhir/$1-$2.html;
    }

    location /fhir {
    	index index.html;
    }        

    location / {
            add_header X-debug-message "Entrou OCL";
            proxy_pass http://localhost:4000/;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_read_timeout 20d;
            proxy_buffering off;
    }    

    ssl_certificate /etc/letsencrypt/live/terminologia.saude.gov.br/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/terminologia.saude.gov.br/privkey.pem; # managed by Certbot
}
