ValueSet: BRCRF
Id: BRCRF
Description: "Conjunto de todos os conselhos regionais de farmácia do Brasil"
* ^title = "Conselhos regionais de Farmácia do Brasil"
* ^name = "BRCRF"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^identifier.system = "https://saude.gov.br/sid/valueset"
* ^identifier.value = "BRCRF"
* ^version = "1.0"
* ^status = #draft
* ^experimental = true
* ^date = "2023-07-18T10:52:24-03:00"
* ^publisher = "Ministério da Saúde do Brasil"
* ^contact.name = "Ministério da Saúde do Brasil"
* ^contact.telecom.system = #url
* ^contact.telecom.value = "https://gov.br/saude"
* ^jurisdiction = urn:iso:std:iso:3166#BR
* ^purpose = "O propósito deste conjunto é agrupar todos os conselhos regionais de farmácia para fins de validação do identificador profissional do farmacêutico"
* ^copyright = "CC-1.0"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-ac "CRF-AC"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-al "CRF-AL"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-am "CRF-AM"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-ap "CRF-AP"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-ba "CRF-BA"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-ce "CRF-CE"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-df "CRF-DF"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-es "CRF-ES"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-go "CRF-GO"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-ma "CRF-MA"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-mg "CRF-MG"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-ms "CRF-MS"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-mt "CRF-MT"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-pa "CRF-PA"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-pb "CRF-PB"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-pe "CRF-PE"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-pi "CRF-PI"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-pr "CRF-PR"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-rj "CRF-RJ"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-rn "CRF-RN"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-ro "CRF-RO"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-rr "CRF-RR"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-rs "CRF-RS"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-sc "CRF-SC"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-se "CRF-SE"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-sp "CRF-SP"
* $BRConselhoProfissional#https://saude.gov.br/sid/crf-to "CRF-TO"