ValueSet: BROutrosProfissionais
Id: BROutrosProfissionais
Description: "Conjunto de todos os conselhos regionais de outros profissionais da saúde do Brasil"
* ^title = "Conselhos regionais de outros profissionais da saúde do Brasil"
* ^name = "BROutrosProfissionais"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^identifier.system = "https://saude.gov.br/fhir/sid/valueset"
* ^identifier.value = "BROutrosProfissionais"
* ^version = "1.0"
* ^status = #draft
* ^experimental = true
* ^date = "2023-07-18T10:52:24-03:00"
* ^publisher = "Ministério da Saúde do Brasil"
* ^contact.name = "Ministério da Saúde do Brasil"
* ^contact.telecom.system = #url
* ^contact.telecom.value = "https://gov.br/saude"
* ^jurisdiction = urn:iso:std:iso:3166#BR
* ^purpose = "O propósito deste conjunto é agrupar todos os conselhos regionais da categoria de outros profissionais da saúde para fins de validação do identificador profissional"
* ^copyright = "CC-1.0"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-ac-ro "CRP-AC-RO"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-al "CRP-AL"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-am-rr "CRP-AM-RR"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-ba "CRP-BA"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-ce "CRP-CE"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-df "CRP-DF"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-es "CRP-ES"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-go "CRP-GO"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-ma "CRP-MA"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-mg "CRP-MG"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-ms "CRP-MS"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-mt "CRP-MT"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-pa-ap "CRP-PA-AP"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-pb "CRP-PB"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-pe "CRP-PE"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-pi "CRP-PI"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-pr "CRP-PR"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-rj "CRP-RJ"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-rn "CRP-RN"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-rs "CRP-RS"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-sc "CRP-SC"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-se "CRP-SE"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-sp "CRP-SP"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crp-to "CRP-TO"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-ba "CREFITO-BA"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-ce "CREFITO-CE"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-es "CREFITO-ES"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-go-df "CREFITO-GO-DF"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-ma "CREFITO-MA"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-mg "CREFITO-MG"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-ms "CREFITO-MS"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-mt "CREFITO-MT"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-pa-am-to-rr-ap "CREFITO-PA-AM-TO-RR-AP"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-pe-pb-al-rn "CREFITO-PE-PB-AL-RN"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-pi "CREFITO-PI"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-pr "CREFITO-PR"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-rj "CREFITO-RJ"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-ro-ac "CREFITO-RO-AC"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-rs "CREFITO-RS"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-sc "CREFITO-SC"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-se "CREFITO-SE"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefito-sp "CREFITO-SP"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crn-al "CRN-AL"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crn-ba-se "CRN-BA-SE"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crn-ce-ma-pi "CRN-CE-MA-PI"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crn-df-go-mt-to "CRN-DF-GO-MT-TO"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crn-pa-ac-am-ap-ro-rr "CRN-PA-AC-AM-AP-RO-RR"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crn-pe-al-pb-rn "CRN-PE-AL-PB-RN"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crn-pr "CRN-PR"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crn-rj-es "CRN-RJ-ES"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crn-rs "CRN-RS"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crn-sc "CRN-SC"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crn-sp-ms "CRN-SP-MS"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefono-am-ac-ap-pa-ro-rr "CREFONO-AM-AC-AP-PA-RO-RR"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefono-ce-ma-pi-rn "CREFONO-CE-MA-PI-RN"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefono-go-df-ms-mt-to "CREFONO-GO-DF-MS-MT-TO"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefono-mg-es "CREFONO-MG-ES"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefono-pe-al-ba-pb-se "CREFONO-PE-AL-BA-PB-SE"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefono-pr-sc "CREFONO-PR-SC"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefono-rj "CREFONO-RJ"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefono-rs "CREFONO-RS"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/crefono-sp "CREFONO-SP"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-ac "CRESS-AC"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-al "CRESS-AL"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-am "CRESS-AM"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-ap "CRESS-AP"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-ba "CRESS-BA"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-ce "CRESS-CE"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-df "CRESS-DF"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-es "CRESS-ES"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-go "CRESS-GO"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-ma "CRESS-MA"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-mg "CRESS-MG"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-ms "CRESS-MS"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-mt "CRESS-MT"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-pa "CRESS-PA"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-pb "CRESS-PB"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-pe "CRESS-PE"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-pi "CRESS-PI"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-pr "CRESS-PR"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-rj "CRESS-RJ"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-rn "CRESS-RN"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-ro "CRESS-RO"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-rr "CRESS-RR"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-rs "CRESS-RS"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-sc "CRESS-SC"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-se "CRESS-SE"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-sp "CRESS-SP"
* $BRConselhoProfissional#https://saude.gov.br/fhir/sid/cress-to "CRESS-TO"
