ValueSet: BRCRO
Id: BRCRO
Description: "Conjunto de todos os conselhos regionais de farmácia do Brasil"
* ^title = "Conselhos regionais de Odontologia do Brasil"
* ^name = "BRCRO"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^identifier.system = "https://saude.gov.br/sid/valueset"
* ^identifier.value = "BRCRO"
* ^version = "1.0"
* ^status = #draft
* ^experimental = true
* ^date = "2023-07-18T10:52:24-03:00"
* ^publisher = "Ministério da Saúde do Brasil"
* ^contact.name = "Ministério da Saúde do Brasil"
* ^contact.telecom.system = #url
* ^contact.telecom.value = "https://gov.br/saude"
* ^jurisdiction = urn:iso:std:iso:3166#BR
* ^purpose = "O propósito deste conjunto é agrupar todos os conselhos regionais de farmácia para fins de validação do identificador profissional do odontólogo"
* ^copyright = "CC-1.0"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-ac "CRO-AC"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-al "CRO-AL"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-am "CRO-AM"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-ap "CRO-AP"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-ba "CRO-BA"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-ce "CRO-CE"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-df "CRO-DF"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-es "CRO-ES"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-go "CRO-GO"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-ma "CRO-MA"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-mg "CRO-MG"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-ms "CRO-MS"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-mt "CRO-MT"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-pa "CRO-PA"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-pb "CRO-PB"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-pe "CRO-PE"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-pi "CRO-PI"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-pr "CRO-PR"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-rj "CRO-RJ"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-rn "CRO-RN"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-ro "CRO-RO"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-rr "CRO-RR"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-rs "CRO-RS"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-sc "CRO-SC"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-se "CRO-SE"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-sp "CRO-SP"
* $BRConselhoProfissional#https://saude.gov.br/sid/cro-to "CRO-TO"