CodeSystem: BRCIAP2
Id: BRCIAP2
Title: "BRCIAP2"
* ^meta.lastUpdated = "2025-07-14T22:07:09.769+00:00"
* ^version = "1.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* ^caseSensitive = true
* ^content = #complete
* #A93 "Recém nascido prematuro"
* #A99 "Outras doenças gerais NE"
* #P16 "Abuso agudo de álcool"
* #P15 "Abuso crônico de álcool"
* #P13 "Encoprese/outros problemas de incontinência fecal"
* #P12 "Molhar a cama/enurese"
* #P11 "Problemas de alimentação da criança"
* #P10 "Gaguejar/balbuciar/tiques"
* #P09 "Preocupação com a preferência sexual"
* #P08 "Diminuição da satisfação sexual"
* #P07 "Diminuição do desejo sexual"
* #Z29 "Problema social NE"
* #P06 "Perturbação do sono"
* #Z28 "Limitação funcional/incapacidade"
* #P05 "Sensação/comportamento senil"
* #Z27 "Medo de problema social"
* #P04 "Sentir/comportar-se de forma irritável/zangada"
* #Z25 "Ato ou acontecimento violento"
* #P03 "Tristeza/ Sensação de depressão"
* #Z24 "Problema de relacionamento com amigos"
* #P02 "Reação aguda ao estresse"
* #Z23 "Perda/falecimento de familiar"
* #P01 "Sensação de ansiedade/nervosismo/tensão"
* #Z22 "Problema por doença familiar"
* #N99 "Outras doenças do sistema neurológico"
* #Z21 "Problema comportamental de familiar"
* #N95 "Cefaléia tensional"
* #Z20 "Problema de relacionamento com familiares"
* #N94 "Neurite/ Nevrite/neuropatia periférica"
* #Z19 "Perda ou falecimento de criança"
* #N93 "Síndrome do túnel do carpo/ Síndrome do canal cárpico"
* #Z18 "Problema com criança doente"
* #N92 "Nevralgia do trigémio"
* #Z16 "Problema de relacionamento com criança"
* #N91 "Paralisia facial/paralisia de Bell"
* #Z15 "Perda ou falecimento do parceiro/ companheiro"
* #N90 "Cefaléia de cluster"
* #Z14 "Problema por doença do parceiro/ companheiro"
* #N89 "Enxaqueca"
* #Z13 "Problema comportamental do parceiro/ companheiro"
* #N88 "Epilepsia"
* #Z12 "Problema de relacionamento com parceiro/ conjugal"
* #N87 "Parkinsonismo"
* #Z11 "Problema relacionado com estar doente"
* #N86 "Esclerose múltipla"
* #Z10 "Problema relacionado com sistema de saúde"
* #N85 "Malformações congênitas"
* #Z09 "Problema de ordem legal"
* #N81 "Outra lesão do sistema neurológico"
* #N80 "Outras lesões cranianas"
* #Z08 "Problema relacionado com sistema de segurança social"
* #N79 "Concussão"
* #Z07 "Problemas relacionados com educação"
* #N76 "Neoplasia do sistema neurológico de natureza incerta"
* #Z06 "Problemas de desemprego"
* #N75 "Neoplasia benigna do sistema neurológico"
* #Z05 "Problemas com condições de trabalho"
* #N74 "Neoplasia maligna do sistema neurológico"
* #Z04 "Problema socio-cultural"
* #N73 "Outra infecção neurológica"
* #Z03 "Problemas de habitação/vizinhança"
* #Z02 "Problemas relacionados a água/alimentação"
* #N72 "Tétano"
* #N71 "Meningite/encefalite"
* #Z01 "Pobreza/problemas econômicos"
* #N70 "Poliomielite"
* #Y99 "Doença genital masculina, outra"
* #N29 "Sinais/sintomas do sistema neurológico, outros"
* #Y86 "Hidrocele"
* #N28 "Limitação funcional/incapacidade"
* #Y85 "Hipertrofia benigna da próstata/ hiperplasia prostática benigna"
* #N27 "Medo de outras doenças neurológicas"
* #Y84 "Malformação genital congénita masculina, outra"
* #N26 "Medo de câncer do sistema neurológico"
* #Y83 "Testículo não descido/ Criptorquidia/ Testículo ectópico"
* #N19 "Perturbações da fala"
* #Y82 "Hipospádias"
* #N18 "Paralisia/fraqueza"
* #Y81 "Fimose/prepúcio redundante"
* #N17 "Vertigens/tonturas"
* #Y80 "Traumatismo genital masculino, outro"
* #N16 "Alterações do olfato/gosto"
* #Y79 "Neoplasia benigna genital masculina NE"
* #N08 "Movimentos involuntários anormais"
* #Y78 "Neoplasia maligna genital masculina, outra"
* #N07 "Convulsões/ataques"
* #Y77 "Neoplasia maligna da próstata"
* #N06 "Outras alterações da sensibilidade"
* #Y76 "Condiloma acuminado"
* #N05 "Formigamento/ parestesia nos dedos das mãos/pés"
* #Y75 "Balanite/ Balanopostite"
* #N04 "Síndrome das pernas inquietas"
* #Y74 "Orquite/epididimite"
* #N03 "Dores da face"
* #Y73 "Prostatite/vesiculite seminal"
* #N01 "Cefaléia"
* #Y72 "Herpes genital"
* #L99 "Outra doença do aparelho músculo-esquelético"
* #Y71 "Gonorréia masculina"
* #L98 "Malformação adquirida de um membro"
* #Y70 "Sífilis masculina"
* #L97 "Neoplasia benigna/incertas"
* #Y29 "Sinais/sintomas, outros"
* #L96 "Lesão interna aguda do joelho"
* #Y28 "Limitação funcional/incapacidade"
* #L95 "Osteoporose"
* #Y27 "Medo de doença genital masculina, outra"
* #L94 "Osteocondrose"
* #Y26 "Medo de câncer genital masculino"
* #L93 "Cotovelo de tenista"
* #Y25 "Medo de doença sexualmente transmissível"
* #L92 "Síndrome do ombro doloroso"
* #Y24 "Medo de disfunção sexual masculina"
* #L91 "Outras osteoartroses"
* #Y16 "Sinais/sintomas da mama masculina"
* #L90 "Osteoartrose do joelho"
* #Y14 "Planejamento familiar, outros"
* #L89 "Osteoartrose do quadril"
* #Y13 "Esterilização masculina"
* #L88 "Artrite reumatóide/seropositiva"
* #Y10 "Infertilidade/subfertildade masculina"
* #L87 "Bursite/tendinite/sinovite NE"
* #Y08 "Sinais/sintomas da função sexual masculina, outros"
* #L86 "Síndrome vertebral com irradiação dor"
* #Y07 "Impotência NE"
* #L85 "Deformação adquirida da coluna"
* #Y06 "Sinais/sintomas da próstata"
* #L84 "Doenças ou síndromes da coluna sem irradiação de dor"
* #Y05 "Sinais/sintomas do escroto/testículos, outros"
* #Y04 "Sinais/sintomas do pênis, outros"
* #L83 "Doenças ou síndromes da coluna cervical"
* #Y03 "Secreção uretral"
* #L82 "Malformações congênitas do aparelho músculo-esquelético"
* #Y02 "Dor no escroto/testículos"
* #L81 "Traumatismos do aparelho musculoesquelético NE"
* #Y01 "Dor no pênis"
* #L80 "Luxação/subluxação"
* #X99 "Doença genital feminina, outra"
* #L79 "Entorses e distensões das articulações NE"
* #X92 "Infecção por clamídia"
* #L78 "Entorses e distensões do joelho"
* #X91 "Condiloma acuminado feminino"
* #L77 "Entorses e distensões do tornozelo"
* #X90 "Herpes genital feminino"
* #L76 "Outras fraturas"
* #X89 "Síndrome da tensão pré-menstrual"
* #L75 "Fratura: fémur"
* #X88 "Doença fibrocística da mama"
* #L74 "Fratura: osso da mão/pé"
* #X87 "Prolapso utero-vaginal"
* #L73 "Fratura: tíbia/perônio/ fíbula"
* #X86 "Esfregaço de Papanicolau/colpocitologia oncótica anormal"
* #L72 "Fratura: rádio/cúbito"
* #X85 "Doença do colo NE"
* #L71 "Neoplasia maligna do aparelho músculo-esquelético"
* #X84 "Vaginite/vulvite NE"
* #L70 "Infecções do aparelho músculo-esquelético"
* #X83 "Malformações congênitas genitais"
* #L29 "Outros sinais/sintomas do aparelho músculo-esquelético"
* #X82 "Lesão traumática genital feminina"
* #L28 "Limitação funcional/incapacidade"
* #X81 "Neoplasia genital feminina, outra/NE"
* #L27 "Medo de doença no aparelho músculo-esquelético, outro"
* #X80 "Neoplasia benigna genital"
* #L26 "Medo de câncer no aparelho músculo-esquelético"
* #X79 "Neoplasia benigna da mama feminina/ fibroadenoma"
* #L20 "Sinais/sintomas das articulações NE"
* #X78 "Fibromioma uterino"
* #L19 "Sinais/sintomas musculares NE"
* #X77 "Neoplasia maligna genital feminina, outra"
* #L18 "Dores musculares"
* #X76 "Neoplasia maligna da mama feminina"
* #L17 "Sinais/sintomas do pé/dedos pé"
* #X75 "Neoplasia maligna do colo"
* #L16 "Sinais/sintomas do tornozelo"
* #X74 "Doença inflamatória pélvica"
* #L15 "Sinais/sintomas do joelho"
* #X73 "Tricomoníase genital feminina"
* #L14 "Sinais/sintomas da coxa/perna"
* #X72 "Candidíase genital feminina"
* #L13 "Sinais/sintomas do quadril"
* #X71 "Gonorréia feminina"
* #L12 "Sinais/sintomas das mãos e dedos"
* #X70 "Sífilis feminina"
* #L11 "Sinais/sintomas dos punhos"
* #X29 "Sinais/sintomas do aparelho genital feminino, outra"
* #L10 "Sinais/sintomas dos cotovelos"
* #X28 "Limitação funcional/incapacidade"
* #L09 "Sinais/sintomas dos braços"
* #X27 "Medo de outra doença genital/mama"
* #L08 "Sinais/sintomas dos ombros"
* #X26 "Medo de câncer na mama"
* #L07 "Sinais/sintomas da mandíbula"
* #X25 "Medo de câncer genital"
* #L05 "Sinais/sintomas da axila"
* #X24 "Medo de disfunção sexual"
* #L04 "Sinais/sintomas do tórax"
* #X23 "Medo de doença de transmissão sexual"
* #L03 "Sinais/sintomas da região lombar"
* #X22 "Preocupação com a aparência da mama feminina"
* #L02 "Sinais/sintomas da região dorsal"
* #X21 "Sinais/sintomas da mama feminina, outros"
* #L01 "Sinais/sintomas do pescoço"
* #X20 "Sinais/sintomas do mamilo da mulher"
* #K99 "Outras doenças do aparelho circulatório"
* #X19 "Tumor ou nódulo na mama feminina"
* #K96 "Hemorróidas"
* #X18 "Dor na mama feminina"
* #K95 "Veias varicosas da perna"
* #X17 "Sinais/sintomas da pélvis feminina"
* #K94 "Flebite/tromboflebite"
* #X16 "Sinais/sintomas da vulva"
* #K93 "Embolia pulmonar"
* #X15 "Sinais/sintomas da vagina"
* #K92 "Aterosclerose/doença vascular periférica"
* #X14 "Secreção vaginal"
* #K91 "Doença vascular cerebral"
* #X13 "Hemorragia pós-coital"
* #K90 "Trombose/acidente vascular cerebral"
* #X12 "Hemorragia pós-menopausa"
* #K89 "Isquêmia/ acidente cerebral transitória(o)"
* #X11 "Sinais/sintomas da menopausa/ climatério"
* #K88 "Hipotensão postural"
* #X10 "Desejo de alterar a data menstruação"
* #K87 "Hipertensão com complicações"
* #X09 "Sinais/sintomas pré-menstruais"
* #X08 "Hemorragia intermenstrual"
* #K86 "Hipertensão sem complicações"
* #X07 "Menstruação irregular/frequente"
* #K85 "Pressão arterial elevada"
* #X06 "Menstruação excessiva"
* #K84 "Outras doenças cardíacas"
* #X05 "Menstruação escassa/ausente"
* #K83 "Doença valvular cardíaca NE"
* #X04 "Relação sexual dolorosa na mulher"
* #K82 "Doença cardiopulmonar"
* #X03 "Dores intermenstruais"
* #K81 "Sopro cardíaco/arterial NE"
* #X02 "Dores menstruais"
* #K80 "Arritmia cardíaca NE"
* #X01 "Dor genital"
* #K79 "Taquicardia Paroxística"
* #W99 "Outros problemas da gravidez/parto"
* #K78 "Fibrilação/flutter auricular/ atrial"
* #W96 "Outras complicações do puerpério"
* #K77 "Insuficiência cardíaca"
* #W95 "Outros problemas da mama durante gravidez/puerpério"
* #K76 "Doença cardíaca isquémica sem angina"
* #W94 "Mastite puerperal"
* #K75 "Infarto ou Enfarte agudo miocárdio"
* #W93 "Parto com complicações de natimorto"
* #K74 "Doença cardíaca isquémica com angina"
* #W92 "Parto com complicações de nascido vivo"
* #K73 "Malformações congênitas do aparelho circulatório"
* #W91 "Parto sem complicações de natimorto"
* #K72 "Neoplasia do aparelho circulatório"
* #W90 "Parto sem complicações de nascido vivo"
* #K71 "Febre reumática/cardiopatia"
* #W85 "Diabetes gestacional"
* #K70 "Doença infecciosa do aparelho circulatório"
* #W84 "Gravidez de alto risco"
* #K29 "Outros sinais/sintomas cardiovasculares"
* #W83 "Aborto provocado"
* #K28 "Limitação funcional/incapacidade"
* #W82 "Aborto espontâneo"
* #K27 "Medo de outra doença cardiovascular"
* #W81 "Toxemia gravídica/ DHEG"
* #K25 "Medo de hipertensão"
* #W80 "Gravidez ectópica"
* #K24 "Medo de doença cardíaca"
* #W79 "Gravidez não desejada"
* #W78 "Gravidez"
* #K22 "Fator de risco para doença cardiovascular"
* #W76 "Malformação congénita que complica a gravidez"
* #K07 "Tornozelos inchados/edema"
* #W75 "Lesões traumáticas que complicam a gravidez"
* #K06 "Veias proeminentes"
* #K05 "Outras irregularidades dos batimentos cardíacos"
* #W73 "Neoplasia benigna/incerta relacionada com a gravidez"
* #K04 "Palpitações/percepção dos batimentos cardíacos"
* #W72 "Neoplasia maligna relacionada com gravidez"
* #K03 "Dores atribuídas ao aparelho circulatório NE"
* #W71 "Infecções que complicam a gravidez"
* #K02 "Sensação de pressão/aperto atribuída ao coração"
* #W70 "Sepsis/infecção puerperal"
* #K01 "Dor atribuída ao coração"
* #W29 "Sinais/sintomas da gravidez, outros"
* #H99 "Outra doença do ouvido/mastóide"
* #W28 "Limitação funcional/incapacidade"
* #H86 "Surdez"
* #W27 "Medo de complicações na gravidez"
* #H85 "Lesão acústica"
* #W21 "Preocupação com a imagem corporal na gravidez"
* #H84 "Presbiacusia"
* #W19 "Sinais/sintomas da mama/lactação"
* #W18 "Sinais/sintomas pós-parto"
* #H83 "Otoesclerose"
* #W17 "Hemorragia pós-parto"
* #H82 "Síndrome vertiginosa"
* #H81 "Cerúmen no ouvido em excesso"
* #W15 "Infertilidade/subfertildade"
* #H80 "Malformações congênitas do ouvido"
* #W14 "Contracepção/outros"
* #H79 "Outros traumatismos do ouvido"
* #W13 "Esterilização"
* #W12 "Contracepção intra-uterina/ Dispositivo Intrauterino/ DIU"
* #H78 "Traumatismo superficial do ouvido"
* #W11 "Contracepção oral"
* #H77 "Perfuração do tímpano"
* #H76 "Corpo estranho do ouvido"
* #W10 "Contracepção pós-coital"
* #W05 "Vómitos/náuseas durante a gravidez"
* #H75 "Neoplasia do ouvido"
* #W03 "Hemorragia antes do parto"
* #H74 "Otite media crónica"
* #W02 "Medo de estar grávida"
* #H73 "Infecção da Trompa de Eustáquio"
* #H72 "Otite média serosa"
* #W01 "Questão sobre gravidez"
* #U99 "Outras doenças urinárias"
* #H71 "Otite media aguda/miringite"
* #U98 "Análise de urina anormal NE"
* #H70 "Otite externa"
* #U95 "Cálculo urinário"
* #H29 "Outros sinais/sintomas ouvido"
* #U90 "Albuminúria/proteinúria ortostática"
* #H28 "Limitação funcional/incapacidade"
* #U88 "Glomerulonefrite/ sindrome nefrótica"
* #H27 "Medo de doença do ouvido"
* #U85 "Malformação congénita do aparelho urinário"
* #H15 "Preocupação com a aparência das orelhas"
* #U80 "Lesões traumáticas do aparelho urinário"
* #H13 "Sensação de ouvido tapado"
* #U79 "Neoplasia do aparelho urinário NE"
* #H05 "Hemorragia no ouvido"
* #U78 "Neoplasia benigna do aparelho urinário"
* #H04 "Secreção no ouvido"
* #U77 "Neoplasia maligna do aparelho urinário, outra"
* #H03 "Acufeno, zumbidos, ruído, assobios"
* #U76 "Neoplasia benigna do rim"
* #H02 "Problemas de audição"
* #U75 "Neoplasia maligna do rim"
* #H01 "Dor de ouvidos"
* #U72 "Uretrite"
* #F99 "Outra doenças oculares/anexos"
* #U71 "Cistite/outra infecção urinária"
* #F95 "Estrabismo"
* #U70 "Pielonefrite"
* #F94 "Cegueira"
* #U29 "Sinais/sintomas aparelho urinário, outros"
* #F93 "Glaucoma"
* #U28 "Limitação funcional/incapacidade"
* #F92 "Catarata"
* #U27 "Medo de outra doença urinária"
* #F91 "Erro de refração"
* #U26 "Medo de câncer no aparelho urinário"
* #F86 "Tracoma"
* #U14 "Sinais/sintomas dos rins"
* #U13 "Sinais/sintomas da bexiga, outros"
* #F85 "Ulcera da córnea"
* #F84 "Degeneração macular"
* #U08 "Retenção urinária"
* #U07 "Outros sinais/sintomas urinários"
* #F83 "Retinopatia"
* #U06 "Hematúria"
* #F82 "Descolamento da retina"
* #U05 "Outros problemas com a micção"
* #F81 "Outras malformações congênitas do olho"
* #U04 "Incontinência urinária"
* #F80 "Obstrução canal lacrimal da criança"
* #U02 "Micção frequente/urgência urinária/ polaciúria"
* #U01 "Disúria/micção dolorosa"
* #F79 "Outras lesões traumáticas oculares"
* #T99 "Outras doenças endocrinológica/metabólica/nutricionais"
* #F76 "Corpo estranho ocular"
* #T93 "Alteração no metabolismo dos lípidos"
* #F75 "Contusão/hemorragia ocular"
* #T92 "Gota"
* #F74 "Neoplasia do olho/anexos"
* #F73 "Outras infecções/inflamações oculares"
* #T91 "Deficiência vitamínica/nutricional"
* #F72 "Blefarite/hordéolo/calázio"
* #T90 "Diabetes não insulino-dependente"
* #F71 "Conjuntivite alérgica"
* #T89 "Diabetes insulino-dependente"
* #F70 "Conjuntivite infecciosa"
* #T87 "Hipoglicemia"
* #F29 "Outros sinais/sintomas oculares"
* #T86 "Hipotiroidismo/mixedema"
* #F28 "Limitação funcional/incapacidade"
* #T85 "Hipertiroidismo/tireotoxicose"
* #F27 "Medo de doença ocular"
* #T83 "Excesso de peso"
* #F18 "Sinais/sintomas relacionados a lentes de contato"
* #T82 "Obesidade"
* #F17 "Sinais/sintomas relacionados a óculos"
* #T81 "Bócio"
* #F16 "Sinais/sintomas das pálpebras"
* #T80 "Malformação congénita endócrina/metabólica"
* #F15 "Aparência anormal nos olhos"
* #T78 "Cisto do canal tiroglosso"
* #F14 "Movimentos oculares anormais"
* #T73 "Outra neoplasia endócrina NE"
* #F13 "Sensações oculares anormais"
* #T72 "Neoplasia benigna da tiróide"
* #F05 "Outras perturbações visuais"
* #T71 "Neoplasia maligna da tiróide"
* #F04 "Moscas volantes/pontos luminosos/escotomas/ manchas"
* #T70 "Infecção endócrina"
* #F03 "Secreção ocular"
* #T29 "Sinais/sintomas endocrinológicos/metabolicos/nutricionais, outros"
* #F02 "Olho vermelho"
* #T28 "Limitação funcional/incapacidade"
* #F01 "Dor no olho"
* #T27 "Medo de outra doença endócrina/metabólica"
* #D99 "Outra doença do aparelho digestivo"
* #T26 "Medo de câncer do sistema endócrino"
* #D98 "Colecistite, colelitiase"
* #T11 "Desidratação"
* #D97 "Doenças do fígado /NE"
* #T10 "Atraso do crescimento"
* #D96 "Lombrigas /outros parasitas"
* #T08 "Perda de peso"
* #D95 "Fissura anal / abcesso perianal"
* #T07 "Aumento de peso"
* #D94 "Enterite crónica/colite ulcerosa"
* #T05 "Problemas alimentares do adulto"
* #D93 "Síndrome do cólon irritável"
* #T04 "Problemas alimentares de lactente/criança"
* #D92 "Doença diverticular intestinal"
* #T03 "Perda de apetite"
* #D91 "Hérnia abdominal, outras"
* #T02 "Apetite excessivo"
* #D90 "Hérnia de hiato /diafragmática"
* #T01 "Sede excessiva"
* #D89 "Hérnia inguinal"
* #S99 "Outras doenças da pele"
* #D88 "Apendicite"
* #S98 "Urticária"
* #S97 "Úlcera crónica da pele"
* #D87 "Alterações funcionais estômago"
* #D86 "Úlcera péptica, outra"
* #S96 "Acne"
* #D85 "Úlcera do duodeno"
* #S95 "Molusco contagioso"
* #D84 "Doença do esôfago"
* #S94 "Unha encravada"
* #D83 "Doença da boca/língua/lábios"
* #S93 "Cisto sebáceo"
* #D82 "Doença dos dentes/gengivas"
* #S92 "Doença das glândulas sudoríparas"
* #D81 "Malformações congênitas do aparelho digestivo"
* #S91 "Psoríase"
* #S90 "Pitiríase rosada"
* #D80 "Outras lesões traumáticas"
* #S89 "Dermatite das fraldas"
* #D79 "Corpo estranho no aparelho digestivo"
* #S88 "Dermatite de contato/alérgica"
* #D78 "Neoplasia benigna do aparelho digestivo/incerta"
* #S87 "Dermatite/eczema atópico"
* #D77 "Neoplasia maligna do aparelho digestivo NE"
* #S86 "Dermatite seborreica"
* #D76 "Neoplasia maligna do pâncreas"
* #S85 "Cisto pilonidal/fistula"
* #D75 "Neoplasia maligna do cólon/reto"
* #S84 "Impetigo"
* #D74 "Neoplasia maligna do estômago"
* #S83 "Lesões da pele congênitas, outras"
* #D73 "Gastroenterite, presumível infecção"
* #S82 "Nevos/sinais da pele"
* #D72 "Hepatite viral"
* #S81 "Hemangioma/linfangioma"
* #D71 "Caxumba/parotidite epidêmica"
* #S80 "Ceratose/ Queratose solar/queimadura solar"
* #D70 "Infecção gastrointestinal"
* #S79 "Neoplasia cutânea benigna/incerta"
* #D29 "Outros sinais/sintomas digestivos"
* #S78 "Lipoma"
* #D28 "Limitação funcional/incapacidade"
* #S77 "Neoplasias malignas da pele"
* #D27 "Medo de outras doenças aparelho digestivo"
* #S76 "Outras infecções da pele"
* #D26 "Medo de câncer no aparelho digestivo"
* #S75 "Monilíase oral/candidíase na pele"
* #D25 "Distensão abdominal"
* #S74 "Dermatofitose"
* #D24 "Massa abdominal NE"
* #S73 "Pediculose/outras infecções da pele"
* #D23 "Hepatomegalia"
* #S72 "Escabiose/outras acaríases"
* #D21 "Problemas de deglutição"
* #S71 "Herpes simples"
* #D20 "Sinais/sintomas da boca/língua/lábios"
* #S70 "Herpes zoster"
* #D19 "Sinais/sintomas dos dentes/gengivas"
* #S29 "Sinais/sintomas da pele, outros"
* #D18 "Alterações nas fezes/mov. intestinais"
* #S28 "Limitação funcional/incapacidade"
* #D17 "Incontinência fecal"
* #S27 "Medo de outra doença da pele"
* #D16 "Hemorragia retal"
* #S26 "Medo de câncer de pele"
* #D15 "Melena"
* #D14 "Hematêmese/vómito sangue"
* #S24 "Sinais/sintomas do cabelo/couro cabeludo"
* #D13 "Icterícia"
* #S23 "Queda de cabelo/calvície"
* #D12 "Obstipação"
* #S22 "Sinais/sintomas das unhas"
* #S21 "Sinais/sintomas da textura da pele"
* #D11 "Diarreia"
* #S20 "Calos/calosidades"
* #D10 "Vomito"
* #S19 "Outra lesão cutânea"
* #D09 "Náusea"
* #S18 "Laceração/corte"
* #D08 "Flatulência /gases/eructações"
* #S17 "Abrasão/arranhão/bolhas"
* #D07 "Dispepsia/indigestão"
* #S16 "Traumatismo/contusão"
* #D06 "Outras dores abdominais localizadas"
* #S15 "Corpo estranho na pele"
* #D05 "Irritação perianal"
* #S14 "Queimadura/escaldão"
* #D04 "Dor anal/retal"
* #S13 "Mordedura animal/humana"
* #D03 "Azia/ Queimação"
* #S12 "Picada ou mordedura de inseto"
* #D02 "Dores abdominais, epigástricas"
* #S11 "Infecção pós-traumática da pele"
* #D01 "Dor abdominal generalizada/cólicas"
* #S10 "Furúnculo/carbúnculo"
* #B99 "Outra doença do sangue/linfáticos/baço"
* #S09 "Infecção dos dedos das mãos/pés"
* #B90 "Infecção por VIH/ HIV/SIDA/ AIDS"
* #S08 "Alterações da cor da pele"
* #B87 "Esplenomegalia"
* #S07 "Erupção cutânea generalizada"
* #B84 "Glóbulos brancos anormais"
* #S06 "Erupção cutânea localizada"
* #B83 "Púrpura/defeitos de coagulação"
* #S05 "Tumores/inchaços generalizados"
* #B82 "Outras anemias NE"
* #S04 "Tumor/inchaço localizado"
* #B81 "Anemia perniciosa/deficiência de folatos"
* #S03 "Verrugas"
* #B80 "Anemia por deficiência de ferro"
* #S02 "Prurido"
* #B79 "Outra malformação congênita do sangue/linfática"
* #S01 "Dor/sensibilidade dolorosa da pele"
* #B78 "Anemia hemolítica hereditária"
* #R99 "Outras doenças respiratórias"
* #R98 "Síndrome de hiperventilação"
* #B77 "Outras lesões traumáticas do sangue/linfa/baço"
* #R97 "Rinite alérgica"
* #B76 "Rotura traumática do baço"
* #R96 "Asma"
* #B75 "Neoplasia benigna NE"
* #R95 "Doença pulmonar obstrutiva crónica"
* #B74 "Outra neoplasia maligna no sangue"
* #R92 "Neoplasia respiratória NE"
* #B73 "Leucemia"
* #R90 "Hipertrofia das amígdalas/adenóides"
* #B72 "Doença de Hodgkin/linfomas"
* #R89 "Malformação congénita do aparelho respiratório"
* #B71 "Linfadenite crónica NE"
* #R88 "Outra lesão respiratória"
* #B70 "Linfadenite aguda"
* #R87 "Corpo estranho nariz/laringe/brônquios"
* #B29 "Outros sinais/ sintomas do sangue/ sistema linfático/ baço NE"
* #R86 "Neoplasia benigna respiratória"
* #B28 "Limitação funcional/incapacidade"
* #R85 "Outra neoplasia respiratória maligna"
* #B27 "Medo de outras doenças do sangue /vasos linfáticos"
* #R84 "Neoplasia maligna dos brônquios/pulmão"
* #B26 "Medo de câncer no sangue/linfático"
* #R83 "Outra infecção respiratória"
* #R82 "Pleurite/derrame pleural"
* #B25 "Medo de VIH/ HIV/SIDA/ AIDS"
* #R81 "Pneumonia"
* #B04 "Sinais/sintomas sangue"
* #R80 "Gripe"
* #R79 "Bronquite crônica"
* #B02 "Gânglio linfático aumentado/doloroso"
* #R78 "Bronquite/bronquiolite aguda"
* #R77 "Laringite/traqueíte aguda"
* #R76 "Amigdalite aguda"
* #A98 "Medicina preventiva/manutenção da saúde"
* #R75 "Sinusite crónica/aguda"
* #A97 "Sem doença"
* #R74 "Infecção aguda do aparelho respiratório superior (IVAS)"
* #A96 "Morte"
* #R73 "Abcesso/furúnculo no nariz"
* #A95 "Mortalidade perinatal"
* #R72 "Infecção estreptocócica da orofaringe"
* #A94 "Morbidade perinatal, outra"
* #R71 "Tosse convulsa/ pertussis"
* #R29 "Sinais/sintomas do aparelho respiratório, outros"
* #A92 "Alergia/reação alérgica NE"
* #R28 "Limitação funcional/incapacidade"
* #A91 "Investigação com resultado anormal NE"
* #R27 "Medo de outras doenças respiratórias"
* #A90 "Malformação congênita NE/múltiplas"
* #R26 "Medo de câncer do aparelho respiratório"
* #A89 "Efeito da prótese"
* #R25 "Expectoração/mucosidade anormal"
* #A88 "Efeito adverso de fator físico"
* #R24 "Hemoptise"
* #A87 "Complicações de tratamento médico"
* #R23 "Sinais/sintomas da voz"
* #A86 "Efeito tóxico de substância não medicinal"
* #R21 "Sinais/sintomas da garganta"
* #A85 "Efeito adverso de fármaco dose correta"
* #R09 "Sinais/sintomas dos seios paranasais"
* #A84 "Intoxicação por medicamento"
* #R08 "Outros sinais/sintomas nasais"
* #A82 "Efeito secundário de lesão traumática"
* #R07 "Espirro/congestão nasal"
* #A81 "Politraumatismos/ferimentos múltiplos"
* #R06 "Hemorragia nasal/epistaxe"
* #A80 "Lesão traumática/acidente NE"
* #R05 "Tosse"
* #A79 "Carcinomatose (localização primária desconhecida)"
* #R04 "Outros problemas respiratórios"
* #A78 "Hanseníase e outras doenças infecciosas NE"
* #R03 "Respiração ruidosa"
* #A77 "Dengue e outras doenças virais NE"
* #R02 "Dificuldade respiratória, dispneia"
* #A76 "Outro exantema viral"
* #R01 "Dor atribuída ao aparelho respiratório"
* #A75 "Mononucleose infecciosa"
* #P99 "Outras perturbações psicológicas"
* #A74 "Rubéola"
* #P98 "Outras psicoses NE"
* #A73 "Malária"
* #P86 "Anorexia nervosa, bulimia"
* #A72 "Varicela"
* #P85 "Retardo/ Atraso mental"
* #A71 "Sarampo"
* #P82 "Estresse pós traumático"
* #A70 "Tuberculose"
* #P81 "Perturbação hipercinética"
* #A29 "Outros sinais/sintomas gerais"
* #P80 "Perturbações de personalidade"
* #A28 "Limitação funcional/incapacidade NE"
* #P79 "Fobia/perturbação compulsiva"
* #A27 "Medo de outra doença NE"
* #P78 "Neurastenia"
* #A26 "Medo de câncer NE"
* #P77 "Suicídio/tentativa de suicídio"
* #A25 "Medo de morrer/medo da morte"
* #P76 "Perturbações depressivas"
* #A23 "Fator de risco NE"
* #P75 "Somatização"
* #A21 "Fator de risco de malignidade"
* #P74 "Distúrbio ansioso/estado de ansiedade"
* #A20 "Pedido/discussão eutanásia"
* #P73 "Psicose afetiva"
* #A18 "Preocupação com aparência"
* #P72 "Esquizofrenia"
* #A16 "Criança irritável"
* #P71 "Outras psicoses orgânicas NE"
* #A13 "Receio/Medo do tratamento"
* #P70 "Demência"
* #P29 "Sinais/sintomas psicológicos, outros"
* #A11 "Dores torácicas NE"
* #A10 "Sangramento/Hemorragia NE"
* #P28 "Limitação funcional/incapacidade"
* #P27 "Medo de perturbações mentais"
* #A09 "Problemas de sudorese"
* #P25 "Problemas da fase de vida de adulto"
* #A08 "Inchaço"
* #P24 "Dificuldades especificas de aprendizagem"
* #A07 "Coma"
* #P23 "Sinais/sintomas relacionados ao comportamento do adolescente"
* #A06 "Desmaio/síncope"
* #P22 "Sinais/sintomas relacionados ao comportamento da criança"
* #A05 "Sentir-se doente"
* #P20 "Alterações da memória"
* #A04 "Debilidade/cansaço geral/fadiga"
* #A03 "Febre"
* #P19 "Abuso de drogas"
* #A02 "Arrepios/ calafrios"
* #P18 "Abuso de medicação"
* #A01 "Dor generalizada /múltipla"
* #P17 "Abuso do tabaco"