CodeSystem: BRConselhoProfissional
Id: BRConselhoProfissional
Title: "Conselhos profissionais de saúde do Brasil"
Description: "Esse CodeSystem inclui os conselhos profissionais de saúde do Brasil, conforme a Resolução CNS 251/1997."
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablecodesystem"
* ^identifier.system = "https://saude.gov.br/fhir/sid/codesystem"
* ^identifier.value = "BRConselhoProfissional"
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = true
* ^date = "2023-07-18T10:05:57-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* ^caseSensitive = true
* ^content = #complete
* ^count = 197
* #https://saude.gov.br/fhir/sid/crf-ac "CRF-AC" "Conselho Regional de Farmácia do Estado do Acre."
* #https://saude.gov.br/fhir/sid/crf-al "CRF-AL" "Conselho Regional de Farmácia do Estado de Alagoas."
* #https://saude.gov.br/fhir/sid/crf-am "CRF-AM" "Conselho Regional de Farmácia do Estado de Amazonas."
* #https://saude.gov.br/fhir/sid/crf-ap "CRF-AP" "Conselho Regional de Farmácia do Estado do Amapá."
* #https://saude.gov.br/fhir/sid/crf-ba "CRF-BA" "Conselho Regional de Farmácia do Estado da Bahia."
* #https://saude.gov.br/fhir/sid/crf-ce "CRF-CE" "Conselho Regional de Farmácia do Estado do Ceará."
* #https://saude.gov.br/fhir/sid/crf-df "CRF-DF" "Conselho Regional de Farmácia do Distrito Federal."
* #https://saude.gov.br/fhir/sid/crf-es "CRF-ES" "Conselho Regional de Farmácia do Estado do Espírito Santo."
* #https://saude.gov.br/fhir/sid/crf-go "CRF-GO" "Conselho Regional de Farmácia do Estado de Goiás."
* #https://saude.gov.br/fhir/sid/crf-ma "CRF-MA" "Conselho Regional de Farmácia do Estado do Maranhão."
* #https://saude.gov.br/fhir/sid/crf-mg "CRF-MG" "Conselho Regional de Farmácia do Estado de Minas Gerais."
* #https://saude.gov.br/fhir/sid/crf-ms "CRF-MS" "Conselho Regional de Farmácia do Estado de Mato Grosso do Sul."
* #https://saude.gov.br/fhir/sid/crf-mt "CRF-MT" "Conselho Regional de Farmácia do Estado de Mato Grosso."
* #https://saude.gov.br/fhir/sid/crf-pa "CRF-PA" "Conselho Regional de Farmácia do Estado do Pará."
* #https://saude.gov.br/fhir/sid/crf-pb "CRF-PB" "Conselho Regional de Farmácia do Estado da Paraíba."
* #https://saude.gov.br/fhir/sid/crf-pe "CRF-PE" "Conselho Regional de Farmácia do Estado de Pernambuco."
* #https://saude.gov.br/fhir/sid/crf-pi "CRF-PI" "Conselho Regional de Farmácia do Estado do Piauí."
* #https://saude.gov.br/fhir/sid/crf-pr "CRF-PR" "Conselho Regional de Farmácia do Estado do Paraná."
* #https://saude.gov.br/fhir/sid/crf-rj "CRF-RJ" "Conselho Regional de Farmácia do Estado do Rio de Janeiro."
* #https://saude.gov.br/fhir/sid/crf-rn "CRF-RN" "Conselho Regional de Farmácia do Estado do Rio Grande do Norte."
* #https://saude.gov.br/fhir/sid/crf-ro "CRF-RO" "Conselho Regional de Farmácia do Estado de Rondônia."
* #https://saude.gov.br/fhir/sid/crf-rr "CRF-RR" "Conselho Regional de Farmácia do Estado de Roraima."
* #https://saude.gov.br/fhir/sid/crf-rs "CRF-RS" "Conselho Regional de Farmácia do Estado do Rio Grande do Sul."
* #https://saude.gov.br/fhir/sid/crf-sc "CRF-SC" "Conselho Regional de Farmácia do Estado de Santa Catarina."
* #https://saude.gov.br/fhir/sid/crf-se "CRF-SE" "Conselho Regional de Farmácia do Estado de Sergipe."
* #https://saude.gov.br/fhir/sid/crf-sp "CRF-SP" "Conselho Regional de Farmácia do Estado de São Paulo."
* #https://saude.gov.br/fhir/sid/crf-to "CRF-TO" "Conselho Regional de Farmácia do Estado de Tocantins."
* #https://saude.gov.br/fhir/sid/cro-ac "CRO-AC" "Conselho Regional de Odontologia do Estado do Acre."
* #https://saude.gov.br/fhir/sid/cro-al "CRO-AL" "Conselho Regional de Odontologia do Estado de Alagoas."
* #https://saude.gov.br/fhir/sid/cro-am "CRO-AM" "Conselho Regional de Odontologia do Estado de Amazonas."
* #https://saude.gov.br/fhir/sid/cro-ap "CRO-AP" "Conselho Regional de Odontologia do Estado do Amapá."
* #https://saude.gov.br/fhir/sid/cro-ba "CRO-BA" "Conselho Regional de Odontologia do Estado da Bahia."
* #https://saude.gov.br/fhir/sid/cro-ce "CRO-CE" "Conselho Regional de Odontologia do Estado do Ceará."
* #https://saude.gov.br/fhir/sid/cro-df "CRO-DF" "Conselho Regional de Odontologia do Distrito Federal."
* #https://saude.gov.br/fhir/sid/cro-es "CRO-ES" "Conselho Regional de Odontologia do Estado do Espírito Santo."
* #https://saude.gov.br/fhir/sid/cro-go "CRO-GO" "Conselho Regional de Odontologia do Estado de Goiás."
* #https://saude.gov.br/fhir/sid/cro-ma "CRO-MA" "Conselho Regional de Odontologia do Estado do Maranhão."
* #https://saude.gov.br/fhir/sid/cro-mg "CRO-MG" "Conselho Regional de Odontologia do Estado de Minas Gerais."
* #https://saude.gov.br/fhir/sid/cro-ms "CRO-MS" "Conselho Regional de Odontologia do Estado de Mato Grosso do Sul."
* #https://saude.gov.br/fhir/sid/cro-mt "CRO-MT" "Conselho Regional de Odontologia do Estado de Mato Grosso."
* #https://saude.gov.br/fhir/sid/cro-pa "CRO-PA" "Conselho Regional de Odontologia do Estado do Pará."
* #https://saude.gov.br/fhir/sid/cro-pb "CRO-PB" "Conselho Regional de Odontologia do Estado da Paraíba."
* #https://saude.gov.br/fhir/sid/cro-pe "CRO-PE" "Conselho Regional de Odontologia do Estado de Pernambuco."
* #https://saude.gov.br/fhir/sid/cro-pi "CRO-PI" "Conselho Regional de Odontologia do Estado do Piauí."
* #https://saude.gov.br/fhir/sid/cro-pr "CRO-PR" "Conselho Regional de Odontologia do Estado do Paraná."
* #https://saude.gov.br/fhir/sid/cro-rj "CRO-RJ" "Conselho Regional de Odontologia do Estado do Rio de Janeiro."
* #https://saude.gov.br/fhir/sid/cro-rn "CRO-RN" "Conselho Regional de Odontologia do Estado do Rio Grande do Norte."
* #https://saude.gov.br/fhir/sid/cro-ro "CRO-RO" "Conselho Regional de Odontologia do Estado de Rondônia."
* #https://saude.gov.br/fhir/sid/cro-rr "CRO-RR" "Conselho Regional de Odontologia do Estado de Roraima."
* #https://saude.gov.br/fhir/sid/cro-rs "CRO-RS" "Conselho Regional de Odontologia do Estado do Rio Grande do Sul."
* #https://saude.gov.br/fhir/sid/cro-sc "CRO-SC" "Conselho Regional de Odontologia do Estado de Santa Catarina."
* #https://saude.gov.br/fhir/sid/cro-se "CRO-SE" "Conselho Regional de Odontologia do Estado de Sergipe."
* #https://saude.gov.br/fhir/sid/cro-sp "CRO-SP" "Conselho Regional de Odontologia do Estado de São Paulo."
* #https://saude.gov.br/fhir/sid/cro-to "CRO-TO" "Conselho Regional de Odontologia do Estado de Tocantins."
* #https://saude.gov.br/fhir/sid/coren-ac "COREN-AC" "Conselho Regional de Enfermagem do Estado do Acre."
* #https://saude.gov.br/fhir/sid/coren-al "COREN-AL" "Conselho Regional de Enfermagem do Estado de Alagoas."
* #https://saude.gov.br/fhir/sid/coren-am "COREN-AM" "Conselho Regional de Enfermagem do Estado de Amazonas."
* #https://saude.gov.br/fhir/sid/coren-ap "COREN-AP" "Conselho Regional de Enfermagem do Estado do Amapá."
* #https://saude.gov.br/fhir/sid/coren-ba "COREN-BA" "Conselho Regional de Enfermagem do Estado da Bahia."
* #https://saude.gov.br/fhir/sid/coren-ce "COREN-CE" "Conselho Regional de Enfermagem do Estado do Ceará."
* #https://saude.gov.br/fhir/sid/coren-df "COREN-DF" "Conselho Regional de Enfermagem do Distrito Federal."
* #https://saude.gov.br/fhir/sid/coren-es "COREN-ES" "Conselho Regional de Enfermagem do Estado do Espírito Santo."
* #https://saude.gov.br/fhir/sid/coren-go "COREN-GO" "Conselho Regional de Enfermagem do Estado de Goiás."
* #https://saude.gov.br/fhir/sid/coren-ma "COREN-MA" "Conselho Regional de Enfermagem do Estado do Maranhão."
* #https://saude.gov.br/fhir/sid/coren-mg "COREN-MG" "Conselho Regional de Enfermagem do Estado de Minas Gerais."
* #https://saude.gov.br/fhir/sid/coren-ms "COREN-MS" "Conselho Regional de Enfermagem do Estado de Mato Grosso do Sul."
* #https://saude.gov.br/fhir/sid/coren-mt "COREN-MT" "Conselho Regional de Enfermagem do Estado de Mato Grosso."
* #https://saude.gov.br/fhir/sid/coren-pa "COREN-PA" "Conselho Regional de Enfermagem do Estado do Pará."
* #https://saude.gov.br/fhir/sid/coren-pb "COREN-PB" "Conselho Regional de Enfermagem do Estado da Paraíba."
* #https://saude.gov.br/fhir/sid/coren-pe "COREN-PE" "Conselho Regional de Enfermagem do Estado de Pernambuco."
* #https://saude.gov.br/fhir/sid/coren-pi "COREN-PI" "Conselho Regional de Enfermagem do Estado do Piauí."
* #https://saude.gov.br/fhir/sid/coren-pr "COREN-PR" "Conselho Regional de Enfermagem do Estado do Paraná."
* #https://saude.gov.br/fhir/sid/coren-rj "COREN-RJ" "Conselho Regional de Enfermagem do Estado do Rio de Janeiro."
* #https://saude.gov.br/fhir/sid/coren-rn "COREN-RN" "Conselho Regional de Enfermagem do Estado do Rio Grande do Norte."
* #https://saude.gov.br/fhir/sid/coren-ro "COREN-RO" "Conselho Regional de Enfermagem do Estado de Rondônia."
* #https://saude.gov.br/fhir/sid/coren-rr "COREN-RR" "Conselho Regional de Enfermagem do Estado de Roraima."
* #https://saude.gov.br/fhir/sid/coren-rs "COREN-RS" "Conselho Regional de Enfermagem do Estado do Rio Grande do Sul."
* #https://saude.gov.br/fhir/sid/coren-sc "COREN-SC" "Conselho Regional de Enfermagem do Estado de Santa Catarina."
* #https://saude.gov.br/fhir/sid/coren-se "COREN-SE" "Conselho Regional de Enfermagem do Estado de Sergipe."
* #https://saude.gov.br/fhir/sid/coren-sp "COREN-SP" "Conselho Regional de Enfermagem do Estado de São Paulo."
* #https://saude.gov.br/fhir/sid/coren-to "COREN-TO" "Conselho Regional de Enfermagem do Estado de Tocantins."
* #https://saude.gov.br/fhir/sid/crm-ac "CRM-AC" "Conselho Regional de Medicina do Estado do Acre."
* #https://saude.gov.br/fhir/sid/crm-al "CRM-AL" "Conselho Regional de Medicina do Estado de Alagoas."
* #https://saude.gov.br/fhir/sid/crm-am "CRM-AM" "Conselho Regional de Medicina do Estado de Amazonas."
* #https://saude.gov.br/fhir/sid/crm-ap "CRM-AP" "Conselho Regional de Medicina do Estado do Amapá."
* #https://saude.gov.br/fhir/sid/crm-ba "CRM-BA" "Conselho Regional de Medicina do Estado da Bahia."
* #https://saude.gov.br/fhir/sid/crm-ce "CRM-CE" "Conselho Regional de Medicina do Estado do Ceará."
* #https://saude.gov.br/fhir/sid/crm-df "CRM-DF" "Conselho Regional de Medicina do Distrito Federal."
* #https://saude.gov.br/fhir/sid/crm-es "CRM-ES" "Conselho Regional de Medicina do Estado do Espírito Santo."
* #https://saude.gov.br/fhir/sid/crm-go "CRM-GO" "Conselho Regional de Medicina do Estado de Goiás."
* #https://saude.gov.br/fhir/sid/crm-ma "CRM-MA" "Conselho Regional de Medicina do Estado do Maranhão."
* #https://saude.gov.br/fhir/sid/crm-mg "CRM-MG" "Conselho Regional de Medicina do Estado de Minas Gerais."
* #https://saude.gov.br/fhir/sid/crm-ms "CRM-MS" "Conselho Regional de Medicina do Estado de Mato Grosso do Sul."
* #https://saude.gov.br/fhir/sid/crm-mt "CRM-MT" "Conselho Regional de Medicina do Estado de Mato Grosso."
* #https://saude.gov.br/fhir/sid/crm-pa "CRM-PA" "Conselho Regional de Medicina do Estado do Pará."
* #https://saude.gov.br/fhir/sid/crm-pb "CRM-PB" "Conselho Regional de Medicina do Estado da Paraíba."
* #https://saude.gov.br/fhir/sid/crm-pe "CRM-PE" "Conselho Regional de Medicina do Estado de Pernambuco."
* #https://saude.gov.br/fhir/sid/crm-pi "CRM-PI" "Conselho Regional de Medicina do Estado do Piauí."
* #https://saude.gov.br/fhir/sid/crm-pr "CRM-PR" "Conselho Regional de Medicina do Estado do Paraná."
* #https://saude.gov.br/fhir/sid/crm-rj "CRM-RJ" "Conselho Regional de Medicina do Estado do Rio de Janeiro."
* #https://saude.gov.br/fhir/sid/crm-rn "CRM-RN" "Conselho Regional de Medicina do Estado do Rio Grande do Norte."
* #https://saude.gov.br/fhir/sid/crm-ro "CRM-RO" "Conselho Regional de Medicina do Estado de Rondônia."
* #https://saude.gov.br/fhir/sid/crm-rr "CRM-RR" "Conselho Regional de Medicina do Estado de Roraima."
* #https://saude.gov.br/fhir/sid/crm-rs "CRM-RS" "Conselho Regional de Medicina do Estado do Rio Grande do Sul."
* #https://saude.gov.br/fhir/sid/crm-sc "CRM-SC" "Conselho Regional de Medicina do Estado de Santa Catarina."
* #https://saude.gov.br/fhir/sid/crm-se "CRM-SE" "Conselho Regional de Medicina do Estado de Sergipe."
* #https://saude.gov.br/fhir/sid/crm-sp "CRM-SP" "Conselho Regional de Medicina do Estado de São Paulo."
* #https://saude.gov.br/fhir/sid/crm-to "CRM-TO" "Conselho Regional de Medicina do Estado de Tocantins."
* #https://saude.gov.br/fhir/sid/crp-ac-ro "CRP-AC-RO" "Conselho Regional de Psicologia da 24ª Região (AC/RO)."
* #https://saude.gov.br/fhir/sid/crp-al "CRP-AL" "Conselho Regional de Psicologia da 15ª Região (AL)."
* #https://saude.gov.br/fhir/sid/crp-am-rr "CRP-AM-RR" "Conselho Regional de Psicologia da 20ª Região (AM/RR)."
* #https://saude.gov.br/fhir/sid/crp-ba "CRP-BA" "Conselho Regional de Psicologia da 3ª Região (BA)."
* #https://saude.gov.br/fhir/sid/crp-ce "CRP-CE" "Conselho Regional de Psicologia da 11ª Região (CE)."
* #https://saude.gov.br/fhir/sid/crp-df "CRP-DF" "Conselho Regional de Psicologia da 1ª Região (DF)."
* #https://saude.gov.br/fhir/sid/crp-es "CRP-ES" "Conselho Regional de Psicologia da 16ª Região (ES)."
* #https://saude.gov.br/fhir/sid/crp-go "CRP-GO" "Conselho Regional de Psicologia da 9ª Região (GO)."
* #https://saude.gov.br/fhir/sid/crp-ma "CRP-MA" "Conselho Regional de Psicologia da 22ª Região (MA)."
* #https://saude.gov.br/fhir/sid/crp-mg "CRP-MG" "Conselho Regional de Psicologia da 4ª Região (MG)."
* #https://saude.gov.br/fhir/sid/crp-ms "CRP-MS" "Conselho Regional de Psicologia da 14ª Região (MS)."
* #https://saude.gov.br/fhir/sid/crp-mt "CRP-MT" "Conselho Regional de Psicologia da 18ª Região (MT)."
* #https://saude.gov.br/fhir/sid/crp-pa-ap "CRP-PA-AP" "Conselho Regional de Psicologia da 10ª Região (PA/AP)."
* #https://saude.gov.br/fhir/sid/crp-pb "CRP-PB" "Conselho Regional de Psicologia da 13ª Região (PB)."
* #https://saude.gov.br/fhir/sid/crp-pe "CRP-PE" "Conselho Regional de Psicologia da 2ª Região (PE)."
* #https://saude.gov.br/fhir/sid/crp-pi "CRP-PI" "Conselho Regional de Psicologia da 21ª Região (PI)."
* #https://saude.gov.br/fhir/sid/crp-pr "CRP-PR" "Conselho Regional de Psicologia da 8ª Região (PR)."
* #https://saude.gov.br/fhir/sid/crp-rj "CRP-RJ" "Conselho Regional de Psicologia da 5ª Região (RJ)."
* #https://saude.gov.br/fhir/sid/crp-rn "CRP-RN" "Conselho Regional de Psicologia da 17ª Região (RN)."
* #https://saude.gov.br/fhir/sid/crp-rs "CRP-RS" "Conselho Regional de Psicologia da 7ª Região (RS)."
* #https://saude.gov.br/fhir/sid/crp-sc "CRP-SC" "Conselho Regional de Psicologia da 12ª Região (SC)."
* #https://saude.gov.br/fhir/sid/crp-se "CRP-SE" "Conselho Regional de Psicologia da 19ª Região (SE)."
* #https://saude.gov.br/fhir/sid/crp-sp "CRP-SP" "Conselho Regional de Psicologia da 6ª Região (SP)."
* #https://saude.gov.br/fhir/sid/crp-to "CRP-TO" "Conselho Regional de Psicologia da 23ª Região (TO)."
* #https://saude.gov.br/fhir/sid/crefito-ba "CREFITO-BA" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 7ª Região (BA)."
* #https://saude.gov.br/fhir/sid/crefito-ce "CREFITO-CE" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 6ª Região (CE)."
* #https://saude.gov.br/fhir/sid/crefito-es "CREFITO-ES" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 15ª Região (ES)."
* #https://saude.gov.br/fhir/sid/crefito-go-df "CREFITO-GO-DF" "Conselhos Regionais de Fisioterapia e Terapia Ocupacional da 11ª Região (DF) e da 19ª Região (GO)."
* #https://saude.gov.br/fhir/sid/crefito-ma "CREFITO-MA" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 16ª Região (MA)."
* #https://saude.gov.br/fhir/sid/crefito-mg "CREFITO-MG" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 4ª Região (MG)."
* #https://saude.gov.br/fhir/sid/crefito-ms "CREFITO-MS" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 13ª Região (MS)."
* #https://saude.gov.br/fhir/sid/crefito-mt "CREFITO-MT" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 9ª Região (MT)."
* #https://saude.gov.br/fhir/sid/crefito-pa-am-to-rr-ap "CREFITO-PA-AM-TO-RR-AP" "Conselhos Regionais de Fisioterapia e Terapia Ocupacional da 12ª Região (PA/TO/AP) e da 20ª Região (AM/RR)."
* #https://saude.gov.br/fhir/sid/crefito-pe-pb-al-rn "CREFITO-PE-PB-AL-RN" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 1ª Região (PE/PB/AL/RN)."
* #https://saude.gov.br/fhir/sid/crefito-pi "CREFITO-PI" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 14ª Região (PI)."
* #https://saude.gov.br/fhir/sid/crefito-pr "CREFITO-PR" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 8ª Região (PR)."
* #https://saude.gov.br/fhir/sid/crefito-rj "CREFITO-RJ" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 2ª Região (RJ)."
* #https://saude.gov.br/fhir/sid/crefito-ro-ac "CREFITO-RO-AC" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 18ª Região (RO/AC)."
* #https://saude.gov.br/fhir/sid/crefito-rs "CREFITO-RS" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 5ª Região (RS)."
* #https://saude.gov.br/fhir/sid/crefito-sc "CREFITO-SC" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 10ª Região (SC)."
* #https://saude.gov.br/fhir/sid/crefito-se "CREFITO-SE" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 17ª Região (SE)."
* #https://saude.gov.br/fhir/sid/crefito-sp "CREFITO-SP" "Conselho Regional de Fisioterapia e Terapia Ocupacional da 3ª Região (SP)."
* #https://saude.gov.br/fhir/sid/crn-al "CRN-AL" "Conselho Regional de Nutrição da 6ª Região (AL/PB/PE/RN)."
* #https://saude.gov.br/fhir/sid/crn-ba-se "CRN-BA-SE" "Conselho Regional de Nutrição da 5ª Região (BA/SE)."
* #https://saude.gov.br/fhir/sid/crn-ce-ma-pi "CRN-CE-MA_PI" "Conselho Regional de Nutrição da 11ª Região (CE/MA/PI)."
* #https://saude.gov.br/fhir/sid/crn-df-go-mt-to "CRN-DF-GO-MT-TO" "Conselho Regional de Nutrição da 1ª Região (DF/GO/MT/TO)."
* #https://saude.gov.br/fhir/sid/crn-pa-ac-am-ap-ro-rr "CRN-PA-AC-AM-AP-RO-RR" "Conselho Regional de Nutrição da 7ª Região (AC/AM/AP/PA/RO/RR)."
* #https://saude.gov.br/fhir/sid/crn-pe-al-pb-rn "CRN-PE-AL-PB-RN" "Conselho Regional de Nutrição da 6ª Região (AL/PB/PE/RN)."
* #https://saude.gov.br/fhir/sid/crn-pr "CRN-PR" "Conselho Regional de Nutrição da 8ª Região (PR)."
* #https://saude.gov.br/fhir/sid/crn-rj-es "CRN-RJ-ES" "Conselho Regional de Nutrição da 4ª Região (ES/RJ)."
* #https://saude.gov.br/fhir/sid/crn-rs "CRN-RS" "Conselho Regional de Nutrição da 2ª Região (RS)."
* #https://saude.gov.br/fhir/sid/crn-sc "CRN-SC" "Conselho Regional de Nutrição da 10ª Região (SC)."
* #https://saude.gov.br/fhir/sid/crn-sp-ms "CRN-SP-MS" "Conselho Regional de Nutrição da 3ª Região (SP/MS)."
* #https://saude.gov.br/fhir/sid/crefono-am-ac-ap-pa-ro-rr "Conselho Regional de Fonoaudiologia 9ª Região (AC, AM, AP, PA, RO e RR)" "Conselho Regional de Fonoaudiologia 9ª Região (AC, AM, AP, PA, RO e RR)."
* #https://saude.gov.br/fhir/sid/crefono-ce-ma-pi-rn "Conselho Regional de Fonoaudiologia 8ª Região (CE, MA, PI e RN)" "Conselho Regional de Fonoaudiologia 8ª Região (CE, MA, PI e RN)."
* #https://saude.gov.br/fhir/sid/crefono-go-df-ms-mt-to "Conselho Regional de Fonoaudiologia 5ª Região (DF, GO, MS, MT, e TO)" "Conselho Regional de Fonoaudiologia 5ª Região (DF, GO, MS, MT, e TO)."
* #https://saude.gov.br/fhir/sid/crefono-mg-es "Conselho Regional de Fonoaudiologia 6ª Região (ES e MG)" "Conselho Regional de Fonoaudiologia 6ª Região (ES e MG)."
* #https://saude.gov.br/fhir/sid/crefono-pe-al-ba-pb-se "Conselho Regional de Fonoaudiologia 4ª Região (AL, BA, PB, PE e SE)" "Conselho Regional de Fonoaudiologia 4ª Região (AL, BA, PB, PE e SE)."
* #https://saude.gov.br/fhir/sid/crefono-pr-sc "Conselho Regional de Fonoaudiologia 3ª Região (PR e SC)" "Conselho Regional de Fonoaudiologia 3ª Região (PR e SC)."
* #https://saude.gov.br/fhir/sid/crefono-rj "Conselho Regional de Fonoaudiologia 1ª Região (RJ)" "Conselho Regional de Fonoaudiologia 1ª Região (RJ)."
* #https://saude.gov.br/fhir/sid/crefono-rs "Conselho Regional de Fonoaudiologia 7ª Região (RS)" "Conselho Regional de Fonoaudiologia 7ª Região (RS)."
* #https://saude.gov.br/fhir/sid/crefono-sp "Conselho Regional de Fonoaudiologia 2ª Região (SP)" "Conselho Regional de Fonoaudiologia 2ª Região (SP)."
* #https://saude.gov.br/fhir/sid/cress-pi "CRESS-PI" "Conselho Regional de Serviço Social da 22ª Região (PI)."
* #https://saude.gov.br/fhir/sid/cress-am "CRESS-AM" "Conselho Regional de Serviço Social da 15ª Região (AM)."
* #https://saude.gov.br/fhir/sid/cress-sc "CRESS-SC" "Conselho Regional de Serviço Social da 12ª Região (SC)."
* #https://saude.gov.br/fhir/sid/cress-mt "CRESS-MT" "Conselho Regional de Serviço Social da 20ª Região (MT)."
* #https://saude.gov.br/fhir/sid/cress-rj "CRESS-RJ" "Conselho Regional de Serviço Social da 7ª Região (RJ)."
* #https://saude.gov.br/fhir/sid/cress-ce "CRESS-CE" "Conselho Regional de Serviço Social da 3ª Região (CE)."
* #https://saude.gov.br/fhir/sid/cress-es "CRESS-ES" "Conselho Regional de Serviço Social da 17ª Região (ES)."
* #https://saude.gov.br/fhir/sid/cress-al "CRESS-AL" "Conselho Regional de Serviço Social da 16ª Região (AL)."
* #https://saude.gov.br/fhir/sid/cress-ma "CRESS-MA" "Conselho Regional de Serviço Social da 2ª Região (MA)."
* #https://saude.gov.br/fhir/sid/cress-mg "CRESS-MG" "Conselho Regional de Serviço Social da 6ª Região (MG)."
* #https://saude.gov.br/fhir/sid/cress-to "CRESS-TO" "Conselho Regional de Serviço Social da 25ª Região (TO)."
* #https://saude.gov.br/fhir/sid/cress-ac "CRESS-AC" "Conselho Regional de Serviço Social da 26ª Região (AC)."
* #https://saude.gov.br/fhir/sid/cress-rn "CRESS-RN" "Conselho Regional de Serviço Social da 14ª Região (RN)."
* #https://saude.gov.br/fhir/sid/cress-ap "CRESS-AP" "Conselho Regional de Serviço Social da 24ª Região (AP)."
* #https://saude.gov.br/fhir/sid/cress-ro "CRESS-RO" "Conselho Regional de Serviço Social da 23ª Região (RO)."
* #https://saude.gov.br/fhir/sid/cress-se "CRESS-SE" "Conselho Regional de Serviço Social da 18ª Região (SE)."
* #https://saude.gov.br/fhir/sid/cress-pr "CRESS-PR" "Conselho Regional de Serviço Social da 11ª Região (PR)."
* #https://saude.gov.br/fhir/sid/cress-pa "CRESS-PA" "Conselho Regional de Serviço Social da 1ª Região (PA)."
* #https://saude.gov.br/fhir/sid/cress-go "CRESS-GO" "Conselho Regional de Serviço Social da 19ª Região (GO)."
* #https://saude.gov.br/fhir/sid/cress-ms "CRESS-MS" "Conselho Regional de Serviço Social da 21ª Região (MS)."
* #https://saude.gov.br/fhir/sid/cress-df "CRESS-DF" "Conselho Regional de Serviço Social da 8ª Região (DF)."
* #https://saude.gov.br/fhir/sid/cress-ba "CRESS-BA" "Conselho Regional de Serviço Social da 5ª Região (BA)."
* #https://saude.gov.br/fhir/sid/cress-pb "CRESS-PB" "Conselho Regional de Serviço Social da 13ª Região (PB)."
* #https://saude.gov.br/fhir/sid/cress-rr "CRESS-RR" "Conselho Regional de Serviço Social da 27ª Região (RR)."
* #https://saude.gov.br/fhir/sid/cress-rs "CRESS-RS" "Conselho Regional de Serviço Social da 10ª Região (RS)."
* #https://saude.gov.br/fhir/sid/cress-pe "CRESS-PE" "Conselho Regional de Serviço Social da 4ª Região (PE)."
* #https://saude.gov.br/fhir/sid/cress-sp "CRESS-SP" "Conselho Regional de Serviço Social da 9ª Região (SP)."