CodeSystem: BRDose
Id: BRDose
Title: "BRDose"
* ^meta.lastUpdated = "2025-07-17T17:30:44.803+00:00"
* ^version = "1.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* ^caseSensitive = true
* ^content = #complete
* #23 "Tratamento com treze doses"
* #60 "Profilaxia com 2 frascos-ampolas/ampolas"
* #22 "Tratamento com doze doses"
* #2 "2ª Dose"
* #57 "Dose Zero"
* #6 "1º Reforço"
* #20 "Tratamento com dez doses"
* #21 "Tratamento com onze doses"
* #59 "Profilaxia com 1 frasco-ampola/ampola"
* #19 "Tratamento com nove doses"
* #18 "Tratamento com oito doses"
* #17 "Tratamento com sete doses"
* #16 "Tratamento com seis doses"
* #52 "4ª Dose Dobrada"
* #15 "Tratamento com cinco doses"
* #51 "3ª Dose Dobrada"
* #14 "Tratamento com quatro doses"
* #49 "1ª Dose Dobrada"
* #12 "Tratamento com duas doses"
* #11 "Tratamento com uma dose"
* #48 "5ª Dose Fracionada"
* #10 "Revacinação"
* #47 "4ª Dose Fracionada"
* #1 "1ª Dose"
* #50 "2ª Dose Dobrada"
* #13 "Tratamento com três doses"
* #5 "5ª Dose"
* #35 "4ª Dose Revacinação"
* #71 "Profilaxia com 13 frascos-ampolas/ampolas"
* #34 "3ª Dose Revacinação"
* #70 "Profilaxia com 12 frascos-ampolas/ampolas"
* #7 "2º Reforço"
* #33 "2ª Dose Revacinação"
* #32 "1ª Dose Revacinação"
* #31 "Tratamento com vinte e quatro doses"
* #28 "Tratamento com dezoito doses"
* #68 "Profilaxia com 10 frascos-ampolas/ampolas"
* #69 "Profilaxia com 11 frascos-ampolas/ampolas"
* #66 "Profilaxia com 8 frascos-ampolas/ampolas"
* #3 "3ª Dose"
* #30 "Tratamento com vinte doses"
* #65 "Profilaxia com 7 frascos-ampolas/ampolas"
* #67 "Profilaxia com 9 frascos-ampolas/ampolas"
* #29 "Tratamento com dezenove doses"
* #64 "Profilaxia com 6 frascos-ampolas/ampolas"
* #27 "Tratamento com dezessete doses"
* #63 "Profilaxia com 5 frascos-ampolas/ampolas"
* #26 "Tratamento com dezesseis doses"
* #25 "Tratamento com quinze doses"
* #62 "Profilaxia com 4 frascos-ampolas/ampolas"
* #61 "Profilaxia com 3 frascos-ampolas/ampolas"
* #24 "Tratamento com quartorze doses"
* #75 "Profilaxia com 17 frascos-ampolas/ampolas"
* #38 "Reforço"
* #37 "Dose Adicional"
* #74 "Profilaxia com 16 frascos-ampolas/ampolas"
* #36 "Dose Inicial"
* #73 "Profilaxia com 15 frascos-ampolas/ampolas"
* #72 "Profilaxia com 14 frascos-ampolas/ampolas"
* #39 "3º Reforço"
* #76 "Profilaxia com 18 frascos-ampolas/ampolas"
* #4 "4ª Dose"
* #77 "Profilaxia com 19 frascos-ampolas/ampolas"
* #40 "4º Reforço"
* #78 "Profilaxia com 20 frascos-ampolas/ampolas"
* #41 "5º Reforço"
* #79 "Profilaxia com 21 frascos-ampolas/ampolas"
* #42 "6º Reforço"
* #8 "Dose"
* #43 "5ª Dose Revacinação"
* #80 "Profilaxia com 22 frascos-ampolas/ampolas"
* #44 "1ª Dose Fracionada"
* #81 "Profilaxia com 23 frascos-ampolas/ampolas"
* #45 "2ª Dose Fracionada"
* #82 "Profilaxia com 24 frascos-ampolas/ampolas"
* #46 "3ª Dose Fracionada"
* #9 "Única"
* #58 "Reforço Zero"
* #56 "4ª Dose Revacinação Dobrada"
* #55 "3ª Dose Revacinação Dobrada"
* #54 "2ª Dose Revacinação Dobrada"
* #53 "1ª Dose Revacinação Dobrada"