CodeSystem: BRInstalacoesFisicas
Id: BRInstalacoesFisicas
Title: "BRInstalacoesFisicas"
* ^meta.lastUpdated = "2025-07-17T17:28:40.472+00:00"
* ^version = "1.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* ^caseSensitive = true
* ^content = #complete
* #22 "SALA DE REPOUSO/OBSERVACAO - INDIFERENCIADO"
* #21 "SALA REPOUSO/OBSERVACAO - PEDIATRICA"
* #43 "BRINQUEDOTECA"
* #20 "SALA REPOUSO/OBSERVACAO - MASCULINO"
* #42 "SALA DE ACOLHIMENTO COM CLASSIFICACAO DE RISCO"
* #19 "SALA REPOUSO/OBSERVACAO - FEMININO"
* #41 "SALA DE ATENDIMENTO A PACIENTE CRITICO/SALA DE ESTABILIZACAO"
* #18 "OUTROS CONSULTORIOS NAO MEDICOS"
* #40 "LEITOS DE ALOJAMENTO CONJUNTO"
* #17 "CLINICAS INDIFERENCIADO"
* #39 "LEITOS RN PATOLOGICO"
* #16 "CLINICAS ESPECIALIZADAS"
* #38 "LEITOS RN NORMAL"
* #15 "CLINICAS BASICAS"
* #37 "SALA DE CIRURGIA"
* #14 "CONSULTORIOS MEDICOS"
* #36 "SALA DE CURETAGEM"
* #13 "SALA PEQUENA CIRURGIA"
* #35 "SALA DE PARTO NORMAL"
* #12 "SALA DE CURATIVO"
* #34 "SALA DE PREPARTO"
* #11 "SALA DE GESSO"
* #33 "SALA DE CIRURGIA AMBULATORIAL"
* #10 "SALA DE HIGIENIZACAO"
* #32 "SALA DE RECUPERACAO"
* #09 "ODONTOLOGIA"
* #31 "SALA DE CIRURGIA"
* #08 "SALA REPOUSO/OBSERVACAO - INDIFERENCIADO"
* #30 "SALA DE CIRURGIA AMBULATORIAL"
* #07 "SALA REPOUSO/OBSERVACAO - MASCULINO"
* #29 "SALA DE CURATIVO"
* #06 "SALA REPOUSO/OBSERVACAO - FEMININO"
* #28 "SALA DE GESSO"
* #05 "SALA REPOUSO/OBSERVACAO - PEDIATRICA"
* #27 "SALA DE NEBULIZACAO"
* #04 "SALA DE ATENDIMENTO INDIFERENCIADO"
* #26 "SALA DE IMUNIZACAO"
* #03 "SALA DE ATENDIMENTO MASCULINO"
* #25 "SALA DE ENFERMAGEM - SERVICOS"
* #02 "SALA DE ATENDIMENTO FEMININO"
* #24 "SALA DE PEQUENA CIRURGIA"
* #23 "ODONTOLOGIA"
* #01 "SALA DE ATENDIMENTO PEDIATRICO"