CodeSystem: BROrgaoExpedidor
Id: BROrgaoExpedidor
Title: "BROrgaoExpedidor"
* ^meta.lastUpdated = "2025-07-17T17:33:51.989+00:00"
* ^version = "1.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* ^caseSensitive = true
* ^content = #complete
* #CRM "Conselho Regional de Medicina (CRM)"
* #CRFA "Conselho Regional de Fonoaudiologia (CRFa/CREFONO)"
* #other "Outro órgão não listado"
* #CRF "Conselho Regional de Farmácia (CRF)"
* #SSP "Serviço de Segurança Pública"
* #CRESS "Conselho Regional de Serviço Social (CRESS)"
* #RFB "Receita Federal do Brasil"
* #CREFITO "Conselho Regional de Fisioterapia e Terapia Ocupacional (CREFITO)"
* #PM "Polícia Militar"
* #CREF "Conselho Regional de Educação Física (CREF)"
* #PF "Polícia Federal"
* #CRECI "Conselho Regional de Corretores de Imóveis (CRECI)"
* #PCE "Polícia Civil do Estado"
* #CREA "Conselho Regional de Engenharia e Agronomia (CREA)"
* #OAB "Ordem dos Advogados do BRAasil (OAB)"
* #CRC "Conselho Regional de Contabilidade (CRC)"
* #MS "Ministério da Saúde"
* #MC "Ministério da Cidadania"
* #CRBM "Conselho Regional de Biomedicina (CRBM)"
* #MB "Marinha do Brasil"
* #CRBIO "Conselho Regional de Biologia (CRBio)"
* #II "Instituto de Identificação"
* #CRB "Conselho Regional de Biblioteconomia (CRB)"
* #FAB "Força Aérea Brasileira"
* #CRA "Conselho Regional de Administração (CRA)"
* #EB "Exército Brasileiro"
* #COREN "Conselho Regional de Enfermagem (COREn)"
* #DETRAN "Departamento Estadual de Trânsito"
* #CORECON "Conselho Regional de Economia (CORECON)"
* #CRTR "Conselho Regional de Técnicos em Radiologia (CRTR)"
* #CORE "Conselho Regional de Representantes Comerciais (CORE)"
* #CRT "Conselho Regional dos Técnicos Industriais (CRT)"
* #CONRERP "Conselho Regional de Reçações Públicas (CONRERP)"
* #CRQ "Conselho Regional de Química (CRQ)"
* #CONFRE "Conselho Regional de Estatística (CONRE)"
* #CRP "Conselho Regional de Psicologia (CRP)"
* #CBM "Corpo de Bombeiros Militar"
* #CRO "Conselho Regional de Odontologia (CRO)"
* #CAU "Conselho Regional de Arquitetura e Urbanismo (CAU)"
* #CRN "Conselho Regional de Nutrição (CRN)"
* #CRMV "Conselho Regional de Medicina Veterinária (CRMV)"
* #CARTORIO "Cartório de Registro Civil"