CodeSystem: BRTipoAmostraGAL
Id: BRTipoAmostraGAL
Title: "BRTipoAmostraGAL"
* ^meta.lastUpdated = "2025-07-17T17:33:34.370+00:00"
* ^version = "1.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* ^caseSensitive = true
* ^content = #complete
* #SECORF "Secreção Orofaríngea"
* #SGHEM "Sangue"
* #ASNAFA "Aspirado Nasofaríngeo"
* #MTBIO "Material Não Biológico"
* #FRACOR "Fragmentos de coração"
* #FRAFIG "Fragmentos de fígado"
* #FLUORA "Fluido oral"
* #FRABAC "Fragmentos de baço"
* #SGEDT "Sangue com EDTA"
* #SECTRA "Secreção Traqueal"
* #ASPBRO "Aspirado Brônquico"
* #FRAAMI "Fragmentos de ampigdalas"
* #RASPEL "Raspado de pele"
* #FGMT "Fragmento"
* #SECPEN "Secreção peniana"
* #EXSORO "Exsudato de Orofaringe"
* #CORIZA "Coriza"
* #SECBRO "Secreção brônquica"
* #FGMP "Fragmentos do pulmão"
* #SECONF "Secreção Orofaríngea e Nasofaríngea"
* #SECNAS "Secreção Nasofaríngea"
* #EXSNAS "Exsudato de Nasofaringe"
* #SECOC "Secreção ocular"
* #SNCCEB "Fragmento do tecido do SNC - cérebro"
* #FRBRON "Fragmentos de brônquio"
* #FRAGT "Fragmento de tecido"
* #FRATRA "Fragmentos de traquéia"
* #SWLES "Swab de lesão"
* #SWBAN "Swab Anal"
* #FRAPAN "Fragmentos de pâncreas"
* #FRAMOR "Fragmentos de múltiplos órgãos"
* #FRARIM "Fragmentos de rim"
* #SWAB "Swab"
* #SWNAFA "Swab Nasofaríngeo"
* #SNOF "Swab Naso-Orofaríngeo"
* #SWOCU "Swab Ocular"
* #INFP "Infiltrado pulmonar"
* #SWNAS "Swab Nasal"
* #SWLSP "Swab de lesão de pele"
* #INODER "Inoculação intradérmica"
* #LAVBRO "Lavado Brônquico"
* #LAVBRA "Lavado Brônquico Alveolar"
* #SWRET "Swab retal"
* #SWORA "Swab Oral"
* #LAVORO "Lavado de orofaringe"
* #SWORO "Swab Orofaríngeo"
* #LAVTBR "Lavado Traqueo-Brônquico"
* #TECPM "Tecido pós-mortem"