CodeSystem: BRUnidadeMedida
Id: BRUnidadeMedida
Title: "BRUnidadeMedida"
* ^meta.lastUpdated = "2025-07-16T16:51:54.333+00:00"
* ^version = "1.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2026-03-09T15:10:29-03:00"
* ^publisher = "Ministério do Saúde do Brasil"
* ^contact[0].name = "Ministério do Saúde do Brasil"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://gov.br/saude"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "contato@gointerop.com"
* ^contact[+].name = "Italo Macedo"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "italo@gointerop.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#BR "Brazil"
* ^caseSensitive = true
* ^content = #complete
* #82 "Glóbulo"
* #43 "mg (Miligrama)"
* #42 "mEq (Miliequivalente)"
* #41 "m (Metro)"
* #9 "Bisnaga"
* #40 "Lata"
* #80 "Tubo"
* #4 "Aplicação"
* #8 "Barra"
* #39 "L (Litro)"
* #79 "Tubete"
* #38 "kg (Quilograma)"
* #78 "Tablete"
* #37 "Implante"
* #77 "Seringa preenchida"
* #36 "Hora"
* #76 "Sachê"
* #35 "Gota"
* #75 "Pote"
* #34 "Goma"
* #74 "Drágea"
* #33 "g (Grama)"
* #71 "Cartela"
* #70 "Cartão"
* #32 "Frasco-ampola"
* #7 "Bandagem"
* #31 "Frasco"
* #69 "Capsula inalante"
* #30 "Flaconete"
* #66 "Bastão"
* #3 "Anel"
* #64 "Óvulo"
* #29 "Filme"
* #63 "UTR (Unidade Redutora da Turbidez)"
* #28 "Estojo"
* #62 "Unidade"
* #27 "Envelope"
* #61 "UIC (Unidade Inibidora de Calicreína)"
* #26 "Enema"
* #60 "UI (Unidade Internacional)"
* #25 "Endosporos"
* #6 "Atomização"
* #24 "Emplastro"
* #59 "Supositório"
* #23 "Dose"
* #58 "Strip"
* #22 "Dispositivo de injeção pré-carregado"
* #57 "Seringa"
* #21 "Dispositivo"
* #56 "Saco"
* #20 "Desconhecido"
* #55 "Pílula"
* #2 "Ampola"
* #54 "Pastilha gomosa"
* #19 "Comprimido"
* #53 "Pastilha dura"
* #18 "cm² (Centímetro Quadrado)"
* #52 "Pastilha"
* #17 "cm (Centímetro)"
* #51 "nL (Nanolitro)"
* #50 "ng (Nanograma)"
* #16 "Catéter"
* #5 "Aplicador"
* #15 "Cartucho"
* #49 "mm (Milímetro)"
* #14 "Carpule"
* #48 "mL (Mililitro)"
* #13 "Cápsula"
* #47 "MUI (Milhões de unidades internacionais)"
* #12 "Caixa"
* #46 "Milhões"
* #11 "Bolsa"
* #10 "Blíster"
* #45 "Microlitro"
* #44 "Micrograma"
* #1 "Adesivo"